"""
Ingesta verbatim de Título A, Capítulo A.9 (Elementos no estructurales)
-- NSR-10. Fase 6 del plan de cierre del Título A (2026-09-22),
auditoría real de numerales confirmó A.9 en 7/49 (faltan 42).

**Hallazgo real**: los 21 chunks ya cargados para A.9
(`NSR10-A-A_9_general_fuerzas_r*`, `NSR10-A-A_9_5_a_9_6_tablas_r*`) NO
son verbatim -- son texto condensado/parafraseado, mismo patrón ya
documentado en A.3.1/A.3.2/A.3.4/A.9/A.10 (ver también
`_ingest_titulo_a_a3_verbatim.py`). Se borran aquí y se reemplazan por
transcripción verbatim real.

Fuente: NSR-10-130-138.pdf completo, páginas PDF 1-9 (A-87 a A-95,
capítulo completo). Leídas visualmente con Read pages= sobre el PDF
nativo -- nunca extracción mecánica (pypdf).

Uso: python _ingest_titulo_a_a9_verbatim.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "A"

IDS_A_BORRAR_CONDENSADOS = (
    [f"NSR10-A-A_9_general_fuerzas_r{i}" for i in range(1, 13)]
    + [f"NSR10-A-A_9_5_a_9_6_tablas_r{i}" for i in range(1, 10)]
)

CHUNKS = [
    {
        "id": "NSR10-A-A_9_0_nomenclatura",
        "seccion": "A.9.0 — Nomenclatura del Capítulo A.9",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "CAPÍTULO A.9 — ELEMENTOS NO ESTRUCTURALES\n\n"
            "A.9.0 — NOMENCLATURA\n\n"
            "Aa = coeficiente que representa la aceleración horizontal "
            "pico efectiva, para diseño, dado en A.2.2.\n"
            "As = aceleración máxima en la superficie del suelo estimada "
            "como la aceleración espectral correspondiente a un período "
            "de vibración igual a cero, véase A.9.4.2.1.\n"
            "ap = coeficiente de amplificación dinámica del elemento no "
            "estructural. Se da en las tablas A.9.5-1 y A.9.6-1.\n"
            "ax = aceleración horizontal, expresada como un porcentaje "
            "de la aceleración de la gravedad, sobre el elemento no "
            "estructural, localizado en el piso x.\n"
            "E = fuerzas sísmicas reducidas de diseño (E = Fp/Rp).\n"
            "Fp = fuerza sísmica horizontal sobre el elemento no "
            "estructural, aplicada en su centro de masa.\n"
            "g = aceleración debida a la gravedad (9.8 m/s²).\n"
            "heq = altura equivalente del sistema de un grado de libertad "
            "que simula la edificación, véase A.9.4.2.1.\n"
            "hx = altura en metros, medida desde la base, del nivel de "
            "apoyo del elemento no estructural.\n"
            "hn = altura en metros, medida desde la base, del piso más "
            "alto de la edificación, véase A.8.2.1.1.\n"
            "I = coeficiente de importancia dado en A.2.5.2.\n"
            "Mp = masa del elemento no estructural.\n"
            "Rp = coeficiente de capacidad de disipación de energía del "
            "elemento no estructural y sus sistema de soporte. Se da en "
            "las tablas A.9.5-1 y A.9.6-1.\n"
            "Sa = valor del espectro de aceleraciones de diseño para un "
            "período de vibración dado. Máxima aceleración horizontal de "
            "diseño, expresada como una fracción de la aceleración de la "
            "gravedad, para un sistema de un grado de libertad con un "
            "período de vibración T. Está definido en A.2.6."
        ),
    },
    {
        "id": "NSR10-A-A_9_1_general_proposito_alcance_exenciones",
        "seccion": "A.9.1 — General (propósito, alcance y exenciones)",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.1 — GENERAL\n\n"
            "A.9.1.1 — PROPÓSITO — Los requisitos del presente Capítulo "
            "tienen como objetivo establecer los criterios de diseño de "
            "elementos que no hacen parte de la estructura de la "
            "construcción, con el fin de que se cumpla el propósito del "
            "Reglamento.\n\n"
            "A.9.1.2 — ALCANCE — El presente Capítulo cubre las "
            "previsiones sísmicas que deben tenerse en el diseño de los "
            "elementos no estructurales y de sus anclajes a la "
            "estructura, con la excepción de lo indicado en A.9.1.3. "
            "Dentro de los elementos no estructurales que deben ser "
            "diseñados sísmicamente se incluyen:\n\n"
            "(a) Acabados y elementos arquitectónicos y decorativos,\n"
            "(b) Instalaciones hidráulicas y sanitarias,\n"
            "(c) Instalaciones eléctricas,\n"
            "(d) Instalaciones de gas,\n"
            "(e) Equipos mecánicos,\n"
            "(f) Estanterías e\n"
            "(g) Instalaciones especiales.\n\n"
            "A.9.1.3 — EXENCIONES — Están exentas de los requisitos del "
            "presente Capítulo todas las edificaciones pertenecientes a "
            "los grupos de uso I y II localizadas en zonas de amenaza "
            "sísmica baja."
        ),
    },
    {
        "id": "NSR10-A-A_9_2_grado_desempeno",
        "seccion": "A.9.2 — Grado de desempeño de los elementos no estructurales (Tabla A.9.2-1)",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.2 — GRADO DE DESEMPEÑO DE LOS ELEMENTOS NO "
            "ESTRUCTURALES\n\n"
            "A.9.2.1 — DEFINICIÓN DEL DESEMPEÑO — Se denomina desempeño "
            "el comportamiento de los elementos no estructurales de la "
            "edificación ante la ocurrencia del sismo de diseño que la "
            "afecte. El desempeño se clasifica en los siguientes "
            "grados:\n\n"
            "(a) Superior — Es aquel en el cual el daño que se presenta "
            "en los elementos no estructurales es mínimo y no interfiere "
            "con la operación de la edificación debido a la ocurrencia "
            "del sismo de diseño.\n\n"
            "(b) Bueno — Es aquel en el cual el daño que se presenta en "
            "los elementos no estructurales es totalmente reparable y "
            "puede haber alguna interferencia con la operación de la "
            "edificación con posterioridad a la ocurrencia del sismo de "
            "diseño.\n\n"
            "(c) Bajo — Es aquel en el cual se presentan daños graves en "
            "los elementos no estructurales, inclusive no reparables, "
            "pero sin desprendimiento o colapso, debido a la ocurrencia "
            "del sismo de diseño.\n\n"
            "A.9.2.2 — CLASIFICACIÓN EN UNO DE LOS GRADOS DE DESEMPEÑO — "
            "La edificación debe clasificarse dentro de uno de los tres "
            "grados de desempeño de los elementos no estructurales "
            "definidos en A.9.2.1. Este grado de desempeño no puede ser "
            "inferior al mínimo permisible fijado en A.9.2.3. El "
            "propietario de la edificación, de manera voluntaria, puede "
            "exigir que los diseños se realicen para un grado de "
            "desempeño mejor que el mínimo exigido, comunicándolo por "
            "escrito a los diseñadores. En ausencia de esta comunicación, "
            "los diseñadores solo están obligados a cumplir con el grado "
            "mínimo permisible fijado en A.9.2.3.\n\n"
            "A.9.2.3 — GRADO DE DESEMPEÑO MÍNIMO — Como mínimo debe "
            "cumplirse el grado de desempeño indicado en la tabla "
            "A.9.2-1, para cada uno de los grupos de uso definidos en "
            "A.2.5.1.\n\n"
            "Tabla A.9.2-1 — Grado de desempeño mínimo requerido: "
            "Grupo de Uso IV → Superior; Grupo de Uso III → Superior; "
            "Grupo de Uso II → Bueno; Grupo de Uso I → Bajo."
        ),
    },
    {
        "id": "NSR10-A-A_9_3_responsabilidades",
        "seccion": "A.9.3 — Responsabilidades (diseñador, supervisor técnico y coordinación)",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.3 — RESPONSABILIDADES\n\n"
            "A.9.3.1 — DEL DISEÑADOR RESPONSABLE — La responsabilidad "
            "del diseño sísmico de los elementos no estructurales recae "
            "en los profesionales bajo cuya dirección se elaboran los "
            "diferentes diseños particulares. Se presume que el hecho de "
            "que un elemento no estructural figure en un plano o "
            "memoria de diseño, es porque se han tomado todas las "
            "medidas necesarias para cumplir el grado de desempeño "
            "apropiado y por lo tanto el profesional que firma o rotula "
            "el plano se hace responsable de que el diseño se realizó "
            "para el grado de desempeño apropiado. El constructor quien "
            "suscribe la licencia de construcción debe cumplir lo "
            "indicado en A.1.3.6.5 y es el responsable final de que los "
            "diseños de los elementos estructurales se haya realizado "
            "adecuadamente y que su construcción se realice "
            "apropiadamente.\n\n"
            "A.9.3.1.1 — En aquellos casos en los cuales en los diseños "
            "se especifican elementos no estructurales cuyo suministro e "
            "instalación se realiza por parte de su fabricante, el "
            "diseñador se debe limitar a especificar en sus planos, "
            "memorias o especificaciones, el grado de desempeño que "
            "deben cumplir los elementos. El constructor que suscribe la "
            "licencia de construcción debe cumplir también en estos "
            "casos lo indicado en A.1.3.6.5.\n\n"
            "A.9.3.2 — DEL SUPERVISOR TÉCNICO — El supervisor técnico "
            "debe verificar que la construcción e instalación de los "
            "elementos no estructurales se realice siguiendo los planos "
            "y especificaciones correspondientes. En aquellos casos en "
            "los cuales en los documentos de diseño (planos, memorias y "
            "especificaciones) sólo se indica el grado de desempeño "
            "requerido, es responsabilidad del supervisor técnico el "
            "verificar que los elementos no estructurales que se instalen "
            "en la edificación, efectivamente estén en capacidad de "
            "cumplir el grado de desempeño especificado por el "
            "diseñador.\n\n"
            "A.9.3.3 — COORDINACIÓN ENTRE DISEÑOS DE ELEMENTOS QUE HACEN "
            "PARTE DE DIFERENTES SISTEMAS — La responsabilidad de la "
            "coordinación entre los diferentes diseños recae en el "
            "profesional que figura como diseñador arquitectónico en la "
            "solicitud de licencia de construcción. El profesional que "
            "realice la coordinación debe tomar todas las precauciones "
            "necesarias para que el diseño resultante de cada uno de los "
            "elementos no estructurales, realizado por profesionales "
            "diferentes a él, no afecte el desempeño de elementos "
            "diseñados por otros profesionales."
        ),
    },
    {
        "id": "NSR10-A-A_9_4_1_a_4_3_general_fuerzas_sismicas_deformacion",
        "seccion": "A.9.4.1 a A.9.4.3 — Criterio de diseño: general, fuerzas sísmicas de diseño y capacidad de deformación",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.4 — CRITERIO DE DISEÑO\n\n"
            "A.9.4.1 — GENERAL — El diseñador de los elementos no "
            "estructurales puede adoptar una de dos estrategias en el "
            "diseño:\n\n"
            "(a) Separarlos de la estructura — En este tipo de diseño "
            "los elementos no estructurales se aíslan lateralmente de la "
            "estructura dejando una separación suficiente para que la "
            "estructura al deformarse como consecuencia del sismo no los "
            "afecte adversamente. Los elementos no estructurales se "
            "apoyan en su parte inferior sobre la estructura, o se "
            "cuelgan de ella; por lo tanto deben ser capaces de resistir "
            "por si mismos las fuerzas inerciales que les impone el "
            "sismo, y sus anclajes a la estructura deben ser capaces de "
            "resistir y transferir a la estructura estas fuerzas "
            "inducidas por el sismo. Además la separación a la "
            "estructura de la edificación debe ser lo suficientemente "
            "amplia para garantizar que no entren en contacto, para los "
            "desplazamientos impuestos por el sismo de diseño. En el "
            "espacio resultante deberá evitarse colocar elementos que "
            "rigidicen la unión eliminando la flexibilidad requerida por "
            "el diseño.\n\n"
            "(b) Disponer elementos que admitan las deformaciones de la "
            "estructura — En este tipo de diseño se disponen elementos "
            "no estructurales que tocan la estructura y que por lo tanto "
            "deben ser lo suficientemente flexibles para poder resistir "
            "las deformaciones que la estructura les impone sin sufrir "
            "daño mayor que el que admite el grado de desempeño "
            "prefijado para los elementos no estructurales de la "
            "edificación. En este tipo de diseño debe haber una "
            "coordinación con el ingeniero estructural, con el fin de "
            "que éste tome en cuenta el potencial efecto nocivo sobre la "
            "estructura que pueda tener la interacción entre elementos "
            "estructurales y no estructurales.\n\n"
            "A.9.4.2 — FUERZAS SÍSMICAS DE DISEÑO — Las fuerzas sísmicas "
            "horizontales reducidas de diseño que actúan sobre cualquier "
            "elemento no estructural deben calcularse utilizando la "
            "siguiente ecuación:\n\n"
            "Fp = (ax·ap/Rp)·g·Mp ≥ (Aa·I/2)·g·Mp       (A.9.4-1)\n\n"
            "A.9.4.2.1 — Aceleración en el punto de soporte del "
            "elemento, ax — Corresponde a la aceleración horizontal que "
            "ocurre en el punto donde el elemento no estructural está "
            "soportado, o anclado, al sistema estructural de la "
            "edificación, cuando ésta se ve afectada por los movimientos "
            "sísmicos de diseño. Esta aceleración depende de las "
            "características dinámicas del sistema de resistencia "
            "sísmica de la edificación y de la localización del elemento "
            "dentro de ella. Debe evaluarse por medio de un análisis "
            "dinámico de la estructura que tenga en cuenta su capacidad "
            "de disipación de energía en el rango inelástico, o bien por "
            "medio de la siguiente ecuación compatible con las fuerzas "
            "sísmicas que se obtienen por medio del método de fuerza "
            "horizontal equivalente tal como se presenta en el Capítulo "
            "A.4 del Reglamento:\n\n"
            "ax = As + (Sa - As)·hx/heq    para hx ≤ heq\n"
            "ax = Sa · hx/heq             para hx ≥ heq\n"
            "(A.9.4-2)\n\n"
            "heq puede estimarse simplificadamente como 0.75hn. El valor "
            "de Sa se debe calcular para las dos direcciones de análisis "
            "en planta de la estructura, y se debe emplear el valor que "
            "conduzca al mayor valor de Sa.\n\n"
            "A.9.4.2.2 — Amplificación dinámica del elemento no "
            "estructural, ap — Dependiendo de la rigidez, distribución de "
            "su masa y características de apoyo sobre la estructura, el "
            "elemento no estructural amplifica las aceleraciones que se "
            "presentan en su punto de soporte debido a efectos de "
            "resonancia. Estos efectos de resonancia dependen de la "
            "relación que exista entre el período fundamental de la "
            "estructura y del elemento no estructural, incluyendo la "
            "acción de sus soportes. Cuando el elemento no estructural es "
            "rígido, su masa se encuentra localizada cerca del punto de "
            "apoyo y está firmemente anclado a la estructura, su "
            "amplificación dinámica es menor, esto se presenta en "
            "elementos no estructurales con períodos de vibración del "
            "orden de 0.06s o menos. Cuando el elemento no estructural es "
            "flexible, o su masa se encuentra distribuida en la altura, "
            "o concentrada lejos del punto de soporte, o sus apoyos "
            "permiten desplazamientos apreciables, las aceleraciones a "
            "que se ve sometido se amplifican apreciablemente con "
            "respecto a las aceleraciones que se presentan en su punto de "
            "soporte. Esta amplificación, ap, debe determinarse por medio "
            "de análisis dinámicos detallados o ensayos dinámicos "
            "experimentales. En ausencia de éstos, pueden emplearse los "
            "valores aproximados dados en las tablas A.9.5-1 y A.9.6-1, "
            "donde los valores de ap varían entre 1.0 y 2.5.\n\n"
            "A.9.4.2.3 — Capacidad de disipación de energía en el rango "
            "inelástico del elemento no estructural, Rp — Este "
            "coeficiente representa, en conjunto, la capacidad de "
            "disipación de energía en el rango inelástico de respuesta "
            "del elemento en sí y de su sistema de anclaje o amarre a la "
            "estructura de la edificación. Un valor de Rp bajo, cercano a "
            "la unidad, indica fragilidad, poca capacidad de disipación "
            "de energía, y anclajes o amarres a la estructura con poca "
            "capacidad de deformarse inelásticamente. En la medida en que "
            "se atienden estos grados potenciales de comportamiento "
            "deficiente es posible incrementar los valores de Rp. En las "
            "tablas A.9.5-1 y A.9.6-1, se dan las condiciones para los "
            "valores de Rp, mínimos permitidos para cada grado de "
            "desempeño, los cuales varían entre 0.5 y 6.0, según "
            "A.9.4.9.\n\n"
            "A.9.4.3 — CAPACIDAD DE DEFORMACIÓN — Los elementos no "
            "estructurales al verse sometidos a los movimientos sísmicos "
            "de diseño sufren desplazamientos con respecto a la "
            "estructura de la edificación que no deben exceder las "
            "holguras de separación que se dejen, o deformaciones del "
            "mismo elemento que pongan en peligro su integridad. Los "
            "desplazamientos de verificación de los elementos no "
            "estructurales y sus anclajes o amarres se fijan en función "
            "de las derivas máximas aceptables para la estructura que se "
            "prescriben en el Capítulo A.6 del Reglamento. Por lo tanto, "
            "deben tenerse en cuenta en el diseño que el elemento debe "
            "ser capaz de resistir, sin sufrir un nivel de daño mayor que "
            "el admisible para su grado de desempeño, las deformaciones "
            "que le impone la respuesta sísmica de la estructura."
        ),
    },
    {
        "id": "NSR10-A-A_9_4_4_a_4_7_aplicacion_transferencia_otras_esfuerzos",
        "seccion": "A.9.4.4 a A.9.4.7 — Aplicación y transferencia de fuerzas sísmicas, otras solicitaciones y método de esfuerzos de trabajo",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.4.4 — APLICACIÓN DE LAS FUERZAS SÍSMICAS — Las fuerzas "
            "sísmicas sobre cualquier elemento no estructural actúan de "
            "acuerdo con la distribución de la masa y la rigidez del "
            "elemento. Se permite suponer que se aplican en el centro de "
            "gravedad del elemento, teniendo en cuenta que éstas pueden "
            "obrar en cualquier dirección horizontal. Para efectos del "
            "diseño de los elementos mecánicos y eléctricos, debe "
            "tenerse en cuenta en el diseño una fuerza vertical que actúa "
            "hacia arriba o hacia abajo, adicional a su peso, igual a un "
            "tercio de él, la cual no debe amplificarse por los "
            "coeficientes ax ni ap, ni dividirse por el coeficiente "
            "Rp.\n\n"
            "A.9.4.5 — TRANSFERENCIA DE LAS FUERZAS SÍSMICAS — Los "
            "elementos no estructurales que requieran ser diseñados para "
            "resistir fuerzas sísmicas, deben amarrarse o anclarse de tal "
            "manera que estas fuerzas sean finalmente transferidas a la "
            "estructura de la edificación. El amarre debe ser una "
            "conexión o anclaje que permita resistir tensiones y "
            "compresiones, sin contar con efectos de fricción, ni de "
            "resistencia a la tensión de morteros de pega.\n\n"
            "A.9.4.6 — OTRAS SOLICITACIONES — El diseñador de los "
            "elementos no estructurales debe tener en cuenta en sus "
            "diseños las demás solicitaciones que puedan afectar el "
            "comportamiento de los elementos no estructurales, de las "
            "mencionadas en el Título B del Reglamento.\n\n"
            "A.9.4.7 — DISEÑO UTILIZANDO EL MÉTODO DE ESFUERZOS DE "
            "TRABAJO — Cuando el material del elemento no estructural se "
            "diseña utilizando el método de esfuerzos de trabajo, tal "
            "como lo define B.2.3, las fuerzas sísmicas reducidas de "
            "diseño, E, que se determinan de acuerdo con los requisitos "
            "del presente Capítulo, debe multiplicarse por un "
            "coeficiente de carga de 0.7, tal como lo indican las "
            "combinaciones de carga de B.2.3 para obtener las fuerzas "
            "sísmicas reducidas de trabajo, que se utilizan en el diseño "
            "de los elementos y sus anclajes."
        ),
    },
    {
        "id": "NSR10-A-A_9_4_8_a_4_10_elementos_base_anclajes_conexion",
        "seccion": "A.9.4.8 a A.9.4.10 — Elementos en la base, tipos de anclaje según Rp y elementos de conexión",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.4.8 — ELEMENTOS NO ESTRUCTURALES LOCALIZADOS EN LA BASE "
            "DE LA ESTRUCTURA Y POR DEBAJO DE ELLA, O FUERA DE ELLA — Los "
            "elementos no estructurales, localizados a la altura, o por "
            "debajo, de la base de la estructura, o por fuera de ella, "
            "deben diseñarse para unas fuerzas sísmicas reducidas de "
            "diseño determinadas de acuerdo con la ecuación A.9.4-1, "
            "para una aceleración ax igual a Aa·I.\n\n"
            "A.9.4.9 — TIPOS DE ANCLAJE SEGÚN EL VALOR DE Rp PERMITIDO "
            "PARA EL ELEMENTO NO ESTRUCTURAL — Los sistemas de anclaje de "
            "los elementos no estructurales deben tener capacidad de "
            "disipación de energía en el rango inelástico y ductilidad "
            "compatible con el nivel mínimo de Rp requerido para el "
            "elemento no estructural. A continuación se indican algunos "
            "de los tipos de anclaje empleados en el medio y su grado de "
            "aceptabilidad para los diferentes valores de Rp:\n\n"
            "A.9.4.9.1 — Especiales (Rp = 6) — Se trata de anclajes "
            "diseñados siguiendo los requisitos del Título F para "
            "estructuras acero estructural para capacidad de disipación "
            "especial (DES). Deben cumplirse todos los requisitos dados "
            "allí para permitir este valor de Rp.\n\n"
            "A.9.4.9.2 — Dúctiles (Rp = 6) — Cuando el anclaje se realiza "
            "por medio de anclajes profundos que emplean químicos "
            "(epóxicos), anclajes profundos vaciados en el sitio, o "
            "anclajes vaciados en el sitio que cumplen los requisitos "
            "del Capítulo C.21. No se permiten los pernos de expansión "
            "ni anclajes colocados por medios explosivos (tiros). "
            "Anclajes profundos son aquellos en los cuales la relación "
            "entre la porción embebida al diámetro del perno es mayor de "
            "8. Este tipo de anclajes debe emplearse cuando el elemento "
            "no estructural es dúctil.\n\n"
            "A.9.4.9.3 — No dúctiles (Rp = 1.5) — Cuando el anclaje se "
            "realiza por medio de pernos de expansión, anclajes "
            "superficiales que emplean químicos (epóxicos), anclajes "
            "superficiales vaciados en el sitio, o anclajes colocados "
            "por medio explosivos (tiros). Anclajes superficiales son "
            "aquellos en los cuales la relación entre la porción "
            "embebida al diámetro del perno es menor de 8. Dentro de "
            "este tipo de anclajes se encuentran las barras de acero de "
            "refuerzo con ganchos en los extremos que se embeben dentro "
            "del mortero de pega de la mampostería. Este tipo de "
            "anclajes se permiten cuando el elemento no estructural no "
            "es dúctil. Si se utilizan en elementos no estructurales "
            "dúctiles, éstos deben diseñarse para el mismo valor de Rp = "
            "1.5.\n\n"
            "A.9.4.9.4 — Húmedos (Rp = 0.5) — Cuando se utiliza mortero, "
            "o adhesivos que pegan directamente al mortero o al concreto, "
            "sin ningún tipo de anclaje mecánico resistente a "
            "tracción.\n\n"
            "A.9.4.10 — ELEMENTOS DE CONEXIÓN PARA COMPONENTES NO "
            "ESTRUCTURALES — El elemento de conexión es el aditamento que "
            "conecta el elemento no estructural con los anclajes a la "
            "estructura. En algunos casos es el mismo elemento de "
            "anclaje. Las conexiones que permiten movimiento deben "
            "disponerse de tal manera que pueda haber movimiento relativo "
            "entre la estructura y el elemento no estructural, por medio "
            "de agujeros alargados, agujeros de un tamaño mayor que los "
            "espigos o tornillos, por medio de elemento de acero que se "
            "flexionan, u otros procedimientos, pero debe ser capaz de "
            "resistir las fuerzas sísmicas reducidas de diseño prescritas "
            "en las direcciones en las cuales no se permite el "
            "movimiento. En fachadas el elemento de conexión en sí, debe "
            "diseñarse para resistir una fuerza sísmica reducida de "
            "diseño igual a 1.33Fp y todos los pernos, tornillos, "
            "soldaduras, y espigos que pertenezcan al sistema de "
            "conexión, deben diseñarse para 3.0Fp."
        ),
    },
    {
        "id": "NSR10-A-A_9_5_1_a_5_2_acabados_general_especial_cuidado",
        "seccion": "A.9.5.1 y A.9.5.2 — Acabados y elementos arquitectónicos: general y elementos que requieren especial cuidado",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.5 — ACABADOS Y ELEMENTOS ARQUITECTÓNICOS\n\n"
            "A.9.5.1 — GENERAL — Los acabados y elementos arquitectónicos "
            "enumerados en la tabla A.9.5-1 y sus anclajes a la "
            "estructura deben diseñarse y detallarse de acuerdo con los "
            "requisitos de esta sección. Los cálculos y diseños de los "
            "elementos arquitectónicos y acabados deben incluirse como "
            "parte de las memorias de diseño de acabados.\n\n"
            "A.9.5.2 — ELEMENTOS QUE REQUIEREN ESPECIAL CUIDADO EN SU "
            "DISEÑO — El comportamiento sísmico de algunos elementos no "
            "estructurales representan un peligro especialmente grave "
            "para la vida y en otros casos pueden llevar a la falla de "
            "elementos estructurales críticos, como pueden ser las "
            "columnas. Dentro de estos elementos se encuentran, entre "
            "otros, los siguientes:\n\n"
            "(a) Muros de fachada — las fachadas deben diseñarse y "
            "construirse para que sus componentes no se disgreguen como "
            "consecuencia del sismo, y además el conjunto debe amarrarse "
            "adecuadamente a la estructura con el fin de que no exista "
            "posibilidad de que caiga poniendo en peligro a los "
            "transeúntes al nivel de calzada. Para sistemas vidriados de "
            "fachadas véase el Capítulo K4.\n\n"
            "(b) Muros interiores — deben tenerse precauciones para "
            "evitar el vuelco de los muros interiores y particiones. "
            "Para sistemas vidriados de fachadas véase el Capítulo K4.\n\n"
            "(c) Cielos rasos — el desprendimiento y caída de los cielos "
            "rasos representa un peligro grave para las personas.\n\n"
            "(d) Enchapes de fachada — el desprendimiento y caída de los "
            "enchapes de fachada representa un peligro grave para los "
            "transeúntes. Los enchapes deben ser considerados para su "
            "diseño como un sistema que involucra todos sus componentes "
            "(soporte, morteros de relleno o revoque, adhesivos y "
            "enchape). Especial consideración deberá prestarse en el "
            "diseño de las movimientos del sistema de fachada por "
            "efectos de temperatura, cambios de humedad, integridad por "
            "meteorización, o deformación del soporte.\n\n"
            "(e) Áticos, parapetos y antepechos — existe el mismo peligro "
            "potencial que presentan los muros de fachada. Cuando la "
            "cubierta de la edificación esté compuesta por tejas o "
            "elementos frágiles debe considerarse en el diseño la "
            "posibilidad de que el parapeto falle hacia adentro, cayendo "
            "sobre la cubierta, produciendo su falla y poniendo en "
            "peligro a los habitantes del último piso.\n\n"
            "(f) Vidrios — la rotura de vidrios generada por la "
            "deformación del marco de la ventana representa un peligro "
            "para las personas que estén dentro o fuera de la "
            "edificación. Deben tenerse precauciones para dejar holguras "
            "suficientes dentro del montaje del vidrio o de la ventanería "
            "para evitar su rotura o garantizar que la rotura se "
            "produzca de forma segura. La colocación de películas "
            "protectoras, vidrios templados y vidrios triplicados son "
            "otras alternativas para evitar el peligro asociado con la "
            "rotura del vidrio. La utilización de vidrios de seguridad "
            "es una alternativa para disminuir el riesgo asociado a la "
            "rotura de vidrio. Para especificaciones de vidrio, "
            "productos de vidrio y sistemas vidriados, véase el Capítulo "
            "K4.\n\n"
            "(g) Paneles prefabricados de fachada — cuando se utilicen "
            "paneles prefabricados de fachada, deben dejarse holguras "
            "suficientes que permitan la deformación de la estructura "
            "sin afectar el panel. Además el panel debe estar "
            "adecuadamente adherido al sistema estructural de resistencia "
            "sísmica, para evitar su desprendimiento. En caso que ellos "
            "sean de vidrio, véase Capítulo K4.\n\n"
            "(h) Columnas cortas o columnas cautivas — ciertos tipos de "
            "interacción entre los elementos no estructurales y la "
            "estructura de la edificación deben evitarse a toda costa. "
            "Dentro de este tipo de interacción se encuentra el caso de "
            "las \"columnas cortas\" o \"columnas cautivas\" en las "
            "cuales la columna está restringida en su desplazamiento "
            "lateral por un muro no estructural que no llega hasta la "
            "losa de entrepiso en su parte superior. En este caso el "
            "muro debe separarse de la columna, o ser llevado hasta la "
            "losa de entrepiso en su parte superior, si se deja adherido "
            "a la columna."
        ),
    },
    {
        "id": "NSR10-A-A_9_5_3_a_5_8_fuerzas_diseno_viento_anclaje_deformacion_perpendicular_cielos",
        "seccion": "A.9.5.3 a A.9.5.8 — Fuerzas sísmicas y de viento, anclaje de fachadas, capacidad de deformación y cielos rasos",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.5.3 — FUERZAS SÍSMICAS DE DISEÑO — Los elementos "
            "arquitectónicos y acabados y sus anclajes a la estructura "
            "deben diseñarse para resistir las fuerzas sísmicas reducidas "
            "de diseño determinadas por medio de la ecuación A.9.4-1, "
            "empleando los coeficientes dados en la tabla A.9.5-1.\n\n"
            "A.9.5.4 — FUERZAS DE VIENTO — Cuando las fuerzas de viento, "
            "positivas o negativas, sobrepasen 0.7Fp para muros no "
            "estructurales de fachada, estas fuerzas deben ser las "
            "empleadas en diseño del elemento no estructural, y sus "
            "anclajes deben diseñarse para resistir 1.4 veces las "
            "fuerzas de viento.\n\n"
            "A.9.5.5 — ANCLAJE DE LAS FACHADAS — Los anclajes y amarres "
            "de los muros no estructurales de fachada, a la estructura de "
            "la edificación y a los muros interiores, deben ser capaces "
            "de resistir las fuerzas sísmicas reducidas de diseño "
            "obtenidas por medio de la ecuación A.9.4-1 y además deben "
            "tener la suficiente ductilidad y capacidad de rotación para "
            "aceptar desplazamientos, en cada piso, entre su base y la "
            "parte superior, iguales a la deriva de diseño, calculada de "
            "acuerdo con los requisitos del Capítulo A.6. El muro debe "
            "ser capaz de resistir la flexión que le imponen las fuerzas "
            "sísmicas reducidas de diseño actuando en una dirección "
            "perpendicular al plano del muro.\n\n"
            "A.9.5.6 — CAPACIDAD DE DEFORMACIÓN — Los acabados y "
            "elementos arquitectónicos deben ser capaces de resistir, "
            "con el nivel de daño aceptable para el grado de desempeño "
            "correspondiente, las deformaciones dictadas por la deriva, "
            "calculada de acuerdo con los requisitos del Capítulo A.6. En "
            "los elementos no estructurales y acabados colocados sobre "
            "elementos estructurales en voladizo debe tenerse en cuenta "
            "la deflexión vertical causada por la rotación en el apoyo "
            "del voladizo.\n\n"
            "A.9.5.7 — FUERZAS SÍSMICAS EN LA DIRECCIÓN PERPENDICULAR AL "
            "PLANO DEL MURO NO ESTRUCTURAL — En el diseño de los muros no "
            "estructurales ante fuerzas sísmicas perpendiculares al plano "
            "del muro debe verificarse que las deflexiones del muro "
            "causadas por estas fuerzas no excedan la capacidad de "
            "deformación del muro.\n\n"
            "A.9.5.8 — CIELOS RASOS — Deben tenerse en cuenta en el "
            "diseño de los sistemas de cielo raso la interacción de los "
            "elementos arquitectónicos, hidráulicos, mecánicos y "
            "eléctricos que se incorporen dentro de él."
        ),
    },
    {
        "id": "NSR10-A-A_9_tabla_9_5_1_coeficientes_ap_rp_acabados",
        "seccion": "Tabla A.9.5-1 — Coeficientes ap y Rp para elementos arquitectónicos y acabados",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "Tabla A.9.5-1 — Coeficiente de amplificación dinámica, ap, "
            "y tipo de anclajes o amarres requeridos, usado para "
            "determinar el coeficiente de capacidad de disipación de "
            "energía, Rp, para elementos arquitectónicos y acabados "
            "(Elemento no estructural | ap | tipo de anclaje/amarre por "
            "grado de desempeño Superior/Bueno/Bajo):\n\n"
            "Fachadas — paneles prefabricados apoyados arriba y abajo: "
            "ap=1.0, dúctiles/no dúctiles/no dúctiles.\n"
            "Fachadas — en vidrio apoyadas arriba y abajo: ap=1.0, "
            "dúctiles/no dúctiles/no dúctiles.\n"
            "Fachadas — lámina en yeso, con costillas de acero: ap=1.0, "
            "no dúctiles/no dúctiles/no dúctiles.\n"
            "Fachadas — mampostería reforzada, separada lateralmente de "
            "la estructura, apoyadas arriba y abajo: ap=1.0, dúctiles/no "
            "dúctiles/no dúctiles.\n"
            "Fachadas — mampostería reforzada, separada lateralmente de "
            "la estructura, apoyadas solo abajo: ap=2.5, dúctiles/no "
            "dúctiles/no dúctiles.\n"
            "Fachadas — mampostería no reforzada, separada lateralmente "
            "de la estructura, apoyadas arriba y abajo: ap=1.0, no se "
            "permite este tipo de elemento/no se permite/no dúctiles "
            "(Nota 1).\n"
            "Fachadas — mampostería no reforzada, separada lateralmente "
            "de la estructura, apoyadas solo abajo: ap=2.5, no se "
            "permite/no se permite/no dúctiles (Nota 1).\n"
            "Fachadas — mampostería no reforzada, confinada por la "
            "estructura: ap=1.0, no se permite/no se permite/no dúctiles "
            "(Nota 2).\n"
            "Muros que encierran puntos fijos y ductos de escaleras, "
            "ascensores, y otros: ap=1.0, dúctiles/no dúctiles/húmedos "
            "(Nota 1).\n"
            "Muros divisorios y particiones — corredores en áreas "
            "públicas: ap=1.0, dúctiles/no dúctiles/húmedos (Nota 1).\n"
            "Muros divisorios y particiones — muros divisorios de altura "
            "total: ap=1.0, no dúctiles/no dúctiles/húmedos (Nota 1).\n"
            "Muros divisorios y particiones — muros divisorios de altura "
            "parcial: ap=2.5, no dúctiles/no dúctiles/húmedos (Nota 1).\n"
            "Elementos en voladizo vertical — áticos, parapetos y "
            "chimeneas: ap=2.5, dúctiles/no dúctiles/no dúctiles.\n"
            "Anclaje de enchapes de fachada: ap=1.0, dúctiles/no "
            "dúctiles/húmedos.\n"
            "Altillos: ap=1.5, dúctiles/no dúctiles/no dúctiles.\n"
            "Cielos rasos: ap=1.0, no dúctiles/no dúctiles/no requerido "
            "(Nota 3).\n"
            "Anaqueles, estanterías y bibliotecas de más de 2.50 m de "
            "altura, incluyendo el contenido — diseñadas de acuerdo al "
            "Título F: ap=2.5, especiales/dúctiles/no requerido (Nota "
            "3).\n"
            "Anaqueles, estanterías y bibliotecas de más de 2.50 m de "
            "altura, incluyendo el contenido — otras: ap=2.5, dúctiles/no "
            "dúctiles/no requerido (Nota 3).\n"
            "Tejas: ap=1.0, no dúctiles/no dúctiles/no requerido (Nota "
            "3).\n\n"
            "Notas: (1) Debe verificarse que el muro no pierde su "
            "integridad al ser sometido a las derivas máximas calculadas "
            "para la estructura. (2) Además de (1) debe verificarse que "
            "no interactúa adversamente con la estructura. (3) El "
            "elemento no estructural no requiere diseño y verificación "
            "sísmica. (4) En el diseño, fabricación y supervisión del "
            "montaje de sistemas de estanterías deberán seguirse los "
            "lineamientos aplicables establecidos en la sección A.1.3.4 "
            "para su diseño estructural, y las demás condiciones que se "
            "estipulen al respecto en el Título F."
        ),
    },
    {
        "id": "NSR10-A-A_9_6_instalaciones_hidraulicas_mecanicas_electricas",
        "seccion": "A.9.6 — Instalaciones hidráulicas, sanitarias, mecánicas y eléctricas",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "A.9.6 — INSTALACIONES HIDRÁULICAS, SANITARIAS, MECÁNICAS Y "
            "ELÉCTRICAS\n\n"
            "A.9.6.1 — GENERAL — Los elementos no estructurales "
            "enumerados en la tabla A.9.6-1 y sus anclajes a la "
            "estructura deben diseñarse y detallarse de acuerdo con los "
            "requisitos de esta sección. Los cálculos y diseños de los "
            "elementos de instalaciones hidráulicas, sanitarias, "
            "mecánicas y eléctricas deben incluirse como parte de las "
            "memorias de diseño de cada uno de los sistemas. Puede "
            "hacerse un análisis del mecanismo de soporte de sus "
            "componentes, de acuerdo con principios establecidos de "
            "dinámica estructural, para justificar una reducción de las "
            "fuerzas determinadas en A.9.6.2. Deben investigarse los "
            "estados de esfuerzos combinados tales como tensión y "
            "cortante en los pernos de anclaje, de acuerdo con "
            "principios establecidos de mecánica estructural.\n\n"
            "A.9.6.2 — FUERZAS SÍSMICAS DE DISEÑO — Los componentes "
            "hidráulicos, mecánicos y eléctricos y sus anclajes deben "
            "diseñarse para fuerzas sísmicas reducidas de diseño "
            "determinadas por medio de la ecuación A.9.4-1, empleando "
            "los coeficientes dados en la tabla A.9.6-1.\n\n"
            "A.9.6.3 — SOPORTES — Los sistemas de soporte deben "
            "diseñarse para las fuerzas sísmicas reducidas de diseño "
            "definidas en A.9.6.2 y de acuerdo con los requisitos "
            "correspondientes del material estructural del soporte, de "
            "acuerdo con lo establecido en el Título correspondiente al "
            "material estructural. Los soportes deben ser capaces de "
            "resistir los desplazamientos de la estructura inducidos por "
            "los movimientos sísmicos, calculados de acuerdo con los "
            "requisitos del Capítulo A.6.\n\n"
            "A.9.6.4 — EMPATES CON LAS REDES DE SERVICIOS PÚBLICOS — "
            "Deben disponerse conexiones flexibles en los empates con "
            "las redes de servicios públicos en todos los casos en los "
            "cuales el empate está localizado en un lugar donde la "
            "estructura se puede desplazar con respecto al terreno como "
            "consecuencia de los movimientos sísmicos. El empate "
            "flexible debe ser capaz de resistir, sin daño, unos "
            "desplazamientos calculados como lo indica el Capítulo "
            "A.6.\n\n"
            "A.9.6.5 — INTERRUPTORES AUTOMÁTICOS — En los empates con "
            "las redes de servicios públicos de electricidad y de gas, "
            "en edificaciones que pertenezcan al grupo de uso IV, "
            "localizadas en zonas de amenaza sísmica intermedia y alta, "
            "debe colocarse, del lado de la edificación, un interruptor "
            "automático. El interruptor automático debe activarse cuando "
            "se presente una aceleración horizontal del terreno mayor "
            "que 0.5Aa.\n\n"
            "A.9.6.6 — ASCENSORES EN EDIFICACIONES DEL GRUPO DE USO IV — "
            "En las edificaciones del grupo de uso IV localizadas en "
            "zonas de amenaza sísmica alta, el diseño, construcción y "
            "montaje de los ascensores debe realizarse cumpliendo los "
            "requisitos de la norma ANSI/ASME A.17.1 \"American National "
            "Standard Safety Code for Elevators and Escalators\", "
            "incluyendo el Apéndice F."
        ),
    },
    {
        "id": "NSR10-A-A_9_tabla_9_6_1_coeficientes_ap_rp_instalaciones",
        "seccion": "Tabla A.9.6-1 — Coeficientes ap y Rp para elementos hidráulicos, mecánicos o eléctricos",
        "titulo": "NSR-10 Título A — Capítulo A.9 — Elementos no estructurales",
        "texto": (
            "Tabla A.9.6-1 — Coeficiente de amplificación dinámica, ap, "
            "y tipo de anclajes o amarres requeridos, usado para "
            "determinar el coeficiente de capacidad de disipación de "
            "energía, Rp, para elementos hidráulicos, mecánicos o "
            "eléctricos (Elemento no estructural | ap | tipo de anclaje/"
            "amarre por grado de desempeño Superior/Bueno/Bajo):\n\n"
            "Sistemas de protección contra el fuego: ap=2.5, dúctiles/no "
            "dúctiles/no dúctiles.\n"
            "Plantas eléctricas de emergencia: ap=1.0, no dúctiles/no "
            "dúctiles/no dúctiles.\n"
            "Maquinaria de ascensores, guías y rieles del ascensor y el "
            "contrapeso: ap=1.0, dúctiles/no dúctiles/no requerido "
            "(Nota g).\n"
            "Equipo en general (calderas, hornos, incineradores, "
            "calentadores de agua y otros equipos que utilicen "
            "combustibles y sus chimeneas y escapes; sistemas de "
            "comunicación; ductos eléctricos, cárcamos y bandejas de "
            "cables; equipo eléctrico, transformadores, subestaciones, "
            "motores, etc.; bombas hidráulicas; tanques, condensadores, "
            "intercambiadores de calor, equipos de presión; empates con "
            "las redes de servicios públicos): ap=1.0, dúctiles/no "
            "dúctiles/no requerido (Nota g).\n"
            "Maquinaria de producción industrial: ap=1.0, dúctiles/no "
            "dúctiles/húmedos.\n"
            "Sistemas de tuberías — tuberías de gases y combustibles: "
            "ap=2.5, dúctiles/no dúctiles/no dúctiles.\n"
            "Sistemas de tuberías — tuberías del sistema contra "
            "incendio: ap=2.5, dúctiles/no dúctiles/no dúctiles.\n"
            "Sistemas de tuberías — otros sistemas de tuberías: ap=2.5, "
            "no dúctiles/no requerido/no requerido (Nota g).\n"
            "Sistemas de aire acondicionado, calefacción y ventilación, "
            "y sus ductos: ap=1.0, dúctiles/no dúctiles/no requerido "
            "(Nota g).\n"
            "Paneles de control y gabinetes eléctricos: (sin ap listado), "
            "no dúctiles/no dúctiles/no requerido (Nota g).\n"
            "Luminarias y sistemas de iluminación: ap=1.0, no dúctiles/no "
            "dúctiles/no requerido (Nota g).\n\n"
            "Notas: (a) Véase las exenciones en A.9.1.3. (b) Los valores "
            "de ap dados son para la componente horizontal. Para la "
            "componente vertical deben incrementarse en un 33%. (c) No "
            "hay necesidad de disponer soportes sísmicos para las "
            "bandejas de cables eléctricos en las siguientes "
            "situaciones: (1) Ductos y bandejas de cables colgados de "
            "soportes individuales que tienen 300 mm o menos de "
            "longitud, (2) en espacios para equipos mecánicos y "
            "calderas, donde el ducto tiene menos de 30 mm de diámetro "
            "interior, (3) cualquier ducto eléctrico de menos de 65 mm de "
            "diámetro interior, localizado en otros espacios. (d) No hay "
            "necesidad de disponer soportes sísmicos para las tuberías "
            "en las siguientes situaciones: (1) tuberías colgadas de "
            "soportes individuales que tienen 300 mm o menos de "
            "longitud, (2) en espacios para equipos mecánicos y "
            "calderas, donde la tubería tiene menos de 30 mm de diámetro "
            "interior, (3) cualquier tubería de menos de 65 mm de "
            "diámetro interior, localizado en otros espacios. (e) No hay "
            "necesidad de disponer soportes sísmicos para los ductos de "
            "calefacción, ventilación y aire acondicionado en las "
            "siguientes situaciones: (1) ductos colgados de soportes "
            "individuales que tienen 300 mm o menos de longitud, (2) "
            "ductos que tienen una sección con un área menor de 0.60 m². "
            "(f) Las luminarias dispuestas como péndulos deben diseñarse "
            "utilizando un valor de ap igual a 1.5. El soporte vertical "
            "debe diseñarse con un factor de seguridad igual a 4.0. (g) "
            "El elemento no estructural no requiere diseño y "
            "verificación sísmica."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])

    print(f"Borrando {len(IDS_A_BORRAR_CONDENSADOS)} chunks condensados (no verbatim) de A.9...")
    sb.table("nsr10_chunks").delete().in_("id", IDS_A_BORRAR_CONDENSADOS).execute()

    print("Cargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

    textos = [c["texto"] for c in CHUNKS]
    print(f"Codificando {len(textos)} chunks...")
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print(f"\nSubiendo {len(rows)} chunks a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()
    print("OK.")


if __name__ == "__main__":
    main()
