"""
Ingesta verbatim de Título A, Capítulo A.3 (Requisitos generales de
diseño sismo resistente) -- NSR-10. Fase 5 del plan de cierre del
Título A (2026-09-22), auditoría real de numerales confirmó A.3 en
13/88 (faltan 75) -- el capítulo más citado de todo el título (todos
los demás capítulos remiten a "el sistema estructural definido en el
Capítulo A.3", "el coeficiente R", "las irregularidades de la tabla
A.3-6/A.3-7").

**Hallazgo real durante la Fase 5**: al inspeccionar el contenido ya
cargado en Supabase antes de escribir este script, se encontró que
buena parte de A.3.1, A.3.2, A.3.4 y A.3.8-A.3.9 (IDs
`NSR10-A3-A_3_1_r*`, `NSR10-A3-A_3_2_r*`, `NSR10-A3-A_3_4_r*`,
`NSR10-A-A_3_8_a_A_3_9_r*`) NO es verbatim -- es texto condensado/
parafraseado de una ingesta anterior (mismo patrón ya documentado para
A.9/A.10/A.3.3/B.3.4/Título J). Ejemplo real encontrado:
`NSR10-A3-A_3_2_r1` dice "Se reconocen CUATRO sistemas estructurales..."
en vez del texto real "A.3.2.1 — TIPOS DE SISTEMAS DE RESISTENCIA
SÍSMICA — Se reconocen cuatro tipos generales...". Ese lote de chunks
condensados se BORRA en este script (ver `IDS_A_BORRAR_CONDENSADOS`)
y se reemplaza por el texto verbatim real transcrito aquí.

En cambio SÍ eran verbatim reales y se dejan intactos: A.3.3.1-3.3.9
(`NSR10-A-A_3_3_*`, transcripción correcta ya hecha en una sesión
anterior) y las 4 tablas de coeficientes R0/Ω0 por sistema estructural
(`NSR10-A3-A_3_{1,2,3,4}-R0_TABLA_*`, Tablas A.3-1 a A.3-4) -- no se
retranscriben aquí. Los chunks `NSR10-A-A_3_3_1_R0_acero_r*` (resumen
cruzado de referencia rápida para acero) también se dejan intactos,
son datos numéricos correctos aunque no verbatim literal.

Fuente: NSR-10-81-94.pdf páginas PDF 2-14 (A-39 a A-51, cuerpo del
capítulo) + NSR-10-95-105.pdf páginas PDF 7-9 (A-58 a A-60, Tablas
A.3-5/A.3-6/A.3-7). Leídas visualmente con Read pages= sobre el PDF
nativo -- nunca extracción mecánica (pypdf). Las Figuras A.3-1
(irregularidades en planta) y A.3-2 (irregularidades en altura,
páginas A-61/A-62) son diagramas geométricos -- no se transcriben como
imagen; los criterios numéricos que ilustran (φp, φa, relaciones de
deriva/rigidez/masa) ya están íntegros en el texto de las Tablas A.3-6
y A.3-7, que sí se transcriben completas.

Uso: python _ingest_titulo_a_a3_verbatim.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "A"

# IDs de chunks condensados/parafraseados (no verbatim) que este script
# reemplaza con transcripción real. Se borran en main() antes de subir
# los nuevos chunks verbatim, para no dejar dos versiones (una buena y
# una mala) compitiendo en el retrieval.
IDS_A_BORRAR_CONDENSADOS = (
    [f"NSR10-A3-A_3_1_r{i}" for i in range(1, 5)]
    + [f"NSR10-A3-A_3_2_r{i}" for i in range(1, 6)]
    + [f"NSR10-A3-A_3_4_r{i}" for i in range(1, 7)]
    + [f"NSR10-A-A_3_8_a_A_3_9_r{i}" for i in range(1, 11)]
)

CHUNKS = [
    {
        "id": "NSR10-A-A_3_0_nomenclatura",
        "seccion": "A.3.0 — Nomenclatura del Capítulo A.3",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "CAPÍTULO A.3 — REQUISITOS GENERALES DE DISEÑO SISMO "
            "RESISTENTE\n\n"
            "A.3.0 — NOMENCLATURA\n\n"
            "Aa = coeficiente que representa la aceleración horizontal "
            "pico efectiva, para diseño, dado en A.2.2.\n"
            "Av = coeficiente de aceleración que representa la velocidad "
            "horizontal pico efectiva, para diseño, dado en A.2.2.\n"
            "As = aceleración máxima en la superficie del suelo estimada "
            "como la aceleración espectral correspondiente a un período "
            "de vibración igual a cero, véase ecuación A.3.6-3.\n"
            "Ax = coeficiente de amplificación de la torsión accidental "
            "en el nivel x, definido en A.3.6.7.\n"
            "ai = aceleración en el nivel i, véase ecuación A.3.6-3.\n"
            "E = fuerzas sísmicas reducidas de diseño (E = Fs/R).\n"
            "Fi = parte del cortante sísmico en la base que se genera en "
            "el nivel i, véase ecuación A.3.6.6.\n"
            "Fs = fuerzas sísmicas, véase A.3.1.1.\n"
            "g = aceleración debida a la gravedad (9.8 m/s²).\n"
            "hi = altura en metros, medida desde la base, del nivel i, "
            "véase ecuación A.3.6-3.\n"
            "hn = altura en metros, medida desde la base, del piso más "
            "alto de la edificación, véase ecuación A.3.6-3.\n"
            "heq = altura equivalente del sistema de un grado de libertad "
            "que simula la edificación, véase ecuación A.3.6-3.\n"
            "I = coeficiente de importancia dado en A.2.5.2.\n"
            "M = masa total de la edificación — M se expresa en kg. Debe "
            "ser igual a la masa total de la estructura más la masa de "
            "aquellos elementos tales como muros divisorios y "
            "particiones, equipos permanentes, tanques y sus contenidos, "
            "etc. En depósitos o bodegas debe incluirse además un 25 por "
            "ciento de la masa correspondiente a los elementos que "
            "causan la carga viva del piso. Capítulos A.4 y A.5.\n"
            "Mp = masa de un elemento o componente, en kg.\n"
            "mi = parte de M que está colocada en el nivel i, en kg. "
            "Véase ecuación A.4.3-3.\n"
            "R0 = coeficiente de capacidad de disipación de energía "
            "básico definido para cada sistema estructural y cada grado "
            "de capacidad de disipación de energía del material "
            "estructural. Véase el Capítulo A.3.\n"
            "R = coeficiente de capacidad de disipación de energía para "
            "ser empleado en el diseño, corresponde al coeficiente de "
            "disipación de energía básico, R0, multiplicado por los "
            "coeficientes de reducción de capacidad de disipación de "
            "energía por irregularidades en altura, en planta y por "
            "ausencia de redundancia en el sistema estructural de "
            "resistencia sísmica (R = φa φp φr R0). Véase el Capítulo "
            "A.3.\n"
            "Sa = valor de la aceleración espectral de diseño para un "
            "período de vibración dado. Véase ecuación A.3.6-3.\n"
            "Vx = fuerza cortante sísmica en el nivel x. Véase A.3.6.6.\n"
            "δmax = desplazamiento horizontal máximo en el nivel x. "
            "Véase ecuación A.3.6-2.\n"
            "δprom = promedio de los desplazamientos horizontales en "
            "puntos extremos de la estructura en el nivel x. Véase "
            "ecuación A.3.6-2.\n"
            "φa = coeficiente de reducción de la capacidad de disipación "
            "de energía causado por irregularidades en altura de la "
            "edificación. Véase A.3.3.3.\n"
            "φp = coeficiente de reducción de la capacidad de disipación "
            "de energía causado por irregularidades en planta de la "
            "edificación. Véase A.3.3.3.\n"
            "φr = coeficiente de reducción de la capacidad de disipación "
            "de energía causado por ausencia de redundancia en el "
            "sistema de resistencia sísmica. Véase A.3.3.8.\n"
            "Ω0 = coeficiente de sobrerresistencia. Véase A.3.3.9."
        ),
    },
    {
        "id": "NSR10-A-A_3_1_1_a_1_3_procedimiento_caracteristicas_capacidad",
        "seccion": "A.3.1.1 a A.3.1.3 — Procedimiento de diseño, características de la estructuración y capacidad de disipación mínima requerida",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.1 — BASES GENERALES DE DISEÑO SISMO RESISTENTE\n\n"
            "A.3.1.1 — PROCEDIMIENTO DE DISEÑO — En A.1.3 se establecen "
            "los pasos que se deben seguir en el diseño sismo resistente "
            "de una edificación. En el Capítulo A.2 se establecen los "
            "movimientos sísmicos de diseño. En el presente Capítulo se "
            "establecen:\n\n"
            "(a) Los tipos de sistemas estructurales de resistencia "
            "sísmica, y los diferentes métodos de análisis, los cuales "
            "dependen del grado de irregularidad del sistema estructural "
            "y, además, permiten determinar el cortante sísmico en la "
            "base y su distribución en la altura de la edificación.\n"
            "(b) Determinadas las fuerzas sísmicas correspondientes a "
            "cada nivel, se aplican al sistema estructural de resistencia "
            "sísmica escogido.\n"
            "(c) Por medio de un modelo matemático apropiado se "
            "determinan las deflexiones de la estructura y las fuerzas "
            "internas en cada elemento del sistema estructural producidas "
            "por las fuerzas sísmicas.\n"
            "(d) La verificación de derivas se realiza para las "
            "deflexiones horizontales de la estructura obtenidas del "
            "análisis.\n"
            "(e) Se efectúa el diseño de los elementos y sus conexiones "
            "utilizando todas las solicitaciones requeridas por el "
            "Título B del Reglamento, debidamente combinadas según se "
            "exige allí. Las fuerzas sísmicas obtenidas del análisis Fs, "
            "se reducen, dividiéndolas por el coeficiente de capacidad de "
            "disipación de energía, R, correspondiente al sistema "
            "estructural de resistencia sísmica, para obtener las "
            "fuerzas sísmicas reducidas de diseño (E = Fs/R) que se "
            "emplean en las combinaciones de carga prescritas en el "
            "Título B.\n"
            "(f) El valor del coeficiente de capacidad de disipación de "
            "energía para ser empleado en el diseño, corresponde al "
            "coeficiente de disipación de energía básico, R0, "
            "multiplicado por los coeficientes de reducción de capacidad "
            "de disipación de energía por irregularidades en altura, en "
            "planta, y por ausencia de redundancia en el sistema "
            "estructural de resistencia sísmica (R = φa φp φr R0).\n"
            "(g) Los elementos frágiles de conexión entre elementos y "
            "otros que de acuerdo con los requisitos de los materiales "
            "estructurales que los constituyen requieran el uso del "
            "coeficiente de sobrerresistencia, Ω0, se diseñan utilizando "
            "las fuerzas sísmicas de diseño E obtenidas de la ecuación "
            "A.3.3-2.\n"
            "(h) El diseño de los elementos estructurales y sus "
            "conexiones se realiza cumpliendo los requisitos exigidos "
            "para el grado de capacidad de disipación de energía "
            "requerido del material.\n"
            "(i) Estas fuerzas de diseño de los elementos estructurales "
            "obtenidas siguiendo el procedimiento anotado, son fuerzas al "
            "nivel de la resistencia, o sea que corresponden a fuerzas "
            "mayoradas que ya han sido multiplicadas por sus coeficientes "
            "de carga. Para elementos que se diseñan utilizando el "
            "método de esfuerzos de trabajo, debe consultarse A.3.1.8.\n\n"
            "A.3.1.2 — CARACTERÍSTICAS DE LA ESTRUCTURACIÓN — El sistema "
            "de resistencia sísmica de la edificación debe clasificarse "
            "dentro de uno de los sistema estructurales dados en A.3.2 y "
            "debe cumplir los requisitos indicados en el presente Título "
            "A del Reglamento y los propios del material estructural que "
            "se indiquen en el Título correspondiente y para el grado de "
            "disipación de energía en el rango inelástico apropiado. Los "
            "efectos sísmicos sobre los elementos estructurales que no "
            "hacen parte del sistema de resistencia sísmica deben "
            "evaluarse siguiendo los requisitos del Capítulo A.8. Los "
            "efectos sísmicos sobre los elementos no estructurales deben "
            "evaluarse siguiendo los requisitos del Capítulo A.9.\n\n"
            "A.3.1.3 — CAPACIDAD DE DISIPACIÓN DE ENERGÍA MÍNIMA "
            "REQUERIDA — Dependiendo del tipo de material estructural y "
            "de las características del sistema de resistencia sísmica "
            "se establecen los grados de capacidad de disipación de "
            "energía mínimos (DES, DMO, o DMI) que debe cumplir el "
            "material estructural en las diferentes zonas de amenaza "
            "sísmica definidas en el Capítulo A.2. Véanse las tablas "
            "A.3-1 a A.3-4."
        ),
    },
    {
        "id": "NSR10-A-A_3_1_4_a_1_8_resistencia_trayectoria_isostatico_prefabricados_esfuerzos",
        "seccion": "A.3.1.4 a A.3.1.8 — Resistencia en direcciones horizontales, trayectoria de fuerzas, sistemas isostáticos, prefabricados y esfuerzos de trabajo",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.1.4 — RESISTENCIA SÍSMICA EN LAS DIFERENTES DIRECCIONES "
            "HORIZONTALES — Dado que los efectos sísmicos pueden ser "
            "preponderantes en cualquier dirección horizontal, la "
            "estructura debe tener resistencia sísmica en todas las "
            "direcciones y por lo tanto el sistema estructural de "
            "resistencia sísmica debe existir en dos direcciones "
            "ortogonales o aproximadamente ortogonales, de tal manera que "
            "se garantice la estabilidad, tanto de la estructura "
            "considerada como un todo, como de cada uno de sus "
            "elementos, ante movimientos sísmicos que puedan ocurrir en "
            "cualquier dirección horizontal.\n\n"
            "A.3.1.5 — TRAYECTORIA DE LAS FUERZAS — Las fuerzas deben "
            "transferirse desde su punto de aplicación hasta su punto "
            "final de resistencia. Por lo tanto debe proveerse una "
            "trayectoria o trayectorias continuas, con suficiente "
            "resistencia y rigidez para garantizar el adecuado traspaso "
            "de las fuerzas. La cimentación debe diseñarse para los "
            "efectos de las fuerzas y movimientos sísmicos.\n\n"
            "A.3.1.6 — SISTEMAS DE RESISTENCIA SÍSMICA ISOSTÁTICOS — En "
            "lo posible el sistema estructural de resistencia sísmica "
            "debe ser hiperestático. En el diseño de edificaciones donde "
            "el sistema de resistencia sísmica no sea hiperestático, "
            "debe tenerse en cuenta el efecto adverso que implicaría la "
            "falla de uno de los miembros o conexiones en la estabilidad "
            "de la edificación.\n\n"
            "A.3.1.7 — SISTEMAS ESTRUCTURALES DE RESISTENCIA SÍSMICA "
            "PREFABRICADOS — Pueden construirse edificaciones cuyo "
            "sistema de resistencia sísmica esté compuesto por elementos "
            "prefabricados. El sistema prefabricado debe diseñarse para "
            "las fuerzas sísmicas obtenidas de acuerdo con este "
            "Reglamento usando un coeficiente de capacidad de disipación "
            "de energía básico, tal como lo define el Capítulo A.13 igual "
            "a uno y medio (R0 = 1.5). Cuando se demuestre con evidencia "
            "experimental y de análisis, que el sistema propuesto tiene "
            "una resistencia, capacidad de disipación de energía y "
            "capacidad de trabajo en el rango inelástico igual o mayor a "
            "las obtenidas con la estructura construida utilizando uno de "
            "los materiales prescritos por este Reglamento, deben "
            "cumplirse los requisitos de los Artículos 10 y 12 de la Ley "
            "400 de 1997, pero en ningún caso el valor de R0 podrá ser "
            "mayor que el fijado por el presente Reglamento para "
            "sistemas de resistencia sísmica construidos monolíticamente "
            "con el mismo material estructural. Al respecto debe "
            "consultarse A.1.4.2.\n\n"
            "A.3.1.8 — MATERIALES ESTRUCTURALES DISEÑADOS USANDO EL "
            "MÉTODO DE ESFUERZOS DE TRABAJO — Cuando el material "
            "estructural se diseña utilizando el método de esfuerzos de "
            "trabajo, tal como lo define B.2.3 de este Reglamento, para "
            "obtener los efectos de las fuerzas sísmicas reducidas de "
            "diseño al nivel de esfuerzos de trabajo que se emplean en el "
            "diseño de los elementos estructurales debe utilizarse un "
            "coeficiente de carga de 0.7 como se presenta en B.2.3."
        ),
    },
    {
        "id": "NSR10-A-A_3_2_1_tipos_sistemas_resistencia_sismica",
        "seccion": "A.3.2.1 — Tipos de sistemas de resistencia sísmica (muros de carga, combinado, pórtico, dual)",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.2 — SISTEMAS ESTRUCTURALES\n\n"
            "A.3.2.1 — TIPOS DE SISTEMAS DE RESISTENCIA SÍSMICA — Se "
            "reconocen cuatro tipos generales de sistemas estructurales "
            "de resistencia sísmica, los cuales se definen en esta "
            "sección. Cada uno de ellos se subdivide según los tipos de "
            "elementos verticales utilizados para resistir las fuerzas "
            "sísmicas y el grado de capacidad de disipación de energía "
            "del material estructural empleado. Los sistemas "
            "estructurales de resistencia sísmica que reconoce este "
            "Reglamento son los siguientes:\n\n"
            "A.3.2.1.1 — Sistema de muros de carga — Es un sistema "
            "estructural que no dispone de un pórtico esencialmente "
            "completo y en el cual las cargas verticales son resistidas "
            "por los muros de carga y las fuerzas horizontales son "
            "resistidas por muros estructurales o pórticos con "
            "diagonales. Véase la tabla A.3-1.\n\n"
            "A.3.2.1.2 — Sistema combinado — Es un sistema estructural, "
            "(véase la tabla A.3-2), en el cual:\n"
            "(a) Las cargas verticales son resistidas por un pórtico no "
            "resistente a momentos, esencialmente completo, y las "
            "fuerzas horizontales son resistidas por muros estructurales "
            "o pórticos con diagonales, o\n"
            "(b) Las cargas verticales y horizontales son resistidas por "
            "un pórtico resistente a momentos, esencialmente completo, "
            "combinado con muros estructurales o pórticos con diagonales, "
            "y que no cumple los requisitos de un sistema dual.\n\n"
            "A.3.2.1.3 — Sistema de pórtico — Es un sistema estructural "
            "compuesto por un pórtico espacial, resistente a momentos, "
            "esencialmente completo, sin diagonales, que resiste todas "
            "las cargas verticales y fuerzas horizontales. Véase la "
            "tabla A.3-3.\n\n"
            "A.3.2.1.4 — Sistema dual — Es un sistema estructural que "
            "tiene un pórtico espacial resistente a momentos y sin "
            "diagonales, combinado con muros estructurales o pórticos "
            "con diagonales. Véase la tabla A.3-4. Para que el sistema "
            "estructural se pueda clasificar como sistema dual se deben "
            "cumplir los siguientes requisitos:\n"
            "(a) El pórtico espacial resistente a momentos, sin "
            "diagonales, esencialmente completo, debe ser capaz de "
            "soportar las cargas verticales.\n"
            "(b) Las fuerzas horizontales son resistidas por la "
            "combinación de muros estructurales o pórticos con "
            "diagonales, con el pórtico resistente a momentos, el cual "
            "puede ser un pórtico de capacidad especial de disipación de "
            "energía (DES), cuando se trata de concreto reforzado o "
            "acero estructural, un pórtico con capacidad moderada de "
            "disipación de energía (DMO) de concreto reforzado, o un "
            "pórtico con capacidad mínima de disipación de energía (DMI) "
            "de acero estructural. El pórtico resistente a momentos, "
            "actuando independientemente, debe diseñarse para que sea "
            "capaz de resistir como mínimo el 25 por ciento del cortante "
            "sísmico en la base.\n"
            "(c) Los dos sistemas deben diseñarse de tal manera que en "
            "conjunto sean capaces de resistir la totalidad del cortante "
            "sísmico en la base, en proporción a sus rigideces relativas, "
            "considerando la interacción del sistema dual en todos los "
            "niveles de la edificación, pero en ningún caso la "
            "responsabilidad de los muros estructurales, o de los "
            "pórticos con diagonales, puede ser menor del 75 por ciento "
            "del cortante sísmico en la base."
        ),
    },
    {
        "id": "NSR10-A-A_3_2_2_a_2_6_clasificacion_limites_combinacion_elementos",
        "seccion": "A.3.2.2 a A.3.2.6 — Clasificación, límites de altura, combinación de sistemas en altura y en planta, elementos comunes",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.2.2 — CLASIFICACIÓN EN UNO DE LOS SISTEMAS "
            "ESTRUCTURALES — Toda edificación o cualquier parte de ella, "
            "debe quedar clasificada dentro de uno de los cuatro sistemas "
            "estructurales de resistencia sísmica descritos en las "
            "tablas A.3-1 a A.3-4.\n\n"
            "A.3.2.3 — LÍMITES DE ALTURA PARA LOS SISTEMAS ESTRUCTURALES "
            "— En las tablas A.3-1 a A.3-4 se dan las alturas máximas, "
            "medidas en metros a partir de la base o en número de pisos "
            "por encima de la misma, que puede tener cada uno de los "
            "sistemas estructurales de resistencia sísmica prescritos, "
            "para cada una de las zonas de amenaza sísmica.\n\n"
            "A.3.2.4 — COMBINACIÓN DE SISTEMAS ESTRUCTURALES EN LA "
            "ALTURA — Cuando se combinen en la altura diferentes sistemas "
            "estructurales dentro de una misma edificación, deben "
            "cumplirse los siguientes requisitos:\n\n"
            "A.3.2.4.1 — Máximo valor de R permitido — Con la excepción "
            "de lo dispuesto en A.3.2.4.2 a A.3.2.4.4, la estructura que "
            "combine en la altura diferentes sistemas estructurales se "
            "clasifica como irregular del tipo 5aA o 5bA (tabla A.3-7), y "
            "el valor del coeficiente de capacidad de disipación de "
            "energía, R, en cualquier dirección y en cualquier nivel, "
            "como máximo debe ser el menor valor de R de los sistemas "
            "estructurales que se estén combinando por encima de ese "
            "nivel y en la dirección considerada. Deben cumplirse los "
            "requisitos de diseño exigidos para cada sistema estructural "
            "y para cada grado de capacidad de disipación de energía del "
            "material estructural.\n\n"
            "A.3.2.4.2 — Pisos livianos — No hay necesidad de aplicar los "
            "requisitos de A.3.2.4.1 cuando la masa de los pisos "
            "localizados por encima del nivel donde se inicia un sistema "
            "estructural sea menor del 10 por ciento de la masa total, "
            "M, de la edificación.\n\n"
            "A.3.2.4.3 — Estructura flexible apoyada sobre una estructura "
            "con mayor rigidez — En estructuras que tengan una parte "
            "superior flexible apoyada en una con mayor rigidez y que "
            "cumplan los requisitos de la tabla A.3-5, puede utilizarse "
            "el procedimiento de diseño indicado allí.\n\n"
            "A.3.2.4.4 — Estructura rígida apoyada sobre una estructura "
            "con menor rigidez — Este tipo de combinación de sistemas "
            "estructurales en la altura presenta inconvenientes en su "
            "comportamiento sísmico, por lo que para este Reglamento no "
            "es un sistema estructural aceptable.\n\n"
            "A.3.2.5 — COMBINACIÓN DE SISTEMAS ESTRUCTURALES EN PLANTA — "
            "Pueden combinarse sistemas estructurales en planta, sin que "
            "esto dé pié a que la estructura se clasifique como "
            "irregular, con las siguientes limitaciones:\n"
            "(a) Los dos sistemas deben coexistir en toda la altura de "
            "la edificación, a menos que se cumplan los requisitos de "
            "A.3.2.4,\n"
            "(b) Cuando la estructura tiene un sistema de muros de carga "
            "únicamente en una dirección, el valor de R para diseñar la "
            "dirección ortogonal, no puede ser mayor que 1.25 veces el "
            "valor de R del sistema estructural de muros de carga,\n"
            "(c) Cuando la estructura tiene dos sistemas de muros de "
            "carga diferentes en la misma dirección, para el sistema que "
            "tiene el mayor valor de R el valor a emplear no puede ser "
            "mayor que 1.25 veces el valor de R del sistema con el menor "
            "valor de R, y\n"
            "(d) Cuando la estructura tiene sistemas diferentes al de "
            "muros de carga en ambas direcciones, para el sistema que "
            "tiene un mayor valor de R, el valor a emplear no puede ser "
            "mayor que 1.25 veces el valor de R del sistema con el menor "
            "valor de R.\n\n"
            "A.3.2.6 — ELEMENTOS COMUNES A VARIOS SISTEMAS ESTRUCTURALES "
            "— Los elementos estructurales comunes a diferentes sistemas "
            "estructurales deben diseñarse y detallarse siguiendo los "
            "requisitos más restrictivos dentro de los sistemas para los "
            "cuales son comunes."
        ),
    },
    {
        "id": "NSR10-A-A_3_4_1_a_4_3_metodos_analisis_completo",
        "seccion": "A.3.4.1 a A.3.4.3 — Métodos de análisis reconocidos, método a utilizar y rigidez de la estructura",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.4 — MÉTODOS DE ANÁLISIS\n\n"
            "A.3.4.1 — MÉTODOS RECONOCIDOS — Se reconocen los siguientes "
            "métodos de análisis del sistema de resistencia sísmica para "
            "efectos de su diseño:\n"
            "(a) Método de la fuerza horizontal equivalente, el cual "
            "está descrito en el Capítulo A.4,\n"
            "(b) Métodos de análisis dinámico elástico, de acuerdo con "
            "los requisitos del Capítulo A.5,\n"
            "(c) Métodos de análisis dinámico inelástico, de acuerdo con "
            "los requisitos del Capítulo A.5, y\n"
            "(d) Métodos de análisis alternos, los cuales deben tener en "
            "cuenta las características dinámicas de la edificación, el "
            "comportamiento inelástico de los materiales, y deben ser de "
            "aceptación general en la ingeniería. En la aplicación de "
            "cualquier método de análisis alterno no se pueden utilizar "
            "períodos fundamentales mayores de los permitidos en los "
            "Capítulos A.4 y A.5.\n\n"
            "A.3.4.2 — MÉTODO DE ANÁLISIS A UTILIZAR — Como mínimo deben "
            "emplearse los siguientes métodos de análisis:\n\n"
            "A.3.4.2.1 — Método de la fuerza horizontal equivalente — "
            "Puede utilizarse el método de la fuerza horizontal "
            "equivalente en las siguientes edificaciones:\n"
            "(a) Todas las edificaciones, regulares e irregulares, en "
            "las zonas de amenaza sísmica baja,\n"
            "(b) Todas las edificaciones, regulares e irregulares, "
            "pertenecientes al grupo de uso I, localizadas en zonas de "
            "amenaza sísmica intermedia,\n"
            "(c) Edificaciones regulares, de 20 niveles o menos y 60 m "
            "de altura o menos medidos desde la base, en cualquier zona "
            "de amenaza sísmica, exceptuando edificaciones localizadas en "
            "lugares que tengan un perfil de suelo tipo D, E o F, con "
            "periodos de vibración mayores de 2TC,\n"
            "(d) Edificaciones irregulares que no tengan más de 6 "
            "niveles ni 18 m de altura medidos a partir de la base,\n"
            "(e) Estructuras flexibles apoyadas sobre estructuras más "
            "rígidas que cumplan los requisitos de A.3.2.4.3.\n\n"
            "A.3.4.2.2 — Método del análisis dinámico elástico — Debe "
            "utilizarse el método del análisis dinámico elástico en "
            "todas las edificaciones que no estén cubiertas por A.3.4.2.1, "
            "incluyendo las siguientes:\n"
            "(a) Edificaciones de más de 20 niveles o más de 60 m de "
            "altura, exceptuando las edificaciones mencionadas en "
            "A.3.4.2.1 (a) y (b),\n"
            "(b) Edificaciones que tengan irregularidades verticales de "
            "los tipos 1aA, 1bA, 2A y 3A, tal como se definen en A.3.3.5,\n"
            "(c) Edificaciones que tengan irregularidades que no estén "
            "descritas en A.3.3.4 y A.3.3.5, exceptuando el caso descrito "
            "en A.3.2.4.3,\n"
            "(d) Edificaciones de más de 5 niveles o de más de 20 m de "
            "altura, localizadas en zonas de amenaza sísmica alta, que "
            "no tengan el mismo sistema estructural en toda su altura, "
            "con la excepción de lo prescrito en A.3.2.4.3,\n"
            "(e) Estructuras, regulares o irregulares, localizadas en "
            "sitios que tengan un perfil de suelo D, E o F y que tengan "
            "un período mayor que 2TC. En este caso el análisis debe "
            "incluir los efectos de interacción suelo-estructura, tal "
            "como lo prescribe el Capítulo A.7, cuando se realice un "
            "análisis de la estructura suponiéndola empotrada en su "
            "base.\n\n"
            "A.3.4.2.3 — Método del análisis dinámico inelástico — Puede "
            "utilizarse el método del análisis dinámico inelástico en "
            "aquellos casos que a juicio del ingeniero diseñador, se "
            "presenten variaciones en la capacidad de disipación de "
            "energía en el rango inelástico que solo sea posible "
            "identificar por este procedimiento. Cuando se utilice este "
            "método de análisis deben cumplirse los requisitos dados en "
            "el Capítulo A.5. Los diseños realizados por esta metodología "
            "deben revisarse por dos profesionales, independientes del "
            "diseñador estructural, que cumplan los requisitos de "
            "idoneidad requeridos para revisores de diseños estructurales "
            "como lo prescribe la Ley 400 de 1997, quienes suscribirán "
            "un memorial en el que se indique taxativamente que los "
            "procedimientos empleados consultan las mejores metodologías "
            "que se disponga sobre estos procedimientos y que la "
            "edificación así diseñada tiene resistencia y expectativas de "
            "comportamiento similares a los de una edificación diseñada "
            "por los otros métodos permitidos por el Reglamento, al verse "
            "sometida a movimientos sísmicos de intensidad similar a los "
            "movimientos sísmicos de diseño prescritos por este "
            "Reglamento. Este memorial se anexará a los documentos "
            "aportados para obtener la correspondiente licencia de "
            "construcción.\n\n"
            "A.3.4.2.4 — Método de análisis no lineal estático de "
            "plastificación progresiva — Puede utilizarse el método del "
            "análisis no lineal estático, conocido como procedimiento "
            "\"push-over\" o de plastificación progresiva, en aquellos "
            "casos que a juicio del ingeniero diseñador se desee evaluar "
            "la capacidad de disipación de energía en el rango inelástico "
            "por este procedimiento. Cuando se utilice este método de "
            "análisis deben cumplirse los requisitos dados en el "
            "Apéndice A-3 y además se deben confrontar con otro de los "
            "métodos de análisis permitidos por el Reglamento, "
            "utilizando en el diseño lo más exigente.\n\n"
            "A.3.4.3 — RIGIDEZ DE LA ESTRUCTURA Y SUS ELEMENTOS — Las "
            "rigideces que se empleen en el análisis estructural para el "
            "diseño sísmico deben ser definidas por el ingeniero "
            "diseñador de acuerdo con su criterio, teniendo en cuenta los "
            "preceptos dados para cada material estructural en el Título "
            "correspondiente de este Reglamento."
        ),
    },
    {
        "id": "NSR10-A-A_3_5_requisitos_materiales_estructurales",
        "seccion": "A.3.5 — Requisitos para los materiales estructurales",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.5 — REQUISITOS PARA LOS MATERIALES ESTRUCTURALES\n\n"
            "A.3.5.1 — Los requisitos especiales para el diseño y los "
            "detalles propios de cada material estructural se dan para "
            "el grado de capacidad de disipación de energía; mínima "
            "(DMI), moderada (DMO) o especial (DES), que se requiera del "
            "material y para cada uno de los sistemas estructurales de "
            "resistencia sísmica en las tablas A.3-1 a A.3-4."
        ),
    },
    {
        "id": "NSR10-A-A_3_6_1_a_6_4_generalidades_combinacion_direccion_amarres",
        "seccion": "A.3.6.1 a A.3.6.4 — Generalidades, combinación de cargas, dirección de aplicación y amarres/continuidad",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.6 — EFECTOS SÍSMICOS EN LOS ELEMENTOS ESTRUCTURALES\n\n"
            "A.3.6.1 — GENERALIDADES — Todos los elementos estructurales "
            "deben diseñarse para los efectos de los movimientos "
            "sísmicos de diseño que actúen sobre ellos, adicionalmente a "
            "todas las cargas que los puedan afectar, tal como lo "
            "prescribe el Título B de este Reglamento.\n\n"
            "A.3.6.1.1 — Elementos del sistema de resistencia sísmica — "
            "Solamente los elementos que pertenezcan al sistema "
            "estructural de resistencia sísmica pueden contribuir a la "
            "resistencia sísmica de la edificación y deben diseñarse de "
            "acuerdo con los requisitos propios de su material "
            "estructural y para el grado de capacidad de disipación de "
            "energía requerido, además de los requisitos adicionales "
            "dados en la presente sección.\n\n"
            "A.3.6.1.2 — Elementos estructurales que no hacen parte del "
            "sistema de resistencia sísmica — Los elementos estructurales "
            "que no formen parte del sistema estructural de resistencia "
            "sísmica, deben investigarse con el fin de determinar si "
            "pueden mantener su capacidad de resistir cargas verticales "
            "cuando se ven sometidos a los desplazamientos horizontales y "
            "a las derivas, causados por los movimientos sísmicos de "
            "diseño, pero sólo hay necesidad de que cumplan los "
            "requisitos del grado de capacidad de disipación de energía "
            "mínimo para su material estructural. Sus anclajes y amarres "
            "de resistencia sísmica deben cumplir los requisitos dados en "
            "la presente sección y en el Capítulo A.8.\n\n"
            "A.3.6.2 — COMBINACIÓN DE LOS EFECTOS DE CARGA — Los "
            "coeficientes de carga que deben emplearse en la combinación "
            "de cargas de gravedad y de fuerzas sísmicas se establecen "
            "en el Título B de este Reglamento. Debe tenerse en cuenta "
            "que las fuerzas sísmicas obtenidas siguiendo este "
            "Reglamento, están definidas al nivel de resistencia, por lo "
            "tanto ya no están mayoradas.\n\n"
            "A.3.6.3 — DIRECCIÓN DE APLICACIÓN DE LAS FUERZAS SÍSMICAS — "
            "En zonas de amenaza sísmica intermedia o alta deben "
            "considerarse los efectos ortogonales, salvo que (1) la "
            "estructura tenga diafragmas flexibles o (2) se trate de "
            "edificios de un piso (naves industriales o similares) en "
            "los cuales no haya irregularidades en planta del tipo 5P. "
            "Los efectos ortogonales pueden tenerse en cuenta suponiendo "
            "la concurrencia simultánea del 100% de las fuerzas sísmicas "
            "en una dirección y el 30% de las fuerzas sísmicas en la "
            "dirección perpendicular. Debe utilizarse la combinación que "
            "requiera la mayor resistencia del elemento. "
            "Alternativamente, los efectos ortogonales pueden calcularse "
            "como la raíz cuadrada de la suma de los cuadrados de los "
            "efectos producidos por el 100% de las fuerzas sísmicas "
            "actuando independientemente en las dos direcciones "
            "ortogonales, asignándole el signo que conduzca al resultado "
            "más conservador. La fuerza sísmica debe combinarse con las "
            "cargas verticales de acuerdo con los requisitos del Título "
            "B de este Reglamento.\n\n"
            "A.3.6.4 — AMARRES Y CONTINUIDAD — Todos los elementos "
            "estructurales deben interconectarse. La conexión y los "
            "elementos conectores deben ser capaces de transmitir las "
            "fuerzas sísmicas inducidas por las partes que conectan; "
            "además de los requisitos del Capítulo A.8, deben cumplirse "
            "los siguientes requisitos:\n\n"
            "A.3.6.4.1 — Partes de la edificación — Cualquier parte o "
            "porción de la edificación que forme un conjunto "
            "indistintamente diferenciado del resto de la estructura, "
            "pero que esté estructuralmente vinculado a ésta, debe estar "
            "vinculada y amarrada al resto de la edificación por medio de "
            "elementos de conexión cuya resistencia se diseñe teniendo en "
            "cuenta las fuerzas axiales, de corte y de flexión "
            "transmitidas por la interacción entre las partes bajo las "
            "combinaciones de carga especificadas en el Título B. La "
            "fuerza sísmica involucrada, como mínimo, debe ser 0.40·Aa·g "
            "veces la masa de la parte o porción. Es particularmente "
            "importante que, en el caso de esta conexión, en el análisis "
            "no se utilice nudo maestro u otro método de igualación de "
            "grados de libertad para el análisis bajo cargas laterales.\n\n"
            "A.3.6.4.2 — Vigas de amarre en la cimentación — Los "
            "elementos de cimentación, tales como zapatas, dados de "
            "pilotes, pilas o \"caissons\", etc., deben amarrarse por "
            "medio de elementos capaces de resistir en tensión o "
            "compresión una fuerza no menor de 0.25·Aa veces la carga "
            "vertical total del elemento que tenga la mayor carga entre "
            "los que interconecta, además de las fuerzas que le "
            "transmita la superestructura. Para efectos del diseño de la "
            "cimentación debe cumplirse lo prescrito en A.3.7."
        ),
    },
    {
        "id": "NSR10-A-A_3_6_5_a_6_6_colectores_distribucion_cortante",
        "seccion": "A.3.6.5 y A.3.6.6 — Elementos colectores y distribución de la fuerza cortante en el piso",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.6.5 — ELEMENTOS COLECTORES — Deben proveerse elementos "
            "colectores capaces de transferir las fuerzas sísmicas que "
            "se originan en otras partes de la edificación hasta el "
            "elemento vertical del sistema de resistencia sísmica que "
            "resiste esas fuerzas.\n\n"
            "A.3.6.6 — DISTRIBUCIÓN DE LA FUERZA CORTANTE EN EL PISO — "
            "Cuando se utilice el método de la fuerza horizontal "
            "equivalente definido en el Capítulo A.4, la fuerza cortante, "
            "Vx, en el nivel x, debe determinarse de acuerdo con la "
            "siguiente fórmula:\n\n"
            "Vx = Σ(i=x a n) Fi       (A.3.6-1)\n\n"
            "La fuerza cortante, Vx, y las torsiones asociadas deben "
            "distribuirse entre los diferentes pórticos y muros "
            "estructurales del sistema de resistencia sísmica de acuerdo "
            "con sus respectivas rigideces de desplazamiento y teniendo "
            "en cuenta la rigidez del diafragma, de acuerdo con la "
            "definición de la rigidez de los diafragmas dada en A.3.6.7.2."
        ),
    },
    {
        "id": "NSR10-A-A_3_6_7_torsion_piso",
        "seccion": "A.3.6.7 — Torsión en el piso (accidental, no coincidencia centro de masa/rigidez, torsión de diseño)",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.6.7 — TORSIÓN EN EL PISO — En el diseño deben tenerse en "
            "cuenta los efectos de torsión en el piso, considerando que "
            "estos provienen de la incertidumbre en la localización de "
            "las masas dentro del piso, lo cual conduce a una torsión "
            "accidental, o debida a la excentricidad entre el centro de "
            "masas y el centro de rigidez cuando los diafragmas se "
            "consideran rígidos en su propio plano, o de la asimetría en "
            "la distribución de la masa y la rigidez de elementos "
            "verticales, cuando los diafragmas no pueden considerarse "
            "como rígidos en su propio plano. En caso de realizarse "
            "análisis dinámico, el análisis mismo reflejará los efectos "
            "de las torsiones que se tengan en la estructura, quedando a "
            "opción del diseñador si en él involucra o no condiciones de "
            "torsión accidental. En el caso que se utilice el método de "
            "la fuerza horizontal equivalente, para la consideración de "
            "la torsión en el piso deben cumplirse los requisitos de "
            "A.3.6.7.1 a A.3.6.7.3, descritos a continuación.\n\n"
            "A.3.6.7.1 — Torsión accidental — Debe suponerse que la masa "
            "de todos los pisos está desplazada transversalmente, hacia "
            "cualquiera de los dos lados, del centro de masa calculado de "
            "cada piso, una distancia igual al 5 por ciento (0.05) de la "
            "dimensión de la edificación en ese piso, medida en la "
            "dirección perpendicular a la dirección en estudio. El "
            "efecto de la torsión que se genera debe tenerse en cuenta en "
            "la distribución del cortante del piso a los elementos "
            "verticales del sistema de resistencia sísmica. Cuando "
            "existan irregularidades en planta del tipo 1aP o 1bP, tal "
            "como las define A.3.3.4.1 (tabla A.3-6), debe aumentarse la "
            "torsión accidental en cada nivel x, multiplicándola por un "
            "coeficiente de amplificación, Ax, determinado de acuerdo con "
            "la siguiente ecuación:\n\n"
            "Ax = [δmax / (1.2 δprom)]² ≤ 3.0       (A.3.6-2)\n\n"
            "A.3.6.7.2 — Torsión debida a la no coincidencia del centro "
            "de masa y de rigidez — Cuando el diafragma pueda "
            "considerarse rígido en su propio plano, debe tenerse en "
            "cuenta el aumento en los cortantes sobre los elementos "
            "verticales del sistema de resistencia sísmica debida a la "
            "distribución, en planta, de la rigidez de los elementos del "
            "sistema de resistencia sísmica.\n\n"
            "(a) Diafragma flexible — El diafragma puede suponerse "
            "flexible, para los efectos de las prescripciones de esta "
            "sección, cuando la máxima deflexión horizontal dentro del "
            "diafragma, al verse sometido a las fuerzas sísmicas, Fs, es "
            "más de 2 veces el promedio de sus deflexiones horizontales. "
            "Esta determinación de la flexibilidad del diafragma puede "
            "realizarse comparando la deflexión horizontal debida a las "
            "fuerzas sísmicas, obtenida en el punto medio del diafragma, "
            "con la de cada uno de los elementos verticales del sistema "
            "de resistencia sísmica, al verse sometidos a una fuerza "
            "horizontal equivalente a la producida por la masa aferente "
            "al elemento.\n\n"
            "(b) Diafragma rígido en su propio plano — El diafragma puede "
            "suponerse rígido en su propio plano cuando se dispone su "
            "rigidez y su resistencia de tal manera que éste actúe como "
            "una unidad y sus propiedades de masa y de rigidez se puedan "
            "concentrar en el centro de masa y en el centro de rigidez "
            "respectivamente. En las edificaciones que tengan "
            "irregularidades de los tipos 2P y 3P la consideración de "
            "diafragma rígido debe evaluarse cuidadosamente, pues en la "
            "mayoría de los casos estas irregularidades inhiben el "
            "comportamiento como diafragma rígido de los entrepisos de la "
            "edificación.\n\n"
            "A.3.6.7.3 — Torsión de diseño — El momento torsional de "
            "diseño en cualquier nivel de la estructura se obtiene como "
            "la suma de las torsiones de diseño de todos los niveles "
            "localizados por encima del nivel en estudio. La porción de "
            "la torsión aportada por cada nivel se obtiene como la "
            "torsión accidental del nivel, más el producto de la fuerza "
            "sísmica horizontal, correspondiente a ese nivel por una "
            "dimensión igual a la proyección, en la dirección "
            "perpendicular a la dirección de las fuerzas, de la distancia "
            "entre el centro de masa y el centro de rigidez del nivel."
        ),
    },
    {
        "id": "NSR10-A-A_3_6_8_diafragmas",
        "seccion": "A.3.6.8 — Diafragmas (deflexión, fuerzas, amarres, conexiones a zonas irregulares)",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.6.8 — DIAFRAGMAS — En las zonas de amenaza sísmica "
            "intermedia y alta, en el diseño de los pisos y cubiertas "
            "que actúan como diafragmas debe tenerse en cuenta lo "
            "siguiente:\n\n"
            "A.3.6.8.1 — La deflexión en el plano del diafragma no debe "
            "exceder la deflexión permisible de los elementos que estén "
            "adheridos a él. La deflexión permisible debe ser aquella "
            "que permita a los elementos adheridos mantener su "
            "integridad estructural bajo las fuerzas impuestas.\n\n"
            "A.3.6.8.2 — Los diafragmas de piso o de cubierta deben "
            "diseñarse para que sean capaces de resistir las fuerzas "
            "causadas por la aceleración en cada nivel, expresada como "
            "una fracción de la gravedad, determinada por medio de la "
            "siguiente ecuación:\n\n"
            "ai = As + (Sa - As)·hi/heq    para hi ≤ heq\n"
            "ai = Sa · hi/heq             para hi ≥ heq\n"
            "(A.3.6-3)\n\n"
            "heq puede estimarse simplificadamente como 0.75hn.\n\n"
            "Alternativamente a la ecuación A.3.6-3 para calcular las "
            "fuerzas que deben resistir los diafragmas de piso o de "
            "cubierta, pueden usarse estimaciones más precisas de las "
            "aceleraciones absolutas máximas a que estarían sometidos "
            "estos diafragmas, resultado por ejemplo, de análisis "
            "dinámicos.\n\n"
            "Cuando el diafragma debe transmitir fuerzas provenientes de "
            "los elementos verticales del sistema de resistencia sísmica "
            "que se encuentren por encima del diafragma, a elementos "
            "verticales del sistema de resistencia sísmica que se "
            "encuentren por debajo del diafragma, debido a "
            "desplazamientos en la localización de los elementos, o por "
            "cambios en la rigidez de los elementos verticales, las "
            "fuerzas correspondientes se deben adicionar a las obtenidas "
            "por medio de la ecuación A.3.6-3.\n\n"
            "A.3.6.8.3 — Los diafragmas que den apoyo a muros de concreto "
            "reforzado o de mampostería, deben tener amarres continuos "
            "entre los diferentes elementos del diafragma con el fin de "
            "distribuir las fuerzas de anclaje especificadas en A.3.6.10.\n\n"
            "A.3.6.8.4 — Las conexiones del diafragma a los elementos "
            "verticales o a los elementos colectores, o entre elementos "
            "colectores, en estructuras localizadas en zonas de amenaza "
            "sísmica alta que tengan irregularidades en planta de los "
            "tipos 1aP, 1bP, 2P, 3P ó 4P (tabla A.3-6), deben diseñarse "
            "para las fuerzas sísmicas correspondientes, multiplicadas "
            "por 1.25.\n\n"
            "A.3.6.8.5 — En las edificaciones localizadas en zonas de "
            "amenaza sísmica alta que tengan irregularidades en planta "
            "del tipo 2P (tabla A.3-6), los elementos del diafragma deben "
            "diseñarse considerando movimientos independientes de las "
            "alas que se proyectan hacia afuera de la estructura. Cada "
            "uno de los elementos del diafragma debe diseñarse para la "
            "condición más severa producida por el movimiento de las "
            "alas del diafragma en la misma dirección, o en direcciones "
            "opuestas."
        ),
    },
    {
        "id": "NSR10-A-A_3_6_9_a_6_13_elementos_debajo_base_muros_pendulo_discontinuos_verticales",
        "seccion": "A.3.6.9 a A.3.6.13 — Elementos debajo de la base, muros estructurales, péndulo invertido, elementos verticales discontinuos y aceleraciones verticales",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.6.9 — ELEMENTOS LOCALIZADOS DEBAJO DE LA BASE — La "
            "resistencia y rigidez de los elementos que formen parte del "
            "sistema de resistencia sísmica que se encuentren localizados "
            "entre la base y la cimentación no deben ser menores que las "
            "de la superestructura. Los elementos localizados entre la "
            "base y la cimentación deben tener el mismo grado de "
            "capacidad de disipación de energía de los elementos del "
            "sistema de resistencia sísmica.\n\n"
            "A.3.6.10 — MUROS ESTRUCTURALES — Los muros estructurales de "
            "concreto o mampostería, exteriores o interiores, deben "
            "amarrarse a los diafragmas o cubiertas que les provean apoyo "
            "lateral, por medio de anclajes diseñados para resistir una "
            "fuerza horizontal que actúa perpendicularmente al plano del "
            "muro. Dicha fuerza se puede calcular a partir de la fuerza "
            "causada por la aceleración en cada piso, calculada con la "
            "ecuación A.3.6-3, pero no menor que 0.10·Mp·g, donde Mp es "
            "la masa del tramo de muro considerado. Alternativamente a "
            "la ecuación A.3.6-3 para calcular las fuerzas horizontales "
            "perpendiculares al plano del muro pueden usarse estimaciones "
            "más precisas de las aceleraciones absolutas máximas a las "
            "que estarían sometidos estos muros.\n\n"
            "A.3.6.11 — ESTRUCTURAS DE TIPO PÉNDULO INVERTIDO — Estas son "
            "estructuras donde el sistema de resistencia sísmica actúa "
            "como uno o varios voladizos aislados y un porcentaje muy "
            "alto de la masa se encuentra concentrada en la parte "
            "superior de la estructura. Las columnas o pilares de apoyo "
            "de las estructuras de tipo péndulo invertido deben "
            "diseñarse para un diagrama de momentos flectores que inicia "
            "en la base con un valor determinado de acuerdo con los "
            "procedimientos establecidos en el Capítulo A.4 y varía "
            "uniformemente hasta llegar a la mitad de este valor en la "
            "parte superior. Véase la tabla A.3-3 para efectos de los "
            "sistemas estructurales permitidos.\n\n"
            "A.3.6.12 — ELEMENTOS VERTICALES DISCONTINUOS — En las zonas "
            "de amenaza sísmica intermedia y alta, cuando se presenten "
            "discontinuidades en el alineamiento de los elementos "
            "verticales del sistema de resistencia sísmica, tales como "
            "las descritas en las irregularidades en planta tipo 4P "
            "(tabla A.3-6) y en altura tipo 4A (tabla A.3-7), deben "
            "cumplirse los siguientes requisitos:\n"
            "(a) Las fuerzas axiales mayoradas de los elementos verticales "
            "que sostengan los elementos que se suspenden se deben "
            "obtener utilizando las combinaciones de carga apropiadas de "
            "las dadas en B.2.4, utilizando un coeficiente de carga igual "
            "a 0.4R, pero no menor de 1.0, en las combinaciones que "
            "incluyan fuerzas sísmicas reducidas de diseño E, en vez del "
            "coeficiente 1.0 prescrito allí,\n"
            "(b) Debe garantizarse que los elementos, tales como vigas, "
            "que llevan estas fuerzas axiales hasta los elementos "
            "verticales las que soportan sean capaces de resistirlas,\n"
            "(c) Los elementos verticales deben diseñarse para las "
            "fuerzas axiales mayoradas como se indica en el literal (a), "
            "acompañadas de los momentos obtenidos del análisis, los "
            "cuales se mayoran utilizando las combinaciones de carga "
            "normales prescritas en B.2.4,\n"
            "(d) Los elementos verticales deben diseñarse y detallarse "
            "siguiendo los requisitos del grado especial de capacidad de "
            "disipación de energía (DES) del material correspondiente.\n\n"
            "Cuando el diseño de los elementos verticales que soportan el "
            "elemento que se suspende se realiza utilizando el método de "
            "esfuerzos de trabajo prescrito en B.2.3, las fuerzas axiales "
            "de diseño al nivel de esfuerzos de trabajo se deben "
            "multiplicar por 0.3R, pero no menos de 0.7, en vez del "
            "coeficiente 0.7 prescrito allí.\n\n"
            "A.3.6.13 — EFECTO DE LAS ACELERACIONES VERTICALES — En las "
            "zonas de amenaza sísmica alta e intermedia, deben tenerse en "
            "cuenta los efectos de los movimientos sísmicos verticales en "
            "los siguientes elementos estructurales:\n"
            "(a) En los voladizos, considerando una fuerza vertical, "
            "ascendente o descendente, en la punta del elemento con un "
            "valor igual al 30 por ciento de la carga muerta del "
            "voladizo en las zonas de amenaza sísmica alta, y del 15 por "
            "ciento en las zonas de amenaza sísmica intermedia, y\n"
            "(b) En los elementos construidos con concreto preesforzado, "
            "deben utilizarse combinaciones de carga adicionales a todas "
            "aquellas que incluyan carga muerta, utilizando el 50 por "
            "ciento de la carga muerta."
        ),
    },
    {
        "id": "NSR10-A-A_3_7_fuerzas_sismicas_diseno_elementos",
        "seccion": "A.3.7 — Fuerzas sísmicas de diseño de los elementos estructurales (sistema de resistencia sísmica y cimentación)",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.7 — FUERZAS SÍSMICAS DE DISEÑO DE LOS ELEMENTOS "
            "ESTRUCTURALES\n\n"
            "A.3.7.1 — SISTEMA DE RESISTENCIA SÍSMICA — Los elementos del "
            "sistema estructural de resistencia sísmica, y sus "
            "conexiones, deben diseñarse utilizando todas las "
            "solicitaciones requerida por el Título B del Reglamento, "
            "debidamente combinadas según se exige allí. Las fuerzas "
            "sísmicas obtenidas del análisis Fs, se reducen, "
            "dividiéndolas por el coeficiente de capacidad de disipación "
            "de energía, R, correspondiente al sistema estructural de "
            "resistencia sísmica, para obtener las fuerzas sísmicas "
            "reducidas de diseño (E = Fs/R) que se emplean en las "
            "combinaciones de carga prescritas en el Título B. El valor "
            "del coeficiente de capacidad de disipación de energía para "
            "ser empleado en el diseño, corresponde al coeficiente de "
            "disipación de energía básico, R0, multiplicado por los "
            "coeficientes de reducción de capacidad de disipación de "
            "energía por irregularidades en altura, en planta, y por "
            "ausencia de redundancia del sistema estructural de "
            "resistencia sísmica (R = φa φp φr R0). El diseño de los "
            "elementos estructurales y sus conexiones se realiza "
            "cumpliendo los requisitos exigidos para el grado de "
            "capacidad de disipación de energía requerido del material. "
            "Estas fuerzas de diseño de los elementos estructurales "
            "obtenidas siguiendo el procedimiento anotado, son fuerzas al "
            "nivel de la resistencia, o sea que corresponden a fuerzas "
            "mayoradas que ya han sido multiplicadas por sus coeficientes "
            "de carga. Para elementos que se diseñan utilizando el "
            "método de esfuerzos de trabajo, debe consultarse A.3.1.8.\n\n"
            "Los elementos frágiles de conexión entre elementos y otros "
            "que de acuerdo con los requisitos de los materiales "
            "estructurales que los constituyen requieran el uso del "
            "coeficiente de sobrerresistencia Ω0, se diseñan utilizando "
            "las fuerzas sísmicas de diseño E obtenidas de la ecuación "
            "A.3.3-2.\n\n"
            "A.3.7.2 — CIMENTACIÓN — Las fuerzas sísmicas que actúan "
            "sobre la cimentación y el suelo de soporte se obtienen "
            "así:\n\n"
            "(a) Para efectos del diseño estructural de los elementos "
            "que componen la cimentación (incluidas las pantallas y los "
            "demás elementos a los que se conecte la estructura), se "
            "emplea el procedimiento indicado en A.3.7.1, empleando las "
            "cargas apropiadas y las fuerzas sísmicas reducidas de "
            "diseño, E, a partir de las reacciones de la estructura "
            "sobre estos elementos, calificando el valor de R usado en "
            "la estructura para establecer las cargas a la cimentación. "
            "En caso que se requiera una evaluación particular, las "
            "acciones de la estructura sobre la cimentación deberán "
            "determinarse con uno de los siguientes métodos: (1) "
            "mediante procedimientos de análisis inelástico de la "
            "estructura, (2) evaluando el desempeño de la estructura "
            "(curvas de demanda y capacidad), (3) calculando las "
            "acciones que la estructura aplicará a los elementos que "
            "componen la cimentación, cuando a la estructura se aplique "
            "la carga cortante necesaria para producir el mecanismo de "
            "plastificación. En el diseño de los elementos de cimentación "
            "deben seguirse los requisitos propios del material "
            "estructural y del Título H de este Reglamento.\n\n"
            "(b) Para efectos de obtener los esfuerzos sobre el suelo de "
            "cimentación, a partir de las reacciones de la estructura y "
            "su cimentación sobre el suelo, se emplean las combinaciones "
            "de carga para el método de esfuerzos de trabajo de la "
            "sección B.2.3, empleando las cargas apropiadas y las "
            "fuerzas sísmicas reducidas de diseño, E. Los efectos sobre "
            "el suelo así obtenidos están definidos al nivel de "
            "esfuerzos de trabajo y deben evaluarse de acuerdo con los "
            "requisitos del Título H de este Reglamento."
        ),
    },
    {
        "id": "NSR10-A-A_3_8_aislamiento_sismico_base",
        "seccion": "A.3.8 — Estructuras aisladas sísmicamente en su base",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.8 — ESTRUCTURAS AISLADAS SÍSMICAMENTE EN SU BASE\n\n"
            "A.3.8.1 — Se permite el empleo de estructuras aisladas "
            "sísmicamente en su base, siempre y cuando se cumplan en su "
            "totalidad los requisitos al respecto de uno de los dos "
            "documentos siguientes:\n"
            "(a) \"NEHRP Recommended Provisions for Seismic Regulations "
            "for New Buildings — Provisions and Commentary\", 2003 "
            "Edition, Federal Emergency Management Agency, FEMA 450, "
            "Building Seismic Safety Council, National Institute of "
            "Buildings Sciences, Washington, D.C., USA, 2004,\n"
            "(b) \"Minimum Design Loads for Building and Other "
            "Structures\", ASCE/SEI 7-05, Structural Engineering "
            "Institute of the American Society of Civil Engineers, "
            "Reston, Virginia, USA, 2006\n\n"
            "A.3.8.2 — En el diseño y construcción de estructuras "
            "aisladas sísmicamente en su base, se deben cumplir los "
            "requisitos de los Artículos 10 y 11 de la Ley 400 de 1997, "
            "asumiendo el diseñador estructural y el constructor las "
            "responsabilidades que allí se indican.\n\n"
            "A.3.8.3 — La construcción de una edificación que utilice "
            "sistemas de aislamiento sísmico en su base debe someterse a "
            "una supervisión técnica permanente, como la describe el "
            "Título I."
        ),
    },
    {
        "id": "NSR10-A-A_3_9_elementos_disipadores_energia",
        "seccion": "A.3.9 — Uso de elementos disipadores de energía",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "A.3.9 — USO DE ELEMENTOS DISIPADORES DE ENERGÍA\n\n"
            "A.3.9.1 — Se permite el empleo de elementos disipadores de "
            "energía, siempre y cuando se cumplan en su totalidad los "
            "requisitos al respecto de uno de los dos documentos "
            "siguientes:\n"
            "(a) \"NEHRP Recommended Provisions for Seismic Regulations "
            "for New Buildings — Provisions and Commentary\", 2003 "
            "Edition, Federal Emergency Management Agency, FEMA 450, "
            "Building Seismic Safety Council, National Institute of "
            "Buildings Sciences, Washington, D.C., USA, 2004,\n"
            "(b) \"Minimum Design Loads for Building and Other "
            "Structures\", ASCE/SEI 7-05, Structural Engineering "
            "Institute of the American Society of Civil Engineers, "
            "Reston, Virginia, USA, 2006\n\n"
            "A.3.9.2 — En el diseño y construcción de estructuras que "
            "tengan elementos disipadores de energía, se deben cumplir "
            "los requisitos de los Artículos 10 y 11 de la Ley 400 de "
            "1997, asumiendo el diseñador estructural y el constructor "
            "las responsabilidades que allí se indican.\n\n"
            "A.3.9.3 — La construcción de una edificación que utilice "
            "elementos disipadores de energía debe someterse a una "
            "supervisión técnica permanente, como la describe el Título "
            "I."
        ),
    },
    {
        "id": "NSR10-A-A_3_tabla_3_5_mezcla_sistemas_altura",
        "seccion": "Tabla A.3-5 — Mezcla de sistemas estructurales en la altura",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "Tabla A.3-5 — Mezcla de sistemas estructurales en la "
            "altura:\n\n"
            "Estructura flexible apoyada sobre una estructura con mayor "
            "rigidez — Puede utilizarse este procedimiento si la "
            "estructura cumple las siguientes condiciones: (a) ambas "
            "partes de la estructura, consideradas separadamente, "
            "puedan ser clasificadas como regulares de acuerdo con los "
            "requisitos de A.3.3, (b) el promedio de las rigideces de "
            "piso de la parte baja sea por lo menos 10 veces el promedio "
            "de las rigideces de piso de la parte alta y (c) el período "
            "de la estructura, considerada como un todo, no sea mayor de "
            "1.1 veces el período de la parte superior, al ser "
            "considerada como una estructura independiente empotrada en "
            "la base. Si no se cumplen las condiciones anteriores la "
            "estructura se considera irregular y deben seguirse los "
            "requisitos de A.3.3. Cuando se cumplen las condiciones, se "
            "permite que esta combinación no se considere irregular "
            "(φp = φa = 1.0), y el sistema puede diseñarse sísmicamente "
            "utilizando el método de la fuerza horizontal equivalente, "
            "tal como lo prescribe el Capítulo A.4, de la siguiente "
            "manera: (1) la parte superior flexible puede ser analizada "
            "y diseñada como una estructura separada, apoyada para "
            "efecto de las fuerzas horizontales por la parte más rígida "
            "inferior, usando el valor apropiado de R0 para su sistema "
            "estructural; (2) la parte rígida inferior debe ser "
            "analizada y diseñada como una estructura separada, usando "
            "el valor apropiado de R0 para su sistema estructural, y las "
            "reacciones de la parte superior, obtenidas de su análisis, "
            "deben ser amplificadas por la relación entre el valor de R0 "
            "para la parte superior y el valor de R0 de la parte "
            "inferior.\n\n"
            "Estructura rígida apoyada sobre una estructura con menor "
            "rigidez — Corresponde a edificaciones en las cuales se "
            "suspende antes de llegar a la base de la estructura, parcial "
            "o totalmente, un sistema estructural más rígido que el que "
            "llega a la base de la estructura. Este tipo de combinación "
            "de sistemas estructurales en la altura presenta "
            "inconvenientes en su comportamiento sísmico. No es "
            "aceptable como una solución estructural para el presente "
            "Reglamento."
        ),
    },
    {
        "id": "NSR10-A-A_3_tabla_3_6_irregularidades_planta",
        "seccion": "Tabla A.3-6 — Irregularidades en planta (tipos 1aP a 5P)",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "Tabla A.3-6 — Irregularidades en planta (Tipo | Descripción "
            "| φp | Referencias):\n\n"
            "1aP — Irregularidad torsional — La irregularidad torsional "
            "existe cuando en una edificación con diafragma rígido, la "
            "máxima deriva de piso de un extremo de la estructura, "
            "calculada incluyendo la torsión accidental y medida "
            "perpendicularmente a un eje determinado, es más de 1.2 y "
            "menor o igual a 1.4 veces la deriva promedio de los dos "
            "extremos de la estructura, con respecto al mismo eje de "
            "referencia. φp = 0.9. Referencias: A.3.3.6, A.3.4.2, "
            "A.3.6.3.1, A.3.6.7.1, A.3.6.8.4, A.5.2.1.\n\n"
            "1bP — Irregularidad torsional extrema — La irregularidad "
            "torsional extrema existe cuando en una edificación con "
            "diafragma rígido, la máxima deriva de piso de un extremo de "
            "la estructura, calculada incluyendo la torsión accidental y "
            "medida perpendicularmente a un eje determinado, es más de "
            "1.4 veces la deriva promedio de los dos extremos de la "
            "estructura, con respecto al mismo eje de referencia. φp = "
            "0.8. Referencias: A.3.3.6, A.3.4.2, A.3.6.3.1, A.3.6.7.1, "
            "A.3.6.8.4, A.5.2.1.\n\n"
            "2P — Retrocesos excesivos en las esquinas — La "
            "configuración de una estructura se considera irregular "
            "cuando ésta tiene retrocesos excesivos en sus esquinas. Un "
            "retroceso en una esquina se considera excesivo cuando las "
            "proyecciones de la estructura, a ambos lados del retroceso, "
            "son mayores que el 15 por ciento de la dimensión de la "
            "planta de la estructura en la dirección del retroceso. φp "
            "= 0.9. Referencias: A.3.4.2, A.3.6.8.4, A.3.6.8.5, A.5.2.1.\n\n"
            "3P — Discontinuidades en el diafragma — Cuando el "
            "diafragma tiene discontinuidades apreciables o variaciones "
            "en su rigidez, incluyendo las causadas por aberturas, "
            "entrantes, retrocesos o huecos con áreas mayores del 50 por "
            "ciento del área bruta del diafragma o existen cambios en la "
            "rigidez efectiva del diafragma de más del 50 por ciento, "
            "entre niveles consecutivos, la estructura se considera "
            "irregular. φp = 0.9. Referencias: A.3.3.7, A.3.4.2, "
            "A.3.6.8.4, A.5.2.1.\n\n"
            "4P — Desplazamientos del plano de acción de elementos "
            "verticales — La estructura se considera irregular cuando "
            "existen discontinuidades en las trayectorias de las fuerzas "
            "inducidas por los efectos sísmicos, tales como cuando se "
            "traslada el plano que contiene a un grupo de elementos "
            "verticales del sistema de resistencia sísmica, en una "
            "dirección perpendicular a él, generando un nuevo plano. Los "
            "altillos o mansardas de un solo piso se eximen de este "
            "requisito en la consideración de irregularidad. φp = 0.8. "
            "Referencias: A.3.3.7, A.3.4.2, A.3.6.8.4, A.3.6.12, "
            "A.5.2.1.\n\n"
            "5P — Sistemas no paralelos — Cuando las direcciones de "
            "acción horizontal de los elementos verticales del sistema "
            "de resistencia sísmica no son paralelas o simétricas con "
            "respecto a los ejes ortogonales horizontales principales "
            "del sistema de resistencia sísmica, la estructura se "
            "considera irregular. φp = 0.9. Referencias: A.3.4.2, "
            "A.3.6.3.1, A.5.2.1.\n\n"
            "Notas: (1) En zonas de amenaza sísmica intermedia para "
            "edificaciones pertenecientes al grupo de uso I, la "
            "evaluación de irregularidad se puede limitar a las "
            "irregularidades de los tipos 1aP, 1bP, 3P y 4P (véase "
            "A.3.3.7). (2) En zonas de amenaza sísmica baja para "
            "edificaciones pertenecientes a los grupos de uso I y II, la "
            "evaluación de irregularidad se puede limitar a las "
            "irregularidades tipo 1aP e 1bP (véase A.3.3.6)."
        ),
    },
    {
        "id": "NSR10-A-A_3_tabla_3_7_irregularidades_altura",
        "seccion": "Tabla A.3-7 — Irregularidades en altura (tipos 1aA a 5bA)",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "Tabla A.3-7 — Irregularidades en altura (Tipo | Descripción "
            "| φa | Referencias):\n\n"
            "1aA — Piso flexible (irregularidad en rigidez) — Cuando la "
            "rigidez ante fuerzas horizontales de un piso es menor del "
            "70 por ciento pero superior o igual al 60 por ciento de la "
            "rigidez del piso superior o menor del 80 por ciento pero "
            "superior o igual al 70 por ciento del promedio de la "
            "rigidez de los tres pisos superiores, la estructura se "
            "considera irregular. φa = 0.9. Referencias: A.3.3.5.1, "
            "A.3.4.2.\n\n"
            "1bA — Piso flexible (irregularidad extrema en rigidez) — "
            "Cuando la rigidez ante fuerzas horizontales de un piso es "
            "menor del 60 por ciento de la rigidez del piso superior o "
            "menor del 70 por ciento del promedio de la rigidez de los "
            "tres pisos superiores, la estructura se considera irregular. "
            "φa = 0.8. Referencias: A.3.3.5.1, A.3.4.2.\n\n"
            "2A — Irregularidad en la distribución de las masas — Cuando "
            "la masa, mi, de cualquier piso es mayor que 1.5 veces la "
            "masa de uno de los pisos contiguos, la estructura se "
            "considera irregular. Se exceptúa el caso de cubiertas que "
            "sean más livianas que el piso de abajo. φa = 0.9. "
            "Referencias: A.3.3.5.1, A.3.4.2.\n\n"
            "3A — Irregularidad geométrica — Cuando la dimensión "
            "horizontal del sistema de resistencia sísmica en cualquier "
            "piso es mayor que 1.3 veces la misma dimensión en un piso "
            "adyacente, la estructura se considera irregular. Se "
            "exceptúa el caso de los altillos de un solo piso. φa = "
            "0.9. Referencias: A.3.4.2.\n\n"
            "4A — Desplazamientos dentro del plano de acción — La "
            "estructura se considera irregular cuando existen "
            "desplazamientos en el alineamiento de elementos verticales "
            "del sistema de resistencia sísmica, dentro del mismo plano "
            "que los contiene, y estos desplazamientos son mayores que "
            "la dimensión horizontal del elemento. Cuando los elementos "
            "desplazados solo sostienen la cubierta sin otras cargas "
            "adicionales de tanques o equipos, se eximen de esta "
            "consideración de irregularidad. φa = 0.8. Referencias: "
            "A.3.3.7, A.3.4.2, A.3.6.12.\n\n"
            "5aA — Piso débil — Discontinuidad en la resistencia — "
            "Cuando la resistencia del piso es menor del 80 por ciento "
            "de la del piso inmediatamente superior pero superior o "
            "igual al 65 por ciento, entendiendo la resistencia del piso "
            "como la suma de las resistencias de todos los elementos que "
            "comparten el cortante del piso para la dirección "
            "considerada, la estructura se considera irregular. φa = "
            "0.9. Referencias: A.3.2.4.1, A.3.3.6, A.3.3.7, A.3.4.2.\n\n"
            "5bA — Piso débil — Discontinuidad extrema en la resistencia "
            "— Cuando la resistencia del piso es menor del 65 por ciento "
            "de la del piso inmediatamente superior, entendiendo la "
            "resistencia del piso como la suma de las resistencias de "
            "todos los elementos que comparten el cortante del piso para "
            "la dirección considerada, la estructura se considera "
            "irregular. φa = 0.8. Referencias: A.3.2.4.1, A.3.3.6, "
            "A.3.3.7, A.3.4.2.\n\n"
            "Notas: (1) Cuando la deriva de cualquier piso es menor de "
            "1.3 veces la deriva del piso siguiente hacia arriba, puede "
            "considerarse que no existen irregularidades de los tipos "
            "1aA, 1bA, 2A ó 3A (véase A.3.3.5.1). (2) En zonas de "
            "amenaza sísmica intermedia para edificaciones pertenecientes "
            "al grupo de uso I, la evaluación de irregularidad se puede "
            "limitar a las irregularidades de los tipos 4A, 5aA y 5bA "
            "(véase A.3.3.7). (3) En zonas de amenaza sísmica baja para "
            "edificaciones pertenecientes a los grupos de usos I y II, "
            "la evaluación de irregularidad se puede limitar a la "
            "irregularidad tipo 5aA y 5bA (véase A.3.3.6)."
        ),
    },
    {
        "id": "NSR10-A-A_3_figuras_3_1_3_2_nota",
        "seccion": "Figuras A.3-1 y A.3-2 — Diagramas geométricos de irregularidades en planta y en altura",
        "titulo": "NSR-10 Título A — Capítulo A.3 — Requisitos generales de diseño sismo resistente",
        "texto": (
            "Figura A.3-1 — Irregularidades en planta: diagramas "
            "geométricos en planta que ilustran cada uno de los 5 tipos "
            "descritos en la Tabla A.3-6 (1aP/1bP irregularidad "
            "torsional, 2P retrocesos en las esquinas con las "
            "proyecciones A, B, C, D, 3P discontinuidad del diafragma "
            "con las áreas C×D y A×B, 4P desplazamiento del plano de "
            "acción, 5P sistemas no paralelos).\n\n"
            "Figura A.3-2 — Irregularidades en altura: diagramas "
            "geométricos en elevación, por piso (A a F), que ilustran "
            "cada uno de los 6 tipos descritos en la Tabla A.3-7 "
            "(1aA/1bA piso flexible por rigidez KC/KD/KE/KF, 2A "
            "distribución de masas mD/mE/mC, 3A irregularidad "
            "geométrica a/b, 4A desplazamiento del plano de acción a/b, "
            "5aA/5bA piso débil por resistencia relativa entre pisos B y "
            "C).\n\n"
            "Los criterios numéricos exactos de cada tipo (porcentajes "
            "de deriva, rigidez, masa, dimensión y resistencia relativa "
            "que definen cuándo una edificación es irregular) están "
            "íntegros en el texto de las Tablas A.3-6 y A.3-7 — estas "
            "figuras son ilustraciones gráficas complementarias, no "
            "contienen criterios normativos adicionales a los ya "
            "transcritos en las tablas."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])

    print(f"Borrando {len(IDS_A_BORRAR_CONDENSADOS)} chunks condensados (no verbatim) de A.3.1/A.3.2/A.3.4/A.3.8-9...")
    sb.table("nsr10_chunks").delete().in_("id", IDS_A_BORRAR_CONDENSADOS).execute()

    print("Cargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

    textos = [c["texto"] for c in CHUNKS]
    print(f"Codificando {len(textos)} chunks...")
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print(f"\nSubiendo {len(rows)} chunks a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()
    print("OK.")


if __name__ == "__main__":
    main()
