"""
NSR-10 Titulo K, Capitulo K.4.2 completo -- Requisitos de Diseño para
vidrios (cargas, combinaciones de carga, areas maximas por espesor,
deflexiones, movimientos de la estructura), en verbatim real.

Continuacion del cierre de Titulo K.4 (K.4.1 ya completo, commit
68336b4). K.4.2 es el numeral mas extenso del capitulo (13 paginas,
K-36 a K-48), con formulas numeradas (K.4.2-1 a K.4.2-21) y 5 tablas
numericas (K.4.2-0 propiedades fisicas, K.4.2-1 cargas concentradas,
K.4.2-2 a K.4.2-5 areas maximas por espesor/tipo de vidrio -- las tablas
mas grandes de todo el Titulo K).

Reemplaza el chunk viejo NSR10-K-K_4_2_requisitos_diseno (2297 chars,
condensado -- el contenido real son 13 paginas con formulas y tablas
completas) por 9 chunks verbatim, uno por sub-numeral.

Honestidad de formulas (mismo criterio ya aplicado a Ecuador/Peru en
este proyecto): las ecuaciones con subindices simples (Fgw, Fga, etc.)
se transcriben literalmente; para las que usan fracciones o
subindices dobles (ej. K.4.2-21) se transcribe la forma reconocible mas
el glosario completo de variables, que es lo que se recupera con
precision total de la lectura visual.

Fuente: NSR-10-1571-1625.pdf (Drive id 1M_lQD8NRDBHaB6pc_GE1n2l2sW34U88Z),
paginas internas K-36 a K-48 (paginas PDF 28-40), leido visualmente
pagina por pagina.

Uso: python _ingest_titulo_k_k42_verbatim.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "NSR-10 Título K — Otros Requisitos Complementarios"

CHUNKS = [
    {
        "id": "NSR10-K-K_4_2_1_a_3_espesores",
        "seccion": "K.4.2.1 a K.4.2.3 (Alcance, Tabla K.4.2-0 y Espesores de Láminas)",
        "titulo": "Alcance de K.4.2, propiedades físicas convencionales del vidrio (Tabla K.4.2-0) y criterios para determinar el espesor de las láminas.",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2 — REQUISITOS DE DISEÑO. K.4.2.1 — "
            "Los elementos no estructurales de vidrio deben cumplir con las "
            "especificaciones del Capítulo A.9, y además con K.4.2.2, K.4.2.3, K.4.3 "
            "y K.4.4. Los elementos estructurales de vidrio deben cumplir con las "
            "especificaciones del Capítulo A.8, y además con K.4.2.3, K.4.3 y K.4.4. "
            "K.4.2.2 — Los elementos del marco se deben diseñar de acuerdo con las "
            "especificaciones de estas normas para el material empleado. El diseño "
            "de los elementos de soporte metálicos debe cumplir con especificaciones "
            "aplicables del Título F.\n\n"
            "Tabla K.4.2-0 — Características físicas y mecánicas convencionales de "
            "productos de base vítrea (Característica — Símbolo — Valor numérico y "
            "unidad): Densidad (a 18 °C) = 2500 kg/m³. Dureza = 6 unidades (escala "
            "de Mohs). Módulo de Young (módulo de elasticidad), E = 7×10¹⁰ Pa. "
            "Índice de Poisson, μ = 0.2. Calor específico, c = 0.72×10³ J/(kg·K). "
            "Coeficiente medio de dilatación lineal entre 20°C y 300°C, α = 9×10⁻⁶ "
            "K⁻¹. Conductividad térmica, λ = 1 W/(m·K). Índice de refracción medio "
            "en el espectro visible (380 nm a 780 nm), n = 1.5.\n\n"
            "K.4.2.3 — ESPESORES DE LAS LÁMINAS DE VIDRIO — El espesor de una "
            "lámina de vidrio debe determinarse teniendo en cuenta sus dimensiones, "
            "la relación largo/ancho, los lados apoyados, la probabilidad de "
            "rotura, la condición de la superficie del vidrio, deflexiones máximas "
            "permitidas, y las cargas inducidas por el viento u otra causa, que "
            "actúen normalmente sobre la lámina, así como la duración de dichas "
            "cargas. Debe tenerse en cuenta el tipo de vidrio utilizado. Para "
            "vidrios laminados y unidades de vidrio aislante se debe evaluar la "
            "interacción de las capas o láminas componentes. Para el "
            "dimensionamiento de espesores de láminas de vidrio sometidas a cargas "
            "de viento, empozamiento y peso propio, con una magnitud combinada "
            "total menor que o igual a 10 kPa, se permite el uso del método "
            "establecido en la norma ASTM E1300-09a. Adicionalmente, para el "
            "dimensionamiento de espesores de láminas y selección de tipos de "
            "vidrio, se deben considerar otros parámetros como esfuerzos térmicos, "
            "rotura espontánea de vidrios templados, efectos de escombros llevados "
            "por el viento, efectos sísmicos, flujo de calor, marcas en el borde, "
            "atenuación de ruido, consecuencias potenciales después de la rotura, "
            "comportamiento de fragmentos de vidrio después de la rotura, "
            "resistencia al impacto humano accidental y otros (véanse los "
            "numerales K.4.2.4.3 y K.4.4). K.4.2.3.1 — Espesores de las láminas de "
            "material plástico para vidriado — Para la determinación de espesores "
            "de las láminas de material plástico para vidriado se deben seguir las "
            "especificaciones del fabricante. Los materiales plásticos para "
            "vidriado deben cumplir con las especificaciones de seguridad y "
            "construcción especificadas en K.4.3 y K.4.4."
        ),
    },
    {
        "id": "NSR10-K-K_4_2_4_cargas",
        "seccion": "K.4.2.4 (Cargas: Viento, Efectos Sísmicos y Esfuerzos Térmicos)",
        "titulo": "Cargas de viento, efectos sísmicos (con los 3 niveles de daño Superior/Bueno/Bajo), esfuerzos térmicos (24 factores de influencia) y otras cargas.",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2.4 — CARGAS. K.4.2.4.1 — Cargas "
            "de Viento — Los componentes exteriores de vidriados, ventanales y "
            "vidrieras de toda instalación, conformados por láminas de vidrio, "
            "deben diseñarse para resistir las presiones inducidas por las cargas "
            "de viento, evaluadas de acuerdo con el Título B. K.4.2.4.2 — Efectos "
            "Sísmicos — Los componentes exteriores de vidriados, ventanales y "
            "vidrieras de toda instalación, conformados por láminas de vidrio, "
            "deben diseñarse para resistir las fuerzas inducidas por los efectos "
            "sísmicos, evaluadas de acuerdo con el Capítulo A.2, para elementos "
            "estructurales, y de acuerdo con el Capítulo A.9, para elementos no "
            "estructurales. K.4.2.4.2.1 — Cuando el diseño se ejecuta de acuerdo "
            "con el Capítulo A.9, la fuerza sísmica debe considerarse actuando "
            "perpendicularmente al plano del sistema vidriado. K.4.2.4.2.2 — Para "
            "efectos de clasificación en función del Grado de Desempeño relacionado "
            "con los efectos sísmicos, debe tenerse en cuenta las definiciones del "
            "Capítulo A.9.2: (a) Superior — Es aquel en el cual el daño que se "
            "presenta en los elementos no estructurales es mínimo y no interfiere "
            "con la operación de la edificación debido a la ocurrencia de un "
            "sismo. (b) Bueno — Es aquel en el cual el daño que se presenta en los "
            "elementos no estructurales es totalmente reparable y puede haber "
            "alguna interferencia con la operación de la edificación con "
            "posterioridad a la ocurrencia del sismo. (c) Bajo — Es aquel en el "
            "cual se presentan daños graves en los elementos no estructurales, "
            "inclusive no reparables.\n\n"
            "K.4.2.4.3 — Esfuerzos Térmicos — Los esfuerzos térmicos son causados "
            "generalmente por diferencias de temperatura entre los bordes cubiertos "
            "y el centro del vidrio. Los esfuerzos en el centro del vidrio "
            "aumentan al aumentar la diferencia de temperatura entre el borde y el "
            "centro. La probabilidad de rotura aumenta a la vez que el esfuerzo "
            "térmico aumenta. Se recomienda realizar un análisis individual para "
            "cada proyecto de construcción donde se considere que los esfuerzos "
            "térmicos tengan relevancia. En el proceso de diseño y selección deben "
            "considerarse todos los requisitos de diseño estructural para vidrio "
            "especificados en K.4.2, así como los requisitos de seguridad de "
            "K.4.3. Si después de considerar dichos aspectos el vidrio se sigue "
            "encontrando apto deben tenerse en cuenta las siguientes "
            "consideraciones: (a) Para vidrio recocido se sugiere hacer una "
            "evaluación de esfuerzos térmicos, como la presentada en ASTM STP 1434 "
            "(páginas 105 a 118) donde se calculan las tensiones admisibles "
            "asociadas con la probabilidad de rotura escogida por el diseñador. "
            "(b) La rotura del vidrio recocido por esfuerzos térmicos ocurre "
            "cuando el esfuerzo térmico excede la resistencia del borde del "
            "vidrio. Con el uso del vidrio templado y el vidrio termoendurecido "
            "normalmente se evita la rotura debida a esfuerzos térmicos. (c) Entre "
            "mayor sea la absorción de calor en el vidrio, mayor es el esfuerzo "
            "térmico. Los vidrios con color y los reflectivos tienen mayor "
            "absorción de calor y por lo tanto son más susceptibles de rotura por "
            "esfuerzos térmicos. (d) De tratarse de vidrio laminado se pueden "
            "realizar ensayos como los especificados en ASTM F1233-06 en los "
            "numerales 7.5, 8.0 y en el apéndice A. K.4.2.4.3.1 — En la evaluación "
            "preliminar de esfuerzos térmicos se sugiere considerar la influencia "
            "de, entre otros, los siguientes aspectos: (a) Disipadores térmicos. "
            "(b) Magnitud de la mordedura en el borde del vidrio. (c) Sombras "
            "verticales, horizontales o diagonales. (d) Utilización de láminas con "
            "formas triangulares o redondeadas. (e) Trampas de calor no "
            "ventiladas. (f) Rótulos aplicados en la superficie del vidrio. (g) "
            "Vidrio reflectivo con recubrimientos aplicados en las superficies. "
            "(h) Unidades selladas dobles o triples. (i) Elementos del marco en "
            "el exterior. (j) Desportillados en concha, daños por impacto u otros "
            "daños en el borde del vidrio. (k) Orientación de las superficies "
            "vidriadas. (l) Áreas de los bordes del vidrio. (m) Posibles roturas "
            "por causas que no son térmicas y que pueden estar relacionadas con "
            "el tipo de marco. (n) Sombras interiores por cortinas, persianas u "
            "otros elementos. (o) Superficies reflectantes adyacentes tales como "
            "agua o vidrios reflectivos. (p) Color y características de "
            "absorción de calor del vidrio. (q) Relación largo/ancho. (r) Tipo, "
            "masa, conducción térmica y color de los elementos del marco. (s) "
            "Sombras exteriores por retrocesos, proyecciones o voladizos. (t) "
            "Bordes del vidrio dentados o con marcas, desportillados o "
            "astillados. (u) Temperatura exterior, temperatura interior y flujo "
            "de aire. (v) Altitud. (w) Intensidad solar. (x) Vidrio recocido "
            "incoloro con espesores superiores a 6 mm. K.4.2.4.3.2 — Es necesario "
            "estimar o calcular el nivel de los esfuerzos de borde inducidos al "
            "vidrio que es sometido a un conjunto de condiciones definidas. El "
            "mejor método para calcular los esfuerzos de borde para una situación "
            "dada es usar técnicas de Análisis de Elementos Finitos, para lo cual "
            "es necesario desarrollar un modelo detallado que represente con "
            "exactitud la situación bajo consideración incluyendo una descripción "
            "detallada de la geometría y de las condiciones de exposición. Se "
            "recomienda que se use un Análisis de Elementos Finitos detallado "
            "especialmente para todos los proyectos de magnitud significante, "
            "particularmente para aquellos que contienen grandes láminas de "
            "vidrio, un gran número de láminas de vidrio, o condiciones inusuales "
            "de vidriado y construcción. K.4.2.4.3.3 — Se debe determinar una "
            "probabilidad de rotura aceptable y la tensión admisible asociada, que "
            "deben ser consistentes con las expectativas del proyecto. La "
            "probabilidad de rotura aceptable para una situación particular se "
            "debe basar en varios factores en los que se incluyen el número de "
            "láminas en la edificación y las consecuencias asociadas con las "
            "fallas térmicas. El profesional de diseño debe determinar la "
            "probabilidad de rotura aceptable para cada aplicación con base en "
            "cada situación única. La selección final de la probabilidad de "
            "rotura es responsabilidad del profesional de diseño. Sin embargo es "
            "recomendable que no sea superior al 0.8%.\n\n"
            "K.4.2.4.4 — Otras Cargas — Adicionalmente a las cargas consideradas "
            "en K.4.2.4.1 y K.4.2.4.2, los componentes exteriores de vidriados, "
            "ventanales y vidrieras de toda instalación, conformados por láminas "
            "de vidrio, deben diseñarse considerando los efectos de otras cargas "
            "como peso propio, lluvia, granizo y empozamiento, de acuerdo con las "
            "definiciones que para estas cargas se presentan en el título B."
        ),
    },
    {
        "id": "NSR10-K-K_4_2_5_1_a_4_combinaciones_basicas",
        "seccion": "K.4.2.5.1 a K.4.2.5.4 (Combinaciones de Carga: Vidrio Vertical, Inclinado, Impreso, Chorro de Arena)",
        "titulo": "Ecuaciones K.4.2-1 a K.4.2-12: combinaciones de carga básicas para vidrio vertical/inclinado y sus variantes impreso/grabado con chorro de arena.",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2.5 — COMBINACIONES DE CARGAS "
            "PARA DISEÑO — En esta sección se presentan algunas especificaciones "
            "sobre combinaciones de carga y otros criterios específicos de "
            "diseño; sin embargo, la carga máxima admisible para el vidrio y el "
            "diseño definitivo deberán ser establecidos por el diseñador "
            "responsable de los sistemas vidriados que puede ser el diseñador de "
            "elementos no estructurales para el caso de sistemas vidriados no "
            "estructurales.\n\n"
            "K.4.2.5.1 — Vidrio Vertical — Puede considerarse que un sistema "
            "vidriado está instalado verticalmente si tiene una inclinación igual "
            "o menor de 15° con respecto a la vertical, en cuyo caso el diseño "
            "debe basarse en la ecuación: Fgw ≤ Fga (K.4.2-1). Donde: Fgw = carga "
            "sobre el vidrio calculada de acuerdo con K.4.2.4. Fga = carga de "
            "corta duración sobre el vidrio, determinada de acuerdo con las "
            "especificaciones de ASTM E1300-09a.\n\n"
            "K.4.2.5.2 — Vidrio Inclinado — Un sistema vidriado debe considerarse "
            "inclinado cuando tiene una inclinación de más de 15° con respecto a "
            "la vertical, utilizado, como sucede en tragaluces o claraboyas, "
            "solárium, techos inclinados u otras aplicaciones similares, en cuyo "
            "caso su diseño debe basarse en la ecuación: Fg ≤ Fga (K.4.2-2). "
            "Donde: Fg = carga total sobre el vidrio determinada como la más "
            "crítica de las combinaciones de carga especificadas con las "
            "ecuaciones K.4.2-3, K.4.2-4 y K.4.2-5: Fg = Wo − D (K.4.2-3); Fg = Wi "
            "+ D + 0.5P (K.4.2-4); Fg = 0.5Wi + D + P (K.4.2-5). Donde: D = carga "
            "muerta del vidrio, expresada en kN/m², cuyos valores son: para "
            "vidrio inclinado 60° o más respecto a la vertical, D = 0.0256·tg; "
            "para vidrio inclinado menos de 60° respecto a la vertical, D = "
            "0.0256·tg·sen(θ). P = carga de empozamiento, expresada en kN/m². tg "
            "= espesor total del vidrio, incluyendo los paneles de vidrio y las "
            "demás capas intermedias (mm). Wi = fuerza de viento hacia el "
            "interior, calculada de acuerdo con el Capítulo B.6, expresada en "
            "kN/m². Wo = fuerza de viento hacia el exterior, calculada de acuerdo "
            "con el Capítulo B.6, expresada en kN/m². θ = ángulo de inclinación "
            "con respecto a la vertical. Fga = carga máxima admisible de corta "
            "duración para el vidrio (ecuaciones K.4.2-3/K.4.2-4) o de larga "
            "duración (ecuación K.4.2-5), determinadas de acuerdo con la norma "
            "ASTM E1300-09a. K.4.2.5.2.1 — Excepción — Las unidades para "
            "tragaluces o claraboyas se deben diseñar de acuerdo con las "
            "secciones K.4.2.5.6 y K.4.4.5.\n\n"
            "K.4.2.5.3 — Vidrio Impreso o Grabado — Un sistema vidriado se "
            "considera impreso cuando contiene vidrio plano fabricado con "
            "rodillos de laminación que tiene un patrón en una o ambas "
            "superficies. El Vidrio Impreso debe cumplir con los requisitos de "
            "la NTC 1909 (2009). K.4.2.5.3.1 — Vidrio Impreso Vertical — Puede "
            "considerarse que un sistema vidriado impreso está instalado "
            "verticalmente si tiene una inclinación igual o menor de 15° con "
            "respecto a la vertical, en cuyo caso el diseño debe basarse en la "
            "ecuación: Fgw < Fge (K.4.2-9). Donde: Fgw = carga sobre el vidrio "
            "calculada de acuerdo con K.4.2.3. Fge = carga no factorada de la "
            "norma ASTM E1300-09a. El valor para vidrio impreso se debe basar en "
            "la parte más delgada del vidrio. Se permite la interpolación entre "
            "gráficos de carga no factorada de la norma ASTM E1300-09a. "
            "K.4.2.5.3.2 — Vidrio Impreso Inclinado — Un sistema vidriado impreso "
            "debe considerarse inclinado cuando tiene una inclinación de más de "
            "15° con respecto a la vertical, utilizado, como sucede en "
            "tragaluces o claraboyas, solárium, techos inclinados u otras "
            "aplicaciones similares, en cuyo caso su diseño debe basarse en una "
            "de las siguientes ecuaciones, de acuerdo con la combinación de "
            "carga utilizada: Fgw < 0.5Fge (K.4.2-10); Fg ≤ 0.6Fge (K.4.2-11). "
            "Donde: Fg = carga total sobre el vidrio determinada así: para la "
            "Ecuación K.4.2-10, la más crítica de las combinaciones de carga "
            "K.4.2-3 y K.4.2-4; para la Ecuación K.4.2-11, la determinada de la "
            "combinación de carga K.4.2-5. Fge = carga no factorada de la norma "
            "ASTM E1300-09a. El valor para vidrio impreso se debe basar en la "
            "parte más delgada del vidrio. Se permite la interpolación entre "
            "gráficos de carga no factorada de la norma ASTM E1300-09a.\n\n"
            "K.4.2.5.4 — Vidrio Grabado con Chorro de Arena — Un sistema vidriado "
            "se considera grabado con chorro de arena cuando contiene vidrios "
            "tratados superficialmente por medio de rociado con partículas "
            "granulares duras para dar aspereza a una o ambas superficies del "
            "vidrio. K.4.2.5.4.1 — Vidrio Vertical Grabado con Chorro de Arena — "
            "Puede considerarse que un sistema vidriado grabado con chorro de "
            "arena está instalado verticalmente si tiene una inclinación igual o "
            "menor de 15° con respecto a la vertical, en cuyo caso el diseño "
            "debe basarse en la siguiente ecuación: Fg < 0.5Fge (K.4.2-12). "
            "Donde: Fg = carga total sobre el vidrio. Fge = carga no factorada "
            "de la norma ASTM E1300-09a. El valor para vidrio grabado con chorro "
            "de arena es para niveles moderados de dicho grabado."
        ),
    },
    {
        "id": "NSR10-K-K_4_2_5_5_tragaluces",
        "seccion": "K.4.2.5.5 (Unidades de Tragaluces o Claraboyas)",
        "titulo": "Ecuaciones K.4.2-13 a K.4.2-15: diseño de unidades de tragaluces/claraboyas según su grado de desempeño (GD).",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2.5.5 — Unidades de Tragaluces o "
            "Claraboyas — Las unidades de tragaluces o claraboyas deben cumplir "
            "con las especificaciones dadas en esta sección y en K.4.3.5. El "
            "fabricante debe garantizar que las unidades de tragaluces o "
            "claraboyas cumplen con lo establecido en las normas AAMA/WDMA/CSA "
            "101/I.S.2/A440-08. Cada unidad debe tener un rótulo fácilmente "
            "visible que contenga, por lo menos, el nombre del fabricante, la "
            "designación del producto y clasificación del grado de desempeño "
            "como se especifica en AAMA/WDMA/CSA 101/I.S.2/A440-08. Si el "
            "fabricante del producto ha clasificado el grado de desempeño de la "
            "claraboya independientemente para presiones de diseño positiva y "
            "negativa, entonces el rótulo debe establecer las dos clasificaciones "
            "de grados de desempeño como se especifica en AAMA/WDMA/CSA "
            "101/I.S.2/A440-08. Además de lo anterior, el diseño de las unidades "
            "de claraboya debe ceñirse a las especificaciones dadas en K.4.2.5.6.1 "
            "y K.4.2.5.6.2.\n\n"
            "K.4.2.5.5.1 — Unidades de Tragaluces o Claraboyas Clasificadas con "
            "el Mismo Grado de Desempeño para Presiones de Diseño Positiva y "
            "Negativa — El diseño de unidades de tragaluces o claraboyas "
            "clasificadas con el mismo grado de desempeño para presiones de "
            "diseño positiva y negativa debe basarse en la siguiente ecuación: "
            "Fg ≤ GD (K.4.2-13). Donde: Fg = carga total sobre el vidrio "
            "determinada como la más crítica de las combinaciones de carga "
            "especificadas con las ecuaciones K.4.2-3, K.4.2-4 y K.4.2-5. GD = "
            "clasificación del grado de desempeño de la claraboya o tragaluz "
            "(ver definición en K.4.1.2).\n\n"
            "K.4.2.5.5.2 — Unidades de Tragaluces o Claraboyas Clasificadas con "
            "Grados de Desempeño Independientes para Presiones de Diseño "
            "Positiva y Negativa — El diseño de unidades de tragaluces o "
            "claraboyas clasificadas con grado de desempeño independientes para "
            "presiones de diseño positiva y negativa, debe basarse en las "
            "siguientes ecuaciones: Fgi ≤ GD_Pos (K.4.2-14); Fgo ≤ GD_Neg "
            "(K.4.2-15). Donde: Fgi y Fgo = carga sobre la claraboya determinada "
            "así: Para Wo ≥ D: Fgi = carga crítica entre las ecuaciones K.4.2-4 "
            "y K.4.2-5. Fgo = carga crítica entre las ecuaciones K.4.2-4. Para "
            "Wo < D: Fgi = carga crítica entre las ecuaciones K.4.2-4 y K.4.2-5. "
            "Fgo = 0. GD_Pos = clasificación del grado de desempeño de la "
            "claraboya bajo la presión de diseño positiva. GD_Neg = "
            "clasificación del grado de desempeño de la claraboya bajo la "
            "presión de diseño negativa. Wo = fuerza de viento hacia el "
            "exterior, calculada de acuerdo con K.4.2.4. D = peso muerto del "
            "vidriado determinado como se indica en la sección K.4.2.5.2 para "
            "vidrio, o en función del peso del plástico para vidriado plástico."
        ),
    },
    {
        "id": "NSR10-K-K_4_2_5_6_a_11_pisos_otros",
        "seccion": "K.4.2.5.6 a K.4.2.5.11 (Vidriados para Pisos, Barandas, Apoyos Puntuales, Movimientos Térmicos, Equipos de Limpieza, Otros Sistemas)",
        "titulo": "Ecuaciones K.4.2-16 a K.4.2-18 y Tabla K.4.2-1 (cargas concentradas): sistemas de vidriados para pisos, barandas (factor de seguridad 4), apoyos puntuales, movimientos térmicos y cargas por equipos de limpieza.",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2.5.6 — Sistemas de Vidriados "
            "para Pisos — Para el diseño de vidrios usados en pisos, descansos, "
            "escalones y lugares similares se debe considerar las cargas que "
            "produzcan mayores esfuerzos de acuerdo con las siguientes "
            "combinaciones de carga: Fg = 2Fu + D (K.4.2-16); Fg = (8Fc/A) + D "
            "(K.4.2-17); Fg = Fa + D (K.4.2-18). Donde: A = área del vidrio "
            "rectangular. D = carga muerta del vidrio. Fa = carga distribuida "
            "real producida por el uso previsto. Fc = carga concentrada "
            "especificada en la Tabla K.4.2-1. Fg = carga total sobre el vidrio. "
            "Fu = carga uniformemente distribuida, especificada en el numeral "
            "B.4.2 de este Reglamento.\n\n"
            "Tabla K.4.2-1 — Cargas mínimas concentradas (elemento — Carga, kN): "
            "Pisos de oficinas = 9.0. Escotillones, nervaduras de tragaluces o "
            "techos accesibles = 1.0 (carga uniformemente distribuida sobre un "
            "área equivalente a un cuadrado de no más de 4 cm de lado, a menos "
            "que se indique otra cosa). Escalones (sobre un área equivalente a un "
            "cuadrado de no más de 5 cm de lado, en el centro del escalón) = 1.5.\n\n"
            "K.4.2.5.6.1 — Aplicaciones dinámicas — Los valores de Fa, Fc, Fu, "
            "deben duplicarse para aplicaciones dinámicas. K.4.2.5.6.2 — Vidrio "
            "laminado — Para sistemas vidriados de piso es necesario usar vidrio "
            "laminado que tenga un mínimo de dos o más capas componentes de "
            "acuerdo con los resultados del análisis y el diseño. El vidrio debe "
            "ser capaz de soportar la carga de diseño total, con cualquiera de "
            "sus capas componentes rota. El vidrio monolítico, incluyendo el "
            "vidrio templado, no se considera seguro, independientemente de su "
            "espesor o del factor de seguridad utilizado en su diseño. "
            "K.4.2.5.6.3 — Resistencia al deslizamiento — La superficie en "
            "contacto con el tránsito peatonal debe tener una resistencia al "
            "deslizamiento adecuada; se recomienda que ésta sea ensayada y "
            "evaluada de acuerdo con la norma UL 410.\n\n"
            "K.4.2.5.7 — Barandas y pasamanos — Los paneles para barandas y "
            "pasamanos, y sus sistemas de soporte, se deben diseñar para "
            "soportar las cargas especificadas en B.4.2.2, usando un factor de "
            "seguridad igual a cuatro (4).\n\n"
            "K.4.2.5.8 — Sistemas vidriados con apoyos puntuales — Los sistemas "
            "vidriados que tengan apoyos puntuales deben diseñarse con base en "
            "las especificaciones dadas en K.4.2.4. Sin embargo, deben tenerse "
            "en cuenta las consideraciones adicionales que se presentan a "
            "continuación. K.4.2.5.8.1 — Métodos de análisis — Los elementos del "
            "sistema de soportes puntuales se pueden analizar mediante modelos "
            "de elementos finitos. Los soportes puntuales y su área circundante "
            "se deben modelar de manera que se obtengan resultados "
            "representativos. El análisis de las láminas de vidrio con "
            "orificios se puede realizar mediante modelos de elementos finitos. "
            "Es necesario que en el análisis y diseño se consideren tanto las "
            "tensiones como las deflexiones que implica inevitables "
            "concentraciones de tensiones que deben considerarse en el diseño. "
            "El modelo de las láminas de vidrio debe incluir datos de la "
            "geometría de los orificios, como por ejemplo el diámetro y la "
            "forma del orificio (cilíndrico, cónico, etc.). El número de "
            "elementos utilizados en la discretización del modelo debe permitir "
            "la precisión adecuada. La malla del modelo debe configurarse "
            "radialmente. Teniendo en cuenta las altas concentraciones de "
            "tensiones en los bordes de orificios, sólo deben usarse los "
            "resultados para vértices realmente calculados y no deben "
            "extrapolarse otros resultados a los vértices. En el modelo se debe "
            "integrar la información correspondiente a holguras, áreas de "
            "contacto entre el vidrio y el material de los soportes. En el "
            "análisis es necesario considerar el tipo de soporte puntual "
            "(rígido, elastómero o rótula), y la localización de su centro de "
            "gravedad. Se debe considerar el efecto de la expansión y "
            "contracción térmica de todos los materiales, así como los "
            "esfuerzos térmicos en las láminas de vidrio. En los casos en que lo "
            "considere la dependencia encargada de estudiar, tramitar y expedir "
            "la licencia de construcción, puede ser necesaria la realización de "
            "ensayos para demostrar que el vidrio propuesto cumple con los "
            "propósitos en cuanto a seguridad, durabilidad y resistencia "
            "especialmente sísmica.\n\n"
            "K.4.2.5.9 — Movimientos térmicos — En algunos diseños de los "
            "elementos de soporte, las expansiones y las contracciones térmicas "
            "en sistemas vidriados se pueden considerar mediante el cálculo del "
            "incremento de esfuerzos y las deformaciones correspondientes, sin "
            "contar con juntas de expansión. También se pueden considerar "
            "mediante una combinación de las juntas de expansión y los "
            "incrementos de esfuerzos a que halla lugar. En cualquier caso el "
            "método utilizado debe proporcionar el comportamiento estructural "
            "adecuado para el sistema en condiciones de expansiones o "
            "contracciones térmicas, y sin exceder las deflexiones ni los "
            "esfuerzos máximos establecidos.\n\n"
            "K.4.2.5.10 — Cargas por equipos de limpieza para ventanas — "
            "K.4.2.5.10.1 — Conexión continua — En el diseño de los elementos del "
            "marco que sirven como conexión continúa para equipos de limpieza, y "
            "de los anclajes, se deben considerar las cargas causadas por "
            "equipos para limpieza de ventanas. La carga por equipos de limpieza "
            "para ventanas que actúa perpendicular al plano del muro debe "
            "incluir la carga del equipo más un tercio de la carga de viento de "
            "diseño que actúa hacia el interior. El diseño de los elementos del "
            "marco estará gobernado por la combinación de carga antes descrita "
            "o por la carga de viento únicamente, la que sea mayor. En los casos "
            "en que las cargas por equipos de limpieza sean muy severas, el "
            "diseñador debe evaluar e incluir un factor de seguridad en estas "
            "cargas. K.4.2.5.10.2 — Estabilización intermitente del equipo de "
            "limpieza para ventanas — El método de estabilización intermitente "
            "únicamente se debe usar cuando los vientos previstos sean menores "
            "que 11 m/s. Todas las edificaciones que utilicen este método de "
            "estabilización se deben equipar con un instrumento para medir la "
            "velocidad del viento. Cuando se utilice estabilización intermitente "
            "del equipo de limpieza, los anclajes se deben localizar en filas "
            "verticales con puntos de estabilización cada tercer piso como "
            "máximo y horizontalmente cerca de los cables para permitir la "
            "estabilización de la conexión para cada uno de los dos cables de "
            "suspensión de la plataforma. La plataforma no debe ser más grande "
            "que 10 m de largo y 1 m de ancho. Cada anclaje a la edificación "
            "debe estar en capacidad de sostener la carga máxima actuando en "
            "dirección tanto paralela como perpendicular a la superficie de la "
            "edificación, pero no aplicadas simultáneamente.\n\n"
            "K.4.2.5.11 — Otros sistemas — Para el diseño de sistemas vidriados "
            "no contemplados en este Capítulo el diseñador de elementos no "
            "estructurales debe presentar el diseño correspondiente acompañado "
            "de las respectivas memorias de cálculo, planos detallados de "
            "fabricación e instalación y toda la información de soporte "
            "pertinente tal como certificaciones, ensayos de laboratorio, etc."
        ),
    },
    {
        "id": "NSR10-K-K_4_2_6_areas_maximas",
        "seccion": "K.4.2.6 (Áreas Máximas de las Láminas de Vidrio — Tablas K.4.2-2 a K.4.2-5)",
        "titulo": "Las 4 tablas completas de área máxima (m²) por espesor (3-16mm) y región de amenaza eólica, para vidrio recocido, termoendurecido, templado y laminado con PVB.",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2.6 — ÁREAS MÁXIMAS DE LAS "
            "LÁMINAS DE VIDRIO — En las tablas K.4.2-3 a K.4-2.6 [sic, K.4.2-2 a "
            "K.4.2-5], las cuales han sido elaboradas a partir de la norma ASTM "
            "E1300-09a, se presenta el área máxima permitida para una lámina de "
            "vidrio recocido, termoendurecido, templado o laminado (recocido), "
            "con relación largo/ancho menor o igual a 2 y soportada en los "
            "cuatro lados. Los valores de área máxima se dan para cada espesor y "
            "para varios valores de presión de viento calculados según K.4.2.4 y "
            "B.6, indicando los intervalos de presión para cada región en la que "
            "se ubica la edificación, de acuerdo con la clasificación de las "
            "velocidades de viento de diseño especificadas en el Mapa de "
            "Amenaza Eólica de la Figura B.6.4.1, considerando que la presión de "
            "viento actúa sobre un solo lado de la lámina. NOTA aplicable a las "
            "4 tablas: el signo (•) indica que en la región especificada en el "
            "Mapa de Amenaza Eólica de la Figura B.6.5.1, marcada con el mismo "
            "signo, se pueden presentar presiones de viento con magnitud igual "
            "al valor del renglón correspondiente de cada tabla; las casillas "
            "que NO están marcadas indican que en esa región no se presentan "
            "presiones de magnitud igual ni superior al valor del renglón "
            "correspondiente de cada tabla.\n\n"
            "Tabla K.4.2-2 — Áreas máximas, en m², de acuerdo con el espesor, en "
            "mm, de vidrios recocidos colocados verticalmente, con relación "
            "largo/ancho menor o igual a dos (2) y soportados en los cuatro "
            "lados (Regiones 1-5 marcadas · Presión kN/m² · Área en m² para "
            "espesores 3/4/5/6/8/10 mm): "
            "presión 0.50 (regiones 1-5) — 3mm no aplica, 4mm=4.40, 5mm=6.60, "
            "6mm=9.00, 8mm=12.18, 10mm=19.76. "
            "0.75 (regiones 1-5) — 4mm=2.85, 5mm=4.27, 6mm=5.76, 8mm=7.72, "
            "10mm=11.52, [3mm=14.58 en col. adicional]. "
            "1.00 (regiones 1-5) — 3mm=2.00, 4mm=3.03, 5mm=3.92, 6mm=4.99, "
            "8mm=7.22, 10mm=9.59. "
            "1.25 (regiones 2-5) — 3mm=1.55, 4mm=2.18, 5mm=2.76, 6mm=3.59, "
            "8mm=5.31, 10mm=6.85. "
            "1.50 (regiones 2-5) — 3mm=1.18, 4mm=1.62, 5mm=2.06, 6mm=2.76, "
            "8mm=4.06, 10mm=5.45. "
            "2.00 (regiones 3-5) — 3mm=0.73, 4mm=1.08, 5mm=1.38, 6mm=1.84, "
            "8mm=2.88, 10mm=3.92. "
            "3.00 (regiones 4-5) — 3mm=0.43, 4mm=0.63, 5mm=0.86, 6mm=1.16, "
            "8mm=1.84, 10mm=2.65. "
            "4.00 (región 5) — 3mm=0.30, 4mm=0.47, 5mm=0.62, 6mm=0.87, "
            "8mm=1.42, 10mm=1.97. "
            "5.00 (región 5) — 3mm=0.23, 4mm=0.38, 5mm=0.50, 6mm=0.70, "
            "8mm=1.09, 10mm=1.50. "
            "7.00 (región 5) — 3mm=0.17, 4mm=0.26, 5mm=0.35, 6mm=0.50, "
            "8mm=0.81, 10mm=1.10.\n\n"
            "Tabla K.4.2-3 — Áreas máximas en m² por espesor para vidrios "
            "termoendurecidos colocados verticalmente, con relación largo/ancho "
            "menor o igual a dos (2) y soportados en los cuatro lados (Presión "
            "kN/m² · Área en m² para espesores 3/4/5/6/8/10 mm): "
            "1.00 (regiones 1-5) — 4mm=4.40, 5mm=6.60, 6mm=9.00, 8mm=12.18, "
            "10mm=19.76. "
            "1.50 (regiones 2-5) — 3mm=2.85, 4mm=4.27, 5mm=5.76, 6mm=7.72, "
            "8mm=11.52, 10mm=14.58. "
            "2.00 (regiones 3-5) — 3mm=2.00, 4mm=3.03, 5mm=3.92, 6mm=4.99, "
            "8mm=7.22, 10mm=9.59. "
            "3.00 (regiones 4-5) — 3mm=1.18, 4mm=1.62, 5mm=2.06, 6mm=2.76, "
            "8mm=4.06, 10mm=5.45. "
            "4.00 (región 5) — 3mm=0.73, 4mm=1.08, 5mm=1.38, 6mm=1.84, "
            "8mm=2.88, 10mm=3.92. "
            "6.00 (región 5) — 3mm=0.43, 4mm=0.63, 5mm=0.86, 6mm=1.16, "
            "8mm=1.84, 10mm=2.65.\n\n"
            "Tabla K.4.2-4 — Áreas máximas en m² por espesor para vidrios "
            "templados colocados verticalmente, con relación largo/ancho menor o "
            "igual a dos (2) y soportados en los cuatro lados (Presión kN/m² · "
            "Área en m² para espesores 3/4/5/6/8/10 mm): "
            "2.00 (regiones 3-5) — 4mm=4.40, 5mm=6.60, 6mm=9.00, 8mm=12.18, "
            "10mm=19.76. "
            "3.00 (regiones 4-5) — 3mm=2.85, 4mm=4.27, 5mm=5.76, 6mm=7.72, "
            "8mm=11.52, 10mm=14.58. "
            "4.00 (región 5) — 3mm=2.00, 4mm=3.03, 5mm=3.92, 6mm=4.99, "
            "8mm=7.22, 10mm=9.59. "
            "5.00 (región 5) — 3mm=1.55, 4mm=2.18, 5mm=2.76, 6mm=3.59, "
            "8mm=5.31, 10mm=6.85. "
            "6.00 (región 5) — 3mm=1.18, 4mm=1.62, 5mm=2.06, 6mm=2.76, "
            "8mm=4.06, 10mm=5.45.\n\n"
            "Tabla K.4.2-5 — Áreas máximas en m² por espesor para vidrios "
            "recocidos laminados con PVB colocados verticalmente, con relación "
            "largo/ancho menor o igual a dos (2) y soportados en los cuatro "
            "lados (Presión kN/m² · Área en m² para espesores 5/6/8/10/12/16 "
            "mm): "
            "0.50 (regiones 1-5) — 5mm=8.64, 6mm=11.56, 8mm no aplica, 10mm no "
            "aplica, 12mm no aplica, 16mm no aplica. "
            "0.75 (regiones 1-5) — 5mm=5.45, 6mm=7.57, 8mm=12.33. "
            "1.00 (regiones 1-5) — 5mm=3.84, 6mm=5.31, 8mm=8.08, 10mm=10.26. "
            "1.25 (regiones 2-5) — 5mm=2.42, 6mm=3.92, 8mm=6.02, 10mm=7.76, "
            "12mm=9.50. "
            "1.50 (regiones 2-5) — 5mm=2.31, 6mm=3.13, 8mm=4.65, 10mm=6.06, "
            "12mm=7.61, 16mm=13.36. "
            "2.00 (regiones 3-5) — 5mm=1.57, 6mm=2.08, 8mm=3.25, 10mm=4.21, "
            "12mm=5.38, 16mm=8.90. "
            "3.00 (regiones 4-5) — 5mm=0.91, 6mm=1.28, 8mm=2.00, 10mm=2.65, "
            "12mm=3.38, 16mm=5.71. "
            "4.00 (región 5) — 5mm=0.63, 6mm=0.90, 8mm=1.30, 10mm=1.84, "
            "12mm=2.41, 16mm=4.15. "
            "5.00 (región 5) — 5mm=0.52, 6mm=0.64, 8mm=0.90, 10mm=1.41, "
            "12mm=1.88, 16mm=3.23. "
            "7.00 (región 5) — 5mm=0.32, 6mm=0.48, 8mm=0.71, 10mm=0.96, "
            "12mm=1.27, 16mm=2.16.\n\n"
            "K.4.2.6.1 — Se prohíbe el uso de vidrios de 2 mm debido a su "
            "excesiva flexibilidad."
        ),
    },
    {
        "id": "NSR10-K-K_4_2_7_deflexiones",
        "seccion": "K.4.2.7 (Deflexiones Admisibles)",
        "titulo": "Límites de deflexión de los elementos de soporte del vidrio (L/175, L/240+6.35mm), torsión máxima 1° y consideraciones de sellantes.",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2.7 — DEFLEXIONES ADMISIBLES — "
            "Deben determinarse analíticamente las deflexiones bajo cargas de "
            "diseño de los elementos que sirvan de apoyo a los vidrios en "
            "cualquier sistema vidriado. Cuando se requieran ensayos "
            "estructurales para determinar las deflexiones, éstos deben "
            "realizarse de acuerdo con la norma ASTM E330-02. Cuando en los "
            "sistemas de marco se utilicen perfiles extruídos para los cuales se "
            "han determinado las propiedades físicas y se han ensayado los "
            "sistemas de anclajes y conexiones, no se requiere la realización de "
            "ensayos estructurales.\n\n"
            "K.4.2.7.1 — Bajo cargas de diseño, para elementos que soporten "
            "vidrio cuyos bordes se consideren firmemente soportados, la "
            "deflexión de los elementos en la dirección perpendicular al plano "
            "del muro debe satisfacer los requisitos de estas normas, pero no "
            "debe exceder la longitud de la luz dividida por 175 (L/175) en "
            "luces de hasta 4 m, y la longitud de la luz dividida por 240 más "
            "6.35 mm (L/240 + 6.35 mm) en luces entre 4 m y 12 m. Las luces "
            "mayores que 12 m pueden requerir restricciones adicionales y deben "
            "ser analizadas por el diseñador estructural o por el diseñador de "
            "elementos no estructurales, según sea el caso. Si el valor L/175 se "
            "considera excesivo para aplicaciones específicas, el diseñador "
            "puede especificar menores deflexiones. Cuando se afecta un panel de "
            "yeso la deflexión no debe exceder 1/360 de la luz. Cuando los "
            "elementos que soportan el vidrio (marco) no cumplan los anteriores "
            "requisitos de deflexión, el análisis de las láminas de vidrio, debe "
            "considerar las deflexiones del marco.\n\n"
            "K.4.2.7.2 — Bajo carga muerta, para elementos horizontales del "
            "marco, que soporten vidrio, su deflexión en la dirección paralela "
            "al plano del muro no debe exceder una cantidad que reduzca la "
            "mordedura en el borde del vidrio a menos del 75% de la dimensión de "
            "diseño ni una cantidad con la cual se puedan reducir las holguras "
            "necesarias del vidriado. La deflexión en esta dirección también se "
            "debe limitar para proporcionar al menos 3 mm de holgura entre el "
            "elemento y la parte superior del panel de vidrio fijado, o "
            "cualquier otra parte inmediatamente debajo del elemento. La holgura "
            "entre el elemento y una ventana o puerta operable por debajo debe "
            "ser al menos de 1.5 m.\n\n"
            "K.4.2.7.3 — La torsión de los elementos horizontales debida al peso "
            "del vidrio no debe exceder 1°, medido entre los extremos y el "
            "centro de cada luz.\n\n"
            "K.4.2.7.4 — Se debe considerar que algunos sellantes requieren "
            "deflexiones menores a las aquí especificadas; para estos casos la "
            "deflexión en los elementos del marco deberá evitar el daño a los "
            "acabados interiores o la desconexión de elementos de revestimiento "
            "aplicados exteriormente."
        ),
    },
    {
        "id": "NSR10-K-K_4_2_8_movimientos_estructura",
        "seccion": "K.4.2.8 (Movimientos de la Estructura: Juntas de Expansión, Marcos de Sujeción, Sistemas de Anclaje)",
        "titulo": "Ecuaciones K.4.2-19 a K.4.2-21: deriva que causa la caída del vidrio (Δcaída), holguras perimetrales y las 3 excepciones al requisito.",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2.8 — MOVIMIENTOS DE LA "
            "ESTRUCTURA — Se requiere que el diseño garantice que no se "
            "transmitan cargas a los vidrios debidas a movimientos de la "
            "estructura.\n\n"
            "K.4.2.8.1 — Juntas de expansión — Debe haber una junta de expansión "
            "vertical por cada piso de la edificación, colocada preferencialmente "
            "en un miembro de soporte horizontal. Las juntas de expansión "
            "horizontal deben colocarse, bien en cada eje de columnas ó a 6.0 m "
            "de distancia cada una, según lo que resulte menor. La expansión "
            "debe ser desde el centro hacia los extremos para minimizar los "
            "movimientos de la junta y así reducir los esfuerzos sobre "
            "sellantes y conectores. Para el dimensionamiento de juntas se deben "
            "considerar la expansión y contracción máxima, así como la "
            "diferencia de coeficientes de dilatación térmica entre el vidrio y "
            "los elementos metálicos del marco. En las juntas de expansión en "
            "montantes no se debe permitir la aplicación de cargas al vidrio "
            "debidas a movimientos de la estructura o al sistema de marco.\n\n"
            "K.4.2.8.2 — Marcos de sujeción — Los marcos de sujeción del vidrio "
            "se deben diseñar para que se acomoden a la deriva y para eliminar "
            "las cargas sobre los bordes y superficies del vidrio, por medio de "
            "holguras perimetrales y laterales. Los elementos de amortiguación "
            "que se coloquen en el marco o en los bordes de las esquinas del "
            "vidrio para eliminar cualquier contacto entre el vidrio y el marco "
            "por la oscilación prevista del marco debido a los efectos sísmicos, "
            "deben fabricarse con material de dureza Shore A de 50 a 70. La "
            "aplicación de sellantes se debe realizar de manera que admitan los "
            "movimientos previstos del sistema de vidriado y para proporcionar "
            "la capacidad estructural junto con los requisitos de "
            "impermeabilización y la habilidad de retención del vidrio.\n\n"
            "K.4.2.8.3 — Sistemas de anclaje — En el diseño de los anclajes de "
            "muros cortina y de juntas se deben considerar los movimientos de la "
            "estructura principal de la edificación y del muro cortina o "
            "fachada flotante por cargas gravitacionales, efectos sísmicos, "
            "cargas térmicas, de viento u otra causa. La expansión y la "
            "contracción de los materiales no deben causar pandeo, falla de "
            "sellos de junta, reducción del desempeño u otros efectos "
            "perjudiciales. Adicionalmente las puertas y ventanas deben "
            "funcionar normalmente en todo el intervalo de temperaturas de "
            "funcionamiento normal de la edificación. Los anclajes para cargas "
            "de viento deben permitir la libre expansión vertical de los "
            "montantes sin causar esfuerzos adicionales sobre los montantes, "
            "conectores o anclajes. Los cojinetes de deslizamiento son lo más "
            "aconsejable para este propósito; el aceite y la grasa pierden sus "
            "cualidades de lubricación al pasar un largo tiempo. Los montantes "
            "de doble luz deben tener un anclaje de carga muerta localizado tan "
            "cerca como sea posible de su punto medio, para así igualar la "
            "expansión y contracción hacia arriba y hacia abajo. Los anclajes "
            "deben tener la dureza, flexibilidad y resistencia suficientes para "
            "soportar las cargas muertas y las cargas dinámicas a que puedan "
            "estar sometidos, y además en el diseño se deben considerar las "
            "tolerancias de fabricación y construcción. Adicionalmente los "
            "anclajes deben permitir al muro cortina o fachada flotante "
            "desempeñarse satisfactoriamente en cuanto a su función básica de "
            "proteger el interior de la edificación del ambiente exterior. El "
            "diseño de los anclajes debe considerar los efectos sísmicos "
            "mediante la aplicación de una carga calculada de acuerdo con el "
            "Capítulo A.9; en el diseño también se deben considerar las demás "
            "especificaciones del Capítulo A.9. En cada detalle de anclaje se "
            "debe revisar cuidadosamente la capacidad de las conexiones "
            "pernadas y la localización y tamaño de las soldaduras. Se deben "
            "usar dispositivos de cierre para evitar que los elementos se "
            "desconecten o se desajusten a causa de movimientos inducidos por "
            "cambios térmicos o por el viento. Los anclajes no deben estar en "
            "el área húmeda de un sistema. K.4.2.8.4 — En los casos en que se "
            "permita la rotación de los montantes del sistema vidriado por "
            "efecto de las derivas, es necesario que los vidrios puedan rotar "
            "libremente sin romperse. En los casos en que se utilicen "
            "siliconas para las juntas entre paneles, éstas deben permitir que "
            "los paneles de vidrio se muevan con relación a los adyacentes. "
            "Igualmente, es necesario considerar, además de las cargas "
            "inerciales, las cargas generadas por la rotación de los paneles de "
            "vidrio como consecuencia de la deriva.\n\n"
            "K.4.2.8.5 — Los sistemas en muros cortina vidriados, fachadas "
            "vidriadas, o particiones vidriadas deben evaluarse de acuerdo con "
            "AAMA 501.6-01 Recommended Dynamic Test Method for Determining the "
            "Seismic Drift Causing Glass Fallout from a Wall System, o por "
            "análisis de ingeniería, de manera que se especifique explícitamente "
            "la deriva que causa la caída del vidrio (Δcaída) del muro cortina "
            "o fachada flotante, fachada, o partición. K.4.2.8.6 — Para los "
            "sistemas en muros cortina vidriados o fachadas flotantes, fachadas "
            "vidriadas, o particiones vidriadas debe verificarse que: Δcaída ≥ "
            "1.25·I·Dp ≥ 13 mm (K.4.2-19). Donde: Δcaída = deriva que causa la "
            "caída del vidrio del muro cortina o fachadas flotantes, fachada, o "
            "partición, determinada de acuerdo con K.4.2.8.5. Dp = deriva o "
            "desplazamiento relativo calculado del análisis sísmico para el "
            "sistema vidriado. I = coeficiente de Importancia para el Grupo de "
            "Uso.\n\n"
            "K.4.2.8.6.1 — El requisito anterior puede obviarse en los "
            "siguientes casos: (a) Vidrios que tengan holguras perimetrales "
            "alrededor de su marco, calculadas de acuerdo con la Ecuación "
            "K.4.2-20, de tal forma que no ocurra contacto físico entre el "
            "vidrio y el marco cuando se aplique la deriva de diseño: Dlibre ≥ "
            "1.25·Dp (K.4.2-20). Donde: Dlibre = desplazamiento relativo "
            "horizontal, medido sobre la altura del panel de vidrio bajo "
            "consideración, que causa el contacto inicial entre el vidrio y su "
            "marco y que para paneles de vidrio rectangulares dentro de un "
            "marco rectangular tiene el valor dado por la Ecuación K.4.2-21: "
            "Dlibre = 2·c1·(1 + hp·c2/(bp·c1)) (K.4.2-21). Donde: hp = altura "
            "del panel de vidrio rectangular. bp = ancho del panel de vidrio "
            "rectangular. c1 = holgura perimetral entre los bordes verticales "
            "del vidrio y el marco. c2 = holgura perimetral entre los bordes "
            "horizontales del vidrio y el marco. (b) Vidrios templados de "
            "seguridad monolíticos en edificaciones de los Grupos de Uso I y "
            "II, que estén localizados a no más de 3 m por encima de una "
            "superficie de tránsito peatonal. (c) Vidrios recocidos laminados o "
            "termoendurecidos laminados con entrecapa no menor que 0.76 mm, que "
            "son capturados mecánicamente en la cavidad del sistema de "
            "vidriado, y cuyo perímetro está asegurado al marco por un tipo de "
            "sello perimetral como sellante elastomérico de curado húmedo con "
            "mínimo 13 mm de ancho en el contacto con el vidrio, u otro sistema "
            "de anclaje aprobado."
        ),
    },
    {
        "id": "NSR10-K-K_4_2_9_efectos_sismicos_otros",
        "seccion": "K.4.2.9 (Consideraciones de los Efectos Sísmicos para el Uso de Otros Elementos en Sistemas Vidriados)",
        "titulo": "Desempeño de empaques, cuñas de apoyo y bandas de acabado a presión bajo efectos sísmicos.",
        "texto": (
            "NSR-10 Título K, Capítulo K.4 — K.4.2.9 — CONSIDERACIONES DE LOS "
            "EFECTOS SÍSMICOS PARA EL USO DE OTROS ELEMENTOS EN SISTEMAS "
            "VIDRIADOS. K.4.2.9.1 — Desempeño de empaques (burletes) — Para un "
            "sistema de vidriado seco consiste en un empaque insertado por un "
            "lado y un empaque aplicado (húmedo) por el otro lado del vidrio, el "
            "empaque húmedo debe tener un método para asegurar de modo que no "
            "se desacople del sistema de marco metálico durante el movimiento "
            "vertical y lateral que ocurre durante un evento sísmico. El "
            "empaque debe permanecer en su lugar cuando el vidrio se mueva por "
            "la oscilación de la edificación.\n\n"
            "K.4.2.9.2 — Cuñas de apoyo y soportes — Las cuñas de apoyo se deben "
            "posicionar de manera permanente mediante acuñado en un elemento "
            "horizontal del marco, usando un sellante compatible para la "
            "colocación u otro método que no permita movimiento del calzo o "
            "cuña. Cuando se usen soportes para las cuñas, deben ser anclados o "
            "asegurados permanentemente al elemento horizontal del marco y "
            "deben posicionar las cuñas de apoyo como se especificó "
            "anteriormente.\n\n"
            "K.4.2.9.3 — Bandas de acabado aplicadas y empaques u otros "
            "elementos a presión — Los elementos del sistema de vidriado que "
            "actúen como bandas de acabado y/o elementos de soporte del vidrio "
            "que utilizan la compresión de empaques o acoples metálicos para "
            "permanecer en su posición, se deben diseñar y sujetar para que el "
            "elemento no llegue a interrumpir, de forma permanente o temporal, "
            "el soporte que le suministra al vidrio, debido a la vibración y "
            "oscilación por efectos sísmicos."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])
    print(f"Chunks a insertar: {len(CHUNKS)}")
    for c in CHUNKS:
        print(f"  {c['id']} ({c['seccion']}): {len(c['texto'])} chars")

    print("\nCargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
    textos = [c["texto"] for c in CHUNKS]
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print("\nSubiendo a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()

    print("\nBorrando el chunk viejo condensado (NSR10-K-K_4_2_requisitos_diseno)...")
    sb.table("nsr10_chunks").delete().eq("id", "NSR10-K-K_4_2_requisitos_diseno").execute()

    print(f"\nOK: {len(rows)} chunks verbatim de K.4.2 cargados. Numeral K.4.2 completo.")


if __name__ == "__main__":
    main()
