"""
Ingesta verbatim de Título A, Capítulo A.13 (Definiciones y nomenclatura
del Título A) -- NSR-10. Fase 1 del plan de cierre del Título A
(2026-09-22). La auditoría real de numerales solo detectó "A.13, A.13.1,
A.13.2" (3 faltantes) porque el capítulo es un glosario alfabético +
tabla de nomenclatura, sin numeración interna de artículos -- el regex de
auditoría (pensado para clausulas numeradas) no detecta cada término
individual como un numeral aparte. En superficie real el capítulo son 14
páginas de definiciones y símbolos, ninguna con chunk antes de esta
ingesta.

Fuente: NSR-10-168-181.pdf, páginas PDF 1-14 (A-125 a A-138, capítulo
completo), leídas visualmente con Read pages= sobre el PDF nativo.

Uso: python _ingest_titulo_a_a13_verbatim.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "A"

CHUNKS = [
    {
        "id": "NSR10-A-A_13_1_def_acabados_a_armadura",
        "seccion": "A.13.1 — Definiciones (Acabados a Armadura)",
        "titulo": "Título A, A.13.1: glosario, términos Acabados a Armadura (aceleración pico efectiva, acelerograma, acelerógrafo, amenaza sísmica, análisis dinámico/elástico/inelástico/espectral/modal, apéndice).",
        "texto": (
            "CAPÍTULO A.13 — DEFINICIONES Y NOMENCLATURA DEL TÍTULO A\n\n"
            "A.13.1 — DEFINICIONES\n\n"
            "Las definiciones siguientes corresponden al Título A de este "
            "Reglamento:\n\n"
            "Acabados — Partes y componentes de una edificación que no hacen "
            "parte de la estructura o de su cimentación. Véase elementos no "
            "estructurales\n\n"
            "Aceleración pico efectiva, Aa — Es un parámetro utilizado para "
            "determinar el espectro de diseño y se da en A.2.2.\n\n"
            "Acelerograma — Descripción en el tiempo de las aceleraciones a que "
            "estuvo sometido el terreno durante la ocurrencia de un sismo real.\n\n"
            "Acelerógrafo — Instrumento que permite registrar las aceleraciones a "
            "que se ve sometido el terreno durante la ocurrencia de un sismo. Este "
            "registro queda consignado en un acelerograma.\n\n"
            "Altura de la edificación en la colindancia — Es la suma de las "
            "alturas de piso en la colindancia.\n\n"
            "Altura del piso — Es la distancia vertical medida entre el terminado "
            "de la losa de piso o de nivel de terreno y el terminado de la losa "
            "del nivel inmediatamente superior. En el caso que el nivel "
            "inmediatamente superior corresponda a la cubierta de la edificación "
            "esta medida se llevará hasta el nivel de enrace de la cubierta "
            "cuando esta sea inclinada o hasta al nivel de la impermeabilización "
            "o elemento de protección contra la intemperie cuando la cubierta "
            "sea plana. En los casos en los cuales la altura de piso medida como "
            "se indica anteriormente exceda 6 m, se considerará para efectos de "
            "calcular el número de pisos como dos pisos. Se permite que para el "
            "primer piso aéreo la altura del piso se mida desde la corona del "
            "muro de contención de la edificación nueva contra el paramento que "
            "está en la colindancia, cuando éste exista.\n\n"
            "Amenaza sísmica — Es el valor esperado de futuras acciones sísmicas "
            "en el sitio de interés y se cuantifica en términos de una "
            "aceleración horizontal del terreno esperada, que tiene una "
            "probabilidad de excedencia dada en un lapso de tiempo "
            "predeterminado.\n\n"
            "Amortiguamiento — Pérdida de energía en un movimiento ondulatorio.\n\n"
            "Amplificación de la onda sísmica — Aumento en la amplitud de las "
            "ondas sísmicas, producido por su paso desde la roca hasta la "
            "superficie del terreno a través de los estratos de suelo.\n\n"
            "Análisis dinámico — Procedimiento matemático por medio del cual se "
            "resuelven las ecuaciones de equilibrio dinámico, con el fin de "
            "obtener las deformaciones y esfuerzos de la estructura al ser "
            "sometida a una excitación que varía en el tiempo.\n\n"
            "Análisis dinámico elástico — Tipo de análisis dinámico en el cual "
            "las propiedades de rigidez y resistencia de la estructura "
            "permanecen dentro del rango de respuesta lineal.\n\n"
            "Análisis dinámico inelástico — Tipo de análisis dinámico en el cual "
            "se tiene en cuenta que las propiedades de rigidez y resistencia de "
            "la estructura pueden salirse del rango de respuesta lineal y entrar "
            "en el rango de respuesta inelástica.\n\n"
            "Análisis espectral — Tipo de análisis dinámico modal en el cual la "
            "respuesta dinámica máxima de cada modo se obtiene utilizando la "
            "ordenada del espectro, correspondiente al período de vibración del "
            "modo.\n\n"
            "Análisis modal — Procedimiento de análisis dinámico por medio del "
            "cual la respuesta dinámica de la estructura se obtiene como la "
            "superposición de las respuestas de los diferentes modos, o formas "
            "de vibración.\n\n"
            "Apéndice — Es un elemento no estructural que sobresale del volumen "
            "general de la edificación.\n\n"
            "Armadura — Véase cercha."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_base_a_r0",
        "seccion": "A.13.1 — Definiciones (Base a Coeficiente de capacidad de disipación de energía básico R0)",
        "titulo": "Título A, A.13.1: glosario, términos Base a R0 (capacidad de disipación de energía, carga muerta/viva, casa, centro de masa/rigidez del piso, cercha, cerramiento, coeficiente de amortiguamiento crítico).",
        "texto": (
            "Base — Es el nivel en el que los movimientos sísmicos son "
            "transmitidos a la estructura o el nivel en el que la estructura, "
            "considerada como un oscilador, está apoyada.\n\n"
            "Capacidad de disipación de energía — Es la capacidad que tiene un "
            "sistema estructural, un elemento estructural, o una sección de un "
            "elemento estructural, de trabajar dentro del rango inelástico de "
            "respuesta sin perder su resistencia. Se cuantifica por medio de la "
            "energía de deformación que el sistema, elemento o sección es capaz "
            "de disipar en ciclos histeréticos consecutivos. Cuando hace "
            "referencia al sistema de resistencia sísmica de la edificación como "
            "un todo, se define por medio del coeficiente de capacidad de "
            "disipación de energía básico R0, el cual después se afecta debido a "
            "irregularidades de la estructura y a ausencia de redundancia en el "
            "sistema de resistencia sísmica, para obtener el coeficiente de "
            "disipación de energía R (R = φa·φp·φr·R0). El grado de capacidad de "
            "disipación de energía se clasifica como especial (DES), moderado "
            "(DMO) y mínimo (DMI).\n\n"
            "Capacidad de rotación de la sección — Es la capacidad que tiene una "
            "sección de un elemento estructural de admitir rotaciones en el "
            "rango inelástico sin perder su capacidad de resistir momentos "
            "flectores y fuerzas cortantes. Se mide en términos de su capacidad "
            "de disipación de energía a la rotación.\n\n"
            "Carga muerta — Es la carga vertical debida a los efectos "
            "gravitacionales de la masa, o peso, de todos los elementos "
            "permanentes ya sean estructurales o no estructurales. Debe "
            "consultarse el Título B de este Reglamento.\n\n"
            "Carga gravitacional o peso, (M.g) — Es el efecto vertical de la "
            "aceleración debida a la gravedad sobre la masa, M, de la "
            "edificación. M debe ser igual a la masa de la estructura más la "
            "masa de los elementos tales como muros divisorios y particiones, "
            "equipos permanentes, tanques y sus contenidos, etc. En depósitos y "
            "bodegas debe incluirse además un 25 por ciento de la masa que "
            "produce la carga viva.\n\n"
            "Carga viva — Es la carga debida al uso de la estructura, sin "
            "incluir la carga muerta, fuerza de viento o sismo. Debe consultarse "
            "el Título B de este Reglamento.\n\n"
            "Casa — Edificación unifamiliar destinada a vivienda. Esta "
            "definición se incluye únicamente para efectos de la aplicación del "
            "Título E del Reglamento.\n\n"
            "Centro de masa del piso — Es el lugar geométrico donde estaría "
            "localizada, en planta, toda la masa del piso al suponer el "
            "diafragma del piso como un cuerpo infinitamente rígido en su "
            "propio plano.\n\n"
            "Centro de rigidez del piso — Es el lugar geométrico, localizado en "
            "planta y determinado bajo el supuesto de que el diafragma del piso "
            "es infinitamente rígido en su propio plano, donde al aplicar una "
            "fuerza horizontal, en cualquier dirección, no se presenta rotación "
            "del diafragma alrededor de un eje vertical.\n\n"
            "Cercha — Es un conjunto de elementos estructurales unidos entre si, "
            "los cuales resisten primordialmente fuerzas axiales.\n\n"
            "Cerramiento — Muro localizado en el paramento del lote de terreno y "
            "que se encuentra separado de la edificación en la dirección "
            "perpendicular al paramento del lote de terreno, que no hace parte "
            "del sistema estructural de soporte de la edificación, y cuya altura "
            "no excede 4 metros.\n\n"
            "Coeficiente de amortiguamiento crítico — Es, para un sistema "
            "elástico, de un grado de libertad con amortiguamiento viscoso, el "
            "cociente entre la cantidad de amortiguamiento del sistema y el "
            "amortiguamiento mínimo que inhibe toda oscilación.\n\n"
            "Coeficiente de capacidad de disipación de energía básico, R0 — "
            "Coeficiente que se prescribe para cada sistema estructural de "
            "resistencia sísmica, cuyo valor depende del tipo de sistema "
            "estructural y de las características de capacidad de disipación de "
            "energía propias del material estructural que se utiliza en el "
            "sistema. Es una medida de la capacidad de disipación de energía "
            "general del sistema de resistencia sísmica cuando los movimientos "
            "sísmicos hacen que responda inelásticamente."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_r_a_disenador_estructural",
        "seccion": "A.13.1 — Definiciones (Coeficiente de capacidad de disipación de energía R a Diseñador estructural)",
        "titulo": "Título A, A.13.1: glosario, R (coeficiente de disipación de energía completo), coincidencia de losas en colindancia, construcción sismo resistente, constructor, cortante de piso Vx, cortante en la base Vs, cuerda, deriva de piso, desempeño de elementos no estructurales, DES, diafragma, diagonal (concéntrica/excéntrica), diseñadores.",
        "texto": (
            "Coeficiente de capacidad de disipación de energía, R — Coeficiente "
            "que corresponde al coeficiente de capacidad de disipación de "
            "energía básico, R0, multiplicado por los coeficientes de reducción "
            "de capacidad de disipación debido a irregularidades en alzado, φa, "
            "irregularidad en planta, φp, y a ausencia de redundancia del "
            "sistema estructural de resistencia sísmica, φr. (R = φa·φp·φr·R0).\n\n"
            "Coincidencia de las losas de entrepiso en la colindancia — Se "
            "considera que las losas de entrepiso de dos estructuras colindantes "
            "coinciden o están en contacto cuando al menos la mitad de la altura "
            "de la losa de entrepiso de la edificación cuya licencia de "
            "construcción se solicita, coincida en nivel con la losa de "
            "entrepiso de la edificación colindante existente.\n\n"
            "Construcción sismo resistente — Es el tipo de construcción que "
            "cumple el objetivo expresado en A.1.2.2, a través de un diseño y "
            "una construcción que cumplan los requisitos de la Ley 400 de 1997 y "
            "del presente Reglamento.\n\n"
            "Constructor — Es el profesional, ingeniero civil, arquitecto o "
            "constructor en arquitectura e ingeniería, bajo cuya responsabilidad "
            "se adelante la construcción de la edificación.\n\n"
            "Cortante de piso, Vx — Es la suma algebraica de las fuerzas "
            "sísmicas horizontales que actúan por encima del piso en "
            "consideración.\n\n"
            "Cortante en la base, Vs — Es la suma algebraica, tomada en la base, "
            "de todas las fuerzas sísmicas horizontales del edificio.\n\n"
            "Cuerda — Es el elemento de borde de un diafragma, el cual resiste "
            "principalmente esfuerzos axiales, en una forma análoga a las aletas "
            "de una viga.\n\n"
            "Deriva de piso — Es la diferencia entre los desplazamientos "
            "horizontales de los niveles entre los cuales está comprendido el "
            "piso.\n\n"
            "Desempeño de los elementos no estructurales — Se denomina "
            "desempeño el comportamiento de los elementos no estructurales de la "
            "edificación ante la ocurrencia de un sismo que la afecte. El "
            "desempeño se clasifica en grado superior, bueno y bajo.\n"
            "(a) Grado de desempeño superior — Es aquel en el cual el daño que "
            "se presenta en los elementos no estructurales es mínimo y no "
            "interfiere con la operación de la edificación en ningún aspecto.\n"
            "(b) Grado de desempeño bueno — Es aquel en el cual el daño que se "
            "presenta en los elementos no estructurales es totalmente reparable "
            "y puede haber alguna interferencia con la operación de la "
            "edificación con posterioridad a la ocurrencia del sismo.\n"
            "(c) Grado de desempeño bajo — Es aquel en el cual se presentan "
            "daños graves en los elementos no estructurales, inclusive no "
            "reparables.\n\n"
            "DES — Capacidad especial de disipación de energía.\n\n"
            "Diafragma — Conjunto de elementos estructurales, tal como una losa "
            "de entrepiso, que transmite las fuerzas inerciales horizontales a "
            "los elementos verticales del sistema de resistencia sísmica. El "
            "término diafragma incluye conjuntos arriostrados horizontales. "
            "Véase sistema de arriostramiento horizontal.\n\n"
            "Diagonal — Es un elemento estructural que hace parte de un pórtico "
            "con diagonales. La diagonal puede ser concéntrica, en pórticos con "
            "diagonales de concreto reforzado o de acero estructural, o "
            "excéntrica en pórticos de acero estructural.\n\n"
            "Diagonal concéntrica — Es una diagonal cuyos dos extremos llegan a "
            "conexiones entre viga y columna.\n\n"
            "Diagonal excéntrica — Es una diagonal en la cual uno de sus "
            "extremos llega a la viga en un punto alejado de la conexión entre "
            "viga y columna. Solo se utiliza en pórticos de acero estructural "
            "con diagonales.\n\n"
            "Diseñador arquitectónico — Es el arquitecto bajo cuya "
            "responsabilidad se realizan el diseño y los planos "
            "arquitectónicos de la edificación, y quien los firma o rotula.\n\n"
            "Diseñador de los elementos no estructurales — Es el profesional "
            "facultado para este fin, bajo cuya responsabilidad se realizan el "
            "diseño y los planos de los elementos no estructurales de la "
            "edificación, y quien los firma o rotula.\n\n"
            "Diseñador estructural — Es el ingeniero civil, facultado para ese "
            "fin, bajo cuya responsabilidad se realiza el diseño y los planos "
            "estructurales de la edificación, y quien los firma o rotula."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_dmo_a_espectro_diseno",
        "seccion": "A.13.1 — Definiciones (DMO a Espectro de diseño)",
        "titulo": "Título A, A.13.1: glosario, DMO, DMI, ductilidad (curvatura/rotación/desplazamiento/deformación), edificación, edificación de atención a la comunidad, edificaciones indispensables, elemento estructural, elemento colector/borde, elementos flexibles/no estructurales, efectos ortogonales, efectos P-Delta, espectro/espectro de diseño.",
        "texto": (
            "DMO — Capacidad moderada de disipación de energía.\n\n"
            "DMI — Capacidad mínima de disipación de energía.\n\n"
            "Ductilidad — Capacidad que tiene un material estructural de "
            "resistir, sin fallar, deformaciones que lleven al material "
            "estructural más allá del límite elástico, o límite donde las "
            "deformaciones son linealmente proporcionales al esfuerzo o fuerza "
            "aplicada. (Véase capacidad de disipación de energía, pues muchas "
            "veces estos términos son confundidos.) Dependiendo del parámetro "
            "que describe las deformaciones, la ductilidad puede hacer "
            "referencia, entre otras, a:\n"
            "(a) Ductilidad de curvatura — cuando la ductilidad se mide con "
            "respecto a la curvatura de la sección del elemento estructural. La "
            "curvatura se define como el cociente entre el momento flector "
            "aplicado y la rigidez de la sección,\n"
            "(b) Ductilidad de rotación — cuando la ductilidad se mide con "
            "respecto a la rotación que tiene un sector longitudinal del "
            "elemento estructural. La rotación se define como la pendiente de "
            "la línea elástica del elemento medida con respecto a la posición "
            "original del eje longitudinal del elemento,\n"
            "(c) Ductilidad de desplazamiento — cuando la ductilidad se mide "
            "con respecto al desplazamiento o deflexión que tiene el elemento "
            "estructural. El desplazamiento se mide con respecto a la posición "
            "original del eje longitudinal del elemento, y\n"
            "(d) Ductilidad de deformación — cuando la ductilidad se mide con "
            "respecto a la deformación unitaria de una fibra paralela al eje "
            "neutro de la sección.\n\n"
            "Edificación — Es una construcción cuyo uso primordial es la "
            "habitación u ocupación por seres humanos.\n\n"
            "Edificación de atención a la comunidad — Son los equipamentos "
            "urbanos necesarios para atender emergencias, preservar la salud y "
            "la seguridad de las personas, tales como estaciones de bomberos, "
            "cuarteles de policía y fuerzas militares, instalaciones de salud, "
            "sedes de organismos operativos de emergencias, entre otros.\n\n"
            "Edificaciones indispensables — Son aquellos equipamentos urbanos "
            "de atención a la comunidad que deben funcionar durante y después "
            "de un sismo, cuya operación no puede ser trasladada rápidamente a "
            "un lugar alterno, tales como hospitales y centrales de operación y "
            "control de líneas vitales.\n\n"
            "Efectos gravitacionales — Véase peso.\n\n"
            "Elemento o miembro estructural — Componente del sistema "
            "estructural de la edificación. En las estructuras metálicas los "
            "dos términos no son sinónimos pues un miembro está compuesto por "
            "elementos. Por ejemplo en una viga con sección en I, la viga en sí "
            "es el miembro estructural, y su alma y alas son elementos del "
            "miembro.\n\n"
            "Elemento colector — Es un elemento que sirve para transmitir las "
            "fuerzas inerciales generadas dentro del diafragma, hasta los "
            "elementos del sistema de resistencia sísmica.\n\n"
            "Elemento de borde — Es un elemento que se coloca en los bordes de "
            "las aberturas, en el perímetro de los muros de cortante o en el "
            "perímetro de los diafragmas.\n\n"
            "Elementos flexibles (o sistemas flexibles) — Son aquellos cuya "
            "deformación, al ser solicitados por una fuerza horizontal, es "
            "significativamente mayor que la de los elementos adyacentes del "
            "sistema.\n\n"
            "Elementos no estructurales — Elementos o componentes de la "
            "edificación que no hacen parte de la estructura o su cimentación. "
            "Véase acabados.\n\n"
            "Efectos ortogonales — Son los que se producen en los elementos "
            "estructurales que pertenecen, simultáneamente, a sistemas "
            "resistentes situados en dos ejes ortogonales, cuando las fuerzas "
            "sísmicas actúan en una dirección distinta a la de estos dos ejes.\n\n"
            "Efectos P-Delta — Son los efectos de segundo orden en los "
            "desplazamientos horizontales y fuerzas internas de la estructura, "
            "causados por la acción de las cargas verticales de la edificación "
            "al verse desplazada horizontalmente.\n\n"
            "Espectro — Es la colección de valores máximos, ya sea de "
            "aceleración, velocidad o desplazamiento, que tienen los sistemas "
            "de un grado de libertad durante un sismo.\n\n"
            "Espectro de diseño — Es el espectro correspondiente a los "
            "movimientos sísmicos de diseño."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_espectro_umbral_a_mamposteria",
        "seccion": "A.13.1 — Definiciones (Espectro del umbral de daño a Mampostería estructural)",
        "titulo": "Título A, A.13.1: glosario, espectro del umbral de daño, estructura, falla geológica (activa), fuerzas mayoradas/sísmicas, grupo de uso, histéresis, índice de deriva, ingeniero geotecnista, interacción suelo-estructura, interventor, licencia de construcción, licuación, líneas vitales, mampostería estructural.",
        "texto": (
            "Espectro del umbral de daño — Es el espectro correspondiente a los "
            "movimientos sísmicos al nivel del umbral de daño.\n\n"
            "Estructura — Es un ensamblaje de elementos, diseñado para soportar "
            "las cargas gravitacionales y resistir las fuerzas horizontales. "
            "Las estructuras pueden ser catalogadas como estructuras de "
            "edificaciones o estructuras diferentes a las de las edificaciones.\n\n"
            "Falla geológica — Ruptura, o zona de ruptura, en la roca de la "
            "corteza terrestre cuyos lados han tenido movimientos paralelos al "
            "plano de ruptura.\n\n"
            "Falla geológica activa — Falla geológica que se considera que es "
            "capaz de producir movimientos sísmicos. Para efectos del presente "
            "Reglamento una falla activa es aquella que haya tenido actividad "
            "sismogénica recurrente durante el Cuaternario (véase A.2.9.3.1).\n\n"
            "Fuerzas mayoradas — Son las fuerzas que han sido multiplicadas por "
            "sus respectivos coeficientes de carga, tal como los define B.2.1 "
            "de este Reglamento.\n\n"
            "Fuerzas sísmicas — Son los efectos inerciales causados por la "
            "aceleración del sismo, expresados como fuerzas para ser "
            "utilizadas en el análisis y diseño de la estructura.\n\n"
            "Grupo de uso — Clasificación de las edificaciones según su "
            "importancia para la atención y recuperación de las personas que "
            "habitan en una región que puede ser afectada por un sismo, o "
            "cualquier tipo de desastre.\n\n"
            "Histéresis — Fenómeno por medio del cual dos, o más, propiedades "
            "físicas se relacionan de una manera que depende de la historia de "
            "su comportamiento previo. En general hace referencia al "
            "comportamiento de los materiales estructurales cuando se ven "
            "sometidos a deformaciones o esfuerzos que están fuera del rango "
            "lineal, o elástico, de comportamiento. Una gran parte de la "
            "energía que es capaz de disipar el material estructural en el "
            "rango inelástico de respuesta se asocia con el área comprendida "
            "dentro de los ciclos de histéresis.\n\n"
            "Índice de deriva — Es la deriva del piso dividida por la altura "
            "del mismo.\n\n"
            "Ingeniero geotecnista — Es el ingeniero civil, quien firma el "
            "estudio geotécnico, bajo cuya responsabilidad se realizan los "
            "estudios geotécnicos o de suelos, por medio de los cuales se fijan "
            "los parámetros de diseño de la cimentación, los efectos de "
            "amplificación de la onda sísmica causados por el tipo y "
            "estratificación del suelo subyacente a la edificación, y la "
            "definición de los parámetros del suelo que se deben utilizar en "
            "la evaluación de los efectos de interacción suelo-estructura.\n\n"
            "Instalaciones indispensables — Véase edificaciones indispensables.\n\n"
            "Interacción suelo-estructura — Es el efecto que tienen en la "
            "respuesta estática y dinámica de la estructura las propiedades de "
            "rigidez del suelo que da apoyo a la edificación, en conjunto con "
            "las propiedades de rigidez de la cimentación y de la estructura.\n\n"
            "Interventor — Es el profesional, ingeniero civil, arquitecto o "
            "constructor en arquitectura e ingeniería, que representa al "
            "propietario durante la construcción de la edificación y bajo "
            "cuya responsabilidad se verifica que ésta se adelante de acuerdo "
            "con todas las reglamentaciones correspondientes y siguiendo los "
            "planos, diseños y especificaciones realizados por los "
            "diseñadores. Véase supervisión técnica. La Interventoría incluye "
            "igualmente actividades de cuantificación de obra y puede "
            "extenderse a tareas administrativas.\n\n"
            "Licencia de construcción — Acto por medio del cual se autoriza, a "
            "solicitud del interesado, la realización de obras en un predio "
            "con construcciones, cualquiera que ellas sean, acordes con el "
            "plan de ordenamiento territorial y las normas urbanísticas del "
            "distrito o municipio.\n\n"
            "Licuación — Respuesta de los suelos sometidos a vibraciones, en la "
            "cual éstos se comportan como un fluido denso y no como una masa "
            "de suelo húmeda.\n\n"
            "Líneas vitales — Infraestructura básica de redes, tuberías o "
            "elementos conectados o continuos, que permite la movilización de "
            "energía eléctrica, aguas, combustibles, información y el "
            "transporte de personas o productos, esencial para realizar con "
            "eficiencia y calidad las actividades de la sociedad.\n\n"
            "Mampostería estructural — Véanse las Definiciones en el Título D "
            "de este Reglamento."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_masa_a_numero_pisos_aereos",
        "seccion": "A.13.1 — Definiciones (Masa a Número de pisos aéreos)",
        "titulo": "Título A, A.13.1: glosario, masa, método de la fuerza horizontal equivalente, métodos de análisis dinámico elástico/inelástico, microzonificación sísmica, modos de vibración, modo fundamental, movimientos sísmicos de diseño/umbral de daño, muro (de carga/cortante/divisorio/estructural/no estructural), número de pisos aéreos de la edificación y en la colindancia.",
        "texto": (
            "Masa — Cantidad de materia que posee un cuerpo. En el Sistema "
            "Internacional de Medidas (SI) se expresa en kilogramos, kg.\n\n"
            "Método de la fuerza horizontal equivalente — Es el método de "
            "análisis sísmico en el cual los efectos de los movimientos "
            "sísmicos de diseño se expresan por medio de unas fuerzas "
            "horizontales estáticas equivalentes.\n\n"
            "Método del análisis dinámico elástico — Es el método de análisis "
            "sísmico en el cual los efectos de los movimientos sísmicos de "
            "diseño se determinan por medio de la solución de las ecuaciones "
            "de equilibrio dinámico, considerando que las propiedades de "
            "rigidez de la estructura permanecen dentro del rango de respuesta "
            "lineal o elástica.\n\n"
            "Método del análisis dinámico inelástico — Es el método de "
            "análisis sísmico en el cual los efectos de los movimientos "
            "sísmicos de diseño se determinan por medio de la solución de las "
            "ecuaciones de equilibrio dinámico, considerando que las "
            "propiedades de rigidez de la estructura se salen del rango de "
            "respuesta lineal o elástica.\n\n"
            "Microzonificación sísmica — División de una región o de un área "
            "urbana, en zonas más pequeñas que presentan un cierto grado de "
            "similitud en la forma como se ven afectadas por los movimientos "
            "sísmicos, dadas las características de los estratos de suelo "
            "subyacente.\n\n"
            "Modos de vibración — Son las diferentes formas de vibración "
            "propias de la estructura. A cada modo corresponde una frecuencia "
            "de vibración propia. La respuesta dinámica de la estructura, en "
            "el rango elástico, se puede expresar como la superposición de "
            "los efectos de los diferentes modos. Una estructura tiene tantos "
            "modos de vibración, como grados de libertad tenga.\n\n"
            "Modo fundamental — Es el modo de vibración correspondiente al "
            "período fundamental de la estructura en la dirección horizontal "
            "de interés.\n\n"
            "Movimientos sísmicos de diseño — Es una caracterización de los "
            "movimientos del terreno, en el sitio donde se encuentra "
            "localizada la edificación, que se producirían como consecuencia "
            "de la ocurrencia del sismo de diseño.\n\n"
            "Movimientos sísmicos para el umbral de daño — Es una "
            "caracterización de los movimientos del terreno, en el sitio "
            "donde se encuentra localizada la edificación, que se producirían "
            "como consecuencia de la ocurrencia del sismo correspondiente al "
            "umbral de daño.\n\n"
            "Movimiento telúrico — Movimiento de la corteza terrestre. Véase "
            "sismo.\n\n"
            "Muro de carga — Es un muro estructural, continuo hasta la "
            "cimentación, que soporta principalmente cargas verticales.\n\n"
            "Muro de cortante — Véase muro estructural.\n\n"
            "Muro divisorio o partición — Es un muro que no cumple una función "
            "estructural y que se utiliza para dividir espacios.\n\n"
            "Muro estructural — Es un muro, de carga o no, que se diseña para "
            "resistir fuerzas horizontales, de sismo o de viento, paralelas al "
            "plano del muro.\n\n"
            "Muro no estructural — Véase muro divisorio.\n\n"
            "Nivel (medido desde la base) de un piso en la colindancia — Es la "
            "suma de las alturas de piso en la colindancia medidas desde la "
            "base hasta la parte superior del piso bajo estudio.\n\n"
            "Número de pisos aéreos de la edificación — Para efectos de la "
            "aplicación de la reglamentación de separación entre "
            "edificaciones de A.6.5.2, el máximo número de pisos aéreos de "
            "una edificación corresponde al número de losas de entrepiso "
            "aéreas, contando dentro de ellas la cubierta como una losa de "
            "entrepiso, y sin contar los sótanos. Una losa de entrepiso aérea "
            "es aquella que no esta en contacto con el terreno en ningún "
            "punto. Cuando un piso tenga más de 6 m de altura, se contará "
            "como dos pisos para efectos de calcular el número de pisos "
            "aéreos de la edificación.\n\n"
            "Número de pisos aéreos en la colindancia — Corresponde al número "
            "de pisos aéreos de la edificación, que se extienden hasta el "
            "paramento del lote de terreno en la zona de colindancia bajo "
            "estudio. Cuando un piso en la colindancia tenga más de 6 m de "
            "altura, se contará como dos pisos para efectos de calcular el "
            "número de pisos aéreos de la edificación en la colindancia."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_perfil_suelo_a_portico_no_arriostrado",
        "seccion": "A.13.1 — Definiciones (Perfil de suelo a Pórtico no arriostrado)",
        "titulo": "Título A, A.13.1: glosario, perfil de suelo, período de vibración/fundamental, peso, piso (flexible/débil), plastificación progresiva push-over, tipos de pórtico (arriostrado, cercha, con diagonales concéntricas/excéntricas, restringido a pandeo, espacial, losa-columna, no arriostrado).",
        "texto": (
            "Perfil de suelo — Son los diferentes estratos de suelo existentes "
            "debajo del sitio de la edificación.\n\n"
            "Período de vibración, T — Es el tiempo que transcurre dentro de un "
            "movimiento armónico ondulatorio, o vibratorio, para que éste se "
            "repita.\n\n"
            "Período de vibración fundamental — Es el mayor período de "
            "vibración de la estructura en la dirección horizontal de "
            "interés.\n\n"
            "Peso — Efecto gravitacional sobre la masa. Se obtiene de "
            "multiplicar la masa en kg, por la aceleración debida a la "
            "gravedad, g (g = 9.8 m/s²). Se expresa en newtons, N (1 N = 1 kg "
            "· 1 m/s²).\n\n"
            "Piso — Es el espacio comprendido entre dos niveles de una "
            "edificación. Piso x es el que está debajo del nivel x.\n\n"
            "Piso flexible — Es aquel en el cual la rigidez ante fuerzas "
            "horizontales, del sistema de resistencia sísmica, es menor que "
            "el 70% de la rigidez ante fuerzas horizontales, del sistema de "
            "resistencia sísmica, del piso inmediatamente superior.\n\n"
            "Piso débil — Es aquel en el cual la resistencia ante fuerzas "
            "horizontales, del sistema de resistencia sísmica, del piso es "
            "menor que el 70% de la resistencia ante fuerzas horizontales, "
            "del sistema de resistencia sísmica, del piso inmediatamente "
            "superior.\n\n"
            "Plastificación progresiva, método de — Método de análisis no "
            "lineal estático conocido en inglés con el nombre de \"push-over\" "
            "(Véase Apéndice A-3).\n\n"
            "Pórtico — Es un conjunto de vigas, columnas y, en algunos casos, "
            "diagonales, todos ellos interconectados entre si por medio de "
            "conexiones o nudos que pueden ser, o no, capaces de transmitir "
            "momentos flectores de un elemento a otro. Dependiendo de sus "
            "características tiene las siguientes denominaciones:\n\n"
            "Pórtico arriostrado — Véase la definición de pórtico con "
            "diagonales.\n\n"
            "Pórtico-cercha de acero resistente a momentos — Pórtico en el que "
            "las vigas son cerchas cuyo tramo central, denominado segmento "
            "especial, se diseña para que actúe como elemento disipador de "
            "energía, de modo que todos los elementos diferentes al segmento "
            "especial permanezcan en el rango elástico.\n\n"
            "Pórtico con diagonales — Pórtico compuesto por vigas, columnas y "
            "diagonales excéntricas, o concéntricas, que se utiliza "
            "primordialmente para resistir fuerzas horizontales. Sus "
            "elementos trabajan principalmente deformándose axialmente, como "
            "en una cercha. Sus nudos pueden, o no, ser capaces de transmitir "
            "momentos flectores, dependiendo del material estructural que se "
            "emplee.\n\n"
            "Pórtico con diagonales concéntricas — Es un pórtico con "
            "diagonales en el cual éstas llegan a los nudos conformados por "
            "las conexiones entre vigas y columnas.\n\n"
            "Pórtico con diagonales excéntricas — Es un pórtico, de acero "
            "estructural, con diagonales que cumple los requisitos "
            "presentados en el Capítulo F.3.\n\n"
            "Pórtico de acero con diagonales restringidas a pandeo — Es un "
            "pórtico con diagonales cuyo pandeo se restringe mediante el "
            "empleo de camisas rellenas de concreto.\n\n"
            "Pórtico espacial — Es un sistema estructural tridimensional, que "
            "no tiene muros de carga, compuesto por elementos interconectados "
            "de tal manera que el conjunto actúe como una unidad, con o sin "
            "la ayuda de diafragmas horizontales o sistemas de "
            "arriostramiento horizontal. (Véase pórtico plano).\n\n"
            "Pórtico losa-columna — Es un sistema estructural tridimensional "
            "aporticado en el cual las losas cumplen la función de las vigas. "
            "Este sistema tiene numerosas restricciones impuestas por el "
            "Reglamento en su uso. Véase reticular celulado.\n\n"
            "Pórtico no arriostrado — Es un pórtico resistente a momentos que "
            "soporta las fuerzas horizontales por medio de momentos flectores "
            "en sus elementos, y que no tiene diagonales ni muros "
            "estructurales."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_portico_no_resistente_a_riesgo_sismico",
        "seccion": "A.13.1 — Definiciones (Pórtico no resistente a momentos a Riesgo sísmico)",
        "titulo": "Título A, A.13.1: glosario, pórtico no resistente a momentos, pórtico plano, pórticos resistentes a momentos (sin capacidad, DES, DMI, DMO), probabilidad, propietario, resistencia, reticular celulado, revisor de los diseños, riesgo sísmico.",
        "texto": (
            "Pórtico no resistente a momentos — Es un pórtico cuyas conexiones "
            "no son resistentes a momentos y que por lo tanto es inestable "
            "ante una solicitación de fuerzas horizontales, a menos que la "
            "responsabilidad de la resistencia ante estas fuerzas sea "
            "atendida por diagonales dentro del mismo pórtico o por "
            "conjuntos de elemento estructurales, tales como muros "
            "estructurales o pórticos con diagonales.\n\n"
            "Pórtico para carga verticales — Es un pórtico espacial diseñado "
            "para resistir únicamente cargas verticales.\n\n"
            "Pórtico plano — Es un pórtico en el cual todos sus elementos "
            "están contenidos dentro de un plano vertical. Este tipo de "
            "pórticos no puede utilizarse a menos que existan elementos "
            "estructurales que restrinjan los desplazamientos en la "
            "dirección perpendicular al plano del pórtico, tales como otros "
            "pórticos o muros estructurales y que exista un diafragma que "
            "amarre horizontalmente el conjunto. (Véase A.3.1.5) Los "
            "enlaces entre pórticos planos a través de la vigueteria del "
            "sistema de entrepiso no se consideran adecuados para efectos "
            "de restringir los desplazamientos en la dirección perpendicular "
            "al plano de pórtico, caso en el cual deben disponerse vigas "
            "paralelas a la vigueteria que enlacen las columnas y conformen "
            "un pórtico espacial.\n\n"
            "Pórtico resistente a momentos — Es un pórtico espacial en el "
            "cual sus miembros y nudos son capaces de resistir las fuerzas, "
            "principalmente, por flexión.\n\n"
            "Pórtico resistente a momentos, sin capacidad de disipación de "
            "energía — Es un pórtico de concreto reforzado que no cumple con "
            "los requisitos especiales de detallado del refuerzo para "
            "lograr un comportamiento dúctil, o que no está dispuesto "
            "espacialmente y no tiene resistencia ante fuerzas horizontales "
            "en la dirección perpendicular a su propio plano.\n\n"
            "Pórtico resistente a momentos con capacidad especial de "
            "disipación de energía (DES) — Es un pórtico espacial diseñado "
            "de acuerdo con las disposiciones correspondientes del Capítulo "
            "C.21 cuando es de concreto reforzado o del Capítulo F.3 cuando "
            "es de acero estructural.\n\n"
            "Pórtico resistente a momentos con capacidad mínima de "
            "disipación de energía (DMI) — Es un pórtico espacial diseñado "
            "de acuerdo con las disposiciones correspondientes del Capítulo "
            "C.21 cuando es de concreto reforzado o los Capítulos F.1 y F.2 "
            "cuando es de acero estructural.\n\n"
            "Pórtico resistente a momentos con capacidad moderada de "
            "disipación de energía (DMO) — Es un pórtico espacial, diseñado "
            "de acuerdo con las disposiciones correspondientes del Capítulo "
            "C.21 cuando es de concreto reforzado, o del Capítulo F.3 cuando "
            "es de acero estructural.\n\n"
            "Probabilidad — Es el cociente del número de casos que realmente "
            "ocurren, dividido por el número total de casos posibles.\n\n"
            "Propietario — Para efectos de este Reglamento, es la persona, "
            "natural o jurídica, titular de derechos reales principales, "
            "poseedor, propietario del derecho de dominio a título de "
            "fiducia y los fideicomitentes de las mismas fiducias, a nombre "
            "de la cual se expide la licencia de construcción.\n\n"
            "Resistencia — Es la capacidad útil de una estructura, o de sus "
            "miembros, para resistir cargas, dentro de los límites de "
            "deformación establecidos en este Reglamento.\n\n"
            "Reticular celulado — Es un tipo de pórtico losa-columna, en el "
            "cual la losa trabaja en dos direcciones y es aligerada en las "
            "zonas lejanas de las columnas y maciza, o con capiteles, en "
            "las zonas aledañas a las columnas. Este sistema tiene numerosas "
            "restricciones impuestas por el Reglamento en su uso.\n\n"
            "Revisor de los diseños — Es el ingeniero civil, diferente del "
            "diseñador e independiente laboralmente de él, que tiene la "
            "responsabilidad de revisar los diseños estructurales y "
            "estudios geotécnicos, o el arquitecto, ingeniero civil o "
            "mecánico, que revisa los diseños de elementos no "
            "estructurales; dentro del trámite de expedición de una "
            "licencia de construcción, para constatar que la edificación "
            "propuesta cumple con los requisitos exigidos por la Ley 400 de "
            "1997 y el presente Reglamento.\n\n"
            "Riesgo sísmico — Corresponde a la determinación de las "
            "consecuencias económicas y sociales, expresada en términos "
            "monetarios, o de víctimas, respectivamente, para el sitio de "
            "interés en función de su probabilidad de excedencia para un "
            "tiempo de exposición dado."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_rigidez_piso_a_sistema_arriostramiento",
        "seccion": "A.13.1 — Definiciones (Rigidez de piso a Sistema de arriostramiento horizontal)",
        "titulo": "Título A, A.13.1: glosario, rigidez de piso, riostra (del diafragma), sello seco registrado, separación sísmica en la colindancia, tipos de sismo (característico, de diseño, de seguridad limitada, del umbral de daño), sistemas estructurales (combinado, de muros de carga, de pórtico, dual, de arriostramiento horizontal).",
        "texto": (
            "Rigidez de piso — Para un piso x, es el cociente entre el "
            "cortante de piso, Vx, y la deriva que éste cortante produce en "
            "el piso.\n\n"
            "Riostra — Véase diagonal.\n\n"
            "Riostra del diafragma (riostra transmisora, amarre, elemento "
            "colector) — Es el elemento de un diafragma, paralelo a la "
            "fuerza aplicada, que recoge y transmite el cortante del "
            "diafragma a los elementos resistentes verticales o el que "
            "distribuye las fuerzas dentro del diafragma. Estos miembros "
            "pueden estar sometidos a efectos axiales de tensión o de "
            "compresión. Véase sistemas de arriostramiento horizontal.\n\n"
            "Sello seco registrado — Marca realzada que queda colocada sobre "
            "un plano de construcción y que reemplaza la firma del "
            "diseñador responsable de los diseños expresados en él. La "
            "marca que produce debe contener el nombre del profesional, su "
            "profesión (ingeniero civil, arquitecto, etc.) y el número de "
            "la matricula profesional.\n\n"
            "Separación sísmica en la colindancia — Es la distancia "
            "horizontal en dirección perpendicular al plano vertical "
            "levantado sobre un plano de construcción y que la lindero "
            "entre los dos lotes de terreno, medida desde la losa de "
            "entrepiso de la edificación hasta este plano.\n\n"
            "Sismo, temblor o terremoto — Vibraciones de la corteza "
            "terrestre inducidas por el paso de ondas sísmicas provenientes "
            "de un lugar o zona donde han ocurrido movimientos súbitos de "
            "la corteza terrestre.\n\n"
            "Sismo característico — Es un sismo definido para una falla "
            "activa que tiene una magnitud igual al mejor estimativo que "
            "pueda hacerse sobre la máxima magnitud que pueda ocurrir en la "
            "falla, pero no menor que la mayor magnitud que haya ocurrido "
            "históricamente en la falla.\n\n"
            "Sismo de diseño — Es la caracterización de los movimientos "
            "sísmicos mínimos que deben utilizarse en la realización del "
            "diseño sismo resistente. Para efectos del presente Reglamento, "
            "es un sismo cuyos efectos en el lugar de interés tienen una "
            "probabilidad de sólo diez por ciento de ser excedidos en un "
            "lapso de cincuenta años, lo cual conduce a un período promedio "
            "de retorno de 475 años. El diseño sismo resistente tiene "
            "dentro de sus objetivos la protección de la vida ante la "
            "ocurrencia del sismo de diseño.\n\n"
            "Sismo de seguridad limitada — Es la caracterización de los "
            "movimientos sísmicos que pueden utilizarse alternativamente en "
            "la evaluación e intervención de ciertas estructuras "
            "existentes. Para efectos del presente Reglamento, es un sismo "
            "cuyos efectos en el lugar de interés tienen una probabilidad "
            "del veinte por ciento de ser excedidos en un lapso de "
            "cincuenta años, lo cual corresponde a un período promedio de "
            "retorno de 225 años. Su uso está sometido a las limitaciones "
            "dadas en A.10.3.\n\n"
            "Sismo del umbral de daño — Es un sismo cuyos efectos en el "
            "lugar de interés tienen una probabilidad del ochenta por "
            "ciento de ser excedidos en un lapso de cincuenta años, lo cual "
            "conduce a un período promedio de retorno de 31 años. "
            "Corresponde a un sismo de intensidad relativamente baja, ante "
            "cuya ocurrencia no deben producirse daños a los elementos "
            "estructurales y no estructurales, que en caso de que ocurran, "
            "éstos deben ser reparables y no deben interferir con el "
            "funcionamiento de la edificación.\n\n"
            "Sistema combinado — Es un sistema estructural en el cual las "
            "cargas verticales son resistidas por un pórtico, resistente a "
            "momentos o no, esencialmente completo, y las fuerzas "
            "horizontales son resistidas por muros estructurales o pórticos "
            "con diagonales. (Véase A.3.2.1.2).\n\n"
            "Sistema de muros de carga — Es un sistema estructural que no "
            "dispone de un pórtico esencialmente completo y en el cual las "
            "cargas verticales son llevadas hasta la cimentación por los "
            "muros de carga y las fuerzas horizontales son resistidas por "
            "muros estructurales o pórticos con diagonales. (Véase "
            "A.3.2.1.1).\n\n"
            "Sistema de pórtico — Es un sistema estructural compuesto por un "
            "pórtico espacial, resistente a momentos, esencialmente "
            "completo, no arriostrado, que resiste todas las cargas "
            "verticales y las fuerzas horizontales. (Véase A.3.2.1.3).\n\n"
            "Sistema dual — Es el sistema estructural resultante de la "
            "combinación de un pórtico espacial resistente a momentos (de "
            "capacidad moderada o alta de disipación de energía) con muros "
            "estructurales o pórticos con diagonales, diseñado de acuerdo "
            "con A.3.2.1.4.\n\n"
            "Sistema de arriostramiento horizontal — Es un sistema de "
            "cercha, o armadura, horizontal que cumple las mismas funciones "
            "de un diafragma."
        ),
    },
    {
        "id": "NSR10-A-A_13_1_def_sistema_resistencia_a_zona_amenaza",
        "seccion": "A.13.1 — Definiciones (Sistema de resistencia sísmica a Zona de amenaza sísmica)",
        "titulo": "Título A, A.13.1: cierre del glosario — sistema de resistencia sísmica, Sistema Internacional de Medidas SI (unidades básicas/derivadas, prefijos exa a atto, reglas a-k de sintaxis), solicitaciones, supervisión técnica/supervisor técnico, umbral de daño, velocidad de la onda de cortante, vulnerabilidad, zona de amenaza sísmica.",
        "texto": (
            "Sistema de resistencia sísmica — Es aquella parte de la "
            "estructura que según el diseño aporta la resistencia requerida "
            "para soportar los movimientos sísmicos de diseño.\n\n"
            "Sistema Internacional de Medidas (SI) — El sistema SI se "
            "estableció en la Decimoprimera Conferencia Mundial de Pesos y "
            "Medidas, que tuvo lugar en Sevres, Francia, en 1960. Por medio "
            "del Decreto 1731 de 18 de Septiembre de 1967, el único sistema "
            "de medidas permitido en el país es el Sistema Internacional de "
            "Medidas SI. El sistema está basado en siete unidades básicas: "
            "que son para longitud el metro (m), para masa el kilogramo "
            "(kg), para tiempo el segundo (s), para corriente eléctrica el "
            "amperio (A), para temperatura el kelvin (K), para intensidad "
            "luminosa el candela (cd) y para cantidad de substancia el mol "
            "(mol). Para efectos del presente Reglamento se utilizan las "
            "siguientes unidades:\n"
            "Unidades básicas — para distancia el metro (m), para masa el "
            "kilogramo (kg), y para tiempo el segundo (s).\n"
            "Unidades suplementarias — para ángulo plano el radian (rad)\n"
            "Unidades derivadas — para frecuencia el hertz (Hz) [1 Hz = 1 "
            "s⁻¹], para fuerza el newton (N) [1 N = 1 kg · m/s²], para "
            "esfuerzo, o fuerza por unidad de área, el pascal (Pa) [1 Pa = "
            "1 N/m²], y para energía o trabajo el joule (J) [1 J = N · m]\n\n"
            "El sistema SI utiliza los siguientes prefijos:\n"
            "exa (E) = 10^18 = 1 000 000 000 000 000 000.\n"
            "peta (P) = 10^15 = 1 000 000 000 000 000.\n"
            "tera (T) = 10^12 = 1 000 000 000 000.\n"
            "giga (G) = 10^9 = 1 000 000 000.\n"
            "mega (M) = 10^6 = 1 000 000.\n"
            "kilo (k) = 10^3 = 1 000.\n"
            "mili (m) = 10^-3 = 0.001\n"
            "micro (μ) = 10^-6 = 0.000 001\n"
            "nano (n) = 10^-9 = 0.000 000 001\n"
            "pico (p) = 10^-12 = 0.000 000 000 001\n"
            "femto (f) = 10^-15 = 0.000 000 000 000 001\n"
            "atto (a) = 10^-18 = 0.000 000 000 000 000 001\n\n"
            "Con el fin de evitar confusión en el uso del sistema SI, "
            "existen las siguientes reglas aceptadas internacionalmente "
            "respecto a la sintaxis que debe emplearse:\n\n"
            "(a) Nunca se intercambian minúsculas y mayúsculas: mm y no MM, "
            "o kg y no KG.\n"
            "(b) Los símbolos no se alteran en el plural: kg, y no kgs.\n"
            "(c) No se deja espacio entre el prefijo y el símbolo: MPa y no "
            "M Pa.\n"
            "(d) No se agrega punto al final del símbolo, a menos que sea "
            "el punto final de una oración.\n"
            "(e) Los símbolos no son abreviaturas, por lo tanto: Pa y no "
            "Pasc, m y no mts.\n"
            "(f) En los productos de símbolos se utiliza un punto "
            "levantado: kN · m.\n"
            "(g) En los cocientes se utiliza un solo símbolo de división, o "
            "pueden utilizarse potencias negativas: kg/(m · s), o "
            "kg · m⁻¹ · s⁻¹, pero no kg/m/s.\n"
            "(h) Puede utilizarse punto, o coma, para indicar los "
            "decimales, dependiendo de la costumbre local. Esto significa "
            "que ninguno de los dos se debe utilizar para separar grupos de "
            "dígitos, para esto se utiliza un blanco. Ejemplo: g = 9.806 "
            "650 m/s².\n"
            "(i) Para números menores que la unidad, nunca se omite el "
            "cero inicial: 0.123 y no .123.\n"
            "(j) Debe haber siempre un espacio entre el número y las "
            "unidades: 12.3 m/s, excepto cuando se trata de grados "
            "celsius: 12°C.\n"
            "(k) Las unidades cuyo nombre es el apellido de un científico, "
            "se emplean con mayúscula: N, Pa, etc., pero cuando se refiere "
            "a ellas no se utiliza la mayúscula: pascales, etc.\n\n"
            "Solicitaciones — Son las fuerzas u otras acciones que afectan "
            "la estructura, dentro de las cuales se cuentan: los efectos "
            "gravitacionales sobre su propia masa, o peso propio, las "
            "cargas generadas por los elementos no estructurales, por sus "
            "ocupantes y sus posesiones, los efectos ambientales tales como "
            "el viento o el sismo, los asentamientos diferenciales, y los "
            "cambios dimensionales causados por variaciones en la "
            "temperatura o efectos reológicos de los materiales. En "
            "general corresponden a todo lo que puede afectar la "
            "estructura.\n\n"
            "Supervisión técnica — Es la verificación de que la "
            "construcción de la estructura de la edificación se adelante de "
            "acuerdo con los diseños, planos y especificaciones realizadas "
            "por el diseñador estructural. Así mismo, que los elementos no "
            "estructurales se construyan siguiendo los diseños, planos, y "
            "especificaciones realizadas por el diseñador de elementos no "
            "estructurales, de acuerdo con el grado de desempeño "
            "requerido.\n\n"
            "Supervisor técnico — Es el profesional, ingeniero civil, "
            "arquitecto o constructor en arquitectura e ingeniería, bajo "
            "cuya responsabilidad se realiza la supervisión técnica. El "
            "alcance de la supervisión técnica está definido en el Título I "
            "de este Reglamento. La supervisión técnica puede ser realizada "
            "por el mismo profesional que realiza la interventoría. Véase "
            "interventor.\n\n"
            "Temblor, terremoto — Véase sismo.\n\n"
            "Umbral de daño — Corresponde al nivel de movimiento sísmico a "
            "partir del cual se pueden presentar daños a los elementos "
            "estructurales y no estructurales.\n\n"
            "Velocidad de la onda de cortante — Es la velocidad con que se "
            "desplaza la onda sísmica de cortante dentro de un suelo.\n\n"
            "Vulnerabilidad — Es la cuantificación del potencial de mal "
            "comportamiento de una edificación con respecto a alguna "
            "solicitación.\n\n"
            "Zona de amenaza sísmica (baja, intermedia o alta) — Son "
            "regiones del país donde la amenaza sísmica se considera baja, "
            "intermedia o alta, tal como se define en A.2.3. Los requisitos "
            "de análisis y diseño estructural varían de una zona a otra."
        ),
    },
    {
        "id": "NSR10-A-A_13_2_nomenclatura_ap_a_ed",
        "seccion": "A.13.2 — Nomenclatura (ap a Ed)",
        "titulo": "Título A, A.13.2: tabla de símbolos usados en todo el Título A, primer bloque (ap, ax, Aa, AB, Ad, Ae, As, Av, Awi, Ax, ai, Ct, Cu, Cvx, dc, di, ds, E, Ed).",
        "texto": (
            "A.13.2 — NOMENCLATURA\n\n"
            "La nomenclatura siguiente corresponde a las variables utilizadas "
            "en el Título A de este Reglamento:\n\n"
            "ap = coeficiente de amplificación dinámica del elemento no "
            "estructural. Véase el Capítulo A.9.\n"
            "ax = aceleración horizontal, expresada como un porcentaje de la "
            "aceleración de la gravedad, sobre el elemento estructural que "
            "no hace parte del sistema de resistencia sísmica, o sobre el "
            "elemento no estructural, localizado en el piso x. Véanse los "
            "Capítulos A.8 y A.9.\n"
            "Aa = coeficiente que representa la aceleración horizontal pico "
            "efectiva, para diseño, dado en A.2.2.\n"
            "AB = área de la edificación en su base, en m².\n"
            "Ad = coeficiente que representa la aceleración pico efectiva, "
            "para el umbral de daño, dado en A.12.2.\n"
            "Ae = coeficiente que representa la aceleración pico efectiva "
            "reducida para diseño con seguridad limitada, dado en A.10.3.\n"
            "As = aceleración máxima en la superficie del suelo estimada "
            "como la aceleración espectral correspondiente a un período de "
            "vibración igual a cero, Véanse ecuaciones A.3.6-3, A.8.2-1 o "
            "A.9.4-2.\n"
            "Av = coeficiente de aceleración que representa la velocidad "
            "horizontal pico efectiva, para diseño, dado en A.2.2.\n"
            "Awi = área mínima de cortante de la sección de un muro "
            "estructural i, medida en un plano horizontal, en el primer "
            "nivel de la estructura y en la dirección en estudio, en m². "
            "Véase A.4.2.\n"
            "Ax = coeficiente de amplificación de la torsión accidental en "
            "el nivel x, definido en A.3.6.7.\n"
            "ai = aceleración en el nivel i, Véanse ecuaciones A.3.6-3 y "
            "A.8.2-1.\n"
            "Ct = coeficiente utilizado para calcular el período de la "
            "estructura, definido en A.4.2.2\n"
            "Cu = coeficiente utilizado para calcular el período máximo "
            "permisible la estructura, definido en A.4.2.1\n"
            "Cvx = coeficiente definido en A.4.3.\n"
            "dc = es la suma de los espesores de los k estratos de suelos "
            "cohesivos localizados dentro de los 30 m superiores del "
            "perfil.\n"
            "di = espesor del estrato i, localizado dentro de los 30 m "
            "superiores del perfil\n"
            "ds = es la suma de los espesores de los m estratos de suelos "
            "no cohesivos localizados dentro de los 30 m superiores del "
            "perfil.\n"
            "E = fuerzas sísmicas reducidas de diseño (E = Fs/R), o "
            "(E = Fp/Rp), o fuerzas sísmicas reducidas para revisión de la "
            "estructura existente y diseño de la ampliación (E = Fs/R').\n"
            "Ed = fuerzas sísmicas del umbral de daño. Véase el Capítulo "
            "A.12."
        ),
    },
    {
        "id": "NSR10-A-A_13_2_nomenclatura_fi_a_pi",
        "seccion": "A.13.2 — Nomenclatura (fi a Pi)",
        "titulo": "Título A, A.13.2: tabla de símbolos, segundo bloque (fi, Fa, Fi, Fx, Fp, Fs, Fv, Fxm, g, heq, hi, hn, hpi, hwi, H, I, IP, j, k, ℓwi, mi, mx, M, Mp, M̄j, M̄m, nw, N, Nef, Nex, Ni, p, Pi).",
        "texto": (
            "fi = fuerza sísmica horizontal en el nivel i para ser utilizada "
            "en la ecuación A.4.2-1.\n"
            "Fa = coeficiente de amplificación que afecta la aceleración en "
            "la zona de períodos cortos, debida a los efectos de sitio, "
            "adimensional.\n"
            "Fi = parte del cortante sísmico en la base que se genera en el "
            "nivel i, véase A.3.6.6.\n"
            "Fi, Fx = fuerzas sísmicas horizontales en los niveles i o x "
            "respectivamente. Véase A.4.3.\n"
            "Fp = fuerza horizontal sobre un elemento estructural que no "
            "hace parte del sistema de resistencia sísmica, o elemento no "
            "estructural, componente o equipo de una edificación, aplicada "
            "en su centro de masa. Véanse los Capítulos A.8 y A.9\n"
            "Fs = fuerzas sísmicas, véase A.3.1.1, o fuerzas sísmicas "
            "equivalentes.\n"
            "Fv = coeficiente de amplificación que afecta la aceleración en "
            "la zona de períodos intermedios, debida a los efectos de "
            "sitio, adimensional, dado en A.2.4.5.\n"
            "Fxm = parte del cortante sísmico modal Vm que se genera en el "
            "nivel x, de acuerdo con A.5.4.\n"
            "g = aceleración debida a la gravedad (g = 9.8 m/s²).\n"
            "heq = altura equivalente del sistema de un grado de libertad "
            "que simula la edificación, véase A.3.6.8.2, A.8.2.1.1 y "
            "A.9.4.2.1.\n"
            "hi = altura en metros, medida desde la base, del nivel i, "
            "véase A.3.6.8.2, A.8.2.1.1 y A.9.4.2.1.\n"
            "hi, hx = altura en metros, medida desde la base, del nivel i o "
            "x. Véase A.4.3.2.\n"
            "hn = altura en metros, medida desde la base, del piso más alto "
            "del edificio, véase A.3.6.8.2, A.4.2.2, A.8.2.1.1 y A.9.4.2.1.\n"
            "hpi = altura del piso i, medida desde la superficie del "
            "diafragma del piso i hasta la superficie del diafragma del "
            "piso inmediatamente inferior, i-1. Véanse los Capítulos A.4, "
            "A.6 y A.12.\n"
            "hwi = altura del muro i medida desde la base, en m.\n"
            "H = espesor total en m de los estratos de suelos cohesivos.\n"
            "I = coeficiente de importancia dado en A.2.5.2.\n"
            "IP = índice de plasticidad, el cual se obtiene cumpliendo la "
            "norma ASTM D 4318.\n"
            "j = índice de una de las direcciones ortogonales principales "
            "en planta, puede ser x o y. Véase el Capítulo A.6.\n"
            "k = exponente relacionado con el período fundamental de la "
            "edificación dado en A.4.3.2.\n"
            "ℓwi = longitud medida horizontalmente, en metros, de un muro "
            "estructural i en el primer nivel de la estructura y en la "
            "dirección en estudio. Véase A.4.2.\n"
            "mi = parte de M que está colocada en el nivel i, en kg. Véase "
            "A.4.3.2.\n"
            "mi, mx = parte de M que está colocada en el nivel i o x "
            "respectivamente. Véanse los Capítulos A.3 y A.4.\n"
            "M = masa total de la edificación — M debe ser igual a la masa "
            "total de la estructura más la masa de aquellos elementos "
            "tales como muros divisorios y particiones, equipos "
            "permanentes, tanques y sus contenidos, etc. En depósitos o "
            "bodegas debe incluirse además un 25 por ciento de la masa "
            "correspondiente a los elementos que causan la carga viva del "
            "piso. Capítulos A.4 y A.5 (en kg).\n"
            "Mp = masa de un elemento o componente, en kg. Véanse los "
            "Capítulos A.3, A.8, y A.9.\n"
            "M̄j = masa actuante total de la edificación en la dirección j. "
            "Ecuación A.5.4-1.\n"
            "M̄m = masa efectiva modal del modo m, determinada de acuerdo "
            "con la ecuación A.5.4-2.\n"
            "nw = número de muros de la edificación efectivos para resistir "
            "las fuerzas sísmicas horizontales en la dirección bajo "
            "estudio.\n"
            "N = número de pisos de la edificación.\n"
            "Nef = resistencia efectiva. Véase el Capítulo A.10.\n"
            "Nex = resistencia existente. Véase el Capítulo A.10.\n"
            "Ni = número de golpes por pié obtenido en el ensayo de "
            "penetración estándar, realizado in situ de acuerdo con la "
            "norma ASTM D 1586, sin hacerle corrección por energía N60. "
            "El valor de Ni usado para obtener el valor medio, no debe "
            "exceder 100.\n"
            "p = número total de modos utilizado en el análisis modal de la "
            "estructura. Véase el Capítulo A.5.\n"
            "Pi = suma de la carga vertical total, incluyendo muerta y "
            "viva, que existe en el piso i, y todos los pisos localizados "
            "por encima. Para el cálculo de los efectos P-Delta de "
            "diseño, no hay necesidad que los coeficientes de carga de "
            "sean mayores que la unidad. Véase el Capítulo A.6."
        ),
    },
    {
        "id": "NSR10-A-A_13_2_nomenclatura_qi_a_vsi",
        "seccion": "A.13.2 — Nomenclatura (Qi a vsi)",
        "titulo": "Título A, A.13.2: tabla de símbolos, tercer bloque (Qi, rj, R, R', R0, RC, Rp, sui, S, S̄, Sa, Sad, Sam, Sd, Sv, T, T0, Ta, TC, TCd, TL, TLd, Tm, Ts, vsi).",
        "texto": (
            "Qi = índice de estabilidad del piso i utilizado en la "
            "evaluación de los efectos P-Delta. Véase A.6.2.3.\n"
            "rj = proyección, sobre la dirección perpendicular en planta a "
            "la dirección en estudio, j, de la distancia entre el centro "
            "de masa del piso y el punto de interés. Véase el Capítulo "
            "A.6.\n"
            "R = coeficiente de capacidad de disipación de energía para ser "
            "empleado en el diseño, corresponde al coeficiente de "
            "disipación de energía básico R0, multiplicado por los "
            "coeficientes de reducción de capacidad de disipación de "
            "energía por irregularidades en altura, en planta, y por "
            "ausencia de redundancia en el sistema estructural de "
            "resistencia sísmica (R = φa·φp·φr·R0). Véase el Capítulo "
            "A.3.\n"
            "R' = coeficiente de capacidad de disipación de energía que se "
            "le asigna a la edificación existente de acuerdo con lo "
            "prescrito en el Capítulo A.10.\n"
            "R0 = coeficiente de capacidad de disipación de energía básico "
            "definido para cada sistema estructural y cada grado de "
            "capacidad de disipación de energía del material estructural. "
            "Véase el Capítulo A.3.\n"
            "RC = coeficiente de capacidad de disipación de energía "
            "definido para la zona de períodos cortos menores de TC en "
            "función del valor de R, cuando se exige así en los estudios "
            "de microzonificación. Definido en la ecuación A.2.9-1\n"
            "Rp = coeficiente de capacidad de disipación de energía del "
            "elemento no estructural y sus sistema de soporte. Se da en "
            "las tablas A.9.5-1 y A.9.6-1.\n"
            "sui = es la resistencia al corte no drenado en kPa (kgf/cm²) "
            "del estrato i, la cual no debe exceder 250 kPa (2.5 kgf/cm²) "
            "para realizar el promedio ponderado. Esta resistencia se "
            "mide cumpliendo la norma NTC 1527 (ASTM D 2166) o la norma "
            "NTC 2041 (ASTM D 2850).\n"
            "S = coeficiente de sitio considerado en A.12.3\n"
            "S̄ = coeficiente de sitio para ser empleado en el espectro "
            "sísmico del umbral de daño (S̄ = 1.25S).\n"
            "Sa = valor del espectro de aceleraciones de diseño para un "
            "período de vibración dado. Máxima aceleración horizontal de "
            "diseño, expresada como una fracción de la aceleración de la "
            "gravedad, para un sistema de un grado de libertad con un "
            "período de vibración T. Está definido en A.2.6.\n"
            "Sad = valor del espectro sísmico del umbral de daño, para un "
            "período de vibración dado. Máxima aceleración horizontal "
            "para el umbral de daño, expresada como una fracción de la "
            "aceleración de la gravedad, para un sistema de un grado de "
            "libertad con un período de vibración T. Está definido en "
            "A.12.3.\n"
            "Sam = valor del espectro de aceleraciones de diseño para el "
            "período de vibración Tm, correspondiente al modo de "
            "vibración m. Véase el Capítulo A.5.\n"
            "Sd = valor del espectro de desplazamientos de diseño para un "
            "período de vibración dado. Máximo desplazamiento horizontal "
            "de diseño, expresado en m, para un sistema de un grado de "
            "libertad con un período de vibración T. Está definido en "
            "A.2.6.3.\n"
            "Sv = valor del espectro de velocidades de diseño para un "
            "período de vibración dado. Máxima velocidad horizontal de "
            "diseño, expresada en m/s, para un sistema de un grado de "
            "libertad con un período de vibración T. Está definido en "
            "A.2.6.2.\n"
            "T = período fundamental del edificio como se determina en "
            "A.4.2.\n"
            "T0 = período de vibración al cual inicia la zona de "
            "aceleraciones constantes del espectro de diseño, en s.\n"
            "Ta = período de vibración fundamental aproximado, en "
            "segundos, calculado de acuerdo con A.4.2.\n"
            "TC = período de vibración, en segundos, correspondiente a la "
            "transición entre la zona de aceleración constante del "
            "espectro de diseño, para períodos cortos, y la parte "
            "descendente del mismo. Véase A.2.6.\n"
            "TCd = período de vibración, en segundos, correspondiente a la "
            "transición entre la zona de aceleración constante del "
            "espectro sísmico del umbral de daño para períodos cortos y "
            "la parte descendente del mismo. Véase el Capítulo A.12.\n"
            "TL = período de vibración, en segundos, correspondiente al "
            "inicio de la zona de desplazamiento aproximadamente "
            "constante del espectro de diseño, para períodos largos. "
            "(Véase A.2.6).\n"
            "TLd = período de vibración, en segundos, correspondiente al "
            "inicio de la zona de desplazamiento aproximadamente "
            "constante del espectro del umbral de daño, para períodos "
            "largos. (Véase A.12.3.4).\n"
            "Tm = período de vibración correspondiente al modo de "
            "vibración m, en seg. Véase el Capítulo A.5.\n"
            "Ts = período de vibración fundamental, en segundos, del "
            "depósito de suelo subyacente en el sitio. Véase A.2.4.\n"
            "vsi = velocidad media de la onda de cortante del suelo del "
            "estrato i, medida en campo, en m/s."
        ),
    },
    {
        "id": "NSR10-A-A_13_2_nomenclatura_vmj_a_theta_i",
        "seccion": "A.13.2 — Nomenclatura (Vmj a θi, cierre del Capítulo A.13)",
        "titulo": "Título A, A.13.2: tabla de símbolos, cuarto y último bloque (Vmj, Vi/Vx, Vs, Vsd, Vtj, Vx, w, α, δ's, Δ's, φa/φe/φc/φp/φr, Ω0, θi).",
        "texto": (
            "Vmj = cortante sísmico en la base correspondiente al modo m en "
            "la dirección horizontal j. Véase el Capítulo A.5.\n"
            "Vi, Vx = fuerza cortante del piso i o x, respectivamente, en la "
            "dirección en estudio, sin dividir por R. Se determina por "
            "medio de las ecuaciones del numeral A.4.3. Corresponde a la "
            "suma de las fuerzas horizontales sísmicas de diseño que se "
            "aplican al nivel i o x, y todos los niveles localizados por "
            "encima de él.\n"
            "Vs = cortante sísmico de diseño en la base de la estructura, "
            "calculado por el método de la fuerza horizontal equivalente "
            "del Capítulo A.4.\n"
            "Vsd = cortante sísmico en la base, para las fuerzas sísmicas "
            "del umbral de daño. Véase A.12.4.\n"
            "Vtj = cortante sísmico total en la base en la dirección "
            "horizontal j. Véase el Capítulo A.5.\n"
            "Vx = fuerza cortante sísmica en el nivel x. Véase A.3.6.6.\n"
            "w = contenido de agua en porcentaje, el cual se determina por "
            "medio de la norma NTC 1495 (ASTM D 2166).\n"
            "α = exponente para ser utilizado en el cálculo del período "
            "aproximado Ta. Véase A.4.2.2.\n"
            "δicm,j = desplazamiento horizontal, del centro de masa del "
            "piso i, en la dirección j. Véase el Capítulo A.6.\n"
            "δi = desplazamiento horizontal del nivel i con respecto a la "
            "base de la estructura, debido a las fuerzas horizontales fi, "
            "para ser utilizado en la ecuación A.4.2-1, o desplazamiento "
            "horizontal del centro de masas del nivel i de la estructura, "
            "en metros, utilizado en el Capítulo A.6.\n"
            "δmax = desplazamiento horizontal máximo en el nivel x. Véase "
            "ecuación A.3.6-2.\n"
            "δipd,j = desplazamiento horizontal adicional, del centro de "
            "masa del piso i, causado por efectos P-Delta, en la "
            "dirección j. Véase el Capítulo A.6.\n"
            "δprom = promedio de los desplazamientos horizontales en puntos "
            "extremos de la estructura en el nivel x. Véase ecuación "
            "A.3.6-2.\n"
            "δit,j = desplazamiento horizontal adicional causado por "
            "efectos de torsión, de cualquier punto del diafragma del "
            "piso i, en la dirección j.\n"
            "δitot,j = desplazamiento total horizontal, de cualquier punto "
            "del diafragma del piso i en la dirección j. Véase el "
            "Capítulo A.6.\n"
            "Δicm,j = deriva del piso i, en la dirección bajo estudio, j, "
            "medida en el centro de masa del piso, como la diferencia "
            "entre el desplazamiento horizontal del piso i menos el del "
            "piso i-1 en la misma dirección j. Véase el Capítulo A.6.\n"
            "Δij = deriva del piso i en la dirección principal en planta "
            "j.\n"
            "Δimax = deriva máxima de diseño para cualquier punto del piso "
            "i. Véase el Capítulo A.6.\n"
            "φa = coeficiente de reducción de la capacidad de disipación "
            "de energía causado por irregularidades en altura de la "
            "edificación. Véase A.3.3.3.\n"
            "φe = coeficiente de reducción de resistencia por estado de "
            "la estructura. Véase A.10.4.3.4.\n"
            "φc = coeficiente de reducción de resistencia por calidad del "
            "diseño y construcción de la estructura. Véase A.10.4.3.4.\n"
            "φijm = amplitud de desplazamiento del nivel i de la "
            "edificación, en la dirección j, cuando está vibrando en el "
            "modo m. Véase el Capítulo A.5.\n"
            "φp = coeficiente de reducción de la capacidad de disipación "
            "de energía causado por irregularidades en planta de la "
            "edificación. Véase A.3.3.3.\n"
            "φr = coeficiente de reducción de la capacidad de disipación "
            "de energía causado por ausencia de redundancia en el sistema "
            "estructural de resistencia sísmica. Véase A.3.3.8.\n"
            "Ω0 = coeficiente de sobreresistencia. Véase A.3.3.9.\n"
            "θi = rotación alrededor de un eje vertical que pasa por el "
            "centro de masa del piso i, causada por los efectos "
            "torsionales, en radianes. Véase el Capítulo A.6."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])

    print("Cargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

    textos = [c["texto"] for c in CHUNKS]
    print(f"Codificando {len(textos)} chunks-padre de A.13...")
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print(f"Subiendo {len(rows)} chunks-padre de A.13 a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()
    print("OK. Ahora correr _resplit_titulo_a_a13_por_limite_tokens.py para re-trocear.")


if __name__ == "__main__":
    main()
