"""
NSR-10 Titulo K, Capitulo K.3 completo (K.3.1 a K.3.18) -- Requisitos para
zonas comunes, en verbatim real.

Hallazgo real (2026-08-27, sesion siguiente al cierre de K.2): al auditar
K.3.4-K.3.6 y K.3.8.5-K.3.8.7 (ya flageados como posible resumen), se
encontro algo mas grande -- los numerales K.3.11 a K.3.18 (requisitos
especificos por grupo de ocupacion: almacenamiento, comercial, fabril,
institucional, lugares de reunion, mixto, alta peligrosidad, residencial)
NO TENIAN NINGUN CHUNK, 0% cubiertos -- no eran un resumen, eran un hueco
completo nunca detectado porque el capitulo K.3 nunca se audito completo
contra el catalogo maestro/PDF real. El usuario eligio cerrar el capitulo
completo en vez de solo parchar los 2 numerales ya flageados.

Reemplaza TODOS los chunks viejos de K.3 (algunos condensados, otros ya
razonables pero reemplazados igual por consistencia de todo el capitulo)
por 24 chunks reales verbatim, uno por numeral (K.3.8 se divide en sus 7
sub-numerales K.3.8.1-K.3.8.7 por ser el mas extenso).

Fuente: NSR-10-1571-1625.pdf (Drive id 1M_lQD8NRDBHaB6pc_GE1n2l2sW34U88Z),
paginas internas K-13 a K-32 (paginas PDF 5-24), leido visualmente pagina
por pagina (Read con `pages`). Sin formulas matematicas -- solo requisitos
narrativos + tablas de valores (numero de salidas, distancias, anchos,
capacidades por modulo de salida) + 1 figura (K.3.15-1, descrita en texto).

Uso: python _ingest_titulo_k_k3_verbatim.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "NSR-10 Título K — Otros Requisitos Complementarios"

CHUNKS = [
    {
        "id": "NSR10-K-K_3_1_general",
        "seccion": "K.3.1 (General)",
        "titulo": "Alcance, requisitos mínimos y las 12 definiciones del Capítulo K.3.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — REQUISITOS PARA ZONAS COMUNES. K.3.1 — "
            "GENERAL. K.3.1.1 — ALCANCE — Las disposiciones de este Capítulo tienen "
            "por objeto presentar requisitos, especificaciones y parámetros para el "
            "diseño, la construcción, la localización, la protección, la disposición "
            "y el mantenimiento de los elementos requeridos para que las zonas comunes "
            "de las edificaciones puedan proporcionar medios de acceso y egreso "
            "adecuados y medios de evacuación seguros en las edificaciones. K.3.1.2 — "
            "REQUISITOS MÍNIMOS — El uso y tipo de ocupación definidas para efectos de "
            "obtener la licencia de construcción, no puede ser modificado de manera "
            "que en las zonas comunes se reduzca el número de salidas o su capacidad a "
            "valores inferiores a los prescritos en este Capítulo.\n\n"
            "K.3.1.3 — DEFINICIONES: Acceso a la salida — Sección inicial de un medio "
            "de evacuación que conduce a una salida. El acceso a ésta incluye el "
            "salón o espacio en el cual esté localizada la persona, y los pasillos, "
            "rampas, corredores y puertas que deben atravesarse en el recorrido hacia "
            "la salida. Anchura por persona — Ancho mínimo de salida por persona para "
            "el cómodo movimiento de una fila de personas a lo largo de un medio de "
            "evacuación; debe medirse en mm, según la Tabla K.3.3-2. Carga de "
            "ocupación — Número promedio de personas que admite una edificación en un "
            "momento cualquiera. Descarga de salida — Parte de un medio de evacuación "
            "entre la terminación de la salida y una vía pública. Escalera exterior — "
            "La que tiene uno de sus lados, por lo menos, directamente abiertos al "
            "exterior, mediante el recurso visible de un antepecho o baranda. Escalera "
            "interior — Aquella en la que ninguno de sus lados está directamente "
            "abierto al exterior, sino indirectamente, mediante ventanas, puertas u "
            "otros medios. Índice de ocupación — Área neta de piso que se presume, "
            "ocupada por personas para efecto de utilizarse en el cálculo de la carga "
            "de ocupación de cualquier piso o espacio ocupado. Medios de evacuación — "
            "Vías libres y continuas que partiendo desde cualquier punto de una "
            "edificación conducen a un lugar o una vía pública. Cada medio de "
            "evacuación consta de partes separadas y distintas: salida, acceso a "
            "ésta, y descarga de salida. Nivel de calle — Piso o nivel de piso "
            "accesible desde la calle o el exterior de la edificación, provisto de "
            "entrada principal a una altura no mayor de 7 escalones sobre el nivel "
            "del suelo. Rampa — Plano inclinado dispuesto para subir y bajar en un "
            "sentido determinado de circulación. Salida — Parte de un medio de "
            "evacuación, separada de los demás espacios de la edificación por "
            "construcciones o equipos como se especifica en este Capítulo, y que "
            "proporciona una vía de recorrido protegida hasta la descarga de salida. "
            "Puede incluir escalera a prueba de humo, corredores, balcones, "
            "exteriores, rampas y puertas. Vía pública — Calle, callejón u otro "
            "espacio seguro, abierto al exterior para fines de uso público y con un "
            "ancho no menor de 3 m."
        ),
    },
    {
        "id": "NSR10-K-K_3_2_requisitos_generales",
        "seccion": "K.3.2 (Requisitos Generales)",
        "titulo": "Planos/especificaciones, localización/mantenimiento, señalización/iluminación, alarmas, aire acondicionado, discapacitados.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.2 — REQUISITOS GENERALES. K.3.2.1 — "
            "GENERAL — Toda edificación debe poseer en sus zonas comunes, salidas que "
            "por su número, clase, localización y capacidad, sean adecuadas para una "
            "fácil, rápida y segura evacuación de todos los ocupantes en caso de "
            "incendio u otra emergencia, de acuerdo con la clase de ocupación, el "
            "número de ocupantes, los sistemas de extinción de incendios y la altura y "
            "superficie de la edificación. K.3.2.1.1 — Los ascensores, escaleras "
            "mecánicas y caminos móviles no deben ser usados como un componente de un "
            "medio de salida requerido desde ninguna otra parte de la edificación "
            "hasta el exterior.\n\n"
            "K.3.2.2 — PLANOS Y ESPECIFICACIONES. K.3.2.2.1 — Disposición de salidas — "
            "Los planos arquitectónicos que se presenten para la solicitud de licencia "
            "de construcción deben mostrar, en cumplimiento del presente Capítulo del "
            "Reglamento, con suficiente detalle, la localización, construcción, "
            "tamaño y tipo de todas las salidas, además de la disposición de "
            "pasillos, corredores y pasadizos relacionados con las mismas. K.3.2.2.2 "
            "— Número de ocupantes — Los planos arquitectónicos que se presenten para "
            "la solicitud de licencia de construcción de todas las edificaciones "
            "clasificadas dentro de los Grupos Comercial (C), Lugares de reunión (L), "
            "Institucional (I), Fabril e Industrial (F) y Alta Peligrosidad (P), deben "
            "indicar el número de personas previstos para la ocupación de cada piso, "
            "habitación o espacio. El número mínimo de ocupantes acomodables en las "
            "salidas de las edificaciones de los grupos mencionados, debe determinarse "
            "según la carga de ocupación prevista en el numeral K.3.3, número al cual "
            "tendrá que limitarse, entonces, la respectiva carga de ocupación del "
            "edificio.\n\n"
            "K.3.2.3 — LOCALIZACION Y MANTENIMIENTO — Los medios de evacuación deben "
            "localizarse y mantenerse de acuerdo con los siguientes requisitos "
            "mínimos: K.3.2.3.1 — Las salidas deben localizarse y mantenerse en forma "
            "tal que provean fácil y rápida evacuación desde cualquier sitio y en "
            "todo momento en que se encuentre ocupada la edificación. K.3.2.3.2 — No "
            "se permite la instalación de cerraduras que bloqueen la libre evacuación "
            "desde el interior, excepto en las edificaciones del Subgrupo de "
            "Ocupación (I-1), caso en el cual corre a cargo de personal administrativo "
            "operar los mecanismos para asegurar la evacuación efectiva de ocupantes, "
            "en caso de fuego o de cualquier otra emergencia. K.3.2.3.3 — Queda "
            "prohibido obstruir o reducir en cualquier forma la capacidad de "
            "cualquier medio de evacuación como puerta, pasaje, pasadizo, etc., "
            "requerido por las disposiciones de estos Reglamentos. K.3.2.3.4 — En "
            "ningún caso debe permitirse que el acceso a una salida se haga a través "
            "de cocinas, cuartos de almacenamiento, dormitorios, salones de trabajo u "
            "otros espacios que puedan estar bajo llave, y a través de espacios que "
            "ofrezcan alto riesgo tales como subestaciones, calderas y cuartos "
            "técnicos, excepto cuando la salida sirva únicamente a un dormitorio o a "
            "otra habitación que deba permanecer cerrada, o a habitaciones adyacentes "
            "que formen partes de la misma unidad de vivienda y sean Subgrupo de "
            "Ocupación (R-1).\n\n"
            "K.3.2.4 — SEÑALIZACIÓN E ILUMINACIÓN — Los medios de evacuación deben "
            "cumplir con los requisitos siguientes en cuanto a señalización e "
            "iluminación se refiere. K.3.2.4.1 — Toda salida o vía de escape debe ser "
            "claramente visible y estar completamente señalizada de tal manera que "
            "todos los ocupantes mentalmente capaces de la edificación, puedan "
            "encontrar sin problema la dirección de salida y en tal forma que la vía "
            "conduzca, de manera inequívoca a sitio seguro. K.3.2.4.2 — Cualquier "
            "salida o pasadizo que no sea parte de una vía de escape, pero que por su "
            "carácter pueda tomarse como tal, debe estar dispuesta y señalizada de tal "
            "manera que se minimicen los riesgos de confusión y el peligro resultante "
            "para las personas que busquen escapar del fuego o de otra emergencia, "
            "así como para evitar que se llegue a espacios que no conduzcan a una "
            "salida. K.3.2.4.3 — Todos los medios de evacuación deben estar provistos "
            "de iluminación artificial y de emergencia.\n\n"
            "K.3.2.5 — ALARMAS — Toda edificación cuyo tamaño, disposición y ocupación "
            "sean tales que en caso de emergencia no permita dar alerta directa "
            "inmediata, debe estar provista de alarmas audibles y visibles que sirvan "
            "como sistemas de aviso que faciliten la evacuación ordenada de los "
            "ocupantes.\n\n"
            "K.3.2.6 — EDIFICACIONES CON AIRE ACONDICIONADO — Las edificaciones con "
            "instalación central de aire acondicionado deben cumplir los siguientes "
            "requisitos especiales: K.3.2.6.1 — Localización de escaleras — En las "
            "edificaciones carentes en todos los pisos de ventanas que abran al "
            "exterior y que tengan un sistema de ventilación artificial o de aire "
            "acondicionado deben localizarse las escaleras de manera que sean "
            "accesibles al cuerpo de bomberos, en todos los pisos, mediante aberturas "
            "como ventanas o puertas. K.3.2.6.2 — Conductos de descarga — No se "
            "permite que los conductos de descarga, de escape o expulsión, o los "
            "respiraderos de los sistemas de aire acondicionado descarguen hacia las "
            "escaleras o huecos de ascensores. Tampoco es admisible que se utilicen "
            "corredores que sirven de acceso a las salidas como descarga de retorno "
            "de espacios de aire acondicionado, a través de rejillas u otros "
            "dispositivos en puertas o particiones que encierran dichos espacios de "
            "aire acondicionado, a menos que se les equipe con detectores de humo "
            "aprobados para la desconexión automática de los ventiladores de "
            "suministro y descargue y el cierre de las rejillas.\n\n"
            "K.3.2.7 — SISTEMAS DE EVACUACIÓN PARA DISCAPACITADOS — Toda obra se "
            "deberá proyectar y construir de tal forma que facilite el ingreso, "
            "egreso y la evacuación de emergencia de las personas con movilidad "
            "reducida, sea ésta temporal o permanente. Así mismo se debe procurar "
            "evitar toda clase de barrera física en el diseño y ejecución de las vías "
            "en la construcción o restauración de edificios de propiedad pública o "
            "privada. K.3.2.7.1 — Todo ascensor que se proyecte e instale debe tener "
            "capacidad para transportar al menos una persona en silla de ruedas y "
            "debe cumplir con la Norma Técnica NTC 4349, Accesibilidad de las "
            "Personas al Medio Físico. Edificios, Ascensores. K.3.2.7.2 — Cuando el "
            "proyecto se refiera a conjuntos de edificios e instalaciones que "
            "constituyan un complejo arquitectónico, éste se proyectará y construirá "
            "en condiciones que permitan en todo caso, la accesibilidad de las "
            "personas discapacitadas a los diferentes inmuebles e instalaciones "
            "complementarias, en concordancia con las Normas Técnicas NTC 4143 "
            "Accesibilidad de las Personas al Medio Físico. Edificios, Rampas Fijas, "
            "NTC 4145 Accesibilidad de la Personas al Medio Físico. Edificios, "
            "escaleras, y NTC 4140 Accesibilidad de las Personas al Medio Físico. "
            "Edificios, pasillos, corredores. K.3.2.7.3 — Las edificaciones para "
            "hospitales y centros de salud, las edificaciones clasificadas en el "
            "Grupo de Uso II y, en general, toda edificación cuya ocupación implique "
            "el servicio al público, que tengan varios niveles y que no cuenten con "
            "ascensor, deberán estar provistas de rampas de acceso a todos los "
            "espacios a los que el público deba ingresar, con las especificaciones "
            "técnicas y de seguridad especificadas a continuación, en concordancia "
            "con K.3.8.6 y con la Norma Técnica NTC 4143 Accesibilidad de las "
            "Personas al Medio Físico. Edificios, Rampas Fijas. K.3.2.7.4 — Todos los "
            "sitios abiertos al público, de carácter recreacional o cultural, como "
            "teatros y cines, deberán disponer de espacios localizados al comienzo o "
            "al final de cada fila central, para personas en silla de ruedas. Para "
            "efectos se utilizará un área igual a la de una silla de teatro y no se "
            "dispondrá de más de dos espacios en la misma fila. La determinación del "
            "número de espacios de esta clase, será del dos por ciento de la "
            "capacidad total del teatro. Un porcentaje similar se aplicará en los "
            "vestuarios de los centros recreacionales, para las personas en sillas "
            "de ruedas. En todo caso, éstas y las demás instalaciones abiertas al "
            "público, deberán contar por lo menos con un sitio accesible para las "
            "personas en silla de ruedas, en concordancia con la Norma Técnica NTC "
            "4143 Accesibilidad de las Personas al Medio Físico. Edificios, Rampas "
            "Fijas. K.3.2.7.5 — Los pasillos y corredores de todas las edificaciones "
            "deben cumplir las dimensiones mínimas y características funcionales y "
            "constructivas señaladas en la Norma Técnica NTC 4140.\n\n"
            "K.3.2.8 — SEÑALIZACIÓN DE SALIDAS PARA DISCAPACITADOS — Cuando el diseño "
            "de un sistema de salida haya sido ejecutado expresamente para permitir "
            "la salida de discapacitados, deberá proveerse de señalización adecuada "
            "que exprese esta condición."
        ),
    },
    {
        "id": "NSR10-K-K_3_3_capacidad_evacuacion",
        "seccion": "K.3.3 (Capacidad de los Medios de Evacuación)",
        "titulo": "Carga de ocupación, Tabla K.3.3-1 (índice de ocupación) y Tabla K.3.3-2 (índices de ancho de salida por persona).",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.3 — CAPACIDAD DE LOS MEDIOS DE "
            "EVACUACIÓN. K.3.3.1 — CARGA DE OCUPACION — Para determinar la carga de "
            "ocupación debe cumplirse: K.3.3.1.1 — La capacidad de los medios de "
            "evacuación de cualquier piso, gradería u otro espacio ocupado, debe ser "
            "suficiente para la respectiva carga de ocupación. K.3.3.1.2 — La carga "
            "de ocupación debe determinarse por el mayor de los dos valores "
            "siguientes: (a) Número real de ocupantes para los cuales esté diseñado, "
            "según el caso, cada espacio, piso o edificación. (b) El número "
            "resultante de dividir el área del espacio, piso o edificación, por el "
            "índice de ocupación previsto en el numeral K.3.3.2, para los Grupos de "
            "Ocupación especificados, excepto para áreas con asientos fijos, caso en "
            "el cual la carga de ocupación debe ser igual al número de asientos "
            "contenidos. K.3.3.1.3 — La carga de ocupación de cualquier espacio debe "
            "incluir la correspondiente a todos los espacios que descarguen a través "
            "del mismo con objeto de lograr acceso a alguna salida. K.3.3.1.4 — Si "
            "alguna zona de la edificación tiene más de un tipo de ocupación, la "
            "carga de ocupación debe determinarse por el que dé lugar al mayor número "
            "de ocupantes. Las áreas de uso accesorias como pasillos y corredores, al "
            "servicio de las personas que ocupan las áreas principales, deben "
            "diseñarse y construirse con los medios de salida necesarios, "
            "considerando que lleguen a estar completamente ocupadas; pero dichas "
            "áreas no deben utilizarse en el cálculo de la carga total de ocupación "
            "del piso o de la edificación. K.3.3.1.5 — Cuando las salidas sirvan a "
            "varios pisos, en el cálculo de ocupación de cada uno apenas debe "
            "utilizarse la carga correspondiente a él solo; en ningún caso, se ha de "
            "permitir que disminuya la capacidad de las salidas en la dirección del "
            "recorrido hacia el exterior de la edificación.\n\n"
            "K.3.3.2 — FACTOR DE CARGA DE OCUPACION — En la tabla K.3.3-1 se "
            "presentan los valores normales del factor de carga que deben utilizarse "
            "para el cálculo de la carga de ocupación de un piso o espacio ocupado, "
            "según los diferentes Grupos de Ocupación. K.3.3.2.1 — Cuando la carga de "
            "ocupación de cualquier espacio vaya a ser significativamente más baja "
            "que la correspondiente al valor especificado por la tabla K.3.3-1, dicho "
            "valor puede establecerse mediante la aprobación del departamento de "
            "planeación distrital o municipal. K.3.3.2.2 — Cuando la ocupación de una "
            "edificación existente se altere o modifique de manera que haya "
            "necesidad de contar con mayores facilidades para las salidas, la "
            "autoridad competente puede autorizar dicho cambio o alteración, sin "
            "cambiar los medios de evacuación, siempre que la carga de ocupación real "
            "se limite a la determinada de acuerdo con las condiciones existentes y "
            "las disposiciones de este Capítulo. K.3.3.2.3 — Cuando haya baños, "
            "cuartos de aseo y de almacenamiento, espacios de entrada y espacios "
            "similares ocupados al mismo tiempo con otros espacios del mismo piso de "
            "una edificación, su carga de ocupación puede omitirse en los cálculos de "
            "lo que corresponde al piso en el cual aquellos cuartos están "
            "localizados.\n\n"
            "Tabla K.3.3-1 — Índice de ocupación (Nomenclatura — Grupos de Ocupación "
            "— Área neta de piso en m² por ocupante): A ALMACENAMIENTO = 28. C "
            "COMERCIAL: C-1 Servicios = 10; C-2 Bienes y Productos, Piso a Nivel de la "
            "Calle e Inferiores = 3, Otros pisos = 6. E ESPECIAL = según ocupación. F "
            "FABRIL E INDUSTRIAL = 9. I INSTITUCIONAL: I-1 Reclusión = 11, I-2 Salud o "
            "Incapacidad = 7, I-3 Educación (Salones de Clase) = 2, I-4 Seguridad "
            "Pública = 2.8, I-5 Servicio Público = 0.3. L LUGARES DE REUNIÓN: L-1 "
            "Deportivos (sin asientos fijos) = 0.7, L-2 Culturales y teatros (sin "
            "asientos fijos) = 1.3, L-3 Sociales y Recreativos = 0.7, L-4 Religiosos = "
            "0.7, L-5 De transporte (no menos de 1.5 veces la capacidad de todos los "
            "vehículos que puedan descargarse simultáneamente) = 0.3. M MIXTO Y OTROS "
            "= la mayor área exigida para las ocupaciones que conforman la ocupación "
            "mixta de la edificación. P ALTA PELIGROSIDAD = 9. R RESIDENCIAL = 18. T "
            "TEMPORAL Y MISCELANEO = según ocupación.\n\n"
            "K.3.3.3 — CAPACIDAD DE LAS SALIDAS — La capacidad de los medios de "
            "evacuación aprobados debe calcularse con base en los índices de ancho "
            "por persona especificados en la tabla K.3.3-2 y según el Grupo de "
            "Ocupación al cual pertenezca la edificación o espacio correspondiente. "
            "K.3.3.3.1 — Cuando la edificación o espacio considerados estén provistos "
            "de un sistema completo de extinción de incendios, los valores para el "
            "ancho por persona, dados en la tabla K.3.3-2, pueden reducirse en un "
            "50%. K.3.3.3.2 — El ancho del medio de evacuación debe medirse en el "
            "punto más estrecho del elemento de la correspondiente vía. K.3.3.3.3 — "
            "La capacidad requerida de un corredor la carga de ocupación que utiliza "
            "el corredor para acceder a una salida dividida por el número de salidas "
            "requeridas a las que el corredor llega. K.3.3.3.4 — La capacidad de un "
            "corredor no debe ser inferior a la capacidad de la salida a la que el "
            "corredor llega.\n\n"
            "K.3.3.4 — ANCHO MINIMO — El ancho mínimo de cualquier vía de acceso a "
            "las salidas no debe ser menor a lo especificado para usos individuales "
            "en el numeral K.3.3.3, ni puede ser inferior a 900 mm. En todo caso, "
            "debe cumplirse con la Norma Técnica NTC 4145 Accesibilidad de la "
            "Personas al Medio Físico. Edificios, escaleras, y NTC 4140 Accesibilidad "
            "de las Personas al Medio Físico. Edificios, pasillos, corredores. "
            "K.3.3.4.1 — Cuando la vía de acceso a una salida sea única, la "
            "capacidad, en términos de su ancho, debe ser por lo menos igual a la "
            "que exija la salida hacia la cual se proyecta. K.3.3.4.2 — Cuando exista "
            "más de una vía de acceso a la salida, éstas deben tener el ancho "
            "adecuado para acomodar el número de personas que requieran.\n\n"
            "Tabla K.3.3-2 — Índices de ancho de salida por persona (Grupo o "
            "Subgrupo de ocupación — Anchura por persona, mm: Corredores/puertas/"
            "pasajes de salidas — Escaleras): ALMACENAMIENTO (A) = 5 — 8. COMERCIAL "
            "(C) = 5 — 10. ESPECIAL (E) = según ocupación — según ocupación. FABRIL E "
            "INDUSTRIAL (F) = 6 — 10. INSTITUCIONAL (I-1) = 6 — 10. INSTITUCIONAL "
            "(I-2, I-3, I-4 e I-5) = 13 — 15. LUGARES DE REUNIÓN (L) = 5 — 10. MIXTO Y "
            "OTROS (M) = el menor número exigido para las ocupaciones que conforman "
            "la ocupación mixta de la edificación. ALTA PELIGROSIDAD (P) = 10 — 18. "
            "RESIDENCIAL (R) = 5 — 10. TEMPORAL (T) = según la ocupación."
        ),
    },
    {
        "id": "NSR10-K-K_3_4_numero_salidas",
        "seccion": "K.3.4 (Número de Salidas)",
        "titulo": "Regla general de redundancia y Tabla K.3.4-1, número mínimo de salidas por carga de ocupación.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.4 — NUMERO DE SALIDAS. K.3.4.1 — "
            "GENERAL — Las salidas y los medios de evacuación deben diseñarse y "
            "localizarse de manera que la seguridad no dependa únicamente de uno "
            "solo de estos medios, y proveerse de dispositivos de seguridad para "
            "evitar que cualquier medio único de salida sea ineficiente debido a "
            "alguna falla humana o mecánica. K.3.4.1.1 — En toda edificación, o área "
            "de ésta, cuya ocupación, tamaño y disposición sea tal que la seguridad "
            "de sus ocupantes se vea comprometida por el bloqueo de alguno de los "
            "medios de evacuación en caso de incendio u otra emergencia, éstos deben "
            "ubicarse tan alejados entre sí como sea posible y de tal manera que se "
            "minimice la posibilidad de que ambos medios se bloqueen "
            "simultáneamente. K.3.4.2 — NUMERO DE SALIDAS — El número mínimo de "
            "salidas por carga de ocupación está dado en la tabla K.3.4-1.\n\n"
            "Tabla K.3.4-1 — Número mínimo de salidas por carga de ocupación (Carga "
            "de ocupación — Número mínimo de salidas): 0-100 = 1. 101-500 = 2. "
            "501-1000 = 3. 1001 o más = 4."
        ),
    },
    {
        "id": "NSR10-K-K_3_5_accesos_salidas",
        "seccion": "K.3.5 (Accesos a las Salidas)",
        "titulo": "Requisitos generales de acceso a salidas, incluyendo el límite de 6 m de trayecto ciego.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.5 — ACCESOS A LAS SALIDAS. K.3.5.1 — "
            "GENERAL — Los siguientes son los requisitos generales que deben cumplir "
            "los accesos a las salidas. K.3.5.1.1 — El acceso a las salidas incluye "
            "el salón o espacio en el cual esté localizado un ocupante, así como los "
            "pasillos, rampas, corredores y puertas que deben atravesarse en el "
            "recorrido hacia la respectiva salida. Los corredores utilizados como "
            "acceso a una salida, y de carga de ocupación superior a 30, deben "
            "separarse de las otras partes del edificio, por elementos tales como "
            "muros o divisiones, construidos con materiales incombustibles. Las "
            "aberturas en tales elementos, tienen que protegerse con puertas hechas "
            "de materiales de combustión lenta. K.3.5.1.2 — El ancho de los accesos "
            "a las salidas debe determinarse con la carga de ocupación del área que "
            "descarga sus ocupantes hacia estos accesos y con observancia de los "
            "requisitos tal y como lo define K.3.4. K.3.5.1.3 — Cuando se requiera "
            "más de una salida en cada piso, cada una debe localizarse para que "
            "tenga acceso desde cualquier punto de un corredor, y limitarse los "
            "trayectos ciegos en los pasillos a una longitud máxima de 6 m."
        ),
    },
    {
        "id": "NSR10-K-K_3_6_distancia_recorrido",
        "seccion": "K.3.6 (Distancia de Recorrido hasta una Salida)",
        "titulo": "Reglas de medición de la distancia de recorrido y Tabla K.3.6-1, distancias máximas por grupo de ocupación.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.6 — DISTANCIA DE RECORRIDO HASTA "
            "UNA SALIDA. K.3.6.1 — La distancia de recorrido debe medirse sobre el "
            "piso, a lo largo de la línea central en el sentido natural del "
            "recorrido. Cuando el recorrido incluya escaleras, éstas deben medirse "
            "en el plano del borde de las huellas. K.3.6.2 — En el caso de áreas "
            "abiertas, la distancia de recorrido debe medirse desde el punto más "
            "remoto sujeto a ocupación. K.3.6.3 — En el caso de salones individuales "
            "ocupables por no más de 6 personas, la distancia de recorrido debe "
            "medirse desde las puertas de dichos salones, previendo que la distancia "
            "de recorrido desde cualquier punto del salón hasta la puerta del mismo, "
            "no exceda de 15 m. K.3.6.4 — Cuando se permitan escaleras abiertas o "
            "rampas como recorrido a las salidas, tales como las que hay entre "
            "balcones o entrepisos y el piso inferior, la distancia debe incluir el "
            "recorrido sobre la escalera o rampa, más el que va desde el final de la "
            "escalera o rampa, hasta una puerta exterior u otra salida, además de la "
            "distancia para llegar a la escalera o rampa. K.3.6.5 — DISTANCIA — La "
            "distancia máxima de recorrido desde el punto más alejado hasta el "
            "centro de cualquier salida exterior, salida vertical, escalera "
            "interior, corredor de salida o salida horizontal, no debe sobrepasar "
            "los límites especificados en la tabla K.3.6-1.\n\n"
            "Tabla K.3.6-1 — Distancia en metros de recorrido hasta la salida (Grupo "
            "de ocupación — Distancia de recorrido, m: Sin sistema de rociadores — "
            "Con sistema de rociadores): ALMACENAMIENTO (A-1) = 60 — 75. "
            "ALMACENAMIENTO (A-2) = 90 — 120. COMERCIAL (C-1) = 60 — 90. COMERCIAL "
            "(C-2) = 60 — 75. FABRIL E INDUSTRIAL (F-1) = 60 — 75. FABRIL E "
            "INDUSTRIAL (F-2) = 90 — 120. INSTITUCIONAL (I) = 45 — 60. LUGARES DE "
            "REUNION (L) = 60 — 75. ALTA PELIGROSIDAD (P) = No se permite — 22. "
            "RESIDENCIAL (R) = 60 — 75. NOTA: Estas distancias se pueden incrementar "
            "hasta en un 30% si los elementos de evacuación son rectilíneos, carecen "
            "de escaleras intermedias y conducen a zonas exteriores a nivel, de área "
            "adecuada para recibir la descarga de ocupación que determinen los casos "
            "individuales."
        ),
    },
    {
        "id": "NSR10-K-K_3_7_proteccion_evacuacion",
        "seccion": "K.3.7 (Protección de los Medios de Evacuación)",
        "titulo": "Separación de corredores y salidas del resto de la edificación.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.7 — PROTECCIÓN DE LOS MEDIOS DE "
            "EVACUACIÓN. K.3.7.1 — CORREDORES — Los corredores utilizados como "
            "acceso a una salida con carga de ocupación superior a 30, deben "
            "separarse de las demás partes de la edificación por muros, particiones "
            "u otros elementos hechos con materiales no combustibles. K.3.7.2 — "
            "SALIDAS — Cuando una salida requiera protección de las demás partes de "
            "la edificación, el elemento de separación debe construirse de acuerdo "
            "con los requisitos de éste. K.3.7.2.1 — Las salidas deben proporcionar "
            "protección contra el fuego y el humo a lo largo de todo su recorrido, "
            "por medio de separaciones levantadas con materiales no combustibles. "
            "K.3.7.2.2 — Todas las aberturas de las salidas deben protegerse con "
            "marcos y puertas de materiales de combustión lenta o incombustible."
        ),
    },
    {
        "id": "NSR10-K-K_3_8_1_general_medios_salida",
        "seccion": "K.3.8.1 (Medios de Salida — General)",
        "titulo": "Requisitos generales de visibilidad y desembocadura de las salidas.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.8 — MEDIOS DE SALIDA. K.3.8.1 — "
            "GENERAL — Los medios de salida deben cumplir los requisitos generales "
            "siguientes: K.3.8.1.1 — Es preciso que todas las salidas se localicen "
            "de tal manera que sean claramente visibles; su ubicación debe indicarse "
            "claramente y su acceso debe mantenerse sin obstrucciones y libres de "
            "obstáculos durante todo el tiempo. K.3.8.1.2 — Toda salida debe "
            "desembocar directamente a la calle, a un espacio abierto o a un área de "
            "refugio no obstruible por fuego, humo u otra causa, y tener dimensiones "
            "tales que aseguren la evacuación de los ocupantes."
        ),
    },
    {
        "id": "NSR10-K-K_3_8_2_puertas",
        "seccion": "K.3.8.2 (Medios de Salida — Puertas)",
        "titulo": "Dimensiones, cerraduras, secuencia, restricciones, giro, fuerza de apertura y nivel del piso de las puertas de salida.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.8.2 — PUERTAS — Toda puerta, "
            "incluyendo en ella el marco y la cerradura, puede considerarse como "
            "elemento de un medio de evacuación siempre y cuando cumpla con los "
            "requisitos especificados en éste y en el numeral K.3.3. K.3.8.2.1 — "
            "Dimensiones — Cada puerta individual debe tener a lo ancho una luz "
            "mínima efectiva de 800 mm, salvo las destinadas a dormitorios, en que "
            "esa longitud se puede disminuir hasta 700 mm. Cuando la puerta se "
            "subdivida en dos o más aberturas separadas, el ancho mínimo de cada una "
            "de éstas no debe ser menor de 700 mm; las aberturas se calculan "
            "separadamente para determinar el número de módulos de ancho de salida "
            "requeridos. En cuanto a la altura, las puertas no deben tener menos de "
            "2.0 m. Se excluyen las puertas de particiones sanitarias. K.3.8.2.2 — "
            "Cerraduras de puertas — Cada puerta de salida que sirva un área con "
            "carga de ocupación superior a diez o una edificación de Alta "
            "Peligrosidad (P), deben poder abrirse fácilmente en cualquier momento, "
            "desde el lado en el cual va a realizarse la evacuación y sin que se "
            "requiera mayor esfuerzo ni el uso de llaves. K.3.8.2.3 — Secuencia de "
            "puertas — Las puertas en serie deben tener un espaciamiento libre entre "
            "ellas de por lo menos 2.10 m, medido cuando están cerradas. K.3.8.2.4 — "
            "Restricciones — No se permite utilizar como puertas de salida las "
            "simplemente giratorias o plegables. Si por cualquier motivo deben usarse "
            "dichas puertas, éstas deberán permanecer abiertas o retiradas mientras "
            "la edificación esté ocupada. K.3.8.2.5 — Giro de puertas — Las puertas "
            "de salida de espacios o habitaciones de edificaciones de carga de "
            "ocupación superior a 100 personas o clasificadas en Alta Peligrosidad y "
            "de corredores desde habitaciones que requieran más de una puerta, deben "
            "girar en la dirección de evacuación. No se permite utilizar puertas de "
            "vaivén cuando la carga de ocupación del área donde se hallen sea "
            "superior a 100. K.3.8.2.6 — Fuerza de apertura — La fuerza requerida "
            "para abrir completamente una puerta debe ser inferior a 250 N. "
            "K.3.8.2.7 — Nivel del piso — El piso a ambos lados de cualquier puerta "
            "de salida o de corredor, debe tener el mismo nivel a lo largo de una "
            "distancia perpendicular a la abertura de la puerta, por lo menos igual "
            "al ancho de la puerta."
        ),
    },
    {
        "id": "NSR10-K-K_3_8_3_escaleras_interiores",
        "seccion": "K.3.8.3 (Medios de Salida — Escaleras Interiores)",
        "titulo": "Capacidad, ancho mínimo, huella/contrahuella, descansos, pasamanos, altura libre, materiales y escaleras circulares.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.8.3 — ESCALERAS INTERIORES — Toda "
            "escalera interior de dos o más peldaños que sirva como medio de "
            "evacuación, debe cumplir los requisitos de este numeral, salvo cuando "
            "sólo se utilice como medio de acceso a sitios ocupados por equipos que "
            "exijan revisión periódica, o cuando se localice dentro de apartamentos "
            "o residencias individuales. K.3.8.3.1 — Toda escalera que sirva como "
            "medio de evacuación debe tener el carácter de construcción fija "
            "permanente. K.3.8.3.2 — Capacidad — La capacidad de escaleras y "
            "puertas que accedan a escaleras encerradas, debe calcularse de acuerdo "
            "con los numerales K.3.4 y K.3.5. K.3.8.3.3 — Ancho mínimo — Las "
            "escaleras con carga de ocupación superior a 50 personas, deben tener "
            "ancho mínimo de 1.20 m; cuando la carga de ocupación sea inferior a 50, "
            "dicho ancho mínimo puede reducirse a 900 mm. Las escaleras en el "
            "interior de las viviendas deberán tener un ancho mínimo de 90 cm. Las "
            "escaleras de uso público deberán tener un ancho mínimo de 120cm. Si la "
            "separación de los pasamanos a la pared supera 50 mm, el ancho de la "
            "escalera debe incrementarse en igual magnitud. En edificaciones "
            "residenciales unifamiliares sin límite de pisos, o en escaleras "
            "privadas interiores de apartamentos, el ancho mínimo permisible es de "
            "750 mm. K.3.8.3.4 — Huella y contrahuella — La huella y contrahuella de "
            "las escaleras interiores deben cumplir los requisitos de la NTC 4145 "
            "Accesibilidad de las Personas al Medio Físico. Edificios, escaleras, y "
            "NTC 4140 Accesibilidad de las Personas al Medio Físico. Edificios, "
            "pasillos, corredores y demás requisitos de la NTC 4140 que apliquen "
            "así: (a) El ancho mínimo de huella, sin incluir proyecciones, debe ser "
            "de 280 mm y la diferencia entre la huella más ancha y la más angosta, "
            "en un trayecto de escaleras, no debe llegar a los 20 mm. (b) La altura "
            "de la contrahuella no debe ser menor de 100 mm ni mayor de 180 mm y la "
            "diferencia entre la contrahuella más alta y la más baja, en un trayecto "
            "de escaleras, mantenerse por debajo de 20 mm. (c) La altura de la "
            "contrahuella y el ancho de la huella deben dimensionarse en tal forma "
            "que la suma de 2 contrahuellas y una huella, sin incluir proyecciones, "
            "oscile entre 620 mm y 640 mm. (d) Puede permitirse el uso de tramos "
            "curvos entre 2 niveles o descansos, con solo si los peldaños tienen un "
            "mínimo de 240 mm de huella, medidos sobre una línea situada a 1/3 del "
            "borde interior del tramo, y como máximo a 420 mm en el borde exterior. "
            "(e) Las huellas deben tener el borde o arista redondeados, con un radio "
            "de curvatura máximo de 1 cm y de forma que no sobresalga del plano de la "
            "contrahuella. (f) Las contrahuellas no deberán ser caladas. (g) El "
            "ángulo que forma la contrahuella con la huella, debe ser de 90°. (h) "
            "Los pisos deben ser antideslizantes, sin relieves en su especie, con "
            "las puntas diferenciadas visualmente. (i) Los escalones aislados, "
            "deberán presentar textura, color e iluminación que los diferencie del "
            "pavimento general. (j) Las escaleras deben estar debidamente "
            "señalizadas, de acuerdo con la NTC 4144. K.3.8.3.5 — Descansos — Todo "
            "descanso debe tener una dimensión mínima, medida en la dirección del "
            "movimiento, igual al ancho de la escalera, pero tal dimensión no "
            "necesita exceder de 1.20 m. La diferencia de nivel entre dos descansos "
            "o entre un descanso y un nivel de piso, debe ser inferior a 2.40 m en "
            "sitios de reunión y edificaciones institucionales; en todos los demás "
            "casos esta diferencia de nivel debe ser inferior a 3.50 m. K.3.8.3.6 — "
            "Pasamanos — Los pasamanos deben cumplir los requisitos de la NTC 4145 "
            "Accesibilidad de la Personas al Medio Físico. Edificios, escaleras, y "
            "NTC 4140 Accesibilidad de las Personas al Medio Físico. Edificios. "
            "Pasillos. K.3.8.3.7 — Altura libre mínima — Toda escalera debe disponer "
            "de una altura libre mínima de 2 m, medida verticalmente desde un plano "
            "paralelo y tangente a las proyecciones de los peldaños hasta la línea "
            "del cielo raso. K.3.8.3.8 — Materiales de las escaleras — Las huellas "
            "de las escaleras y de los descansos, deben acabarse con material rígido "
            "antideslizante. No se permiten las escaleras de madera como medio de "
            "evacuación en ningún caso. K.3.8.3.9 — Escaleras circulares — Las "
            "escaleras circulares pueden emplearse como elementos de salida cuando "
            "el ancho mínimo de la huella sea de 250 mm y el radio mínimo resulte "
            "mayor que el doble del ancho de la escalera. K.3.8.3.10 — Escaleras de "
            "caracol — Las escaleras de caracol pueden servir como elementos de "
            "acceso a la salida en el interior de apartamentos y cuando conduzcan a "
            "un acceso de un mezanine no mayor de 40 m². El ancho mínimo de la "
            "escalera debe ser de 700 mm y la dimensión mínima de la huella, 190 mm, "
            "medida a una distancia de 300 mm del borde interior de la escalera."
        ),
    },
    {
        "id": "NSR10-K-K_3_8_4_escaleras_exteriores",
        "seccion": "K.3.8.4 (Medios de Salida — Escaleras Exteriores)",
        "titulo": "Condiciones de uso de una escalera exterior como salida y protección contra el fuego.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.8.4 — ESCALERAS EXTERIORES — "
            "Cualquier escalera exterior instalada permanentemente en una "
            "edificación, puede servir como salida cuando cumpla los requisitos "
            "exigidos anteriormente para escaleras interiores y los prescritos en "
            "este numeral. K.3.8.4.1 — Protección contra el fuego — Las escaleras "
            "exteriores utilizadas en edificaciones de 3 o más pisos, deben estar "
            "sólidamente integradas al edificio y su capacidad portante se "
            "determinará según los factores y carga de ocupación que el uso "
            "determine."
        ),
    },
    {
        "id": "NSR10-K-K_3_8_5_escaleras_mecanicas",
        "seccion": "K.3.8.5 (Medios de Salida — Escaleras Mecánicas y Caminos Móviles)",
        "titulo": "Requisitos operativos, equivalencia en módulos de salida y restricción en estaciones de transporte.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.8.5 — ESCALERAS MECANICAS Y CAMINOS "
            "MÓVILES — Las escaleras mecánicas deben cumplir los requisitos "
            "establecidos en K.3.8.5.1 a K.3.8.5.3. K.3.8.5.1 — Las escaleras "
            "mecánicas deben operar sólo en un sentido, tienen que ser de huella "
            "horizontal y estar constituidas por materiales incombustibles, a "
            "excepción de equipos eléctricos, cableado, ruedas de los peldaños, "
            "pasamanos y revestimientos. Los revestimientos de madera en barandas "
            "deben ser de 0.9 mm de espesor, o menos, respaldados con materiales no "
            "combustibles. Adicionalmente deben existir escaleras convencionales "
            "como medio de evacuación alterno a las escaleras mecánicas en todos los "
            "edificios que las posean. K.3.8.5.2 — Para efectos de capacidad, una "
            "escalera mecánica de 800 mm de ancho representa un módulo de salida. "
            "Las escaleras de 1200 mm de ancho proporcionan 2 módulos de salida. "
            "K.3.8.5.3 — En estaciones de transporte que tengan escaleras mecánicas "
            "hacia niveles por debajo del terreno, la anchura de las escaleras "
            "mecánicas no puede ser inferior a un módulo de salida."
        ),
    },
    {
        "id": "NSR10-K-K_3_8_6_rampas",
        "seccion": "K.3.8.6 (Medios de Salida — Rampas)",
        "titulo": "Inclinación, pendientes, ancho, altura libre, restricciones, descansos, acabados, pasamanos, techos y rampas mecánicas.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.8.6 — RAMPAS — Las rampas "
            "utilizadas como medio de evacuación, deben cumplir los requisitos "
            "especificados en el numeral K.3.6 y en la norma NTC 4143 Accesibilidad "
            "de las Personas al Medio Físico. Edificios, Rampas Fijas, además de los "
            "especificados a continuación. K.3.8.6.1 — Inclinación — La inclinación "
            "de la rampa debe ser constante a lo largo de toda su longitud. Los "
            "cambios de inclinación que haya necesidad de hacer en la dirección del "
            "recorrido se practicarán únicamente en los descansos. K.3.8.6.2 — "
            "Pendiente longitudinal — Las rampas usadas como parte de un medio de "
            "salida deben tener una pendiente de recorrido no mayor a una unidad "
            "vertical en 12 unidades horizontales (8%). La pendiente de otras "
            "rampas para peatones no debe ser mayor que una unidad vertical en ocho "
            "unidades horizontales (12.5%). K.3.8.6.3 — Pendiente transversal — La "
            "pendiente medida en forma perpendicular a la dirección de "
            "desplazamiento de una rampa no debe ser mayor a una unidad vertical en "
            "48 unidades horizontales (2%). K.3.8.6.4 — Ancho — El ancho mínimo de "
            "una rampa de un medio de salida no debe ser menor que 1.10 m. El ancho "
            "libre de una rampa y el ancho libre entre pasamanos, si son provistos, "
            "deben ser de 90 cm, como mínimo, con las siguientes excepciones: (a) "
            "Para acceso y utilización de sistemas mecánicos o hidráulicos y "
            "sanitarios, o equipos eléctricos, puede ser de 60 cm. (b) Dentro de una "
            "unidad de vivienda o para una capacidad de ocupantes requerida menor a "
            "50 puede ser de 90 cm. (c) Para edificaciones de los sub-grupos I-2 "
            "(Salud), en corredores que sirven a las edificaciones con carácter "
            "quirúrgico, o a centros de cuidado de salud para pacientes ambulatorios "
            "que reciben atención médica externa, lo que causa que el paciente no "
            "sea capaz de cuidarse a sí mismo, e I-3 (Educación) con un corredor que "
            "tenga una capacidad requerida de 100 ó más, debe ser de 1.8 m. (d) En "
            "Grupo I-2 en áreas que sean requeridas para movimiento de camas, debe "
            "ser de 2.4 m. K.3.8.6.5 — Altura libre — La altura libre mínima en "
            "todas las partes de la rampa del medio de salida no debe ser menor a "
            "2.0 m. K.3.8.6.6 — Restricciones — Las rampas de medios de salida no "
            "deben reducirse en ancho en la dirección del desplazamiento a la "
            "salida. Las proyecciones dentro del ancho requerido de la rampa o "
            "descanso están prohibidas. Las puertas que abren sobre un descanso no "
            "deben reducir el ancho libre a menos de 1.05 m. K.3.8.6.7 — Descansos — "
            "Las rampas deben tener descansos en la parte inferior y superior de "
            "cada rampa, puntos de quiebre, entradas, salidas y en las puertas. Los "
            "descansos deben tener una longitud mínima de 1.8 m y una longitud "
            "máxima de 3.6 m. K.3.8.6.8 — Superficie de acabados — La superficie de "
            "las rampas debe ser rugosa, estriada o estar provista de material "
            "antideslizante. K.3.8.6.9 — Pasamanos — Las rampas deben estar "
            "provistas de pasamanos los cuales deben cumplir los requisitos "
            "especificados en el numeral K.3.8.3.6. K.3.8.6.10 — Techos — Los "
            "techos sobre las rampas deben estar a una altura mínima de 2 m. "
            "K.3.8.6.11 — Rampas mecánicas — Cuando se utilicen rampas mecánicas, "
            "además de las especificaciones contenidas en K.3.8.6.1 a K.3.8.6.10, "
            "deben cumplir con las especificaciones contenidas en K.3.8.5."
        ),
    },
    {
        "id": "NSR10-K-K_3_8_7_salidas_prueba_humo",
        "seccion": "K.3.8.7 (Medios de Salida — Salidas a Prueba de Humo)",
        "titulo": "Composición, descarga, acceso y muros de cerramiento de las salidas a prueba de humo.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.8.7 — SALIDAS A PRUEBA DE HUMO — "
            "Las salidas a prueba de humo deben cumplir las disposiciones "
            "siguientes: K.3.8.7.1 — Deben constar de escalera, vestíbulo y muros de "
            "cerramiento, construidos con materiales no combustibles o de alta "
            "resistencia al fuego. K.3.8.7.2 — Deben descargar sus ocupantes en el "
            "exterior del edificio o en un pasaje de salida que conduzca a él. En "
            "edificaciones de seis o más pisos de altura, por lo menos una de las "
            "salidas debe ser a prueba de humo. K.3.8.7.3 — Acceso — El acceso a la "
            "escalera debe hacerse en cada piso a través de un descanso o "
            "plataforma de ancho mayor o igual al de la escalera. K.3.8.7.4 — Muros "
            "— Los muros de cerramiento de las escaleras deben construirse con "
            "material no combustible."
        ),
    },
    {
        "id": "NSR10-K-K_3_9_iluminacion",
        "seccion": "K.3.9 (Iluminación de los Medios de Evacuación)",
        "titulo": "Iluminación general, luces de emergencia (con procedimiento de ensayo periódico) y cambio de fuentes.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.9 — ILUMINACIÓN DE LOS MEDIOS DE "
            "EVACUACION. K.3.9.1 — GENERAL — La iluminación de los medios de "
            "evacuación debe cumplir todas las disposiciones generales siguientes: "
            "K.3.9.1.1 — La iluminación de los medios de evacuación debe ser "
            "continua durante todo el tiempo en que por condiciones de ocupación, se "
            "requiera que las vías de escape estén disponibles para ser utilizadas. "
            "K.3.9.1.2 — Los medios de evacuación deben iluminarse en todos los "
            "puntos, incluyendo ángulos e intersecciones de corredores y pasillos, "
            "escaleras, descansos y puertas de salida, con no menos de 10 lux "
            "medidos en el nivel del piso. K.3.9.1.3 — Las escaleras que hagan parte "
            "de los medios de evacuación deben iluminarse con no menos de 100 lux "
            "medidos en los escalones. K.3.9.1.4 — En auditorios, teatros y salas de "
            "conciertos, la iluminación puede reducirse a 2 lux durante la función. "
            "K.3.9.1.5 — Toda iluminación debe disponerse en forma tal que si se "
            "presenta una falla en alguna unidad de iluminación, ésta no deje en "
            "oscuridad el área servida. K.3.9.1.6 — La iluminación tiene que "
            "suministrarse por medio de una fuente que asegure razonable "
            "confiabilidad, tal como se exige, para el servicio eléctrico público.\n\n"
            "K.3.9.2 — LUCES DE EMERGENCIA — Los medios de evacuación de toda "
            "edificación, excepción hecha de las del Grupo (R-1), deben estar "
            "provistos de las instalaciones indispensables para que haya luces de "
            "emergencia. K.3.9.2.1 — El sistema de iluminación de emergencia debe "
            "alimentarse con dos fuentes independientes de suministro; una tomada de "
            "la acometida del edificio y derivada antes del control general de la "
            "edificación, pero después del contador, con circuitos e interruptores "
            "independientes en forma tal que al desconectar la corriente de los "
            "demás circuitos de la edificación ésta quede energizada, la otra tomada "
            "de una fuente auxiliar que garantice el funcionamiento del sistema en "
            "caso de un corte en la energía eléctrica. K.3.9.2.2 — El sistema de "
            "iluminación de emergencia debe proveerse de manera tal que esté en "
            "servicio por no menos de 1.5 horas después de iniciarse el evento de "
            "falla del sistema principal de energía. K.3.9.2.3 — El sistema de "
            "iluminación de emergencia debe proveerse de manera tal que no tenga "
            "menos de 10 lux, en promedio, medidos a nivel de piso, pero que no sea "
            "menor que 1 lux en ningún punto del recorrido, medido en el nivel del "
            "piso. K.3.9.2.4 — El sistema de iluminación de emergencia puede "
            "disminuir con el tiempo, pero de manera que su nivel no sea menor de 6 "
            "lux, en promedio, y 0.65 en cualquier punto, medidos en el nivel del "
            "piso, al final del periodo de 1.5 horas. K.3.9.2.5 — El sistema de "
            "iluminación de emergencia debe cumplir con las especificaciones de la "
            "norma NFPA 110 Estándar para sistemas de fuentes de poder de emergencia "
            "y alternos, u otra norma reconocida internacionalmente al respecto del "
            "mismo tema. K.3.9.2.6 — Las unidades y baterías que integren el sistema "
            "de iluminación de emergencia deben certificar aprobación por UL925, "
            "Estándar para equipos de iluminación y fuente de poder de emergencia, u "
            "otro estándar reconocido internacionalmente al respecto del mismo "
            "tema. K.3.9.2.7 — El sistema de iluminación de emergencia debe "
            "ensayarse periódicamente de acuerdo con el siguiente procedimiento: "
            "(a) El funcionamiento del sistema debe probarse mensualmente por un "
            "tiempo no inferior a 30 segundos. (b) El funcionamiento del sistema "
            "debe probarse anualmente por un tiempo no inferior a 1.5 horas. (c) "
            "Durante la prueba anual debe medirse el nivel de iluminación en el "
            "nivel del piso. (d) Si el sistema de iluminación de emergencia tiene "
            "funciones de auto-ensayo y auto-diagnóstico, el sistema automático debe "
            "tener la capacidad de realizar un ensayo mensual por no menos de 30 "
            "segundos y un ensayo anual por no menos de 1.5 horas e indicar los "
            "resultados mediante un sistema luminoso. El sistema automático debe "
            "inspeccionarse visualmente, por lo menos, una vez al mes. (e) Debe "
            "mantenerse un registro escrito de las pruebas realizadas y sus "
            "resultados para sistemas de emergencia, automáticos o manuales.\n\n"
            "K.3.9.3 — CAMBIOS DE FUENTES — Cuando el suministro de iluminación "
            "dependa de un cambio de una fuente de energía a otra, no debe haber "
            "una interrupción apreciable de la iluminación durante el cambio. "
            "Cuando la iluminación de emergencia la proporcione un generador "
            "operado por un motor primario, de gasolina o diesel (nunca eléctrico), "
            "no debe permitirse un retardo mayor a diez segundos."
        ),
    },
    {
        "id": "NSR10-K-K_3_10_senalizacion",
        "seccion": "K.3.10 (Señalización de Salidas)",
        "titulo": "Dimensiones, texto, flechas de dirección y restricción de avisos que confundan con la señal de salida.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.10 — SEÑALIZACIÓN DE SALIDAS. "
            "K.3.10.1 — Toda señal requerida en la ubicación de medios de "
            "evacuación, debe dimensionarse y diseñarse con colores verde sobre "
            "blanco, tal como se especifica en la norma NTC 1461 Higiene y "
            "seguridad. Colores y señales de seguridad, en tal forma que sea "
            "claramente visible. La localización de estas señales debe ser tal que "
            "puedan ser vistas desde cualquier punto del recorrido y que guíen hacia "
            "la salida más cercana. K.3.10.2 — Toda señal de los medios de egreso "
            "debe tener la palabra \"SALIDA\" escrita en caracteres legibles, no "
            "menores de 150 mm de alto, y trazo no menor de 20 mm de ancho, "
            "iluminados por una fuente de energía confiable. K.3.10.3 — La señal "
            "debe tener, además una flecha que indique la dirección apropiada, "
            "cuando no sea evidente cuál ha de seguirse para llegar a la salida más "
            "próxima. K.3.10.4 — RESTRICCIONES — Las puertas, corredores o "
            "escaleras que, no siendo salida ni formen parte de un acceso de "
            "salida, estén localizadas en forma tal que se presten a "
            "equivocaciones deben señalizarse con un aviso que diga, \"NO PASE\" "
            "dispuesto de modo que no se confunda con los avisos de salida. No se "
            "permiten decoraciones, amoblado, o equipos que impidan la visibilidad "
            "de las señales de salida."
        ),
    },
    {
        "id": "NSR10-K-K_3_11_almacenamiento",
        "seccion": "K.3.11 (Requisitos Específicos — Grupo Almacenamiento A)",
        "titulo": "Número de salidas y capacidad de los medios de evacuación específicos del Grupo A.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.11 — REQUISITOS ESPECÍFICOS PARA "
            "EDIFICACIONES PERTENECIENTES AL GRUPO DE OCUPACION ALMACENAMIENTO (A). "
            "K.3.11.1 — NUMERO DE SALIDAS — En toda edificación o estructura, o "
            "sección de ésta, que se considere separada, debe haber, por lo menos "
            "dos medios de evacuación distantes entre sí tanto como sea posible. "
            "K.3.11.1.1 — En espacios o áreas cerradas puede permitirse que haya una "
            "sola salida cuando la edificación tenga un área menor de 900 m², "
            "siempre que normalmente esté ocupada apenas por un centenar de "
            "personas y no contenga material de alta peligrosidad. K.3.11.1.2 — La "
            "distancia de recorrido hasta cualquier medio único de salida no debe "
            "ser superior a 15 m si se tiene un sistema de extinción sin "
            "rociadores y a 30 m, en caso que sí los haya. K.3.11.2 — CAPACIDAD DE "
            "LOS MEDIOS DE EVACUACIÓN — La capacidad de un módulo de ancho de "
            "salida debe ser la que se prescribe, como sigue: K.3.11.2.1 — Puertas "
            "— Remitirse a la tabla K.3.3-2. K.3.11.2.2 — Escaleras — interiores o "
            "exteriores: 75 personas por módulo de ancho de salida. K.3.11.2.3 — "
            "Rampas — Deben cumplir con lo estipulado en el numeral K.3.8."
        ),
    },
    {
        "id": "NSR10-K-K_3_12_comercial",
        "seccion": "K.3.12 (Requisitos Específicos — Grupo Comercial C)",
        "titulo": "Capacidad de medios de evacuación, acceso a salidas y número de salidas por subgrupo C-1/C-2.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.12 — REQUISITOS ESPECÍFICOS PARA "
            "EDIFICACIONES PERTENECIENTES AL GRUPO DE OCUPACION COMERCIAL (C). "
            "K.3.12.1 — CAPACIDAD DE LOS MEDIOS DE EVACUACIÓN — La capacidad de un "
            "módulo de ancho de salida debe ser la que en seguida se prescribe, "
            "según el elemento del cual se trate. K.3.12.1.1 — Puertas que den "
            "directamente al exterior de la edificación o a nivel del piso, o cuyo "
            "nivel no exceda por encima o por debajo en tres escalones: 100 personas "
            "por módulo de ancho de salida. K.3.12.1.2 — Escaleras interiores o "
            "exteriores y ductos a prueba de humo: 60 personas por módulo de ancho "
            "de salida. K.3.12.1.3 — Rampas — Deben contar con una capacidad de 100 "
            "personas por módulo de ancho de salida, cumplir con lo estipulado en el "
            "numeral K.3.8.6 y con lo especificado en la norma NTC 4143 "
            "Accesibilidad de las Personas al Medio Físico. Edificios, Rampas Fijas. "
            "K.3.12.1.4 — Salidas Horizontales: 100 personas por módulo de ancho de "
            "salida. K.3.12.1.5 — En almacenes con área superior a 270 m², el "
            "número de puertas de salida al nivel de la calle o de puertas "
            "simplemente horizontales, debe ser suficiente para proporcionar los "
            "siguientes módulos de salida: (a) Uno por cada 100 personas, a nivel de "
            "la calle. (b) Uno por cada dos módulos requeridos para las escaleras "
            "que conduzcan al nivel de la calle desde pisos inferiores. (c) Uno y "
            "medio por cada dos módulos requeridos para escaleras que conduzcan al "
            "nivel de la calle. (d) Uno y medio por cada dos módulos requeridos "
            "para escaleras mecánicas que conduzcan al nivel de la calle, o donde "
            "éstas se utilicen como medio auxiliar de evacuación o de acceso a las "
            "salidas requeridas.\n\n"
            "K.3.12.2 — ACCESO A LAS SALIDAS — El ancho total de los corredores que "
            "conduzcan a una salida, debe por lo menos ser igual al ancho que se "
            "haya fijado para ésta. K.3.12.2.1 — En edificaciones del Grupo de "
            "Ocupación (C-2), con más de 270 m² en el piso a nivel de la calle, debe "
            "disponerse por lo menos de un corredor con ancho mínimo de 1.50 m, que "
            "conduzca directamente a una salida al exterior de la edificación.\n\n"
            "K.3.12.3 — NUMERO DE SALIDAS — Las edificaciones del Grupo de "
            "Ocupación Comercial (C), deben tener el número de salidas "
            "especificado según lo siguiente: K.3.12.3.1 — Edificaciones del "
            "Subgrupo de Ocupación Comercial Servicios (C-1) — Debe existir, por lo "
            "menos, dos salidas accesibles desde cualquier punto de todos los "
            "pisos, incluyendo los inferiores a nivel de la calle, con excepción de "
            "los que tengan salida directa a la calle o a un área abierta, con "
            "distancia total de recorrido no mayor de 30 m hasta la salida y carga "
            "de ocupación inferior a 100 personas. Las salidas directas deben "
            "disponerse en el mismo nivel del piso, y cuando haya que atravesar "
            "escaleras éstas no podrán salvar en tramos individuales más de 4.50 m "
            "de altura, deben estar aisladas de cualquier otra parte de la "
            "edificación y carecer de puertas dentro de su desarrollo. K.3.12.3.2 — "
            "Edificaciones del Subgrupo de Ocupación Comercial Bienes (C-2) — Toda "
            "edificación o área clasificada en el Subgrupo C-2 debe contar por lo "
            "menos, con dos salidas separadas y accesibles desde cualquier lugar de "
            "la edificación, incluyendo los pisos colocados bajo el nivel de la "
            "calle. Únicamente las edificaciones o áreas de menos de 270 m² y cuyos "
            "puntos no disten entre sí más de 15 metros, pueden tener una sola "
            "salida."
        ),
    },
    {
        "id": "NSR10-K-K_3_13_fabril",
        "seccion": "K.3.13 (Requisitos Específicos — Grupo Fabril e Industrial F)",
        "titulo": "Capacidad de evacuación, distancia de recorrido extendida hasta 90 m y número de salidas del Grupo F.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.13 — REQUISITOS ESPECÍFICOS PARA "
            "EDIFICACIONES PERTENECIENTES AL GRUPO DE OCUPACION FABRIL E INDUSTRIAL "
            "(F). K.3.13.1 — CAPACIDAD DE LOS MEDIOS DE EVACUACIÓN — La capacidad "
            "por módulo de ancho de salida debe ser, según los elementos a que se "
            "refiere, como sigue y de acuerdo con las especificaciones de la NTC "
            "4145 Accesibilidad de la Personas al Medio Físico. Edificios, "
            "escaleras, y NTC 4140 Accesibilidad de las Personas al Medio Físico. "
            "Edificios, pasillos, corredores: K.3.13.1.1 — Puertas exteriores — 100 "
            "personas por módulo de ancho de salida. Una puerta se considera "
            "exterior cuando conduce directamente al exterior de la edificación a "
            "nivel del terreno, o su nivel no excede tres escalones por encima o, "
            "por debajo de éste. K.3.13.1.2 — Escaleras interiores o exteriores — 60 "
            "personas por módulo de ancho de salida. K.3.13.1.3 — Rampas — Además "
            "de lo especificado en el numeral K.3.8, las rampas deben calcularse "
            "basándose en una capacidad de 100 personas por módulo de ancho de "
            "salida y cumplir con lo especificado en la norma NTC 4143 "
            "Accesibilidad de las Personas al Medio Físico. Edificios, Rampas "
            "Fijas. K.3.13.1.4 — Salidas horizontales — 100 personas por módulo de "
            "ancho de salida, pero no más del 50% de la capacidad requerida de "
            "salida. K.3.13.1.5 — En ocupaciones industriales especiales, hay que "
            "proporcionar los medios de evacuación en espacios ocupados por "
            "personas, sin considerar los que sirven exclusivamente a maquinaria y "
            "equipos.\n\n"
            "K.3.13.2 — DISTANCIA DEL RECORRIDO — En edificaciones industriales con "
            "riesgos leves o altos, y en ocupaciones industriales generales y "
            "especiales, que requieran áreas de piso no divididas y distancias de "
            "recorrido superiores a 45 m, la movilización a las salidas debe "
            "efectuarse por medio de escaleras que conduzcan a través de muros "
            "cortafuego o de túneles de evacuación a prueba de humo, pasajes "
            "elevados o salidas horizontales. Cuando sea imposible proveer estos "
            "dispositivos puede permitirse el uso de distancias hasta de 90 m a la "
            "salida más próxima, siempre que en conjunto se observen los siguientes "
            "requisitos adicionales: K.3.13.2.1 — Limitación a edificios de un "
            "piso, con acabados de difícil combustión y no productores de humo. "
            "K.3.13.2.2 — Provisión de iluminación de emergencia. K.3.13.2.3 — "
            "Provisión de sistemas automáticos de extinción, supervisados "
            "periódicamente. K.3.13.2.4 — Provisión de ventilación por medios "
            "mecánicos o en virtud de una apropiada configuración arquitectónica "
            "que evite que, dentro de un espacio de 1.80 m del nivel, los ocupantes "
            "se vean afectados por los humos o gases provenientes del fuego, antes "
            "de llegar a las salidas.\n\n"
            "K.3.13.3 — NUMERO DE SALIDAS — Debe haber por lo menos dos salidas "
            "para cada piso o sección de éste, incluyendo los que quedan bajo el "
            "nivel de descarga. K.3.13.3.1 — Las áreas con capacidad no mayor de 25 "
            "personas, con salida directa a la calle o a una zona abierta fuera de "
            "la edificación y a nivel de tierra, y en las que el recorrido desde "
            "cualquier punto hasta el exterior no exceda de 15 m, pueden tener una "
            "sola salida; ésta debe ubicarse sobre el propio nivel del piso y si es "
            "preciso atravesar escaleras, el recorrido vertical de cada tramo no ha "
            "de sobrepasar los 4.50 m. Deben estar aisladas de cualquier otra parte "
            "de la edificación y carecer de puertas en su desarrollo."
        ),
    },
    {
        "id": "NSR10-K-K_3_14_institucional",
        "seccion": "K.3.14 (Requisitos Específicos — Grupo Institucional I)",
        "titulo": "Requisitos específicos por subgrupo I-1 (reclusión), I-2 (salud/incapacidad) e I-3/I-4/I-5 (educación, seguridad y servicio público).",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.14 — REQUISITOS ESPECÍFICOS PARA "
            "EDIFICACIONES PERTENECIENTES AL GRUPO DE OCUPACIÓN INSTITUCIONAL (I). "
            "K.3.14.1 — REQUISITOS ESPECÍFICOS PARA EDIFICACIONES DEL SUBGRUPO DE "
            "OCUPACION (I-1) — Los medios de evacuación de las edificaciones que "
            "clasifiquen en el Subgrupo de Ocupación Institucional de Reclusión "
            "(I-1) deben cumplir las reglamentaciones siguientes: K.3.14.1.1 — "
            "Accesos a las salidas — Los diferentes tipos de accesos a las salidas "
            "deben cumplir los requisitos especificados a continuación: Puertas — "
            "Todo salón debe tener una puerta de acceso a un corredor provisto de "
            "salida, excepto cuando las que posea, abran directamente al exterior. "
            "Las puertas que sirven al interior de un corredor deben tener un "
            "retroceso para que prevenga interferencias con el tránsito del "
            "corredor. Cualquier puerta que no disponga de tal artificio debe abrir "
            "en un ángulo de 180° hasta parar contra el muro. Corredores y "
            "mezzanines — Los pasillos, corredores o rampas que sirvan de acceso a "
            "una salida, deben tener ancho mínimo de 1.20 m como acceso a una "
            "salida, pero sin que sus trayectos ciegos excedan de los 6 m. Todo "
            "corredor tiene un ancho mínimo 1.20 m, el cual debe estar siempre "
            "libre de obstrucción por parte de cualquier clase de maquinaria fija o "
            "móvil. Donde se utilicen corredores exteriores o mezanines como medio "
            "de evacuación, éstos deben conducir a una salida situada a una "
            "distancia no mayor de 45 m, medida desde cualquier punto del corredor "
            "o mezanine. Salones bajo el nivel de descarga — Los salones o "
            "espacios situados bajo el nivel de descarga de salidas, deben tener "
            "acceso por lo menos a una salida que conduzca al exterior de la "
            "edificación en el nivel de descarga de las salidas o al nivel del "
            "terreno, sin tener que pasar por el piso superior. Ventanas — Cada "
            "salón o espacio utilizado para enseñanza, debe estar provisto, al "
            "menos, de una ventana exterior utilizable para rescate de emergencia, "
            "a menos que el salón disponga de una puerta que conduzca directamente "
            "al exterior del edificio. K.3.14.1.2 — Distancia de recorrido — Es "
            "preciso que la distancia de recorrido no supere los siguientes "
            "valores: (a) Entre cualquier puerta de una edificación considerada "
            "como acceso de salida y una salida: 30 m. (b) Entre cualquier punto de "
            "una habitación y una salida: 45 m. (c) Entre cualquier punto de una "
            "habitación utilizada para el cuidado de enfermos y una puerta de "
            "dicha habitación para el acceso de una salida: 15 m. K.3.14.1.3 — "
            "Medios de salida — En edificaciones Institucionales de Reclusión, es "
            "preciso que las puertas tengan cerraduras que impidan la libre "
            "circulación y es conveniente que haya sistemas de apertura de las "
            "puertas por control remoto.\n\n"
            "K.3.14.2 — REQUISITOS ESPECÍFICOS PARA EDIFICACIONES DEL SUBGRUPO DE "
            "OCUPACION (I-2) — Los medios de evacuación de las edificaciones que "
            "clasifiquen en el Subgrupo de Ocupación Institucional Salud o "
            "Incapacidad (I-2), deben cumplir las reglamentaciones siguientes: "
            "K.3.14.2.1 — Capacidad de los medios de evacuación — La capacidad de "
            "los medios de evacuación por escaleras debe ser de 22 personas por "
            "módulo de ancho de salida y la de los medios de evacuación "
            "recorrido horizontal (sin escaleras), tales como puertas y "
            "corredores, de 30 personas por módulo de ancho de salida. La "
            "velocidad de evacuación para estos casos debe ser de 22 a 30 "
            "personas por minuto y por módulo de ancho de salida. La capacidad "
            "de los medios de evacuación protegidos en todo su recorrido "
            "mediante un sistema debidamente aprobado de rociadores automáticos, "
            "puede aumentarse a 35 personas por módulo de ancho de salida para "
            "medios de evacuación por escaleras y a 45 personas por módulo de "
            "ancho de salida, para medios de evacuación horizontales sin "
            "escaleras. K.3.14.2.2 — Número de salidas — Los dormitorios de "
            "pacientes deben estar provistos de sendas puertas de acceso a "
            "corredores que conduzcan a una salida. Los pasillos, corredores y "
            "rampas de salida deben tener ancho libre mínimo de 2.40 m; en "
            "cualquier ala de alcobas con áreas mayores de 200 m², debe haber por "
            "lo menos dos puertas de salida, tan separadas entre sí como sea "
            "posible. K.3.14.2.3 — Medios de salida — Las puertas de salida "
            "utilizadas para el desplazamiento de camas y camillas deben tener por "
            "lo menos 1.10 m de ancho. Es preciso que las puertas dispongan de un "
            "sistema de apertura contra pánico, excepto las que evacuen una carga "
            "de ocupación inferior a 75 personas.\n\n"
            "K.3.14.3 — REQUISITOS ESPECÍFICOS PARA EDIFICACIONES DEL SUBGRUPO DE "
            "OCUPACION (I-3) — Los medios de evacuación de las edificaciones que "
            "clasifiquen en los Subgrupos de Ocupación Institucional Educación "
            "(I-3), Seguridad Pública (I-4) y Servicio Público (I-5) deben cumplir "
            "las reglamentaciones siguientes: K.3.14.3.1 — Capacidad de los medios "
            "de evacuación — Toda edificación educacional y de seguridad o "
            "Servicio Público, y cualquiera de sus secciones o áreas que se "
            "consideren separadamente deben tener el número de salidas suficiente "
            "para que según su capacidad, se ofrezcan uno o más de los siguientes "
            "tipos de salidas: Puertas exteriores — 30 personas por módulo de "
            "ancho de salida. Una puerta se considera exterior cuando conduce "
            "directamente al exterior de la edificación a nivel del terreno, o su "
            "nivel no excede tres escalones por encima o, por debajo de éste. "
            "Escaleras interiores y exteriores o de incendio — 22 personas por "
            "módulo de ancho de salida. Salidas horizontales — 30 personas por "
            "módulo de ancho de salida. Rampas — Deben cumplir con lo estipulado "
            "en el numeral K.3.8.6 y contar con una capacidad de 100 personas por "
            "módulo de ancho de salida. K.3.14.3.2 — Ancho mínimo de corredores — "
            "Abarcará el número de módulos de ancho de salida que determine el "
            "número de ocupantes del área en cuestión según lo estipulado en la "
            "tabla K.3.3-2, y no debe hallarse obstruido por equipos móviles. Las "
            "puertas que abren hacia el interior de un corredor de salida, deben "
            "tener un retroceso que prevenga interferencias con el tránsito del "
            "corredor; cualquier puerta que carezca de retroceso debe abrirse en "
            "un ángulo de 180 grados hasta parar contra el muro. K.3.14.3.3 — Los "
            "módulos de ancho de salida o las fracciones de ellos que se requieran "
            "para cualquier piso individual pueden servir simultáneamente a todos "
            "los niveles por encima del primer piso o del piso del nivel de "
            "descarga. K.3.14.3.4 — Número de salidas — Cada área de piso debe "
            "disponer, por lo menos, de dos salidas. Todo espacio con capacidad "
            "mayor de 50 personas o con más de 90 m² de área, debe disponer, de "
            "por lo menos, de 2 puertas de salida tan separadas como sea posible; "
            "estas puertas han de dar acceso a salidas diferentes o a corredores "
            "comunes que conduzcan a salidas separadas en direcciones opuestas."
        ),
    },
    {
        "id": "NSR10-K-K_3_15_lugares_reunion",
        "seccion": "K.3.15 (Requisitos Específicos — Grupo Lugares de Reunión L)",
        "titulo": "Capacidad de medios de evacuación, accesos, filas de asientos (Tabla K.3.15-1) y medios de salida del Grupo L.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.15 — REQUISITOS ESPECÍFICOS PARA "
            "EDIFICACIONES PERTENECIENTES AL GRUPO DE OCUPACION LUGARES DE REUNION "
            "(L). K.3.15.1 — CAPACIDAD DE LOS MEDIOS DE EVACUACIÓN — Todo sitio de "
            "reunión tiene que contar con un número de salidas suficiente como para "
            "satisfacer la capacidad total del recinto, tales salidas deben cumplir "
            "los requisitos siguientes: K.3.15.1.1 — Ningún medio de evacuación "
            "puede medir menos de dos módulos de ancho de salida. K.3.15.1.2 — Debe "
            "haber una salida principal cuyo ancho sea el necesario para acomodar "
            "la mitad de la carga total de ocupación, pero sin que resulte menor "
            "del ancho total indispensable para todo corredor, pasillo o escalera "
            "que desemboquen en ella y de manera que el nivel de salida se coloque "
            "al exterior o se conecte a una rampa o escalera dirigida a cualquier "
            "vía pública. K.3.15.1.3 — Cada nivel de un sitio de reunión debe tener "
            "acceso a la salida principal y salidas suficientes para evacuar las "
            "dos terceras partes de la carga de ocupación total del nivel en flujo "
            "continuo, con promedio de 60 personas por minuto, por módulo de ancho "
            "de salida. Estas salidas deben conducir directamente a una vía "
            "pública, o a patios, escaleras protegidas, escaleras exteriores o "
            "pasillos que conduzcan a una calle y estar localizadas tan lejos como "
            "sea posible de la salida principal. Cuando se disponga únicamente de "
            "dos salidas, cada una debe tener el ancho suficiente para recibir, por "
            "lo menos, la mitad de la carga de ocupación total.\n\n"
            "K.3.15.2 — ACCESOS A LAS SALIDAS — Toda sección de edificación que "
            "aloje el grupo de Ocupación Lugares de Reunión (L), que aloje "
            "asientos, mesas u otros objetos, debe estar provista de pasillos que "
            "conduzcan a las salidas. K.3.15.2.1 — Todo pasillo debe tener un ancho "
            "mínimo de 900 mm cuando sirva a más de 60 asientos sobre un lado y no "
            "menos de 1.20 m cuando sirva a asientos sobre ambos lados. Estos "
            "anchos mínimos deben medirse en el punto más alejado de cualquier "
            "salida, pasillo cruzado o salón de entrada. El ancho mínimo debe "
            "incrementarse en 35 mm por cada 1.5 m de longitud hacia la salida, "
            "pasillo cruzado o salón de entrada. K.3.15.2.2 — Todo pasillo que "
            "sirva a 60 asientos o menos no debe tener menos de 750 mm de ancho. "
            "K.3.15.2.3 — Los pasillos deben terminar en una salida, pasillo "
            "cruzado o salón de entrada y su ancho no debe ser menor que la suma "
            "del requerido para el pasillo más amplio y el 50% del ancho agregado "
            "de los demás pasillos. La máxima pendiente de todo pasillo inclinado "
            "se limita al 13%.\n\n"
            "K.3.15.3 — FILAS DE ASIENTOS — Las filas de asientos dispuestas en "
            "lugares de reunión deben cumplir las reglamentaciones siguientes: "
            "K.3.15.3.1 — Una fila de asientos no puede tener más de 100 sillas, "
            "si tiene acceso a través de ambos de sus extremos, o no más de 50 "
            "sillas, si reacceso se hace sólo desde uno de sus extremos. K.3.15.3.2 "
            "— La distancia horizontal libre entre filas de asientos, medida tal "
            "como se muestra en la figura K.3.15-1, no debe exceder los valores "
            "dados en la Tabla K.3.15-1, cuando existen corredores en ambos "
            "extremos de las filas. Figura K.3.15-1 describe la medida de la "
            "distancia horizontal entre filas (dH), para (a) asiento fijo y (b) "
            "asiento auto-basculante — la distancia dH se mide en el plano "
            "horizontal entre el respaldo de una fila y el borde delantero del "
            "asiento (fijo o abatido) de la fila siguiente.\n\n"
            "Tabla K.3.15-1 — Distancias horizontales libres entre filas de "
            "asientos (Máximo número de sillas entre corredores — Distancia "
            "horizontal libre entre filas, mm): 14 = 300. 18 = 350. 24 = 400. 30 = "
            "450. 36 = 500. 42 = 550. 48 = 600. 54 = 650. 60 = 700. 66 a 100 = "
            "750.\n\n"
            "K.3.15.3.3 — Si uno solo de los extremos de una fila de asientos da a "
            "un corredor, el número máximo de sillas en la Tabla K.3.15-1 debe "
            "dividirse por 2. K.3.15.3.4 — Los asientos sin brazos divisorios "
            "tienen limitada su capacidad a 450 mm lineales por persona.\n\n"
            "K.3.15.4 — MEDIOS DE SALIDA — Las puertas deben llevar directamente "
            "al exterior o a un espacio o pasaje que sin interferencias conduzca a "
            "aquel. K.3.15.4.1 — Las puertas que linden con pasillos y las locales "
            "o espacios con cargas de ocupación mayores de 100, deben tener un "
            "sistema de apertura contra pánico; a tal fin puede servir un "
            "dispositivo que permita abrir la puerta y levantar el pestillo "
            "mediante una fuerza del orden de 75 N aplicada en la dirección de "
            "evacuación o una barra o panel cuya zona de activación esté a no "
            "menos de la mitad del ancho de la hoja de la puerta y a una altura "
            "sobre el piso variable entre 0.75 y 1.10 m. K.3.15.4.2 — Rampas — Los "
            "lugares de reunión con carga de ocupación superior a 1000, deben "
            "disponer de rampas según lo estipulado en el numeral K.3.6."
        ),
    },
    {
        "id": "NSR10-K-K_3_16_mixto",
        "seccion": "K.3.16 (Requisitos Específicos — Grupo Mixto M)",
        "titulo": "Límite de distancia de recorrido de 30 m (45 m con protección automática) cuando no aplica un grupo específico.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.16 — REQUISITOS ESPECÍFICOS PARA "
            "EDIFICACIONES PERTENECIENTES AL GRUPO DE OCUPACION MIXTO (M). K.3.16.1 "
            "— DISTANCIA DE RECORRIDO — Cuando no sea posible proceder de acuerdo "
            "con lo establecido para Grupos de Ocupación específicos, en la "
            "determinación del recorrido, éste quedará limitado a un máximo de 30 "
            "m. K.3.16.1.1 — Esta distancia de recorrido puede aumentarse a 45 m "
            "en estructuras dotadas con equipos automáticos o de detección y "
            "extinción de incendios."
        ),
    },
    {
        "id": "NSR10-K-K_3_17_alta_peligrosidad",
        "seccion": "K.3.17 (Requisitos Específicos — Grupo Alta Peligrosidad P)",
        "titulo": "Trayecto máximo de 22 m a lugar seguro y capacidad mínima de salidas del Grupo P.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.17 — REQUISITOS ESPECÍFICOS PARA "
            "EDIFICACIONES PERTENECIENTES AL GRUPO DE OCUPACION ALTA PELIGROSIDAD "
            "(P). K.3.17.1 — En todos los casos en los que las edificaciones o "
            "espacios se clasifiquen como de alta peligrosidad, las salidas deben "
            "ser del tipo y número que permitan a todos los ocupantes salir de la "
            "edificación o estructura o del área de peligro al exterior a un lugar "
            "seguro, mediante un trayecto inferior a 22 m. K.3.17.2 — La capacidad "
            "de las salidas no debe ser inferior a la requerida para una capacidad "
            "de 30 personas por módulo de ancho de salida cuando la salida sea a "
            "través de escaleras interiores o exteriores o para 50 personas por "
            "módulo de ancho de salida cuando la salida sea a través de puertas a "
            "nivel del terreno, o por salidas horizontales o rampas."
        ),
    },
    {
        "id": "NSR10-K-K_3_18_residencial",
        "seccion": "K.3.18 (Requisitos Específicos — Grupo Residencial R)",
        "titulo": "Requisitos específicos por subgrupo R-1 (unifamiliar/bifamiliar), R-2 (multifamiliar) y R-3 (hoteles) — número de salidas, medios de salida y distancia de recorrido.",
        "texto": (
            "NSR-10 Título K, Capítulo K.3 — K.3.18 — REQUISITOS ESPECÍFICOS PARA "
            "EDIFICACIONES PERTENECIENTES AL GRUPO DE OCUPACION RESIDENCIAL (R). "
            "K.3.18.1 — REQUISITOS ESPECÍFICOS PARA EDIFICACIONES DEL GRUPO DE "
            "OCUPACION (R-1) — Los medios de evacuación de las edificaciones del "
            "Subgrupo de Ocupación Residencial Unifamiliar y Bifamiliar (R-1) deben "
            "cumplir los requisitos siguientes: K.3.18.1.1 — Número de salidas — Se "
            "permite que haya una sola salida por piso en el caso de edificaciones "
            "unifamiliares y bifamiliares de las siguientes características: "
            "construida con materiales incombustibles, con una altura inferior a 9 "
            "m, un área por piso que no exceda de 200 m² y una distancia máxima de "
            "travesía de 15 m. K.3.18.1.2 — Medios de salida — No es necesario que "
            "las puertas se abran en la misma dirección de evacuación. (a) Las "
            "puertas de entrada y salida deben estar provistas de cerraduras y "
            "tener un sistema de iluminación adecuado. (b) Se requiere que las "
            "puertas de las unidades de vivienda tengan cerraduras provistas de "
            "perillas con botón que impida la apertura por otro medio que facilite "
            "las llaves; puede, además, proveérseles de una cadena que facilite su "
            "apertura parcial y de un sistema de visión que permita a quien esté en "
            "el interior de la habitación, ver a cualquier persona colocada en la "
            "parte de afuera. (c) Las ventanas dispuestas para su apertura deben "
            "estar dotadas de un sistema de cerradura en los marcos que sólo se "
            "abra desde el interior.\n\n"
            "K.3.18.2 — REQUISITOS ESPECÍFICOS PARA EDIFICACIONES DEL GRUPO DE "
            "OCUPACION (R-2) — Los medios de evacuación del Subgrupo de Ocupación "
            "Residencial Multifamiliar (R-2) deben cumplir los requisitos "
            "siguientes: K.3.18.2.1 — Número de salidas — Se acepta que haya una "
            "salida por piso en edificaciones multifamiliares, siempre que "
            "cumplan con las especificaciones siguientes: construida con "
            "materiales incombustibles, con una altura inferior a 15 m, un área "
            "por piso que no exceda de 400 m² y una distancia máxima de travesía "
            "de 15 m. K.3.18.2.2 — Todo dormitorio de edificaciones residenciales "
            "colocado a menos de cinco pisos debe tener al menos una ventana libre "
            "para su apertura o una puerta exterior dispuesta para evacuación o "
            "rescate. K.3.18.2.3 — Se admite que cualquier unidad de vivienda "
            "tenga una sola salida, siempre que ésta vaya directamente a una vía "
            "pública al nivel del terreno, una escalera exterior o a una escalera "
            "interior a prueba de incendios que no forme parte del apartamento "
            "servido. K.3.18.2.4 — La distancia de recorrido desde la puerta de "
            "entrada a una habitación hasta la salida más próxima no debe exceder "
            "45 m y 35 m respectivamente, según que las edificaciones tengan un "
            "sistema de rociadores o carezcan de él. K.3.18.2.5 — Medios de "
            "salida — Los medios de salida deben cumplir los requisitos "
            "siguientes: (a) En edificaciones multifamiliares, es indispensable "
            "que las puertas se abran en la misma dirección de evacuación. (b) Las "
            "puertas de entrada y salida deben estar provistas de cerraduras y de "
            "un sistema de iluminación adecuado. (c) Las ventanas aptas para su "
            "apertura, deben tener un sistema de cerradura en los marcos que "
            "permita abrirlos únicamente desde el interior. K.3.18.2.6 — Escaleras "
            "interiores — Las escaleras interiores de apartamentos y edificios "
            "residenciales de dos pisos, con carga de ocupación inferior a 10, "
            "pueden construirse teniendo en cuenta una huella mínima de 210 mm y "
            "una contrahuella máxima de 210 mm.\n\n"
            "K.3.18.3 — REQUISITOS ESPECÍFICOS PARA EDIFICACIONES DEL GRUPO DE "
            "OCUPACION (R-3) — Los medios de evacuación de las edificaciones del "
            "Subgrupo de Ocupación Residencial Hoteles (R-3) deben cumplir los "
            "requisitos siguientes: K.3.18.3.1 — Capacidad de los medios de "
            "evacuación — Las salidas a nivel de la calle deben proyectarse con "
            "base en los siguientes módulos de ancho de salida: (a) Un módulo por "
            "cada 100 personas de capacidad en el acceso principal, para puertas y "
            "otros niveles de salida, incluyendo aquellos cuyo inicio se encuentre "
            "a 600 mm o 3 escalones bien sobre, o bajo el nivel de la calle. (b) Un "
            "módulo por cada 75 personas de capacidad en el acceso principal, para "
            "escaleras u otras salidas que requieran descenso al nivel de la "
            "calle. (c) Un módulo y medio de salida por cada dos módulos "
            "requeridos para escaleras que, descendiendo de los pisos superiores, "
            "conduzcan directamente al nivel de la calle. (d) Un módulo y medio de "
            "salida por cada dos módulos requeridos para escaleras que, "
            "ascendiendo de los pisos inferiores, conduzcan directamente al nivel "
            "de la calle. Cada piso bajo el nivel de descarga de salida debe tener "
            "salidas suficientes para la carga de ocupación y del mismo piso, "
            "sobre la base de una salida por cada 100 personas en travesías al "
            "mismo nivel y una salida por cada 75 personas en travesías por "
            "escaleras de más de 3 escalones. Las salidas de pisos sobre el nivel "
            "de descarga de salida deben tener el mínimo de módulos de salida "
            "indispensable para que se cumplan los requisitos del numeral "
            "K.3.18.3.1. K.3.18.3.2 — Número de salidas — Todos los pisos, "
            "inclusive aquellos que se encuentran bajo el nivel de salidas o el "
            "nivel ocupado para propósitos públicos, deben tener por lo menos dos "
            "salidas. Cualquier habitación con capacidad inferior a 50 personas, "
            "puede tener una sola salida, siempre y cuando dé a la calle o al "
            "nivel del terreno y ningún punto de la habitación esté a más de 15 m "
            "de dicha salida, medidos a lo largo del recorrido normal. Puede "
            "tenerse una salida por piso en edificaciones de menos de dos pisos o "
            "de 9 m de altura, siempre que la distancia máxima de recorrido sea de "
            "24 m y que se cuente con un sistema automático extintor de incendios. "
            "K.3.18.3.3 — Distancia de recorrido — La distancia de recorrido del "
            "extremo de una alcoba a su corredor de salida no debe ser superior a "
            "15 m."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])
    print(f"Chunks a insertar: {len(CHUNKS)}")
    for c in CHUNKS:
        print(f"  {c['id']} ({c['seccion']}): {len(c['texto'])} chars")

    print("\nCargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
    textos = [c["texto"] for c in CHUNKS]
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print("\nSubiendo a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()

    ids_viejos = [
        "NSR10-K-K_3_1", "NSR10-K-K_3_2", "NSR10-K-K_3_3",
        "NSR10-K-K_3_4_a_K_3_6", "NSR10-K-K_3_7_proteccion_evacuacion",
        "NSR10-K-K_3_8_1_general_medios_salida", "NSR10-K-K_3_8_2_a_K_3_8_3",
        "NSR10-K-K_3_8_4_escaleras_exteriores", "NSR10-K-K_3_8_5_a_K_3_8_7",
        "NSR10-K-K_3_9_a_K_3_10",
    ]
    print(f"\nBorrando {len(ids_viejos)} chunks viejos de K.3 (condensados/reemplazados)...")
    sb.table("nsr10_chunks").delete().in_("id", ids_viejos).execute()

    print(f"\nOK: {len(rows)} chunks verbatim de K.3 cargados. Capítulo K.3 completo (K.3.1-K.3.18).")


if __name__ == "__main__":
    main()
