"""
NSR-10 Titulo F, F.3.9 (Fabricacion y Montaje) + F.3.10 (Control de
Calidad e Inspeccion) + F.3.11 (Ensayos para Calificacion de Conexiones)
-- ultimo batch de la decision del usuario 2026-08-27 de rehacer
F.3.5-F.3.11 verbatim. Con esto, TODO el Capitulo F.3 (Provisiones
sismicas para acero) queda en verbatim real.

Fuente: NSR-10-901-980.pdf (Drive, id 14q4ylyJYB9H1IdLrdZ0X0crekxxbajmm),
paginas internas F-285 a F-299. Leido visualmente pagina por pagina.

6 chunks. Reemplaza los chunks viejos resumidos NSR10-F-F_3_9_fabricacion_montaje
(2010 chars), F_3_10_inspeccion_soldaduras (1738), F_3_10_inspeccion_pernos
(1184), F_3_11_precalificacion (2192), F_3_11_ensayos_viga_columna (2419),
F_3_11_ensayos_BRB (2543) -- todos se borran tras verificar cobertura.

Uso: python _ingest_titulo_f_f39_a_f311.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "NSR-10 Título F — Estructuras Metálicas"

CHUNKS = [
    {
        "id": "NSR10-F-F_3_9_fabricacion_montaje_completo",
        "seccion": "F.3.9 (Fabricación y Montaje — planos, zona protegida, uniones pernadas/soldadas, placas de continuidad)",
        "titulo": (
            "Fabricación y montaje del SRS completo: contenido requerido de planos "
            "de fabricación/montaje (localización de pernos, superficies especiales, "
            "agujeros de acceso), reglas de zona protegida (sin conectores de "
            "cortante soldados ni fijaciones dentro), uniones AWS D1.1/D1.8, "
            "placas de continuidad y atiesadores."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.9 — FABRICACIÓN Y MONTAJE — establece los requisitos para la "
            "fabricación y montaje. Se deben cumplir todos los requisitos de F.2.13, "
            "excepto lo modificado específicamente en este numeral. Secciones: "
            "F.3.9.1 Planos de fabricación y montaje, F.3.9.2 Fabricación y montaje.\n\n"
            "F.3.9.1 — PLANOS DE FABRICACIÓN Y MONTAJE.\n"
            "F.3.9.1.1 Planos de fabricación para construcción en acero — deben "
            "indicar el trabajo que debe realizarse e incluir los aspectos "
            "requeridos por el Capítulo F.2, el Código de Prácticas Estándar para "
            "Estructuras de Acero ICONTEC, y los requisitos aplicables de F.3.1.4.1 "
            "y F.3.1.4.2, así como los siguientes, si son aplicables: (1) "
            "localización de pernos pretensionados; (2) localización de superficies "
            "con acabados especiales, clase A o mejores; (3) placas de unión "
            "dibujadas a escala cuando se diseñan para permitir rotaciones "
            "inelásticas; (4) dimensiones del agujero de acceso, perfil de "
            "superficie y su acabado; (5) sitios donde las platinas de respaldo "
            "deben ser removidas; (6) sitios donde se requieren filetes de "
            "soldadura cuando se permita que se dejen las platinas de respaldo; (7) "
            "sitios donde se requieren filetes de soldadura para reforzar "
            "soldaduras acanaladas, o donde se necesitan para mejorar la geometría "
            "de la conexión; (8) sitios donde deben removerse las extensiones de "
            "soldadura; (9) ensayos no destructivos que debe realizar el "
            "fabricante.\n"
            "F.3.9.1.2 Planos de montaje para construcción en acero — deben "
            "indicar el trabajo que debe realizarse e incluir los aspectos "
            "requeridos por el Capítulo F.2, el Código de Prácticas Estándar para "
            "Estructuras de Acero ICONTEC, y los requisitos aplicables de F.3.1.4.1 "
            "y F.3.1.4.2, así como los siguientes, cuando sean aplicables: (1) "
            "localización de pernos pretensionados; (2) sitios donde las platinas "
            "de respaldo deben ser removidas; (3) sitios donde se requieren filetes "
            "de soldadura suplementarios cuando pueda dejarse instalada la platina "
            "de respaldo; (4) sitios donde se requieren filetes de soldadura para "
            "reforzar soldaduras acanaladas, o donde se necesitan para mejorar la "
            "geometría de la conexión; (5) sitios donde deben removerse las "
            "extensiones de soldadura; (6) juntas o grupos de juntas en los que se "
            "requiera un orden específico de ensamble, secuencia de soldadura, "
            "técnica de soldadura u otras precauciones especiales.\n"
            "F.3.9.1.3 Planos de fabricación y montaje para construcción compuesta "
            "— los planos de fabricación y montaje para los componentes de acero de "
            "construcción compuesta acero-concreto deben satisfacer los requisitos "
            "de F.3.9.1.1 y F.3.9.1.2, y también los requisitos de F.3.1.4.3.\n\n"
            "F.3.9.2 — FABRICACIÓN Y MONTAJE.\n"
            "F.3.9.2.1 Zona protegida — cuando una zona sea denominada como "
            "protegida en estas provisiones debe cumplir con lo siguiente: (1) las "
            "discontinuidades creadas por la fabricación o montaje, tales como "
            "soldaduras provisionales, ayudas de montaje y corte con soplete, deben "
            "ser reparadas; (2) no se permite la colocación de conectores de "
            "cortante soldados ni fijaciones de lámina colaborante que penetren en "
            "la aleta de la viga dentro de la zona protegida — solo se permite la "
            "fijación del tablero metálico mediante soldaduras de tapón; (3) las "
            "fijaciones de accesorios para fachadas, particiones, ductos, y "
            "tuberías soldadas o pernadas, con pernos autoperforantes o disparados, "
            "no se pueden colocar dentro de la zona protegida.\n"
            "F.3.9.2.2 Uniones pernadas — deben satisfacer los requisitos de "
            "F.3.4.2.2.\n"
            "F.3.9.2.3 Uniones soldadas — las soldaduras y conexiones soldadas deben "
            "cumplir con las especificaciones AWS D1.1 y AWS D1.8. Las extensiones "
            "de soldadura deben estar de acuerdo con el numeral 6.10 de AWS D1.1, "
            "excepto que en las soldaduras de los bordes externos de placas de "
            "continuidad a las columnas no se requiere remover las extensiones de "
            "soldadura a menos de 6 mm del borde de una placa de continuidad. Las "
            "especificaciones AWS D1.8 deben aplicarse tanto a soldaduras de taller "
            "como de campo.\n"
            "F.3.9.2.4 Placas de continuidad y atiesadores — las esquinas de "
            "placas de continuidad y los atiesadores colocados en el alma de "
            "perfiles laminados deben detallarse de acuerdo con AWS D1.8 numeral "
            "4.1."
        ),
    },
    {
        "id": "NSR10-F-F_3_10_1_a_F_3_10_2",
        "seccion": "F.3.10.1 a F.3.10.2 (Control de calidad — alcance, inspección de soldaduras: visual y ensayos no destructivos)",
        "titulo": (
            "Alcance del plan de calidad del SRS (según F.2.14 + este numeral). "
            "Inspección visual de soldaduras (antes/durante/después de soldar, "
            "checklist completo AWS D1.8). Ensayos no destructivos requeridos: "
            "área k, soldaduras de penetración completa, desgarramiento lamelar, "
            "destijeres, reducción de porcentajes de ensayo por operario."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.10 — CONTROL DE CALIDAD Y SUPERVISIÓN TÉCNICA PARA ESTRUCTURAS "
            "DEL SISTEMA DE RESISTENCIA SÍSMICA — establece los requisitos para el "
            "control de calidad y supervisión técnica del SRS. Se deben cumplir "
            "todos los requisitos de F.2.14, excepto lo modificado específicamente "
            "en este numeral. Secciones: F.3.10.1 Alcance, F.3.10.2 Inspección de "
            "soldaduras, F.3.10.3 Inspección de pernos.\n\n"
            "F.3.10.1 — ALCANCE — los requisitos y las responsabilidades para el "
            "cumplimiento de un plan de calidad deben estar de acuerdo con este "
            "Reglamento (incluyendo el Título I) y las especificaciones dadas por "
            "el ingeniero estructural. Las inspecciones y ensayos necesarios para "
            "establecer que la construcción cumple con estas provisiones se deben "
            "incluir en un plan de calidad. Dicho plan de calidad debe incluir los "
            "ensayos e inspecciones mínimas, adicionales a los requeridos por el "
            "Capítulo F.2, que se presentan en esta sección.\n\n"
            "F.3.10.2 — INSPECCIÓN DE SOLDADURAS — deben cumplirse los requisitos "
            "de AWS D1.8, además de lo especificado en este numeral.\n"
            "F.3.10.2.1 Inspección visual — debe ser el método principal usado "
            "para confirmar que los procedimientos, los materiales y la mano de "
            "obra usados en la construcción corresponden con los especificados y "
            "aprobados para el proyecto. La inspección visual debe llevarse a cabo "
            "por personal calificado, de acuerdo con procedimientos escritos. Como "
            "mínimo debe incluir las siguientes actividades:\n"
            "(1) Inspección visual antes de soldar: (a) acondicionamiento de "
            "soldaduras acanaladas (preparación de la junta; dimensiones — "
            "alineamiento, abertura de raíz, hombro de la raíz, bisel; limpieza de "
            "superficies a soldar; puntos de soldadura — localización y calidad; "
            "platinas de respaldo y su acondicionamiento); (b) configuración y "
            "acabado de los agujeros de acceso; (c) acondicionamiento de filetes "
            "de soldadura (dimensiones — alineamiento, aberturas de raíz; limpieza "
            "de superficies a soldar; puntos de soldadura — localización y "
            "calidad).\n"
            "(2) Inspección visual durante la soldadura: (a) seguimiento al "
            "procedimiento de soldadura (parámetros del equipo, velocidad de "
            "avance, materiales de soldadura seleccionados, tipo y flujo de gas de "
            "protección, precalentamiento aplicado, temperatura entre pases "
            "min/máx, posición de soldadura adecuada, mezcla de metales de aporte "
            "según lo aprobado); (b) operarios de soldadura calificados; (c) "
            "control y manejo de consumibles de soldadura (empaque y conservación, "
            "temperatura de aplicación/manejo/condiciones de exposición: humedad, "
            "contaminación); (d) condiciones ambientales (velocidad de viento, "
            "lluvia y temperatura ambiente); (e) técnicas de soldadura (limpieza "
            "entre pases y final, control de tolerancias de cada pase, requisitos "
            "de calidad de cada pase); (f) revisión de fisuras en puntos de "
            "soldadura.\n"
            "(3) Inspección visual después de la aplicación de la soldadura: (a) "
            "limpieza de la soldadura; (b) identificación legible del operario; "
            "(c) verificación del tamaño, longitud y localización de la soldadura; "
            "(d) inspección visual de las soldaduras según criterios de "
            "aceptación: no existencia de fisuras, fusión adecuada entre soldadura "
            "y metal base, tamaño de cráteres, perfil, tamaño, socavación, "
            "porosidad; (e) localización de filetes de refuerzo; (f) retiro y "
            "acabado de placas de respaldo y extensiones de soldadura (si se "
            "requieren); (g) reparaciones, si se requieren.\n"
            "F.3.10.2.2 Inspección con ensayos no destructivos — de acuerdo con: "
            "(1) Procedimientos: (a) ensayos de ultrasonido — según AWS D1.1 "
            "vigentes; (b) ensayos de partículas magnéticas — según AWS D1.1 "
            "vigentes. (2) Ensayos no destructivos requeridos: (a) Área \"k\" — "
            "cuando se realicen soldaduras de placas de enchape, placas de "
            "continuidad o atiesadores en el área \"k\", ensayos de partículas "
            "magnéticas para detectar fisuras hasta 75 mm de la soldadura; (b) "
            "Soldaduras acanaladas de penetración completa — 100% de ensayo de "
            "ultrasonido en soldaduras acanaladas de penetración completa en "
            "materiales de espesor >=8mm; en espesores <8mm, ensayos radiográficos; "
            "ensayos de partículas magnéticas al 25% de las soldaduras "
            "viga-columna acanaladas de penetración completa; (c) Desgarramiento "
            "lamelar y laminaciones en el material base — en materiales de base "
            ">38mm con cargas de tensión perpendiculares a la laminación, para "
            "juntas en T y en esquina con materiales >19mm, con soldaduras "
            "acanaladas de penetración completa, ensayos de ultrasonido para "
            "detectar discontinuidades por detrás/adyacentes a la línea de fusión; "
            "cualquier discontinuidad hasta t/4 de la superficie evaluada según "
            "AWS D1.1 tabla 6.2, t=espesor de la pieza sometida a deformaciones a "
            "través del espesor; (d) Destijeres de vigas y agujeros de acceso — en "
            "conexiones/empalmes soldados con destijeres o agujeros de acceso por "
            "corte, ensayos de partículas magnéticas o tintas penetrantes cuando "
            "el espesor de la aleta >38mm (laminados) o alma >38mm (armados); (e) "
            "Reparaciones en vigas de sección reducida — ensayos de partículas "
            "magnéticas en soldaduras y áreas adyacentes a la rótula plástica "
            "reparadas con soldadura, o metal base si se removieron "
            "protuberancias con pulidora; (f) Sitios de remoción de extensiones de "
            "soldadura — ensayos de partículas magnéticas en terminación de "
            "soldaduras a las que se retiró la extensión, excepto placas de "
            "continuidad; (g) Reducción del porcentaje de ensayos de ultrasonido y "
            "radiográficos — puede reducirse a 25% para un operario con menos del "
            "5% de rechazos (en soldaduras continuas, cada 150mm se considera una "
            "soldadura); (h) Reducción del porcentaje de partículas magnéticas — "
            "puede reducirse a 10% con las mismas condiciones; esta reducción no "
            "aplica en el área \"k\", reparaciones, remoción de respaldos/"
            "extensiones y agujeros de acceso. (3) Documentación — todos los "
            "ensayos no destructivos deben estar documentados e identificados por "
            "soldadura, marca y ubicación en la pieza y en la estructura."
        ),
    },
    {
        "id": "NSR10-F-F_3_10_3_inspeccion_pernos",
        "seccion": "F.3.10.3 (Inspección de pernos)",
        "titulo": (
            "Inspección de pernos del SRS: verificación antes/durante/después del "
            "empernado (selección, procedimiento, pretensionamiento según "
            "F.2.10.3.1, orden de apriete desde el punto de mayor rigidez), "
            "documentación de aceptación."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.10.3 — INSPECCIÓN DE PERNOS — el principal método para confirmar "
            "que los procedimientos, materiales y mano de obra utilizada en la "
            "construcción cumple con lo especificado para el proyecto será la "
            "observación de las operaciones de empernado. Como mínimo deben "
            "revisarse los siguientes conceptos:\n"
            "(1) Inspección antes del empernado: (a) selección correcta de los "
            "pernos especificados para la unión; (b) selección del procedimiento "
            "de empernado adecuado para la junta; (c) correcta fabricación de los "
            "elementos de la conexión, incluido el tipo de preparación de "
            "superficie; (d) ensayos de calificación de procedimiento de "
            "empernado; (e) almacenamiento adecuado de pernos, tuercas, y "
            "arandelas en caso de requerirse.\n"
            "(2) Inspección durante el empernado: (a) correcta colocación de los "
            "pernos, y las arandelas si se requieren, en todos los agujeros; (b) "
            "verificación de apriete inicial de los pernos; (c) garantía de la no "
            "rotación de uno de los componentes del perno mediante una llave de "
            "tuercas; (d) verificación del pretensionamiento para cumplir con lo "
            "especificado en F.2.10.3.1, de acuerdo con el método de "
            "tensionamiento utilizado; (e) verificación de que los pernos sean "
            "apretados desde el punto de mayor rigidez de la junta hacia los "
            "bordes libres.\n"
            "(3) Inspección después del empernado: (a) documentar las conexiones "
            "aceptadas o rechazadas."
        ),
    },
    {
        "id": "NSR10-F-F_3_11_1_precalificacion",
        "seccion": "F.3.11.1 (Precalificación de conexiones viga-columna y vínculo-columna — alcance, bases, requisitos de ensayo, 8 variables de precalificación, registro)",
        "titulo": (
            "Precalificación de conexiones completa: alcance (PRM-DES/DMO, "
            "vínculo-columna PAE), autorización por ANSI/AISC 358 o CASACRS, "
            "requisitos del ensayo, 8 categorías de variables de precalificación "
            "(viga/vínculo, columna, relaciones viga-columna, placas de "
            "continuidad, soldaduras, pernos, fabricación, otros detalles), "
            "procedimiento de diseño y registro de calificación."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.11 — ENSAYOS PARA CALIFICACIÓN DE CONEXIONES — establece los "
            "requisitos para la calificación de conexiones mediante ensayos. "
            "Secciones: F.3.11.1 Precalificación de conexiones viga-columna y "
            "vínculo-columna, F.3.11.2 Ensayos cíclicos de calificación de "
            "conexiones viga-columna y vínculo-columna, F.3.11.3 Ensayos cíclicos "
            "de calificación de riostras de pandeo restringido.\n\n"
            "F.3.11.1 — PRECALIFICACIÓN DE CONEXIONES VIGA-COLUMNA Y "
            "VÍNCULO-COLUMNA.\n"
            "F.3.11.1.1 Alcance — contiene los requisitos mínimos para la "
            "precalificación de las conexiones resistentes a momento viga-columna "
            "en pórticos resistentes a momento con capacidad especial y moderada "
            "de disipación de energía, y de las conexiones vínculo-columna en "
            "pórticos arriostrados excéntricamente. Se permite utilizar "
            "conexiones precalificadas que estén dentro de los límites aplicados "
            "en los ensayos de precalificación, sin necesidad de pruebas cíclicas "
            "de calificación adicionales. Cuando los límites de precalificación o "
            "requisitos de diseño para conexiones precalificadas contradigan los "
            "requisitos de estas provisiones, gobernarán los requisitos de la "
            "conexión precalificada.\n"
            "F.3.11.1.2 Requisitos generales.\n"
            "F.3.10.1.2.1 Bases para precalificación — la precalificación de la "
            "conexión se debe basar en los datos de los ensayos descritos en "
            "F.3.10.1.3, soportados mediante estudios analíticos y modelos de "
            "diseño. Las evidencias de los ensayos deben ser suficientes para "
            "garantizar que la conexión puede soportar el ángulo de deriva de "
            "entrepiso requerido para PRM-DES y PRM-DMO, o lo requerido para el "
            "ángulo de rotación del vínculo en sistemas PAE, sobre una base "
            "consistente y confiable, dentro de los límites especificados de "
            "precalificación. Deben ser identificados todos los estados límite "
            "aplicables a la conexión que afecten la rigidez, la resistencia y la "
            "capacidad de deformación de la conexión y el sistema de resistencia "
            "sísmica. Lo anterior incluye estados límite de fractura, de "
            "estabilidad y todos los otros estados límite pertinentes para la "
            "conexión bajo consideración. Los efectos de las variables de diseño "
            "se listan en la sección F.3.10.1.4.\n"
            "F.3.10.1.2.2 Autorización de la precalificación — podrán utilizarse "
            "las conexiones precalificadas del Estándar ANSI/AISC 358 "
            "\"Prequalified Connections for Special and Intermediate Steel Moment "
            "Frames for Seismic Applications\", o más reciente. En su defecto, la "
            "Comisión Asesora Permanente para el Régimen de Construcciones Sismo "
            "Resistentes será la responsable de aprobar la precalificación de una "
            "conexión y sus límites asociados.\n"
            "F.3.11.1.3 Requisitos del ensayo — los datos utilizados para "
            "sustentar la precalificación de la conexión se deben basar en "
            "ensayos realizados de acuerdo con F.3.10.2. Se debe realizar un "
            "suficiente número de ensayos en especímenes diferentes para "
            "demostrar que la conexión tiene la capacidad y confiabilidad "
            "suficientes para incursionar en la deriva de entrepiso requerida "
            "para pórticos resistentes a momentos con disipación de energía "
            "especial y moderada, o el ángulo de rotación del vínculo requerido "
            "para sistemas PAE, cuando el vínculo sea adyacente a las columnas. "
            "Los límites en las dimensiones de los miembros para precalificación "
            "no serán mayores que los especificados en F.3.10.2.5.2.\n"
            "F.3.11.1.4 Variables de precalificación — para efectos de la "
            "precalificación deben ser considerados los efectos de las "
            "siguientes variables en las conexiones:\n"
            "(1) Parámetros de la viga o del vínculo: (a) forma de la sección "
            "transversal (ancho de aleta, cajón u otro); (b) método de "
            "fabricación del miembro (perfil laminado, ensamblado u otro); (c) "
            "peralte; (d) peso por unidad de longitud; (e) espesor de la aleta; "
            "(f) especificación del material; (g) relación luz/peralte (PRM) o "
            "longitud del vínculo (PAE); (h) relación ancho-espesor de los "
            "elementos de la sección; (i) arriostramiento lateral; (j) otros "
            "parámetros pertinentes a la conexión específica considerada.\n"
            "(2) Parámetros de la columna: (a) forma de la sección transversal; "
            "(b) método de fabricación; (c) peralte; (d) peso por unidad de "
            "longitud; (e) espesor de aleta; (f) especificación del material; (g) "
            "relación luz/peralte o longitud del vínculo; (h) relación "
            "ancho-espesor; (i) arriostramiento lateral; (j) orientación de la "
            "columna respecto a la viga o el vínculo (conectada a la aleta, al "
            "alma, aleta y alma, etc.); (k) otros parámetros pertinentes.\n"
            "(3) Relaciones viga (vínculo) - columna: (a) resistencia de la zona "
            "de panel; (b) detalles de las placas de enchape; (c) relación de "
            "momentos viga (vínculo) - columna.\n"
            "(4) Placas de continuidad: (a) identificación de condiciones bajo "
            "las cuales se requieren; (b) espesores, anchos y longitudes; (c) "
            "detalles de unión al alma y a las aletas.\n"
            "(5) Soldaduras: (a) localización, longitud (incluyendo retornos), "
            "tipo (penetración completa, filete, tapón, penetración parcial u "
            "otra), y cualquier refuerzo o contorno requerido; (b) resistencia y "
            "tenacidad del metal de aporte; (c) detalles y tratamiento de las "
            "soldaduras o de las placas de respaldo y extensiones; (d) agujeros "
            "de acceso de soldaduras: dimensiones, geometría y acabado; (e) "
            "controles de calidad adicionales a los especificados en F.3.1.17.\n"
            "(6) Pernos: (a) diámetro del perno; (b) grado del perno (ASTM A325, "
            "A490, otro); (c) requisitos de instalación (pretensionado, apriete "
            "normal, otro); (d) tipo de perforación (estándar, agrandadas, "
            "ranura corta, ranura larga, otra); (e) método de fabricación de la "
            "perforación (taladrado, punzonado, sub-punzonado y rimado, otro); "
            "(f) otros parámetros pertinentes.\n"
            "(7) Fabricación — todos los parámetros pertinentes que excedan los "
            "requisitos del Título F o AWS: (a) rugosidad de la superficie en "
            "cortes por fusión o bordes pulidos; (b) tolerancias de corte; (c) "
            "refuerzo o perfil de la soldadura; (d) presencia de agujeros de "
            "pernos o soldaduras para accesorios.\n"
            "(8) Detalles adicionales de la conexión — todos los parámetros "
            "pertinentes a la conexión considerada.\n"
            "F.3.11.1.5 Procedimiento de diseño — debe presentarse un "
            "procedimiento de diseño de la conexión, completo y detallado, "
            "aplicando todos los estados límite dentro de los parámetros de "
            "precalificación.\n"
            "F.3.11.1.6 Registro de precalificación — una conexión precalificada "
            "debe suministrarse con un registro de calificación escrito que "
            "incluya: (1) descripción general de la conexión precalificada con "
            "gráficas que identifiquen claramente los aspectos relevantes y los "
            "componentes de la conexión; (2) descripción del comportamiento "
            "esperado de la conexión en el rango elástico e inelástico, "
            "localización de la zona inelástica y una descripción de los estados "
            "límites que controlan la resistencia y la capacidad de deformación "
            "de la conexión; (3) listado de los sistemas para los cuales la "
            "conexión está precalificada: pórticos resistentes a momento con "
            "capacidad especial o moderada de disipación de energía o pórticos "
            "arriostrados excéntricamente; (4) listado de los límites para todas "
            "las variables de calificación enunciadas en F.3.10.1.4; (5) listado "
            "de las soldaduras de demanda crítica; (6) definición de la región "
            "de la conexión que debe ser considerada como zona protegida; (7) "
            "procedimiento detallado de diseño de la conexión, tal como se "
            "requiere en F.3.10.1.5; (8) listado de referencias o reportes de "
            "ensayos, reportes de investigación u otras publicaciones que "
            "presenten las bases para la precalificación; (9) resumen de "
            "procedimientos de control de calidad requeridos."
        ),
    },
    {
        "id": "NSR10-F-F_3_11_2_ensayos_ciclicos_viga_columna",
        "seccion": "F.3.11.2 (Ensayos cíclicos de calificación de conexiones viga-columna y vínculo-columna — completo)",
        "titulo": (
            "Ensayos cíclicos de calificación viga-columna/vínculo-columna "
            "completo: requisitos del conjunto de prueba, tamaño de miembros "
            "(≥90% peralte, ≥75% peso), secuencias de carga completas para PRM "
            "(θ hasta 0.04+ rad) y PAE (γtotal hasta 0.09 rad), requisitos de "
            "materiales/soldaduras/pernos, informe del ensayo, criterio de "
            "aceptación."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.11.2 — ENSAYOS CÍCLICOS DE CALIFICACIÓN DE CONEXIONES "
            "VIGA-COLUMNA Y VÍNCULO-COLUMNA.\n"
            "F.3.11.2.1 Alcance y propósito — incluye los requisitos para ensayos "
            "cíclicos de calificación de conexiones viga-columna para PRM-DES y "
            "PRM-DMO, y conexiones vínculo-columna en PAE. El propósito es "
            "proporcionar evidencia de que la conexión cumple con los requisitos "
            "de resistencia y deriva de piso o ángulo de rotación del vínculo de "
            "este Capítulo. Esta sección proporciona las recomendaciones mínimas "
            "para condiciones simplificadas de ensayo.\n"
            "F.3.11.2.2 Símbolos — θ=ángulo de deriva; γtotal=ángulo total de "
            "rotación del vínculo.\n"
            "F.3.11.2.3 Requisitos del conjunto de prueba — debe reproducir lo "
            "más cercanamente posible las condiciones que ocurrirán en el "
            "prototipo bajo solicitaciones sísmicas: (1) el espécimen consistirá "
            "por lo menos de una sola columna con vigas o vínculos conectados a "
            "uno o ambos lados de la columna; (2) los puntos de inflexión en el "
            "conjunto de prueba deben coincidir aproximadamente con los del "
            "prototipo bajo acción sísmica; (3) se permite arriostramiento "
            "lateral del conjunto cerca de los puntos de aplicación de carga o "
            "reacciones, cuando se requiera para estabilidad lateral; no se "
            "permite el uso de arriostramientos adicionales a menos que "
            "reproduzcan condiciones del prototipo.\n"
            "F.3.11.2.4 Variables esenciales del ensayo — el espécimen debe "
            "reproducir lo más cercanamente posible el diseño, detallado, "
            "aspectos constructivos y propiedades de los materiales del "
            "prototipo. F.3.11.2.4.1 Fuentes de rotación inelástica — debe "
            "desarrollarse mediante la acción inelástica de los mismos miembros "
            "y elementos de conexión que en el prototipo (viga/vínculo, zona de "
            "panel, columna fuera de zona de panel, o elementos de conexión); la "
            "porción de rotación inelástica de cada componente del espécimen "
            "debe estar dentro del 25% de la prevista para el correspondiente "
            "elemento del prototipo. F.3.11.2.4.2 Tamaño de los miembros — el "
            "peralte de la viga/vínculo del ensayo no debe ser menor del 90% del "
            "prototipo; peso por unidad de longitud no menor del 75% del "
            "prototipo. El tamaño de la columna debe representar apropiadamente "
            "la acción inelástica en la columna (F.3.11.2.5.1), con peralte no "
            "menor del 90% del prototipo. Se permite extrapolación fuera de "
            "estos límites si lo considera el ingeniero estructural y lo aprueba "
            "la Comisión Asesora Permanente del Régimen Sismo Resistente. "
            "F.3.11.2.4.3 Detalles de la conexión — deben representar lo más "
            "cercanamente posible los del prototipo; los elementos de conexión "
            "deben ser una representación a escala real, para los tamaños de "
            "miembros ensayados. F.3.11.2.4.4 Placas de continuidad — deben "
            "representar, lo más cercanamente posible, tamaños y detalles del "
            "prototipo. F.3.11.2.4.5 Resistencia del material — cada miembro o "
            "elemento de conexión que suministre rotación inelástica por "
            "fluencia debe cumplir: (1) esfuerzo de fluencia determinado "
            "mediante ensayos de los materiales reales usados en el espécimen "
            "(F.3.11.2.8) — no se permite usar valores de certificados de "
            "calidad de la acería; (2) esfuerzo de fluencia de la viga no debe "
            "estar más del 15% por debajo de Ry*Fy para el grado de acero del "
            "prototipo; esfuerzos de fluencia de columnas y elementos de "
            "conexión no deben estar más del 15% por encima ni por debajo de "
            "Ry*Fy — Ry*Fy se determina según F.3.1.5.2. F.3.11.2.4.6 "
            "Soldaduras: (1) siguiendo estrictamente procedimientos AWS D1.1, "
            "dentro de parámetros del fabricante de metal de aporte; resistencia "
            "a tensión y tenacidad Charpy con ranura en V del conjunto de "
            "prueba según F.3.11.2.8.3; no usar valores de certificado del "
            "fabricante a menos que cumplan F.3.1.17; (2) resistencia mínima a "
            "tensión del metal de aporte igual a la del prototipo, la ensayada "
            "no debe exceder en más de 125 MPa la del prototipo; (3) tenacidad "
            "mínima Charpy del metal de aporte del ensayo no debe exceder la "
            "del prototipo, ni ser más del 50% ni 34kJ mayor (el que sea "
            "mayor) que la del prototipo; (4) posiciones de ejecución iguales "
            "que en el prototipo; (5) detalles de platinas de respaldo, "
            "extensión de soldadura, agujeros de acceso iguales a los del "
            "prototipo, no removerse a menos que se remuevan en el prototipo; "
            "(6) métodos de inspección y ensayos no destructivos iguales a los "
            "del prototipo. F.3.11.2.4.7 Pernos — las partes empernadas del "
            "espécimen deben reproducir estrechamente el prototipo: (1) grado "
            "del perno (ASTM A325/A325M/A490/A490M/F1852) igual al usado en el "
            "prototipo, excepto A325 reemplazables por F1852 y viceversa, no "
            "reemplazar A325 por SAE Gr 5 ni A490 por SAE Gr 8; (2) tipo y "
            "orientación de agujeros iguales; (3) método de perforación igual "
            "cuando deba desarrollarse rotación inelástica por fluencia o "
            "deslizamiento en la parte empernada; (4) mismo grado de apriete "
            "(pretensionado u otro) y preparación de superficie.\n"
            "F.3.11.2.5 Historia de carga.\n"
            "F.3.11.2.5.1 Requisitos generales — el espécimen debe estar sujeto "
            "a cargas cíclicas acordes con F.3.11.2.5.2 para conexiones "
            "viga-columna en PRM, y F.3.11.2.5.3 para conexiones vínculo-columna "
            "en PAE. Secuencias diferentes se permiten si son equivalentes o "
            "más severas.\n"
            "F.3.11.2.5.2 Secuencia de carga para conexiones viga-columna "
            "resistentes a momento — controlando el ángulo de deriva θ: 6 "
            "ciclos a θ=0.00375 rad; 6 ciclos a θ=0.005; 6 ciclos a θ=0.0075; 4 "
            "ciclos a θ=0.01; 2 ciclos a θ=0.015; 2 ciclos a θ=0.02; 2 ciclos a "
            "θ=0.03; 2 ciclos a θ=0.04. Continuar cargando a incrementos de "
            "θ=0.01 rad, con dos ciclos de carga en cada paso.\n"
            "F.3.11.2.5.3 Secuencia de carga para conexiones vínculo-columna "
            "— controlando el ángulo de rotación del vínculo γtotal: 6 ciclos a "
            "γtotal=0.00375; 6 ciclos a 0.005; 6 ciclos a 0.0075; 6 ciclos a "
            "0.01; 4 ciclos a 0.015; 4 ciclos a 0.02; 2 ciclos a 0.03; 1 ciclo a "
            "0.04; 1 ciclo a 0.05; 1 ciclo a 0.07; 1 ciclo a 0.09. Continuar "
            "cargando con incrementos de γtotal=0.02 rad, con un ciclo de carga "
            "en cada paso.\n"
            "F.3.11.2.6 Instrumentación — suficiente para permitir medición o "
            "cálculo de las cantidades listadas en F.3.11.2.8.\n"
            "F.3.11.2.7 Requisitos para el ensayo de los materiales.\n"
            "F.3.11.2.7.1 Ensayos de tensión del acero — sobre muestras de "
            "acero tomadas del material adyacente a cada espécimen; resultados "
            "de certificados de calidad se reportan pero no reemplazan los "
            "ensayos del espécimen; realizados/reportados para: (1) aletas y "
            "almas de vigas y columnas en lugares estándar; (2) cualquier "
            "elemento de conexión que desarrolle rotación inelástica por "
            "fluencia.\n"
            "F.3.11.2.7.2 Métodos para ensayos de tensión en el acero — según "
            "ASTM A6/A6M, A370 y E8, con excepciones: (1) esfuerzo de fluencia "
            "basado en definición de resistencia a la fluencia ASTM A370, "
            "método de la paralela a deformación unitaria de 0.002; (2) "
            "velocidad de carga debe reproducir tan cerca como sea posible la "
            "usada en el espécimen de prueba.\n"
            "F.3.11.2.7.3 Requisitos para ensayos del metal de soldadura — "
            "resistencia a tensión y tenacidad Charpy con ranura en V del "
            "conjunto de prueba se determina por ensayos de materiales según "
            "F.2.3.17. Resistencias/tenacidades reportadas por certificado del "
            "fabricante no se usan, a menos que cumplan F.2.3.17. Si el "
            "procedimiento de soldadura del espécimen está dentro de ±0.8kJ/mm "
            "del procedimiento de la placa de ensayo, se usa un solo ensayo.\n"
            "F.3.11.2.8 Requisitos para el informe del ensayo — para cada "
            "espécimen debe prepararse un informe escrito documentando "
            "completamente todas las características clave y resultados: (1) "
            "dibujo o descripción clara del conjunto, incluyendo dimensiones "
            "esenciales, condiciones de borde en puntos de carga y reacción, "
            "localización de riostras laterales; (2) dibujo del detalle de la "
            "conexión con tamaños de miembros, grados de acero, tamaños de "
            "elementos de conexión, detalles de soldadura incluyendo metal de "
            "aporte, tamaño y localización de agujeros de pernos, tamaño y "
            "grado de pernos, y demás detalles pertinentes; (3) listado de "
            "otras variables esenciales (F.3.11.2.4); (4) listado o gráfica de "
            "carga aplicada o historia de desplazamientos; (5) listado de "
            "soldaduras de demanda crítica; (6) definición de regiones de "
            "conexión que comprenden zonas protegidas; (7) gráfica de carga "
            "aplicada vs. desplazamiento del espécimen, medido en el punto de "
            "aplicación de carga o cerca; deben identificarse claramente cargas "
            "y desplazamientos medidos; (8) gráfica del momento de la viga en "
            "función de la deriva para conexiones viga-columna resistentes a "
            "momento; o de la fuerza cortante del vínculo contra el ángulo de "
            "rotación para conexiones vínculo-columna — calculadas respecto al "
            "eje de la columna; (9) ángulo de deriva y rotación inelástica "
            "total desarrollada por el espécimen, identificando componentes que "
            "contribuyen a la rotación inelástica total (fluencia o "
            "deslizamiento); (10) listado cronológico de observaciones "
            "significativas (fluencia, deslizamiento, inestabilidad, fractura "
            "de cualquier parte); (11) modo que controla la falla, con razón "
            "indicada claramente si se finalizó antes de la falla; (12) "
            "resultados de ensayos del material especificados en F.3.11.2.7; "
            "(13) procedimientos de soldadura y reportes de la inspección de "
            "la misma.\n"
            "F.3.11.2.9 Criterio de aceptación — el espécimen debe satisfacer "
            "la resistencia y el ángulo de deriva de piso o el ángulo de "
            "rotación del vínculo. Debe sostener el ángulo de deriva o "
            "rotación para un mínimo de un ciclo completo de carga."
        ),
    },
    {
        "id": "NSR10-F-F_3_11_3_ensayos_ciclicos_riostras",
        "seccion": "F.3.11.3 (Ensayos cíclicos de calificación de riostras de pandeo restringido — completo)",
        "titulo": (
            "Ensayos cíclicos de riostras de pandeo restringido completo: ensayo "
            "de conjunto (7 requisitos) y de riostra sola (similitud con "
            "prototipo, materiales del núcleo, historia de carga hasta Δb=2Δbm y "
            "200 veces la deformación de fluencia), criterio de aceptación "
            "(relación compresión/tensión ≤1.3)."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.11.3 — ENSAYOS CÍCLICOS DE CALIFICACIÓN PARA ARRIOSTRAMIENTOS "
            "RESTRINGIDOS AL PANDEO.\n"
            "F.3.11.3.1 Alcance — incluye los requisitos para ensayos cíclicos "
            "de calificación de riostras restringidas al pandeo individuales o "
            "en su conjunto. El propósito del ensayo de riostras solas es "
            "proporcionar evidencia de que el arriostramiento restringido al "
            "pandeo satisface los requisitos de resistencia y deformación "
            "inelástica del Capítulo F.3; también permite la determinación de "
            "las fuerzas máximas en la riostra para efectos del diseño de los "
            "elementos adyacentes. El propósito del ensayo del conjunto es "
            "proporcionar evidencia de que el diseño de la riostra puede "
            "soportar satisfactoriamente las demandas de deformación y "
            "rotación asociadas con el diseño. Además, el ensayo del conjunto "
            "procura demostrar que el comportamiento histerético de la riostra "
            "dentro del conjunto es consistente con el de los elementos "
            "individuales de la riostra con ensayo uniaxial.\n"
            "F.3.11.3.2 Símbolos — Δb=cantidad de deformación usada para el "
            "control de cargas del espécimen (rotación total del extremo de la "
            "riostra para el espécimen del conjunto; deformación axial total "
            "de la riostra para el espécimen de la riostra); Δbm=valor de Δb "
            "correspondiente a la deriva de piso de diseño; Δby=valor de Δb en "
            "la primera fluencia significativa del espécimen de prueba.\n"
            "F.3.11.3.3 Espécimen de ensayo del conjunto — debe satisfacer: (1) "
            "el mecanismo para soportar las rotaciones inelásticas del "
            "conjunto debe ser el mismo que para el prototipo; las demandas de "
            "rotación y deformación en el conjunto deben ser iguales o "
            "mayores que en el prototipo; (2) la resistencia axial de "
            "fluencia del núcleo de acero, Pysc, de la riostra en el espécimen "
            "no debe ser menor que la del prototipo, ambas basadas en el área "
            "del núcleo Asc, multiplicada por la resistencia a la fluencia "
            "determinada en un cupón de ensayo; (3) la sección transversal y "
            "la orientación de la proyección del núcleo de acero deben ser "
            "las mismas que en el prototipo; (4) debe usarse la misma "
            "metodología de diseño documentada para el conjunto y el "
            "prototipo, para permitir la comparación de demandas de rotación "
            "y deformación — en el cálculo de estabilidad, vigas, columnas y "
            "placas que conectan el núcleo se consideran parte del sistema; "
            "(5) márgenes de seguridad calculados para el diseño de la "
            "conexión del prototipo, la estabilidad de la proyección del "
            "núcleo, el pandeo general, y otros detalles constructivos "
            "relevantes del prototipo, deben ser iguales o mayores que los "
            "del ensayo del conjunto; (6) el arriostramiento lateral del "
            "ensayo debe replicar el arriostramiento lateral en el prototipo; "
            "(7) el espécimen de ensayo del conjunto y el prototipo deben ser "
            "fabricados de acuerdo con los mismos procesos y procedimientos "
            "de calidad.\n"
            "F.3.11.3.4 Espécimen de ensayo de la riostra — debe reproducir "
            "tan cercanamente como sea posible el diseño, el detallado, los "
            "aspectos constructivos, y las propiedades del material del "
            "prototipo.\n"
            "F.3.11.3.4.1 Diseño del espécimen — misma metodología documentada "
            "para el ensayo y el prototipo. Los cálculos deben demostrar como "
            "mínimo: (1) el factor de seguridad calculado para la estabilidad "
            "contra pandeo general del prototipo debe ser igual o mayor que el "
            "del espécimen de prueba; (2) los factores de seguridad del "
            "espécimen y el prototipo deben tomar en cuenta las diferencias en "
            "las propiedades del material, incluyendo esfuerzos de fluencia y "
            "último, deformación última, y tenacidad.\n"
            "F.3.11.3.4.2 Fabricación — el espécimen de la riostra y el "
            "prototipo deben ser fabricados de acuerdo con los mismos procesos "
            "y procedimientos de calidad.\n"
            "F.3.11.3.4.3 Similitud del espécimen de ensayo y el prototipo — "
            "debe cumplir: (1) la sección transversal y la orientación del "
            "núcleo de acero deben ser las mismas que en el prototipo; (2) la "
            "resistencia a la fluencia axial del núcleo de acero, Pysc, del "
            "espécimen de la riostra no debe variar más del 50% con respecto "
            "al prototipo, con ambas resistencias basadas en el área del "
            "núcleo Asc, multiplicada por la resistencia a la fluencia "
            "determinada en un cupón de ensayo; (3) el material y el método "
            "de separación entre el núcleo de acero y el mecanismo de "
            "restricción al pandeo en el espécimen deben ser los mismos que "
            "en el prototipo.\n"
            "F.3.11.3.4.4 Detalles de la conexión — deben representar los del "
            "prototipo tan cercanamente como sea posible.\n"
            "F.3.11.3.4.5 Materiales: (1) núcleo de acero — debe satisfacer: "
            "(a) esfuerzo de fluencia mínimo especificado igual al del "
            "prototipo; (b) esfuerzo de fluencia medido en el material del "
            "núcleo del espécimen de la riostra debe ser al menos 90% que el "
            "del prototipo determinado en cupones de ensayo; (c) esfuerzo y "
            "deformación unitaria últimos mínimos especificados del núcleo de "
            "acero del espécimen de la riostra, no deben ser mayores que los "
            "del prototipo; (2) mecanismo de restricción del pandeo — los "
            "materiales usados deben ser los mismos utilizados en el "
            "prototipo.\n"
            "F.3.11.3.4.6 Conexiones — las uniones soldadas, pernadas y con "
            "pasadores del espécimen de la riostra deben replicar las del "
            "prototipo tan cerca como sea posible.\n"
            "F.3.11.3.5 Historia de cargas.\n"
            "F.3.11.3.5.1 Requisitos generales — sujeto a cargas cíclicas de "
            "acuerdo con F.3.11.3.6.2 y F.3.11.3.6.3. Se permiten incrementos "
            "adicionales más allá de los descritos en F.3.11.3.6.3. Cada ciclo "
            "debe incluir incursiones completas en la zona de tensión y "
            "compresión hasta la deformación prescrita.\n"
            "F.3.11.3.5.2 Control del ensayo — controlando el nivel de "
            "deformaciones axiales o rotacionales Δb impuestas al espécimen; "
            "alternativamente, la deformación rotacional máxima puede "
            "aplicarse y mantenerse si se sigue el protocolo de deformaciones "
            "axiales.\n"
            "F.3.11.3.5.3 Secuencia de carga — las cargas se aplican para "
            "producir las siguientes deformaciones (deformación axial del "
            "núcleo de acero para el espécimen de la riostra, y demanda de "
            "deformación rotacional para el espécimen del conjunto): (1) 2 "
            "ciclos a Δb=Δby; (2) 2 ciclos a Δb=0.5*Δbm; (3) 2 ciclos a "
            "Δb=Δbm; (4) 2 ciclos a Δb=1.5*Δbm; (5) 2 ciclos a Δb=2*Δbm; (6) "
            "ciclos completos adicionales a Δb=1.5*Δbm, según se requiera "
            "para que el espécimen de la riostra alcance una deformación "
            "axial inelástica acumulada de al menos 200 veces la deformación "
            "de fluencia (no se requiere para el espécimen de prueba del "
            "conjunto). La deriva de diseño de entrepiso no se puede tomar "
            "como menos de 0.01 veces la altura de piso para los propósitos "
            "de cálculo de Δbm. Se permiten otras secuencias de carga para "
            "calificar el espécimen cuando demuestren ser iguales o más "
            "severas en términos de la deformación inelástica máxima y "
            "acumulada.\n"
            "F.3.11.3.7 Instrumentación — debe suministrarse la suficiente "
            "instrumentación en el espécimen de prueba, tal que permita la "
            "medición o cálculos de las cantidades listadas en F.3.11.3.9.\n"
            "F.3.11.3.8 Requisitos del material de la prueba.\n"
            "F.3.11.3.8.1 Requisitos para ensayos de tensión — sobre muestras "
            "del mismo material usado para la fabricación del núcleo de "
            "acero; certificados de calidad se reportan pero no reemplazan "
            "los ensayos del espécimen; basados en pruebas según F.3.11.3.2 "
            "[referencia tal como aparece en el texto original].\n"
            "F.3.11.3.8.2 Métodos para ensayo de tensión — según ASTM A6, "
            "A370 y E8, con excepciones: (1) esfuerzo de fluencia reportado "
            "basado en definición de resistencia a la fluencia de ASTM A370, "
            "método de la paralela a deformación unitaria de 0.002; (2) "
            "velocidad de carga debe reproducir tan cercanamente como sea "
            "posible la usada en el espécimen de ensayo; (3) el cupón debe "
            "maquinarse de tal manera que su eje longitudinal sea paralelo al "
            "eje longitudinal del núcleo de acero.\n"
            "F.3.11.3.9 Requisitos del informe de la prueba — para cada "
            "espécimen debe elaborarse un informe que cumpla los requisitos "
            "de esta sección, documentando extensivamente todos los aspectos "
            "importantes y resultados: (1) dibujo o descripción clara del "
            "espécimen, incluyendo dimensiones importantes, condiciones de "
            "borde y cargas en puntos de reacción, localización de "
            "arriostramiento lateral si lo hay; (2) dibujo de los detalles de "
            "la conexión con dimensiones de miembros, grado de acero, "
            "medidas de elementos de conexión, detalles de soldadura "
            "incluyendo metal de aporte, sitio y localización de agujeros de "
            "pernos o pasadores, dimensiones y grado de los conectores, y "
            "cualquier otro detalle pertinente; (3) listado de otras "
            "variables esenciales listadas en F.3.11.3.4 y F.3.11.3.5, según "
            "sea apropiado; (4) listado o gráfica que muestre la historia de "
            "cargas o desplazamientos aplicados; (5) gráfica de cargas "
            "aplicadas en función de las deformaciones Δb, mostrando "
            "claramente el método utilizado para determinarlas, e "
            "identificando la ubicación donde fueron medidas cargas y "
            "deformaciones; (6) lista cronológica de observaciones "
            "significativas (fluencia, deslizamiento, inestabilidad, "
            "desplazamiento transversal a lo largo del espécimen, fractura en "
            "cualquier parte del espécimen y sus conexiones, según aplique); "
            "(7) resultados de ensayos de materiales especificados en "
            "F.3.11.3.8; (8) el control de calidad y plan de calidad usado "
            "para la fabricación del espécimen, incluyendo procedimientos de "
            "soldadura y reportes de la inspección de la misma. Se pueden "
            "incluir en el informe dibujos adicionales, datos y discusiones "
            "de los resultados del ensayo.\n"
            "F.3.11.3.10 Criterios de aceptación — debe realizarse por lo "
            "menos un ensayo del conjunto que satisfaga los requisitos de "
            "F.3.11.3.4. Debe realizarse por lo menos un ensayo de riostra "
            "que satisfaga los requisitos de F.3.11.3.5. Dentro del rango de "
            "protocolo requerido, todos los ensayos deben satisfacer: (1) la "
            "gráfica que muestre la carga aplicada vs. la historia de "
            "desplazamientos debe exhibir un comportamiento estable y "
            "repetitivo con incrementos de rigidez; (2) no debe haber "
            "fractura, inestabilidad en la riostra o falla de la conexión en "
            "el extremo de la riostra; (3) para ensayos de riostra, las "
            "fuerzas máximas de tensión y compresión no deben ser menores "
            "que la resistencia nominal del núcleo en cada ciclo para una "
            "deformación mayor que Δby; (4) para ensayos de riostra, la "
            "relación de la fuerza de compresión máxima y la fuerza de "
            "tensión máxima no debe ser mayor de 1.3, para una deformación "
            "mayor que Δby."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])
    print(f"Chunks a insertar: {len(CHUNKS)}")
    for c in CHUNKS:
        print(f"  {c['id']} ({c['seccion']}): {len(c['texto'])} chars")

    print("\nCargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
    textos = [c["texto"] for c in CHUNKS]
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print("\nSubiendo a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()
    print(f"OK: {len(rows)} chunks F.3.9-F.3.11 cargados con embedding. Capitulo F.3 completo.")


if __name__ == "__main__":
    main()
