"""
NSR-10 Titulo F, F.3.7 (Porticos Resistentes a Momentos Compuestos PRMC,
completo: DMI/DMO/DES/PR) + F.3.8 (Sistemas Arriostrados y Muros de
Cortante Compuestos, completo: PACC-DMI/DES, PAEC, MCC-DMI/DES, MCAC) --
reingesta verbatim real, segundo batch de la decision del usuario
2026-08-27 de rehacer F.3.5-F.3.11.

Fuente: NSR-10-901-980.pdf (Drive, id 14q4ylyJYB9H1IdLrdZ0X0crekxxbajmm),
paginas internas F-268 a F-285. Leido visualmente pagina por pagina.

7 chunks single-topic, mismo patron que scripts anteriores de Titulo F.
Reemplaza el chunk viejo NSR10-F-F_3_7_PRMC (resumen de sesion anterior,
2842 caracteres) y los 2 chunks viejos F_3_8_arriostrados_compuestos y
F_3_8_muros_compuestos (2133 y 2748 caracteres) -- los 3 se borran en
este mismo flujo de trabajo tras verificar cobertura completa.

Uso: python _ingest_titulo_f_f37_a_f38.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "NSR-10 Título F — Estructuras Metálicas"

CHUNKS = [
    {
        "id": "NSR10-F-F_3_7_1_a_F_3_7_2",
        "seccion": "F.3.7.1 a F.3.7.2 (PRMC-DMI y PRMC-DMO — pórticos resistentes a momentos compuestos con capacidad mínima y moderada)",
        "titulo": (
            "Intro a F.3.7 (PRMC). PRMC-DMI: sin requisitos especiales, columnas "
            "compuestas/concreto reforzado + vigas de acero/embebidas/compuestas, "
            "conexiones TR. PRMC-DMO: deriva mínima 0.02 rad, resistencia conexión "
            "≥0.8Mp, Emh=2(1.1Ry·Mp,esp)/Lh, columnas C.10.13."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.7 — PÓRTICOS RESISTENTES A MOMENTOS COMPUESTOS (PRMC) — bases de "
            "diseño y requisitos de análisis, sistema, miembros y conexiones para "
            "PRMC-DMI, PRMC-DMO, PRMC-DES y parcialmente restringidos (PRMC-PR).\n\n"
            "F.3.7.1 — PÓRTICOS RESISTENTES A MOMENTOS COMPUESTOS CON CAPACIDAD DE "
            "ENERGÍA MÍNIMA (PRMC-DMI).\n"
            "F.3.7.1.1 Alcance — sistemas PRMC-DMI diseñarse según esta sección. "
            "Aplicable a pórticos resistentes a momentos con conexiones totalmente "
            "restringida (TR) que consten de columnas compuestas o de concreto "
            "reforzado y vigas bien sean de acero, embebidas en concreto, o "
            "compuestas.\n"
            "F.3.7.1.2 Bases de diseño — se espera que los PRMC-DMI diseñados según "
            "estas especificaciones suministren capacidad de deformación inelástica "
            "mínima en sus miembros y conexiones.\n"
            "F.3.7.1.3 Análisis — no se especifican requisitos especiales.\n"
            "F.3.7.1.4 Requisitos del sistema — no se especifican requisitos "
            "especiales.\n"
            "F.3.7.1.5 Miembros — no se especifican requisitos adicionales a los del "
            "Capítulo F.2 para miembros de acero o compuestos. Columnas de concreto "
            "reforzado cumplen el Título C, excluyendo C.21.\n"
            "F.3.7.1.6 Conexiones — totalmente restringidas (TR); diseñarse para las "
            "combinaciones de cargas aplicables de F.3.2.2 y F.3.2.3. Resistencias de "
            "diseño de conexiones viga-columna se determinan según F.2 y F.3.4.2.7.\n\n"
            "F.3.7.2 — PÓRTICOS RESISTENTES A MOMENTOS COMPUESTOS CON CAPACIDAD DE "
            "ENERGÍA MODERADA (PRMC-DMO).\n"
            "F.3.7.2.1 Alcance — sistemas PRMC-DMO, mismas columnas/vigas que "
            "PRMC-DMI.\n"
            "F.3.7.2.2 Bases de diseño — capacidad de deformación inelástica LIMITADA, "
            "a través de fluencia a flexión de vigas y columnas y fluencia a cortante "
            "en las zonas de panel de las columnas. El diseño de las conexiones "
            "viga-columna, incluyendo zona de panel, platinas de continuidad y "
            "diafragmas, debe basarse en ensayos de conexiones que garanticen el "
            "desempeño de F.3.7.2.6.2, y demostrar conformidad con F.3.7.2.6.3.\n"
            "F.3.7.2.3 Análisis — no se especifican requisitos especiales.\n"
            "F.3.7.2.4 Requisitos del sistema: F.3.7.2.4.1 Arriostramiento para "
            "estabilidad de vigas — arriostrarse según ductilidad moderada "
            "(F.3.4.1.2.1). Adicionalmente, a menos que ensayos indiquen otra cosa, "
            "los arriostramientos deben ubicarse cerca de fuerzas concentradas, "
            "cambios de sección transversal, y donde el análisis indique posible "
            "rótula plástica. Resistencia requerida del arriostramiento lateral "
            "adyacente a rótulas plásticas: F.3.4.1.2.3.\n"
            "F.3.7.2.5 Miembros: F.3.7.2.5.1 Requisitos básicos — vigas/columnas "
            "cumplen F.3.4.1.1 para ductilidad moderada. F.3.7.2.5.2 Aletas de "
            "vigas — sin cambios abruptos en zonas de rótulas plásticas; sin "
            "perforaciones/recortes salvo demostración por ensayos. F.3.7.2.5.3 "
            "Zonas protegidas — extremos de viga sujetos a deformaciones inelásticas, "
            "cumplen F.3.4.1.3; zonas de rótula plástica en PRMC-DMO tratadas como "
            "zona protegida; para conexiones sin reforzar, desde cara de columna "
            "hasta mitad del peralte de viga tras la rótula.\n"
            "F.3.7.2.6 Conexiones: F.3.7.2.6.1 Soldaduras de demanda crítica — no se "
            "requieren. F.3.7.2.6.2 Conexiones viga-columna: (1) ángulo de deriva de "
            "piso mínimo 0.02 rad; (2) resistencia medida a flexión en cara de "
            "columna >=0.8*Mp de la viga conectada, para 0.02 rad, donde Mp es la "
            "resistencia nominal a flexión de vigas de acero, embebidas o "
            "compuestas, satisfaciendo F.2.9. F.3.7.2.6.3 Validación de la conexión "
            "— por ensayos de la conexión, o cálculos justificados por modelos "
            "mecánicos y criterios de diseño para estados límite de sus componentes. "
            "F.3.7.2.6.4 Resistencia a cortante requerida — Vu con combinaciones del "
            "Título B incluyendo carga sísmica amplificada: "
            "Emh = 2*(1.1*Ry*Mp,esp) / Lh  (F.3.7.2-1), donde Mp,esp=resistencia a "
            "flexión plástica esperada de vigas de acero, embebidas o compuestas — "
            "para vigas embebidas o compuestas, se calcula usando distribución "
            "plástica de esfuerzos o el método de compatibilidad de deformaciones, "
            "con factores Ry apropiados; Lh=distancia entre rótulas plásticas, mm. "
            "Para vigas de acero, Mp,esp puede tomarse como Ry*Mp. F.3.7.2.6.5 "
            "Placas de continuidad y de diafragma — se pueden usar placas para "
            "diafragmas de conexión con columnas compuestas rellenas, interior o "
            "exterior; espesor >= espesor de aleta de viga; soldadas alrededor del "
            "perímetro de columna con penetración completa o filete por ambos lados, "
            "resistencia requerida >= resistencia de diseño del área de contacto de "
            "la placa con la columna; diafragmas internos con aberturas circulares "
            "suficientes para colocación del concreto. F.3.7.2.6.6 Empalmes de "
            "columna — adicional a F.3.4.2.5: con soldaduras acanaladas, de "
            "penetración completa; sin ellas, resistencia requerida a flexión >= "
            "resistencia nominal a flexión Mpcc de la columna compuesta menor; "
            "resistencia requerida a cortante del empalme del alma >= suma(Mpcc)/H; "
            "resistencia nominal a flexión de columnas compuestas satisface F.2.9 "
            "considerando la resistencia axial requerida Puc."
        ),
    },
    {
        "id": "NSR10-F-F_3_7_3_PRMC_DES",
        "seccion": "F.3.7.3 (Pórticos Resistentes a Momentos Compuestos con capacidad de energía especial PRMC-DES)",
        "titulo": (
            "PRMC-DES completo: relación de momentos ΣM*pcc/ΣM*p,esp>1, deriva "
            "mínima 0.04 rad, resistencia conexión ≥0.8Mp, vigas embebidas con "
            "recubrimiento≥50mm y estribos C.21.5.3, límite Ypna, arriostramiento "
            "ductilidad alta."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.7.3 — PÓRTICOS RESISTENTES A MOMENTOS COMPUESTOS CON CAPACIDAD DE "
            "ENERGÍA ESPECIAL (PRMC-DES).\n"
            "F.3.7.3.1 Alcance — columnas compuestas o de concreto reforzado, vigas "
            "de acero embebidas en concreto o compuestas.\n"
            "F.3.7.3.2 Bases de diseño — capacidad de deformación inelástica "
            "SIGNIFICATIVA a través de fluencia por flexión de vigas y fluencia "
            "limitada a cortante en zonas de panel de columnas. Excepto que se "
            "permita otra cosa, columnas diseñadas para ser más resistentes que las "
            "vigas totalmente plastificadas con endurecimiento por deformación. Se "
            "permite plastificación por flexión en columnas en su base. Diseño de "
            "conexiones viga-columna (incluyendo zona de panel, platinas de "
            "continuidad y diafragmas) basado en ensayos que garanticen desempeño de "
            "F.3.7.3.6.2, con conformidad según F.3.7.3.6.3.\n"
            "F.3.7.3.3 Análisis — no se especifican requisitos especiales.\n"
            "F.3.7.3.4 Requisitos del sistema.\n"
            "F.3.7.3.4.1 Relaciones de momento — deben satisfacerse en conexiones "
            "viga-columna: suma(M*pcc)/suma(M*p,esp) > 1  (F.3.7.3-1)\n"
            "donde: suma(M*pcc)=suma de proyecciones al eje de las vigas, de la "
            "resistencia nominal a flexión de las columnas (incluidas ménsulas si "
            "se usan) arriba y abajo de la unión, con reducción por la fuerza axial "
            "en la columna — para columnas compuestas, la resistencia nominal a "
            "flexión Mpcc debe satisfacer F.2.9 considerando la resistencia axial "
            "requerida Puc; para columnas de concreto reforzado, Mpcc se calcula con "
            "base en las provisiones del Título C considerando Puc. Cuando los ejes "
            "de vigas opuestas en la misma unión no coincidan, usar la línea media "
            "entre los dos ejes. suma(M*p,esp)=suma de los momentos en las vigas de "
            "acero o embebidas en concreto en la intersección de los ejes de la "
            "viga y la columna. Se determina como la suma de las resistencias "
            "esperadas a flexión de las vigas en la rótula plástica, referidas al "
            "eje de la columna. Se puede tomar "
            "suma(M*p,esp) = suma(1.1*Mp,esp + Muv), donde Mp,esp se calcula según "
            "F.3.7.2.6.4; Muv=momento debido a la amplificación por el cortante "
            "desde la posición de la rótula plástica hasta el eje de la columna.\n"
            "Excepción — aplicar las excepciones de F.3.4.3.4.1 (relación de "
            "momentos de F.3.5.3.4.1), excepto que el límite de la fuerza en "
            "F.3.5.3.4.1 debe ser Puc < 0.1*Pc.\n"
            "F.3.7.3.4.2 Arriostramiento para estabilidad de las vigas — arriostrarse "
            "para ductilidad alta (F.3.4.1.2.2). Adicionalmente, a menos que "
            "ensayos indiquen otra cosa, arriostramientos cerca de fuerzas "
            "concentradas, cambios de sección transversal, y donde el análisis "
            "indique posible rótula plástica.\n"
            "F.3.7.3.4.3 Arriostramiento para la estabilidad de conexiones "
            "viga-columna — columnas compuestas con conexiones no arriostradas "
            "deben satisfacer F.3.5.3.4.3(2).\n"
            "F.3.7.3.5 Miembros: F.3.7.3.5.1 Requisitos básicos — miembros de acero "
            "y compuestos satisfacen F.3.4.1.1 para ductilidad alta. Excepción — "
            "vigas embebidas en concreto reforzado satisfacen F.3.4.1.1 para "
            "ductilidad moderada si el recubrimiento de concreto es >=50 mm y se "
            "suministra confinamiento por estribos en regiones donde se espera "
            "formación de rótulas plásticas bajo sismo, cumpliendo C.21.5.3. Vigas "
            "compuestas embebidas del PRMC-DES deben satisfacer también que la "
            "distancia desde la fibra de concreto de mayor compresión al eje "
            "neutro plástico no sea mayor que: "
            "Ypna = (Ycon+d) / [1 + 1700*Fy/E]  (F.3.7.3-2), donde: Fy=esfuerzo "
            "fluencia mínimo especificado de la viga de acero, MPa; E=módulo "
            "elástico, MPa; Ycon=distancia desde la parte superior de la viga de "
            "acero y la parte superior del concreto, mm; d=peralte total de la "
            "viga, mm. F.3.7.3.5.2 Aletas de vigas — sin cambios abruptos en zonas "
            "de rótulas plásticas; sin perforaciones/recortes salvo demostración "
            "por ensayos. F.3.7.3.5.3 Zonas protegidas — extremos de viga sujetos "
            "a deformaciones inelásticas, cumplen F.3.4.1.3; para PRMC-DES, "
            "tratadas como zona protegida, desde cara de columna compuesta hasta "
            "mitad del peralte de viga tras la rótula.\n"
            "F.3.7.3.6 Conexiones — totalmente restringidas (TR), cumplen F.3.4.2 y "
            "este numeral. F.3.7.3.6.1 Soldaduras de demanda crítica — según "
            "F.3.1.3.4.2: (1) empalmes de columna, salvo impedimento de rótula; (2) "
            "columna-placa de base; (3) penetración completa de aletas de vigas, "
            "placas de diafragma que sirven como continuación de aletas, placas de "
            "cortante dentro del peralte de la viga que sirven de transición a un "
            "perfil embebido, y almas de vigas a columnas. F.3.7.3.6.2 Conexiones "
            "viga-columna: (1) ángulo de deriva mínimo 0.04 rad; (2) resistencia "
            "medida a flexión en cara de columna >=0.8*Mp para 0.04 rad, Mp según "
            "F.3.7.2.6.2. F.3.7.3.6.3 Validación — (1) ensayos cíclicos de "
            "calificación (F.3.11.2) cuando vigas interrumpidas en la conexión, "
            "mínimo 2, basados en literatura o ensayos específicos del proyecto; "
            "(2) cuando vigas no interrumpidas o continuas a través de la columna, "
            "sin uniones soldadas a aletas de vigas ni conexión susceptible de "
            "fractura prematura, cumplen desempeño de F.3.7.3.6.2(a). F.3.7.3.6.4 "
            "Resistencia a cortante requerida — combinaciones del Título B con "
            "carga sísmica amplificada: "
            "Emh = 2*(1.1*Ry*Mp,esp) / Lh  (F.3.7.3-3), Mp,esp según F.3.7.2.6.4. "
            "F.3.7.3.6.5 Placas de continuidad y de diafragma — según F.3.7.2.6.5. "
            "F.3.7.3.6.6 Empalmes de columna — según F.3.7.2.6.6.\n\n"
            "F.3.7.4 — PÓRTICOS RESISTENTES A MOMENTOS PARCIALMENTE RESTRINGIDOS "
            "(PRMC-PR).\n"
            "F.3.7.4.1 Alcance — columnas de acero y vigas compuestas que cumplan "
            "F.2.2.3.5.2.2.\n"
            "F.3.7.4.2 Bases de diseño — capacidad de deformación inelástica "
            "significativa a través de fluencia en componentes dúctiles de las "
            "conexiones a momento viga-columna PR compuestas. Fluencia limitada "
            "permitida en otras partes, como fluencia a flexión en la base de "
            "columnas. Diseño de conexiones basado en ensayos que garanticen "
            "desempeño de F.3.7.4.6.3, con conformidad según F.3.7.4.6.4.\n"
            "F.3.7.4.3 Análisis — considerar flexibilidad de conexión y acción de "
            "viga compuesta para características dinámicas, resistencia y derivas. "
            "Rigidez de vigas con el momento de inercia efectivo de la sección "
            "compuesta.\n"
            "F.3.7.4.4 Requisitos del sistema — no se especifican especiales.\n"
            "F.3.7.4.5 Miembros: F.3.7.4.5.1 Columnas — de acero, satisfacen "
            "F.3.4.1.1 para ductilidad alta. F.3.7.4.5.2 Vigas — compuestas, no "
            "embebidas, totalmente compuestas, cumplen F.3.4.1.1 para ductilidad "
            "alta; placa de concreto maciza hasta 300mm de la cara de columna en la "
            "dirección de transferencia de momento.\n"
            "F.3.7.4.6 Conexiones — PR, cumplen F.3.4.2 y este numeral. "
            "F.3.7.4.6.1 Soldaduras de demanda crítica — empalmes de columna (salvo "
            "impedimento de rótula), columna-placa de base. F.3.7.4.6.2 Resistencia "
            "requerida — considerando flexibilidad de conexión y momentos de "
            "segundo orden; conexiones compuestas con resistencia nominal >=50% de "
            "Mp de la viga de acero conectada sin acción compuesta. F.3.7.4.6.3 "
            "Conexiones viga-columna: (1) ángulo deriva mínimo 0.02 rad; (2) "
            "resistencia medida a flexión incrementada monotónicamente hasta "
            ">=0.5*Mp de la viga conectada, para 0.02 rad, Mp=resistencia nominal a "
            "flexión de la viga compuesta según F.2.9. F.3.7.4.6.4 Validación — "
            "ensayos cíclicos de calificación (F.3.11.2), mínimo 2, basados en "
            "literatura o ensayos específicos del proyecto. F.3.7.4.6.5 Resistencia "
            "de la conexión — Mn,PR se toma como la resistencia a flexión para 0.02 "
            "rad durante el primer ciclo en que se excede esta rotación. "
            "F.3.7.4.6.6 Empalmes de columna — según F.3.7.2.6.6."
        ),
    },
    {
        "id": "NSR10-F-F_3_8_1_a_F_3_8_3",
        "seccion": "F.3.8.1 a F.3.8.3 (PACC-DMI, PACC-DES, PAEC — pórticos compuestos arriostrados concéntrica/excéntricamente)",
        "titulo": (
            "Intro a F.3.8 (Sistemas Arriostrados y Muros de Cortante Compuestos: "
            "PACC-DMI/DES, PAEC, MCC-DMI/DES, MCAC). PACC-DMI/DES completos (por "
            "referencia a F.3.5/F.3.6, factor riostras rellenas 0.264+0.0082KL/r). "
            "PAEC completo (por referencia a F.3.6.3)."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.8 — SISTEMAS ARRIOSTRADOS Y MUROS DE CORTANTE COMPUESTOS — bases de "
            "diseño y requisitos de análisis, sistema, miembros y conexiones para "
            "PACC-DMI, PACC-DES, PAEC, MCC-DMI, MCC-DES y MCAC.\n\n"
            "F.3.8.1 — PÓRTICOS COMPUESTOS ARRIOSTRADOS CONCÉNTRICAMENTE CON "
            "CAPACIDAD DE DISIPACIÓN DE ENERGÍA MÍNIMA (PACC-DMI).\n"
            "F.3.8.1.1 Alcance — columnas de acero, embebidas, rellenas o de "
            "concreto reforzado; vigas de acero estructural o compuestas; riostras "
            "de perfiles de acero o miembros compuestos rellenos de concreto. Se "
            "aplica a estructuras arriostradas con miembros conectados "
            "concéntricamente en las cuales al menos uno de los elementos "
            "(columnas, vigas o riostras) es un miembro compuesto.\n"
            "F.3.8.1.2 Bases de diseño — pórticos arriostrados con miembros "
            "arriostrados concéntricamente; se permiten excentricidades menores que "
            "el peralte de la viga si se tienen en cuenta en el diseño (momentos por "
            "excentricidad). Capacidad de acomodar deformaciones inelásticas "
            "LIMITADAS en miembros y conexiones. Los PACC-DMI satisfacen F.3.6.1, "
            "excepto lo que se modifique en esta sección.\n"
            "F.3.8.1.3 Análisis — no se especifican requisitos especiales.\n"
            "F.3.8.1.4 Requisitos del sistema — no se especifican requisitos "
            "especiales.\n"
            "F.3.8.1.5 Miembros: F.3.8.1.5.1 Requisitos básicos — no se especifican "
            "requisitos especiales. F.3.8.1.5.2 Columnas — no se especifican "
            "requisitos especiales para columnas de acero o compuestas. Columnas de "
            "concreto reforzado cumplen C.21. F.3.8.1.5.3 Riostras — no se "
            "especifican requisitos especiales para riostras de acero o compuestas "
            "rellenas.\n"
            "F.3.8.1.6 Conexiones — satisfacen F.3.4.2.7.\n\n"
            "F.3.8.2 — PÓRTICOS COMPUESTOS ARRIOSTRADOS CONCÉNTRICAMENTE CON "
            "CAPACIDAD DE DISIPACIÓN DE ENERGÍA ESPECIAL (PACC-DES).\n"
            "F.3.8.2.1 Alcance — columnas embebidas o rellenas; vigas de acero "
            "estructural o compuestas; riostras de perfiles de acero o compuestos "
            "rellenos.\n"
            "F.3.8.2.2 Bases de diseño — miembros conectados concéntricamente; "
            "excentricidades menores que el peralte de viga permitidas si se "
            "consideran en fuerzas del miembro/conexión resultante, sin cambiar la "
            "fuente de capacidad de deformación inelástica esperada. Capacidad de "
            "acomodar deformaciones inelásticas SIGNIFICATIVAS principalmente a "
            "partir del pandeo de la riostra y fluencia de la riostra en tensión.\n"
            "F.3.8.2.3 Análisis — columnas compuestas y riostras de acero y "
            "compuestas satisfacen F.3.5.2.3.\n"
            "F.3.8.2.4 Requisitos del sistema — cumplen lo dado en F.3.5.2.4.\n"
            "F.3.8.2.5 Miembros: F.3.8.2.5.1 Requisitos básicos — columnas y "
            "riostras de acero o compuestas satisfacen F.3.4.1.1 para ductilidad "
            "alta; vigas de acero o compuestas satisfacen F.3.4.1.1 para ductilidad "
            "moderada. Para satisfacer requisitos de compacidad moderada de "
            "F.3.5.2.5.1, la relación ancho-espesor de riostras rellenas cuadradas y "
            "rectangulares se multiplica por el factor (0.264+0.0082*KL/r), para "
            "KL/r entre 35 y 90, siendo KL/r la esbeltez efectiva de la riostra. "
            "F.3.8.2.5.2 Riostras diagonales — de acero y compuestas rellenas "
            "cumplen F.3.6.2.5.2; el radio de giro se toma como el de la sección de "
            "acero aislada.\n"
            "F.3.8.2.6 Conexiones — diseño basado en F.3.4.2 y las mencionadas en "
            "esta sección. F.3.8.2.6.1 Soldaduras de demanda crítica — según "
            "F.3.1.3.4.2: (1) acanaladas en empalmes de columnas, salvo impedimento "
            "de rótula; (2) columna-placa de base; (3) conexiones viga-columna que "
            "cumplan F.3.8.2.6.2(2). F.3.8.2.6.2 Conexiones viga-columna — cuando "
            "riostra o placa de conexión conecta viga y columna: (1) simple (no a "
            "momento), rotación 0.025 rad (F.2.2.3.6.1); o (2) satisfacen los "
            "numerales F.3.4.2, F.3.7.2.6.4, F.3.7.2.6.5, F.3.7.2.6.6 y F.3.7.3.6.1 "
            "para conexiones a momento TR. F.3.8.2.6.3 Resistencia requerida de "
            "conexiones de riostra — satisface F.3.6.2.6.3. F.3.8.2.6.4 Empalmes de "
            "columnas — cumplen F.3.7.2.6.6.\n\n"
            "F.3.8.3 — PÓRTICOS COMPUESTOS ARRIOSTRADOS EXCÉNTRICAMENTE (PAEC).\n"
            "F.3.8.3.1 Alcance — columnas compuestas embebidas o rellenas; vigas de "
            "acero o compuestas; vínculos de acero; riostras de perfiles de acero o "
            "compuestos rellenos de concreto. Un extremo de cada riostra intercepta "
            "una viga con excentricidad desde la intersección de ejes en la viga y "
            "una riostra adyacente o columna.\n"
            "F.3.8.3.2 Bases de diseño — satisface requisitos de F.3.6.3.2, excepto "
            "lo que se modifique en esta sección. Excentricidades menores que el "
            "peralte de viga permitidas en la conexión de la riostra lejana del "
            "vínculo si se consideran las fuerzas resultantes; no cambian la fuente "
            "esperada de capacidad de deformación inelástica. Capacidad de "
            "deformación inelástica significativa por fluencia a cortante de los "
            "vínculos. Resistencia de diseño de miembros según Capítulo F.2, "
            "excepto lo que se modifique en esta sección.\n"
            "F.3.8.3.3 Análisis — cumple F.3.6.3.3.\n"
            "F.3.8.3.4 Requisitos del sistema — cumplen lo especificado en F.3.6.3.4.\n"
            "F.3.8.3.5 Miembros — cumplen F.3.6.3.5.\n"
            "F.3.8.3.6 Conexiones — cumplen F.3.6.3.6, excepto lo especificado a "
            "continuación. F.3.8.3.6.1 Conexiones viga-columna — cuando riostra o "
            "cartela conecta viga y columna: (1) simple (no a momento), rotación "
            "0.025 rad (F.2.2.3.6.1); o (2) satisfacen los numerales F.3.4.2, "
            "F.3.7.2.6.4 y F.3.7.2.6.5 para conexiones a momento TR."
        ),
    },
    {
        "id": "NSR10-F-F_3_8_4_MCC_DMI",
        "seccion": "F.3.8.4 (Muros de Cortante Compuestos de Concreto Reforzado y Perfiles de Acero con capacidad mínima MCC-DMI)",
        "titulo": (
            "MCC-DMI completo: muros de concreto reforzado con elementos de acero "
            "como elementos de borde y vigas de acople, resistencia a cortante "
            "esperada de vigas de acople Vn=2Ry·Mp/g, longitud de empotramiento "
            "Vn (ecuación completa con f'c, β1), refuerzo vertical de transferencia."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.8.4 — MUROS DE CORTANTE COMPUESTOS DE CONCRETO REFORZADO Y "
            "PERFILES DE ACERO CON CAPACIDAD MÍNIMA DE DISIPACIÓN DE ENERGÍA "
            "(MCC-DMI).\n"
            "F.3.8.4.1 Alcance — aplica cuando muros de concreto reforzado están "
            "compuestos por elementos de acero estructural, incluyendo perfiles "
            "estructurales o secciones compuestas que actúan como elementos de "
            "borde para los muros y vigas de acople de acero estructural o "
            "compuestas que conectan dos o más muros de concreto reforzado "
            "adyacentes.\n"
            "F.3.8.4.2 Bases de diseño — se espera que los MCC-DMI garanticen "
            "capacidad de deformación inelástica limitada a través de la fluencia "
            "en los muros de concreto reforzado y los elementos de acero o "
            "compuestos. Muros de concreto diseñados para desarrollar deformaciones "
            "inelásticas para la deriva de piso de diseño consistentemente con lo "
            "especificado en el Título C, excluyendo C.21. Vigas de acople de acero "
            "y las compuestas diseñadas para desarrollar deformaciones inelásticas "
            "mediante fluencia por flexión. Elementos de borde de acero y los "
            "compuestos diseñados para desarrollar deformaciones inelásticas "
            "mediante fluencia producida por fuerzas axiales. Los muros de concreto "
            "reforzado deben cumplir los requisitos del Título C, excluyendo lo que "
            "se modifica en esta sección.\n"
            "F.3.8.4.3 Análisis — cumple el Título C con las modificaciones "
            "incluidas: (1) para el análisis elástico, asignar rigideces efectivas "
            "no fisuradas según C.10 para muros y vigas de acople compuestas; (2) "
            "con perfiles embebidos en concreto como miembros de borde, el análisis "
            "se basa en la sección transformada usando propiedades elásticas del "
            "material; (3) tomar en cuenta la flexibilidad de la conexión entre "
            "vigas de acople y muros, así como el efecto de las distorsiones de "
            "cortante de la viga de acople y muros.\n"
            "F.3.8.4.4 Requisitos del sistema — para muros acoplados, se permite "
            "que las vigas de acople plastifiquen en toda la altura de la "
            "estructura, la conexión viga de acople-muro debe desarrollar la "
            "resistencia a cortante esperada a la flexión de la viga de acople. Se "
            "permite redistribuir las fuerzas en la viga de acople verticalmente a "
            "los pisos adyacentes. El cortante de cualquier viga de acople "
            "individual no debe ser reducido más del 20% del valor determinado "
            "elásticamente. La suma de la resistencia a cortante de las vigas de "
            "acople en toda la altura del edificio debe ser mayor o igual que los "
            "valores determinados elásticamente.\n"
            "F.3.8.4.5 Miembros: F.3.8.4.5.1 Miembros de borde — (1) resistencia "
            "axial requerida del elemento de borde determinada suponiendo que las "
            "fuerzas de cortante son tomadas por el muro de concreto reforzado y "
            "todas las fuerzas gravitacionales y de volcamiento son tomadas por los "
            "miembros de borde junto con el muro; (2) miembro de borde de acero "
            "embebido en concreto que califique como columna compuesta (F.2.9) se "
            "diseña como columna compuesta satisfaciendo F.2.9; (3) deben "
            "instalarse conectores de espigo o anclajes de refuerzo soldados para "
            "transferir la resistencia a cortante requerida entre los miembros de "
            "borde de acero y los muros de concreto reforzado; con conectores de "
            "espigo, cumplen F.2.9; con refuerzo soldado, cumple AWS D1.4.\n"
            "F.3.8.4.5.2 Vigas de acople:\n"
            "(1) Vigas de acople de acero — las que se usen entre muros de concreto "
            "reforzado adyacentes cumplen F.2 y esta sección (para vigas en "
            "secciones I): (a) cumplen F.3.4.1.1 para miembros de ductilidad "
            "moderada; (b) resistencia a cortante esperada Vn se calcula con "
            "Vn = 2*Ry*Mp/g <= Ry*Vp  (F.3.8.4-1), donde Mp=Fy*Z, N·mm; "
            "Vn=resistencia esperada a cortante de la viga de acople de acero, N; "
            "Vp=0.6*Fy*Atw, N; Atw=área del alma de la viga de acero, mm2; "
            "g=distancia libre de la viga de acople, mm; (c) longitud de "
            "empotramiento Le se calcula con la ecuación F.3.8.4-2, empieza por "
            "dentro de la primera capa de refuerzo de confinamiento del miembro de "
            "borde del muro: Vn = 0.004*raiz(f'c)*(bw/bf)^0.66*beta1*bf*Le*"
            "[(0.58-0.22*beta1)/(0.88+g/(2*Le))]  (F.3.8.4-2), donde Le=longitud de "
            "empotramiento, mm; bw=espesor del muro de concreto, mm; bf=ancho de "
            "la aleta de la viga, mm; f'c=resistencia a compresión del concreto, "
            "MPa; beta1=factor que relaciona la profundidad del bloque rectangular "
            "de esfuerzos de compresión equivalente y la profundidad del eje "
            "neutro, definido en el Título C; (d) debe colocarse refuerzo vertical "
            "en el muro cuya resistencia axial nominal sea igual a la resistencia "
            "a cortante esperada de la viga de acople, sobre la longitud de "
            "empotramiento con dos terceras partes del acero de refuerzo "
            "localizado sobre la primera mitad de la longitud de empotramiento; "
            "este refuerzo debe extenderse una distancia por lo menos igual a la "
            "longitud de desarrollo a la tensión, tanto arriba como debajo de las "
            "aletas de la viga de acople; se puede suministrar refuerzo vertical "
            "para otros propósitos, tales como miembros de borde verticales, como "
            "parte del refuerzo vertical requerido. El área de refuerzo de "
            "transferencia vertical requerido: Atb >= 0.03*f'c*Le*bf/Fytf  "
            "(F.3.8.5-1) [nota: el texto original referencia la ecuación con "
            "numeración F.3.8.5-1 pese a estar en el numeral F.3.8.4.5.2 — "
            "transcrito tal como aparece], donde: Atb=área de refuerzo de "
            "transición requerido en la primera y segunda región, anclado tanto a "
            "la aleta superior como inferior, mm2; Fytf=esfuerzo de fluencia del "
            "refuerzo de transferencia, MPa. Los miembros de acero embebidos deben "
            "contar con 2 regiones de refuerzo de transferencia vertical, ancladas "
            "a la aleta superior e inferior: primera región coincidente con las "
            "barras de refuerzo longitudinales del muro cercanas a la cara del "
            "muro; segunda región a distancia no menor que d/2 desde donde termina "
            "la longitud de empotramiento; barras de transferencia con longitud de "
            "desarrollo completa al envolver las aletas de la viga de acople "
            "(anclajes rectos, con gancho, mecánicos, o acoples metálicos soldados "
            "a las aletas). El área del refuerzo de transferencia vertical no debe "
            "exceder la calculada por: suma(Atb) < 0.08*Le*bw - As  (F.3.8.5-2), "
            "donde: suma(Atb)=área total de refuerzo de transferencia suministrado "
            "para la primera y segunda región, mm2; As=área del refuerzo "
            "longitudinal del muro en toda la longitud de empotramiento Le, mm2.\n"
            "(2) Vigas de acople compuestas — las secciones compuestas embebidas "
            "que sirven como vigas de acople cumplen los requisitos de "
            "F.3.8.4.5.2(1) como se modifica en esta sección: (a) longitud de "
            "empotramiento suficiente para desarrollar la resistencia a cortante "
            "esperada, Vn,comp, calculada con: Vn,comp = 2*Mp,esp/g <= Vcomp  "
            "(F.3.8.4-3), donde Mp,esp=resistencia a flexión esperada de la viga de "
            "acople compuesta, calculada usando distribución plástica de esfuerzos "
            "o el método de compatibilidad de deformaciones, con factores Ry "
            "apropiados para los elementos de la sección; Vcomp=resistencia límite "
            "esperada a cortante de la viga de acople compuesta embebida, "
            "calculada con: Vcomp = Ry*Vp + [0.166*raiz(f'c)*bwc*dc + "
            "As*Fyt*dc/s]  (F.3.8.4-4), donde: As=área del refuerzo transversal, "
            "mm2; Fyt=esfuerzo de fluencia del refuerzo transversal, MPa; "
            "bwc=ancho del concreto, mm; dc=peralte efectivo del concreto, mm; "
            "s=espaciamiento del refuerzo transversal, mm; (b) longitud de "
            "empotramiento requerido se calcula con la ecuación F.3.8.4-2, "
            "usando Vn,comp en lugar de Vn.\n"
            "F.3.8.4.6 Conexiones — no se especifican requisitos adicionales a los "
            "de F.3.8.4.5."
        ),
    },
    {
        "id": "NSR10-F-F_3_8_5_MCC_DES",
        "seccion": "F.3.8.5 (Muros de Cortante Compuestos con capacidad de energía especial MCC-DES)",
        "titulo": (
            "MCC-DES completo: capacidad significativa de deformación, plastificar "
            "vigas de acople en toda la altura, resistencia balanceada Pb del muro, "
            "vigas de acople como zonas dúctiles/protegidas, refuerzo de "
            "transferencia vertical incrementado 1.1Ry factor."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.8.5 — MUROS DE CORTANTE COMPUESTOS DE CONCRETO REFORZADO Y "
            "PERFILES DE ACERO CON CAPACIDAD ESPECIAL DE DISIPACIÓN DE ENERGÍA "
            "(MCC-DES).\n"
            "F.3.8.5.1 Alcance — igual alcance que F.3.8.4.1: muros de concreto "
            "reforzado compuestos por elementos de acero estructural (elementos de "
            "borde) y vigas de acople de acero estructural o compuestas que "
            "conectan dos o más muros de concreto reforzado adyacentes.\n"
            "F.3.8.5.2 Bases de diseño — capacidad de deformación inelástica "
            "SIGNIFICATIVA a través de la fluencia en los muros de concreto "
            "reforzado y los elementos de acero o compuestos. Muros de concreto "
            "diseñados para desarrollar deformaciones inelásticas para la deriva de "
            "diseño consistentemente con el Título C, excluyendo C.21. Vigas de "
            "acople de acero y compuestas diseñadas para desarrollar deformaciones "
            "inelásticas mediante fluencia por flexión. Conexiones de vigas de "
            "acople y diseño de los muros deben tomar en cuenta la resistencia "
            "esperada, incluido el endurecimiento por deformación de las vigas de "
            "acople.\n"
            "F.3.8.5.3 Análisis — cumple F.3.8.4.3, con las siguientes excepciones: "
            "(1) para el análisis elástico, asignar rigideces efectivas de "
            "secciones fisuradas según C.10 para muros y vigas de acople "
            "compuestas; (2) tomar en cuenta el efecto de las distorsiones de "
            "cortante de la viga de acople y muros.\n"
            "F.3.8.5.4 Requisitos del sistema — cumple F.3.8.4.4 con las siguientes "
            "excepciones: (1) para muros acoplados, las vigas de acople deben "
            "plastificarse en toda la altura de la estructura seguida por la "
            "plastificación en la base de los muros; (2) para muros acoplados, la "
            "resistencia de diseño axial del muro en condiciones balanceadas, Pb, "
            "debe ser mayor o igual que la resistencia axial requerida a "
            "compresión del muro, calculada como la suma de las resistencias "
            "requeridas atribuidas a los muros a partir de los componentes de "
            "carga gravitacional de la combinación de carga lateral, más la suma "
            "de la resistencia a cortante de las vigas incrementada por un factor "
            "de 1.1 para reflejar los efectos del endurecimiento por deformación "
            "(1.1*Ry*Vn) de todas las vigas de acople que conectan con los muros.\n"
            "F.3.8.5.5 Miembros: F.3.8.5.5.1 Elementos dúctiles — las vigas de "
            "acople son zonas protegidas, cumplen F.3.4.1.3. Se permiten soldaduras "
            "en vigas de acople de acero para colocar atiesadores, tal como se "
            "requiere en F.3.6.3.5.2(4). F.3.8.5.5.2 Miembros de borde — columnas "
            "de acero NO embebidas cumplen F.3.4.1.1 para ductilidad alta y "
            "F.3.8.4.5.1(1). Adicionalmente a F.3.8.4.3(2) y F.3.8.4.5.1(2), los "
            "requisitos de esta sección aplican a muros con elementos de borde de "
            "acero embebidos. Los miembros de acero embebidos en concreto "
            "reforzado que califiquen como columnas compuestas (F.2.9) cumplen "
            "adicionalmente lo establecido en F.3.4.1.4.2(2) para miembros de "
            "ductilidad alta; de lo contrario, deben diseñarse como miembros "
            "compuestos a compresión cumpliendo C.10.13 incluyendo los requisitos "
            "sísmicos especiales para miembros de borde en C.21.9.6. El refuerzo "
            "transversal para el confinamiento de miembros de borde compuestos "
            "debe extenderse una distancia 2h dentro del muro, donde h es el "
            "peralte total del miembro de borde en el plano del muro. Deben "
            "suministrarse conectores de cortante de espigo o barras de refuerzo "
            "soldadas, como se especifica en F.3.8.4.5.1(3). F.3.8.5.5.3 Vigas de "
            "acople de acero — además de los parámetros de F.3.8.4.5.2, las vigas "
            "de acero estructural cumplen F.3.6.3.5.2. Cuando F.3.6.3.5.2(4) lo "
            "requiere, la rotación de la viga de acople se supone como 0.08 "
            "radianes, a menos que un valor menor se justifique por análisis "
            "racionales de deformaciones inelásticas esperadas bajo la deriva de "
            "diseño. Deben colocarse por ambos lados de la viga de acople "
            "atiesadores de cara contra el muro de concreto reforzado, cumpliendo "
            "F.3.6.3.5.2(4). Las vigas de acople de acero cumplen F.3.4.1.1 para "
            "ductilidad alta. La resistencia a cortante esperada para calcular la "
            "longitud de empotramiento (ecuación F.3.8.4-1) debe incrementarse por "
            "un factor de 1.1 para reflejar los efectos del endurecimiento por "
            "deformación (1.1*Ry*Vn). El refuerzo vertical del muro definido en "
            "F.3.8.4.5.2(1)(d) debe ser confinado por un refuerzo transversal que "
            "cumpla lo establecido para miembros de borde en C.21.9.6.\n"
            "F.3.8.5.5.4 Vigas de acople compuestas — las secciones compuestas "
            "embebidas que sirven como vigas de acople cumplen los requisitos de "
            "F.3.8.5.5.3, excepto los de F.3.6.3.5.2(4), y debe usarse la ecuación "
            "F.3.8.5-3 en lugar de la ecuación F.3.8.4-4. Para todas las vigas de "
            "acople compuestas embebidas, la resistencia a cortante esperada, "
            "Vcomp, es: Vcomp = 1.1*Ry*Vp + 1.56*[0.166*raiz(f'c)*bwc*dc + "
            "As*Fyt*dc/s]  (F.3.8.5-3).\n"
            "F.3.8.5.6 Conexiones: F.3.8.5.6.1 Soldaduras de demanda crítica — "
            "según F.3.1.3.4.2: (1) acanaladas en empalmes de columna, salvo "
            "impedimento de rótula; (2) columna-placa de base. F.3.8.5.6.2 "
            "Empalmes de columna — cumplen F.2.7.2.6.6 [nota: transcrito tal como "
            "aparece en el texto original]."
        ),
    },
    {
        "id": "NSR10-F-F_3_8_6_MCAC",
        "seccion": "F.3.8.6 (Muros de Cortante de Acero Compuestos MCAC)",
        "titulo": (
            "MCAC completo: placa de acero + recubrimiento de concreto reforzado en "
            "uno/ambos lados, resistencia Vn=0.6·Asp·Fy, espesor mínimo placa "
            "9.5mm, elementos de rigidización de concreto (100/200mm), refuerzo "
            "horizontal/vertical, conexiones a elementos de borde."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.8.6 — MUROS DE CORTANTE DE ACERO COMPUESTOS (MCAC).\n"
            "F.3.8.6.1 Alcance — consisten en placas de acero con recubrimiento de "
            "concreto reforzado en uno o ambos lados de la placa, las placas de "
            "acero en ambos lados de un relleno de concreto reforzado, y acero "
            "estructural o compuestos en los miembros de borde.\n"
            "F.3.8.6.2 Bases de diseño — capacidad de deformación inelástica "
            "significativa, principalmente por medio de fluencia de la placa del "
            "alma. Los elementos de borde horizontales (EBH) y verticales (EBV) "
            "adyacentes a las almas compuestas deben diseñarse para permanecer "
            "esencialmente elásticos bajo las fuerzas máximas que pueden generarse "
            "por las almas de acero totalmente plastificadas junto con las almas "
            "de concreto reforzado después de que el alma de acero haya "
            "plastificado completamente, excepto que se permite la formación de "
            "rótulas plásticas en los extremos de los EBH.\n"
            "F.3.8.6.3 Análisis: F.3.8.6.3.1 Almas — diseñadas para resistir la "
            "carga sísmica E determinada a partir del análisis requerido por el "
            "Título B. El análisis debe tener en cuenta las aberturas en el alma. "
            "F.3.8.6.3.2 Otros miembros y conexiones — columnas, vigas y "
            "conexiones en MCAC deben diseñarse para resistir las fuerzas sísmicas "
            "determinadas a partir de un análisis que incluye la resistencia "
            "esperada de las almas de acero a cortante, 0.6*Ry*Fy*Asp, y cualquier "
            "porción de concreto en el muro activa para la deriva de diseño de "
            "piso. Los EBV pueden plastificarse en la base.\n"
            "F.3.8.6.4 Requisitos del sistema: F.3.8.6.4.1 Espesor de la placa de "
            "acero — no se permiten placas con espesores menores que 9.5 mm. "
            "F.3.8.6.4.2 Rigidez de los elementos de borde verticales — los EBV "
            "cumplen F.3.6.5.4.1. F.3.8.6.4.3 Relación de momentos en la conexión "
            "EBH-EBV — cumple F.3.6.5.4.2. F.3.8.6.4.4 Riostras — arriostramiento "
            "cumple F.3.6.5.4.3. F.3.8.6.4.5 Aberturas en el alma — deben "
            "instalarse miembros de borde alrededor de las aberturas de almas de "
            "muros de cortante según se requiera en los análisis.\n"
            "F.3.8.6.5 Miembros: F.3.8.6.5.1 Requisitos básicos — EBH y EBV de "
            "acero y los compuestos cumplen F.3.4.1.1 para ductilidad alta. "
            "F.3.8.6.5.2 Almas — resistencia de diseño a cortante del tablero, "
            "phi*Vn, para el estado límite de fluencia por cortante de una placa "
            "compuesta que cumpla F.3.8.6.5.3: "
            "Vn = 0.6*Asp*Fy  (F.3.8.6-1), phi=0.9, donde: Asp=área horizontal de "
            "la placa de acero atiesada, mm2; Fy=esfuerzo de fluencia mínimo "
            "especificado de la placa de acero, MPa; Vn=resistencia a cortante "
            "nominal de la placa de acero, N. La resistencia de diseño de MCAC con "
            "una placa que no cumpla los requisitos de rigidez de F.3.8.6.5.3 debe "
            "basarse en la resistencia de la placa especificada en F.3.6.5.5 y "
            "satisfacer los requisitos de F.2.7.2 y F.2.7.3. F.3.8.6.5.3 Elementos "
            "de rigidización de concreto — la placa de acero debe estar rigidizada "
            "adecuadamente por un recubrimiento de un tablero de concreto "
            "reforzado. La validación puede demostrarse mediante análisis de placa "
            "con pandeo elástico que muestre que el muro compuesto puede resistir "
            "una fuerza nominal igual a Vns. El espesor de concreto debe ser como "
            "mínimo 100 mm a cada lado cuando el concreto se coloque a ambos lados "
            "de la placa de acero, y 200 mm cuando el concreto se coloque en un "
            "solo lado. Deben instalarse conectores de espigo u otros conectores "
            "mecánicos que prevengan el pandeo local y la separación de la placa y "
            "el concreto reforzado. Debe colocarse refuerzo horizontal y vertical "
            "en el recubrimiento de concreto que cumpla o exceda los requisitos de "
            "C.14.3. La cuantía de refuerzo en ambas direcciones no debe ser menor "
            "que 0.0025. El espaciamiento máximo entre barras no debe ser mayor "
            "que 450 mm. F.3.8.6.5.4 Miembros de borde — los de acero y los "
            "compuestos deben diseñarse para resistir una acción igual a la "
            "resistencia esperada a cortante de la placa de acero y cualquier "
            "porción de concreto reforzado del muro activa para la deriva de "
            "diseño de piso. Los miembros de borde compuestos y los de concreto "
            "reforzado deben satisfacer también los requisitos de F.3.8.5.5.2. Los "
            "miembros de borde de acero deben satisfacer también los requisitos de "
            "F.3.6.5.\n"
            "F.3.8.6.6 Conexiones: F.3.8.6.6.1 Soldaduras de demanda crítica — "
            "según F.3.1.3.4.2: (1) acanaladas en empalmes de columnas, salvo "
            "impedimento de rótula; (2) columna-placa de base; (3) conexiones "
            "EBH-EBV. F.3.8.6.6.2 Conexiones EBH-EBV — cumplen F.3.6.5.6.2. "
            "F.3.8.6.6.3 Conexiones de placas de acero a elementos de borde — la "
            "placa de acero debe estar continuamente soldada o atornillada en "
            "todos sus bordes a la estructura de acero o a los miembros de borde "
            "compuesto. Se requiere que las soldaduras o los pernos de alta "
            "resistencia de deslizamiento crítico desarrollen la resistencia "
            "nominal a cortante de la placa. F.3.8.6.6.4 Conexiones de placa al "
            "tablero de concreto reforzado — los anclajes de acero entre la placa "
            "y el tablero de concreto reforzado deben diseñarse para prevenir su "
            "pandeo, satisfaciendo: (1) tensión en el conector — el anclaje debe "
            "diseñarse para resistir la fuerza de tensión resultante del pandeo "
            "local inelástico de la placa de acero; (2) cortante en el conector — "
            "los anclajes deben diseñarse en conjunto para transferir la "
            "resistencia a cortante de la placa de acero o el panel de concreto "
            "reforzado, la que sea menor. F.3.8.6.6.5 Empalmes de columnas — "
            "cumplen los requisitos del numeral F.3.7.2.6.6."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])
    print(f"Chunks a insertar: {len(CHUNKS)}")
    for c in CHUNKS:
        print(f"  {c['id']} ({c['seccion']}): {len(c['texto'])} chars")

    print("\nCargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
    textos = [c["texto"] for c in CHUNKS]
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print("\nSubiendo a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()
    print(f"OK: {len(rows)} chunks F.3.7-F.3.8 cargados con embedding.")


if __name__ == "__main__":
    main()
