"""
NSR-10 Titulo F, resto de F.3.5.3 (PRM-DES) + F.3.5.4 (PCD) + F.3.5.5-F.3.5.6
(SCV-DMI/DES) + F.3.6 completo (PAC-DMI/DES, PAE, PAPR, MCA) -- reingesta
verbatim real, reemplaza los chunks resumidos de sesiones anteriores
(NSR10-F-F_3_5_PRM, NSR10-F-F_3_6_PAC, NSR10-F-F_3_6_3_PAE,
NSR10-F-F_3_6_4_PAPR, NSR10-F-F_3_6_5_MCA -- 562 caracteres/pagina de
densidad real, comparado con 1300-1950 caracteres/pagina logrados hoy
leyendo el PDF real, confirma que eran resumenes condensados, no verbatim).

Decision del usuario 2026-08-27: rehacer F.3.5-F.3.11 verbatim ANTES de
tocar F.4/F.5 (mas critico para seguridad estructural). Este es el primer
batch de esa reingesta -- el segundo (F.3.7 PRMC a F.3.11 ensayos) va en
otro script.

Fuente: NSR-10-901-980.pdf (Drive, id 14q4ylyJYB9H1IdLrdZ0X0crekxxbajmm),
paginas internas F-240 a F-268. Leido visualmente pagina por pagina (Read
con `pages`), no el texto plano exportado por Drive.

Los 5 chunk_ids viejos (F_3_5_PRM, F_3_6_PAC, F_3_6_3_PAE, F_3_6_4_PAPR,
F_3_6_5_MCA) se eliminan en un script aparte (_borrar_chunks_resumidos_f35_f36.py)
una vez confirmado que el contenido nuevo los cubre por completo.

11 chunks single-topic, mismo patron que scripts anteriores de Titulo F.

Uso: python _ingest_titulo_f_f353_a_f365.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "NSR-10 Título F — Estructuras Metálicas"

CHUNKS = [
    {
        "id": "NSR10-F-F_3_5_3_4_a_F_3_5_3_5",
        "seccion": "F.3.5.3.4 a F.3.5.3.5 (PRM-DES: relación columna fuerte-viga débil, arriostramiento de columnas, miembros)",
        "titulo": (
            "Requisito de columna fuerte-viga débil para PRM-DES: cuándo se puede "
            "suponer que la columna permanece elástica (relación >2), arriostramiento "
            "lateral directo/indirecto de aletas de columna (resistencia 2% de "
            "Fy·bf·tf), columnas sin arriostramiento lateral transversal (esbeltez "
            "L/r<=60), y requisitos de miembros/aletas de vigas en zonas de rótula."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.5.3.4 — RELACIÓN COLUMNA FUERTE-VIGA DÉBIL (continuación) — se puede "
            "suponer que la columna permanece en estado elástico fuera de la zona de "
            "panel cuando la relación calculada con la ecuación F.3.5.3-1 (suma de "
            "resistencias plásticas de columna / suma de momentos esperados en vigas) "
            "sea mayor de 2. Cuando NO se puede demostrar que la columna permanece "
            "elástica fuera de la zona de panel:\n"
            "(1) Arriostramiento de las aletas de la columna: las aletas deben estar "
            "arriostradas lateralmente en el nivel superior e inferior de las aletas "
            "de las vigas. El arriostramiento puede ser directo (riostras u otros "
            "miembros, o lámina colaborante y su losa, anclados a la aleta de la "
            "columna en o cerca del punto que se desea arriostrar) o indirecto "
            "(a través de la rigidez de los miembros y conexiones no directamente "
            "ancladas a las aletas, sino que actúa a través del alma de la columna o "
            "de los rigidizadores). Resistencia requerida de las riostras laterales: "
            "2% de la resistencia de diseño de la aleta de la viga, Fy*bf*tf.\n"
            "(2) Conexiones no arriostradas — la columna con conexión viga-columna sin "
            "arriostramiento lateral transversal al pórtico sísmico debe diseñarse "
            "usando la distancia entre riostras laterales adyacentes como altura de "
            "columna para pandeo transversal, cumpliendo F.2.8 con excepciones:\n"
            "(a) resistencia requerida de la columna con combinaciones del Título B "
            "incluyendo la carga sísmica amplificada; al determinar Emh (que incluye "
            "sobrerresistencia), no se requiere mayor del 125% de la resistencia de "
            "diseño del pórtico, con base en la resistencia de diseño a flexión de la "
            "viga o la resistencia de diseño a cortante de la zona de panel.\n"
            "(b) la esbeltez L/r de la columna no debe ser mayor de 60.\n"
            "(c) la resistencia a flexión requerida de la columna transversal al pórtico "
            "sísmico debe incluir el momento causado por la aplicación de la fuerza de "
            "la aleta de la viga especificada en F.3.5.3.4.3(1)(b), adicionalmente a los "
            "momentos de segundo orden por el desplazamiento resultante de la aleta de "
            "la columna.\n\n"
            "F.3.5.3.5 — MIEMBROS.\n"
            "F.3.5.3.5.1 Requisitos básicos — miembros para vigas y columnas deben "
            "satisfacer F.3.4.1.1 para miembros con ductilidad alta, a menos que los "
            "ensayos de calificación lo precisen. Las vigas con perfiles de acero pueden "
            "ser compuestas con placa de concreto reforzado para resistir cargas de "
            "gravedad.\n"
            "F.3.5.3.5.2 Aletas de vigas — no se permiten cambios abruptos en la aleta "
            "en zonas de rótulas plásticas; tampoco perforaciones en la aleta ni "
            "recortes en el ancho a menos que los ensayos de calificación demuestren "
            "que la configuración resultante puede desarrollar rótulas plásticas "
            "estables para el ángulo de deriva de piso requerido. La configuración debe "
            "ser consistente con una conexión precalificada de acuerdo con ANSI/AISC "
            "358, o determinada en una precalificación (F.3.11.1) o programa de ensayos "
            "de calificación (F.3.11.2)."
        ),
    },
    {
        "id": "NSR10-F-F_3_5_3_6",
        "seccion": "F.3.5.3.6 (PRM-DES: conexiones — zonas protegidas, soldaduras de demanda crítica, resistencia a cortante requerida, zona de panel, placas de continuidad, empalmes de columna)",
        "titulo": (
            "Requisitos completos de conexiones para PRM-DES: zona protegida en "
            "extremos de vigas, soldaduras de demanda crítica, conexión viga-columna "
            "(ángulo de deriva 0.04 rad, resistencia 0.8Mp mínima), validación por "
            "conexión precalificada o ensayos, Emh=2(1.1Ry·Mp)/Lh, zona de panel "
            "(t≥(dz+wz)/90), placas de enchape y de continuidad, y empalmes de columna."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.5.3.5.3 Zonas protegidas — la región en cada extremo de la viga sujeta "
            "a deformaciones inelásticas es zona protegida, debe satisfacer F.3.4.1.3. "
            "La extensión debe estar de acuerdo con ANSI/AISC 358, o como se determine "
            "en precalificación (F.3.11.1) o programa de ensayos (F.3.11.2). Las zonas "
            "de rótulas plásticas en extremos de vigas en PRM-DES se tratan como zonas "
            "protegidas, establecidas a partir de precalificación o programa según "
            "F.3.5.3.6.3. Para conexiones sin reforzar, la zona protegida va desde la "
            "cara de la columna hasta una distancia igual a la mitad del peralte de la "
            "viga más allá de la rótula plástica.\n\n"
            "F.3.5.3.6 — CONEXIONES.\n"
            "F.3.5.3.6.1 Soldaduras de demanda crítica — deben satisfacer F.3.1.3.4.2: "
            "(1) soldaduras acanaladas en empalmes de columna; (2) soldaduras de la "
            "conexión columna-placa de base, excepto cuando pueda demostrarse que se "
            "impide la formación de la rótula en la columna o cerca de la placa de "
            "base mediante restricciones, y en ausencia de tensiones netas bajo las "
            "combinaciones de carga que incluyen la carga sísmica amplificada; (3) "
            "soldaduras acanaladas de penetración completa de las aletas de vigas y "
            "almas de vigas a las columnas, a menos que se especifique otra cosa en "
            "ANSI/AISC 358, en precalificación (F.3.11.1) o en programa de ensayos "
            "(F.3.11.2).\n"
            "F.3.5.3.6.2 Conexiones viga-columna del SRS: (1) la conexión debe soportar "
            "un ángulo de deriva de piso de 0.04 radianes como mínimo; (2) la "
            "resistencia medida a flexión de la conexión, en la cara de la columna, "
            "debe ser por lo menos 0.8*Mp de la viga conectada, a un ángulo de deriva "
            "de piso de 0.04 radianes.\n"
            "F.3.5.3.6.3 Validación de la conexión — la conexión viga-columna del SRS "
            "debe satisfacer F.3.5.3.6.2 mediante: (1) uso de conexiones PRM-DES según "
            "ANSI/AISC 358; (2) uso de conexión precalificada PRM-DES según F.3.11.1; "
            "(3) especificaciones de resultados de ensayos cíclicos de calificación "
            "según F.3.11.2 — al menos 2 ensayos de la conexión, basados en: (a) "
            "ensayos reportados en artículos de investigación o documentados para "
            "otros proyectos representativos de las condiciones del proyecto, con los "
            "límites de F.3.11.2; (b) ensayos enfocados específicamente al proyecto, "
            "representativos de tamaños de miembros, resistencia del material, "
            "configuración de conexión, procesos constructivos, con los límites de "
            "F.3.11.2.\n"
            "F.3.5.3.6.4 Resistencia a cortante requerida — Vu de la conexión debe "
            "basarse en las combinaciones del Título B incluyendo la carga sísmica "
            "amplificada, con el efecto de fuerzas horizontales incluyendo la "
            "sobrerresistencia:\n"
            "Emh = 2*(1.1*Ry*Mp) / Lh  (F.3.5.3-6)\n"
            "donde: Ry=relación esfuerzo fluencia esperado/mínimo especificado, Fy; "
            "Mp=Fy*Z, N·mm; Lh=distancia entre rótulas plásticas, mm. En lugar de la "
            "ecuación F.3.5.2-1, la resistencia requerida a cortante de la conexión "
            "debe ser la que especifica ANSI/AISC 358, o la determinada en "
            "precalificación (F.3.11.1) o programa de ensayos (F.3.11.2).\n"
            "F.3.5.3.6.5 Zona de panel: (1) Resistencia a cortante — el espesor "
            "requerido del alma de la columna se determina a partir de la suma de "
            "momentos en las caras de la columna, calculada proyectando los momentos "
            "esperados en los puntos de rótula plástica hasta la cara de la columna. "
            "Resistencia de diseño phi_v*Vn, phi_v=1.0, Vn según el estado límite de "
            "fluencia a cortante de F.2.10.10.6. (2) Espesor de la zona de panel — "
            "espesores individuales t de almas de columna y placas de enchape deben "
            "cumplir: t >= (dz+wz)/90  (F.3.5.3-7), donde dz=altura de la zona de panel "
            "entre placas de continuidad, mm; wz=ancho de la zona de panel entre "
            "aletas de columna, mm. Alternativamente, cuando el pandeo local del alma "
            "de columna y placa de enchape se previene uniéndolas con soldaduras de "
            "tapón (mínimo 4 cuando se requieran), el espesor total debe satisfacer "
            "F.3.5.3-7. (3) Placas de enchape en zona de panel — colocadas directamente "
            "en el alma cuando esta no cumple (2), o separadas del alma. En contacto "
            "con el alma: soldadas a las aletas de la columna con soldaduras acanaladas "
            "de penetración completa o de filete capaces de desarrollar toda la "
            "resistencia de diseño a cortante; sin placas de continuidad, unidas con "
            "filete arriba y abajo para desarrollar la porción de fuerza total "
            "transmitida, salvo que cumplan (2). Separadas del alma: en pares "
            "simétricos entre 1/3 y 2/3 de la distancia entre el borde de la aleta de "
            "la viga y el eje de la columna, unidas con soldadura acanalada de "
            "penetración completa a las aletas de columna para desarrollar la "
            "resistencia completa. Sin placas de continuidad: extenderse mínimo 150 mm "
            "arriba y debajo de la parte superior/inferior de la viga de mayor peralte "
            "conectada a momento.\n"
            "F.3.5.3.6.6 Placas de continuidad: (1) requeridas excepto cuando: (a) se "
            "determine en precalificación (F.3.11.1) o programa de ensayos (F.3.11.2); "
            "(b) la aleta de la viga soldada a la aleta de columna laminada/armada "
            "sección I cumple tcf >= 0.4*raiz[1.8*bbf*tbf*(Fyb*Ryb)/(Fyc*Ryc)]  "
            "(F.3.5.3-8) y tcf >= bbf/6  (F.3.5.3-9), donde tcf=espesor mínimo aleta "
            "columna sin placas, mm; bbf=ancho aleta viga, mm; tbf=espesor aleta viga, "
            "mm; Fyb=esfuerzo fluencia mínimo aleta columna, MPa; Ryb=relación "
            "fluencia esperada/mínima del material de la viga; Ryc=relación fluencia "
            "esperada/mínima del material de la columna; (c) aleta soldada a columna "
            "de perfil I encajonado cumpliendo tcf >= 0.4*raiz[(1-bbf/bcf²)*(bcf-bbf/4)*"
            "1.8*bbf*tbf*(Fyb*Ryb)/(Fyc*Ryc)]  (F.3.5.3-10) y tcf >= bf/12  "
            "(F.3.5.3-11); (d) para conexiones pernadas, aplicar ANSI/AISC 358. (2) "
            "Espesor: conexiones exteriores (1 lado columna), mitad del espesor de la "
            "aleta de viga como mínimo; conexiones interiores (2 lados), igual al "
            "espesor más grueso de las aletas de vigas a ambos lados. Deben cumplir "
            "también F.2.10.10. (3) Soldaduras de placas de continuidad — a las aletas "
            "de columna con soldaduras acanaladas de penetración completa; al alma con "
            "soldaduras acanaladas o de filete. Resistencia requerida de la suma de "
            "uniones soldadas al alma de columna = la menor entre: (a) suma resistencias "
            "diseño a tensión de áreas de contacto con aletas de columna que tienen "
            "aletas de vigas conectadas; (b) resistencia diseño a cortante del área de "
            "contacto de la placa con el alma de la columna; (c) resistencia diseño a "
            "cortante de la zona de panel; (d) suma de resistencias a fluencia "
            "esperadas de aletas de viga que transmiten fuerza a las placas.\n"
            "F.3.5.3.6.7 Empalmes de columna — deben cumplir F.3.4.2.5; con soldaduras, "
            "de penetración completa. Con pernos, resistencia requerida a flexión "
            ">= Ry*Fy*Zx de la menor columna; resistencia requerida a cortante de "
            "empalmes del alma >= suma(Mpc)/H, donde suma(Mpc) es la suma de "
            "resistencias plásticas nominales a flexión de columnas arriba/abajo del "
            "empalme. Excepción: la resistencia requerida no necesita ser mayor que la "
            "determinada por análisis no lineal (F.3.3), considerando factores de "
            "concentración de esfuerzos o de intensidad de esfuerzos de mecánica de "
            "fracturas."
        ),
    },
    {
        "id": "NSR10-F-F_3_5_4_PCD",
        "seccion": "F.3.5.4 (Pórticos con Cerchas Dúctiles PCD — segmento especial, arriostramiento, miembros, conexiones)",
        "titulo": (
            "Pórticos con Cerchas Dúctiles (PCD): cerchas horizontales con un segmento "
            "especial dúctil (viga Vierendeel o diagonal en X) entre 0.25-0.75 de la "
            "luz, resistencia vertical a cortante esperada Vne con fórmula completa, "
            "límites geométricos (luz≤20m, peralte≤1.8m), arriostramiento y zonas "
            "protegidas."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.5.4 — PÓRTICOS CON CERCHAS DÚCTILES (PCD).\n"
            "F.3.5.4.1 Alcance — los PCD deben satisfacer los requisitos de esta "
            "sección.\n"
            "F.3.5.4.2 Bases de diseño — capacidad de soportar deformaciones "
            "inelásticas significativas dentro de un segmento de cercha especialmente "
            "diseñado. Límites: luces entre columnas <=20 m, peralte total de la "
            "cercha <=1.8 m. Columnas y segmentos de cercha por fuera del segmento "
            "especial se diseñan para permanecer elásticos bajo las cargas generadas "
            "por la fluencia total y endurecimiento por deformación del segmento "
            "especial.\n"
            "F.3.5.4.3 Análisis — F.3.5.4.3.1 Segmento especial: resistencia vertical a "
            "cortante requerida se calcula con las combinaciones del Título B. "
            "F.3.5.4.3.2 Segmento no especial: resistencia requerida de elementos "
            "fuera del segmento especial y sus conexiones se calcula con combinaciones "
            "del Título B incluyendo la carga sísmica amplificada; Emh se determina a "
            "partir de las fuerzas laterales necesarias para desarrollar la resistencia "
            "vertical a cortante esperada del segmento especial, actuando en el centro "
            "de la luz (F.3.5.4.5.2), incluyendo efectos de segundo orden para la "
            "máxima deriva de diseño.\n"
            "F.3.5.4.4 Requisitos del sistema:\n"
            "F.3.5.4.4.1 Segmento especial — cada cercha horizontal del SRS debe tener "
            "un segmento especial localizado en la zona central entre 0.25 y 0.75 de la "
            "luz de la cercha. Longitud del segmento entre 0.1 y 0.5 veces la luz. "
            "Relación longitud-altura de cualquier panel del segmento especial <=1.5 ni "
            "<0.67. Paneles dentro del segmento especial: todos viga Vierendeel o todos "
            "arriostrados en X; no se permite combinar ni otras configuraciones "
            "diagonales. Diagonales del segmento especial en X separados por elementos "
            "verticales, fabricadas con platinas de la misma sección, interconectadas "
            "en los puntos de cruce con resistencia adecuada para resistir al menos "
            "0.25 veces la resistencia nominal a tensión del miembro diagonal. No se "
            "permiten conexiones pernadas para miembros del alma dentro del segmento "
            "especial. No se permite empate de miembros de cuerdas dentro del segmento "
            "especial ni a distancia menor a la mitad de la longitud del panel fuera de "
            "él. Resistencias axiales requeridas de diagonales en el segmento especial "
            "por cargas vivas y muertas no deben exceder 0.03*Fy*Ag.\n"
            "F.3.5.4.4.2 Arriostramiento para estabilidad de la cercha — cada aleta de "
            "cuerda del segmento especial debe estar arriostrada lateralmente en los "
            "extremos; resistencia requerida de la riostra: Pu = 0.06*Ry*Fy*Af  "
            "(F.3.5.4-1), donde Af=área bruta de la aleta del miembro de cuerda del "
            "segmento especial, mm2.\n"
            "F.3.5.4.4.3 Arriostramiento para estabilidad de conexiones cercha-columna "
            "— la columna debe estar arriostrada lateralmente al nivel de cuerdas "
            "superior e inferior de cerchas conectadas: Pu = 0.02*Ry*Pnc  (F.3.5.4-2), "
            "donde Pnc=resistencia nominal a compresión de miembros de la cuerda en los "
            "extremos, N.\n"
            "F.3.5.4.4.4 Rigidez del arriostramiento para estabilidad — según F.2.20: "
            "Pr = Ry*Pnc  (F.3.5.4-3)\n"
            "F.3.5.4.5 Miembros:\n"
            "F.3.5.4.5.1 Miembros del segmento especial — resistencia de diseño a "
            "cortante = suma de resistencia diseño a cortante por flexión de miembros "
            "de cuerda + 0.3 veces la resistencia diseño a compresión de miembros "
            "diagonales (cuando se usen). Miembros de cuerdas superior/inferior en el "
            "segmento especial deben ser de la misma sección, y proveer al menos 25% de "
            "la resistencia vertical a cortante requerida. La resistencia de diseño "
            "phi*Pn por fluencia a tensión debe ser >= 2.2 veces la resistencia "
            "requerida, phi=0.9, con Pn = Fy*Ag  (F.3.5.4-4).\n"
            "F.3.5.4.5.2 Resistencia vertical a cortante esperada del segmento especial "
            "(al centro de la luz):\n"
            "Vne = (3.60*Ry*Mnc/Ls) + (0.036*E*I*(L-Ls)/Ls^3) + Ry*(Pnt+0.3*Pnc)*sen(α)  "
            "(F.3.5.4-5)\n"
            "donde: Mnc=resistencia nominal a flexión de un miembro de cuerda del "
            "segmento especial, N·mm; E=módulo de elasticidad de un miembro de cuerda, "
            "N/mm2; I=momento de inercia de un miembro de cuerda, mm4; L=luz de la "
            "cercha, mm; Ls=longitud del segmento especial, mm; Pnt=resistencia "
            "nominal a tensión de un miembro diagonal, N; Pnc=resistencia nominal a "
            "compresión de un miembro diagonal, N; α=ángulo que forma un miembro "
            "diagonal con la horizontal, grados.\n"
            "F.3.5.4.5.3 Límites de la relación ancho-espesor — miembros de cuerdas y "
            "miembros diagonales del alma dentro del segmento especial deben cumplir "
            "F.3.4.1.1.2 para miembros de ductilidad alta; relaciones ancho-espesor de "
            "platinas de miembros diagonales no mayores que 2.5.\n"
            "F.3.5.4.5.4 Miembros de cuerdas armados — espaciamiento de uniones no "
            "mayor que 0.04*E*ry/Fy, ry=radio de giro de componentes individuales "
            "respecto a su eje débil.\n"
            "F.3.5.4.5.5 Zonas protegidas — la región en cada extremo de un miembro de "
            "cuerda dentro del segmento especial es zona protegida, cumple F.3.4.1.3; "
            "se extiende una longitud igual a dos veces el peralte del miembro de "
            "cuerda desde la conexión con los miembros del alma de la cercha. Los "
            "miembros del alma verticales y diagonales de extremo a extremo del "
            "segmento especial son zonas protegidas.\n"
            "F.3.5.4.6 Conexiones: F.3.5.4.6.1 Soldaduras de demanda crítica: (1) "
            "soldaduras acanaladas en empalmes de columna; (2) soldaduras de conexión "
            "columna-placa base, salvo que se demuestre que se impide la formación de "
            "rótula. F.3.5.4.6.2 Conexiones de miembros diagonales en el segmento "
            "especial: resistencia requerida al menos igual a la resistencia a "
            "fluencia esperada a tensión de los miembros diagonales, Ry*Fy*Ag. "
            "F.3.5.4.6.3 Empalmes de columnas — cumplir F.3.4.2.5; con soldaduras, de "
            "penetración completa. Con pernos, resistencia requerida a flexión >= "
            "Ry*Fy*Zx de la menor columna; resistencia requerida a cortante del "
            "empalme de alma >= suma(Mpc)/H."
        ),
    },
    {
        "id": "NSR10-F-F_3_5_5_a_F_3_5_6",
        "seccion": "F.3.5.5 a F.3.5.6 (Sistemas de Columnas en Voladizo con disipación de energía mínima SCV-DMI y especial SCV-DES)",
        "titulo": (
            "Sistemas de columnas en voladizo (SCV): resistencia axial requerida "
            "limitada al 15% de la resistencia de diseño para ambos niveles de "
            "disipación (DMI y DES); DES requiere además ductilidad alta en miembros, "
            "arriostramiento de vigas de ductilidad moderada, zonas protegidas en la "
            "base y soldaduras de demanda crítica."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.5.5 — SISTEMAS DE COLUMNAS EN VOLADIZO CON DISIPACIÓN DE ENERGÍA "
            "MÍNIMA (SCV-DMI).\n"
            "F.3.5.5.1 Alcance — diseñarse de conformidad con esta sección.\n"
            "F.3.5.5.2 Bases de diseño — se espera capacidad mínima de soportar "
            "derivas inelásticas por fluencia a flexión de las columnas.\n"
            "F.3.5.5.3 Análisis — no se especifican requisitos especiales.\n"
            "F.3.5.5.4 Requisitos del sistema: F.3.5.5.4.1 Columnas — diseñarse con "
            "combinaciones de carga que incluyan la carga sísmica amplificada; la "
            "resistencia axial requerida Prc no debe exceder el 15% de la resistencia "
            "axial de diseño Pc para estas combinaciones únicamente. F.3.5.5.4.2 "
            "Arriostramiento para estabilidad de columnas — no se especifican "
            "requisitos especiales.\n"
            "F.3.5.5.5 Miembros: F.3.5.5.5.1 Requisitos básicos — no se especifican "
            "requisitos especiales. F.3.5.5.5.2 Aletas de columnas — no se especifican "
            "requisitos especiales. F.3.5.5.5.3 Zonas protegidas — no se especifican "
            "zonas protegidas.\n"
            "F.3.5.5.6 Conexiones: F.3.5.5.6.1 Soldaduras de demanda crítica — no se "
            "especifican. F.3.5.5.6.2 Bases de columnas — no se especifican requisitos.\n\n"
            "F.3.5.6 — SISTEMAS DE COLUMNAS EN VOLADIZO CON DISIPACIÓN DE ENERGÍA "
            "ESPECIAL (SCV-DES).\n"
            "F.3.5.6.1 Alcance — diseñarse de conformidad con esta sección.\n"
            "F.3.5.6.2 Bases de diseño — se espera capacidad LIMITADA de soportar "
            "derivas inelásticas por fluencia a flexión de las columnas.\n"
            "F.3.5.6.3 Análisis — no se especifican requisitos especiales.\n"
            "F.3.5.6.4 Requisitos del sistema: F.3.5.6.4.1 Columnas — combinaciones "
            "incluyendo carga sísmica amplificada; Prc no debe exceder 15% de Pc para "
            "estas combinaciones únicamente. F.3.5.6.4.2 Arriostramiento para "
            "estabilidad — las columnas deben estar arriostradas de manera que "
            "satisfagan los requisitos aplicables a vigas de ductilidad moderada "
            "(F.3.4.1.2.1).\n"
            "F.3.5.6.5 Miembros: F.3.5.6.5.1 Requisitos básicos — miembros de columnas "
            "satisfacen F.3.4.1.1 para ductilidad alta. F.3.5.6.5.2 Aletas de columnas "
            "— prohibidos cambios abruptos en aletas designadas como zonas protegidas "
            "(F.3.5.6.5.3). F.3.5.6.5.3 Zonas protegidas — la región en la base de la "
            "columna sujeta a deformaciones inelásticas es zona protegida (F.3.4.1.3), "
            "longitud igual a dos veces el peralte de la columna, salvo que se "
            "determine de otra manera mediante ensayos.\n"
            "F.3.5.6.6 Conexiones: F.3.5.6.6.1 Soldaduras de demanda crítica — según "
            "F.3.1.3.4.2: (1) soldaduras acanaladas en empalmes de columna; (2) "
            "soldaduras de conexiones columna-placa base. F.3.5.6.6.2 Bases de "
            "columnas — deben diseñarse de acuerdo con F.3.4.2.6."
        ),
    },
    {
        "id": "NSR10-F-F_3_6_1_PAC_DMI",
        "seccion": "F.3.6 intro + F.3.6.1 (Sistemas Arriostrados y Muros de Cortante intro; PAC-DMI completo)",
        "titulo": (
            "Intro al numeral F.3.6 (sistemas arriostrados y muros de cortante: PAC-DMI/"
            "DES, PAE, PAPR, MCA-DES). PAC-DMI completo: estructuras con riostras en V/"
            "V invertida (vigas continuas, distribución de fuerzas tensión/compresión "
            "0.3Pn), prohibición de K, esbeltez KL/r≤4√(E/Fy), PAC-DMI sobre "
            "aisladores sísmicos."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.6 — SISTEMAS ARRIOSTRADOS Y MUROS DE CORTANTE — bases de diseño y "
            "requisitos de análisis, sistema, miembros y conexiones para PAC-DMI, "
            "PAC-DES, PAE, PAPR y MCA-DES. Secciones: F.3.6.1 Pórticos arriostrados "
            "concéntricamente con capacidad mínima (PAC-DMI), F.3.6.2 PAC con "
            "capacidad especial (PAC-DES), F.3.6.3 Pórticos arriostrados "
            "excéntricamente (PAE), F.3.6.4 Pórticos arriostrados de pandeo "
            "restringido (PAPR), F.3.6.5 Muros de cortante de acero (MCA-DES).\n\n"
            "F.3.6.1 — PÓRTICOS ARRIOSTRADOS CONCÉNTRICAMENTE CON CAPACIDAD DE "
            "DISIPACIÓN DE ENERGÍA MÍNIMA (PAC-DMI).\n"
            "F.3.6.1.1 Alcance — en estructuras aisladas sísmicamente, los PAC-DMI "
            "deben cumplir F.3.6.1.4.2, F.3.6.1.5, F.3.6.1.6 y F.3.6.1.7, y no se "
            "requiere que satisfagan F.3.6.1.4.1.\n"
            "F.3.6.1.2 Bases de diseño — aplica a pórticos arriostrados con miembros "
            "arriostrados concéntricamente. Se permiten excentricidades menores que el "
            "peralte de la viga si se tienen en cuenta en el diseño (momentos por "
            "excentricidad evaluados con la carga sísmica amplificada). Deben tener "
            "capacidad de soportar deformaciones inelásticas LIMITADAS en miembros y "
            "conexiones.\n"
            "F.3.6.1.3 Análisis — no se especifican requisitos especiales.\n"
            "F.3.6.1.4 Requisitos del sistema: F.3.6.1.4.1 Estructuras con riostras en "
            "V y V invertida — vigas continuas en las conexiones de riostra fuera de "
            "la conexión viga-columna, y deben satisfacer: (1) resistencia requerida "
            "con combinaciones del Título B suponiendo que las riostras no dan soporte "
            "a carga viva/muerta; para combinaciones con sismo, E se calcula: (a) "
            "fuerzas en riostras a tensión = la menor entre resistencia a fluencia "
            "esperada a tensión (Ry*Fy*Ag), efecto de la carga con sobreresistencia, "
            "y máxima fuerza desarrollable por el sistema; (b) fuerzas en riostras a "
            "compresión = 0.3*Pn. (2) como mínimo se requiere un juego de riostras "
            "laterales en el punto de intersección, salvo que el miembro tenga "
            "suficiente resistencia y rigidez fuera del plano. F.3.6.1.4.2 Estructuras "
            "con riostras en K — no permitidas para PAC-DMI.\n"
            "F.3.6.1.5 Miembros: F.3.6.1.5.1 Requisitos básicos — riostras satisfacen "
            "F.3.4.1.1 para ductilidad moderada. F.3.6.1.5.2 Esbeltez — riostras en "
            "V o V invertida cumplen KL/r <= 4*raiz(E/Fy).\n"
            "F.3.6.1.6 Conexiones: F.3.6.1.6.1 Conexiones de riostras diagonales — "
            "resistencia requerida = el efecto de la carga sísmica amplificada, sin "
            "necesidad de ser mayor que: (1) la máxima fuerza desarrollable por el "
            "sistema; (2) en tensión, la resistencia a fluencia esperada Ry*Fy*Ag; (3) "
            "en compresión, la resistencia esperada a compresión, la menor entre "
            "Ry*Fy*Ag y 1.14*Fcre*Ag, con Fcre según F.2.5 usando el esfuerzo a "
            "fluencia esperado Ry*Fy en vez de Fy — longitud de riostra usada para "
            "Fcre no mayor que la distancia entre extremos de la riostra; (4) con "
            "perforaciones agrandadas, la resistencia requerida para deslizamiento de "
            "pernos no necesita ser mayor que el efecto con combinaciones del Título B "
            "sin carga sísmica amplificada.\n"
            "F.3.6.1.7 PAC-DMI sobre sistemas con aisladores sísmicos: F.3.6.1.7.1 "
            "Requisitos del sistema — vigas en V y V invertida continuas entre "
            "columnas. F.3.6.1.7.2 Miembros — riostras con relación de esbeltez "
            "KL/r <= 4*raiz(E/Fy)."
        ),
    },
    {
        "id": "NSR10-F-F_3_6_2_PAC_DES",
        "seccion": "F.3.6.2 (Pórticos Arriostrados Concéntricamente con capacidad de disipación de energía especial PAC-DES)",
        "titulo": (
            "PAC-DES completo: fluencia dúctil por pandeo de riostra y fluencia a "
            "tensión, análisis con carga sísmica amplificada (mayor entre riostras "
            "todas a resistencia esperada vs. tensión+post-pandeo 0.3Fcr), "
            "distribución de fuerzas 30-70%, esbeltez KL/r≤200, prohibición de K y "
            "de riostras a tensión únicamente, zonas protegidas, conexiones."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.6.2 — PÓRTICOS ARRIOSTRADOS CONCÉNTRICAMENTE CON CAPACIDAD DE "
            "DISIPACIÓN DE ENERGÍA ESPECIAL (PAC-DES).\n"
            "F.3.6.2.1 Alcance — deben diseñarse de acuerdo con esta sección.\n"
            "F.3.6.2.2 Bases de diseño — pórticos arriostrados con miembros "
            "arriostrados concéntricamente; se permiten excentricidades menores que el "
            "peralte de la viga si se consideran en el diseño del miembro y sus "
            "fuerzas de conexión, sin cambiar la fuente de capacidad de deformación "
            "inelástica esperada. Deben soportar deformaciones inelásticas "
            "SIGNIFICATIVAS principalmente a partir del pandeo de la riostra y la "
            "fluencia de la riostra en tensión.\n"
            "F.3.6.2.3 Análisis — resistencia requerida de columnas, vigas y "
            "conexiones basada en combinaciones del Título B incluyendo la carga "
            "sísmica amplificada; Emh calculada como la MAYOR fuerza determinada de "
            "dos análisis: (1) las riostras actúan con las fuerzas correspondientes a "
            "su resistencia esperada en compresión o en tensión; (2) las riostras a "
            "tensión actúan con las fuerzas de su resistencia esperada y TODAS las "
            "riostras en compresión actúan con su resistencia esperada a post-pandeo. "
            "La determinación de si las riostras están en compresión o tensión se hace "
            "sin incluir los efectos de gravedad; el análisis debe considerar las 2 "
            "direcciones de carga. Resistencia esperada a tensión de la riostra: "
            "Ry*Fy*Ag. Resistencia esperada a compresión: la menor entre Ry*Fy*Ag y "
            "1.14*Fcre*Ag (Fcre según F.2.5 con esfuerzo esperado Ry*Fy en vez de Fy, "
            "longitud no mayor que la distancia entre extremos). Resistencia a "
            "post-pandeo esperada = máximo 0.3 veces la resistencia esperada a "
            "compresión; para esbeltez límite 200 (F.3.6.2.5.2), este valor es 15 MPa "
            "— puede usarse como estimación conservadora para cualquier esbeltez, o "
            "alternativamente 0 para simplificar. Excepciones: (1) se permite "
            "despreciar momentos por deriva sísmica en estos cálculos, pero considerar "
            "momentos por cargas aplicadas a la columna entre puntos de soporte "
            "lateral; (2) resistencia requerida de columnas no mayor que la menor "
            "entre: (a) fuerzas con combinaciones del Título B con carga sísmica "
            "amplificada, con todas las riostras a compresión retiradas del modelo; "
            "(b) fuerzas correspondientes a la resistencia de la fundación al "
            "levantamiento; (c) fuerzas de análisis no lineal (F.3.3.3).\n"
            "F.3.6.2.4 Requisitos del sistema: F.3.6.2.4.1 Distribución de fuerzas "
            "laterales — riostras dispuestas en direcciones alternadas a lo largo de "
            "cualquier eje de arriostramiento, tal que para cualquier dirección de "
            "fuerza, al menos 30% pero no más de 70% de la fuerza horizontal total "
            "sea resistida por riostras a tensión — a menos que la resistencia nominal "
            "de cada riostra en compresión sea mayor que la requerida con carga "
            "sísmica amplificada. Eje de arriostramiento = eje único o ejes paralelos "
            "que no se desvían en planta más de 10% de la dimensión del edificio "
            "perpendicular al eje. F.3.6.2.4.2 Estructuras con riostras V/V invertida "
            "— vigas continuas entre columnas; vigas conectadas a riostras satisfacen "
            "ductilidad moderada (F.3.4.1.2.1); juego de riostras laterales en el "
            "punto de intersección, salvo suficiente rigidez fuera del plano; la "
            "fuerza F.2.19-7 se aplica en cada aleta formando un par torsional, "
            "conjuntamente con las fuerzas de flexión, y la rigidez debe satisfacer "
            "F.3.1.19-8. F.3.6.2.4.3 Riostras en K — no permitidas. F.3.6.2.4.4 "
            "Pórticos con riostras a tensión únicamente — no permitidos.\n"
            "F.3.6.2.5 Miembros: F.3.6.2.5.1 Requisitos básicos — columnas y riostras "
            "satisfacen F.3.4.1.1 para ductilidad alta; vigas satisfacen F.3.4.1.1 "
            "para ductilidad moderada. F.3.6.2.5.2 Riostras diagonales: (1) esbeltez "
            "KL/r <= 200; (2) riostras armadas — espaciamiento de conectores tal que "
            "l/r de elementos individuales entre conectores no exceda 0.4 veces la "
            "esbeltez del miembro armado; resistencia de diseño a cortante de "
            "conectores >= resistencia de diseño a tensión de cada elemento; "
            "espaciamiento uniforme, mínimo 2 conectores, ninguno en el cuarto medio "
            "de la longitud libre (excepción: cuando el pandeo respecto al eje crítico "
            "no genera cortante en conectores, espaciamiento tal que l/r no exceda "
            "0.75 veces la esbeltez del miembro fabricado que gobierna); (3) área neta "
            "efectiva no menor que el área bruta; con reforzamiento, resistencia "
            "mínima especificada a fluencia del refuerzo como mínimo igual a la "
            "resistencia a fluencia de la riostra, conexiones del refuerzo con "
            "resistencia suficiente para desarrollar la resistencia esperada del "
            "refuerzo a cada lado de la sección reducida. F.3.6.2.5.3 Zonas "
            "protegidas — para riostras: el cuarto central de la longitud, y zona "
            "adyacente a cada conexión igual al peralte de la riostra en el plano de "
            "pandeo; elementos que conectan riostras a vigas y columnas.\n"
            "F.3.6.2.6 Conexiones: F.3.6.2.6.1 Soldaduras de demanda crítica — según "
            "F.3.1.3.4.2: (1) empalmes de columna; (2) conexión columna-placa de base, "
            "salvo que se demuestre impedimento de rótula; (3) conexiones "
            "viga-columna según F.3.6.2.6.2(2). F.3.6.2.6.2 Conexiones viga-columna — "
            "cuando un miembro diagonal o su cartela conecta a viga y columna: (1) "
            "conexión simple (rotación requerida 0.025 rad, F.2.2.3.6.1); o (2) "
            "diseñada para momento igual al menor de: (a) 1.1*Ry*Fy*Z de la viga; (b) "
            "suma(1.1*Ry*Fy*Z) de la columna — este momento se considera en "
            "combinación con la resistencia requerida de la conexión de la riostra y "
            "de la viga incluyendo fuerzas amplificadas del diafragma colector. "
            "F.3.6.2.6.3 Resistencia requerida de conexiones de riostra (independiente "
            "entre sí, sin interacción): (1) tensión — la menor entre: (a) resistencia "
            "esperada a fluencia a tensión Ry*Fy*Ag (excepto sección reducida por "
            "ranurado de PTE, sin requisito de F.2.10.4-1/4-2, resistencia según "
            "F.3.1.3.2); (b) fuerza máxima transferible por análisis racional; con "
            "perforaciones agrandadas, resistencia requerida deslizamiento no mayor "
            "que combinaciones sin sismo amplificado. (2) compresión — >= 1.1 veces la "
            "resistencia esperada a compresión (F.3.6.2.3(2)). (3) restricciones al "
            "pandeo de la riostra — cumpliendo (a) resistencia a flexión mínima "
            "1.1*Ry*Mp respecto al eje crítico de pandeo, o (b) capacidad de rotación "
            "suficiente (tolerancia verificada típicamente con cartela única, "
            "distancia mínima igual al doble del espesor de la cartela entre extremo "
            "de riostra y línea de fluencia). F.3.6.2.6.4 Empalmes de columnas — "
            "F.3.4.2.5, soldaduras acanaladas de penetración completa, desarrollar al "
            "menos 50% de la menor resistencia de diseño a flexión; planos de "
            "fabricación/montaje según F.3.1.4.3; resistencia requerida a cortante "
            "suma(Mpc)/Hc."
        ),
    },
    {
        "id": "NSR10-F-F_3_6_3_PAE_completo",
        "seccion": "F.3.6.3 (Pórticos Arriostrados Excéntricamente PAE — completo: bases, análisis, requisitos sistema, vínculos, conexiones)",
        "titulo": (
            "PAE completo: vínculo (segmento de viga entre riostras) sujeto a "
            "cortante+flexión, resistencia a cortante Vn=menor(Vp, 2Mp/e), límites de "
            "longitud del vínculo según relación ρ', ángulo de rotación (0.08 rad "
            "vínculos cortos, 0.02 rad largos), rigidizadores de alma, conexiones "
            "vínculo-columna."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.6.3 — PÓRTICOS ARRIOSTRADOS EXCÉNTRICAMENTE (PAE).\n"
            "F.3.6.3.1 Alcance — diseñarse según esta sección.\n"
            "F.3.6.3.2 Bases de diseño — un extremo de cada riostra intercepta una "
            "viga con excentricidad desde la intersección de ejes de viga y riostra "
            "adyacente o columna, formando un vínculo sujeto a cortante y flexión. Se "
            "permiten excentricidades menores que el peralte de la viga en la conexión "
            "lejana del vínculo si se consideran las fuerzas resultantes. Capacidad de "
            "deformación inelástica significativa por fluencia a cortante de los "
            "vínculos. Vínculos conectados directamente a columnas: diseño de la "
            "conexión vínculo-columna debe garantizar desempeño según F.3.6.3.6.5.\n"
            "F.3.6.3.3 Análisis — resistencia requerida de riostras diagonales y "
            "conexiones, vigas fuera del vínculo y columnas: combinaciones del Título "
            "B con carga sísmica amplificada; Emh calculada como las fuerzas "
            "desarrolladas en el miembro suponiendo que las fuerzas en extremos del "
            "vínculo corresponden a la resistencia a cortante ajustada del vínculo, "
            "Ry veces la resistencia a cortante nominal Vn (F.3.6.3.5.2(2)), "
            "multiplicada por 1.25 (secciones I) o 1.4 (secciones cajón). Excepciones: "
            "(1) Emh puede tomarse como 0.88 veces las fuerzas anteriores para: (a) "
            "parte de vigas fuera del vínculo; (b) columnas en estructuras de 3+ "
            "pisos; (2) se pueden despreciar momentos por deriva, pero considerar los "
            "de cargas aplicadas entre puntos de soporte lateral; (3) resistencia "
            "requerida de columnas no mayor que la menor entre fuerzas de "
            "levantamiento de fundación o análisis no lineal (F.3.3.3). Ángulo de "
            "rotación inelástico del vínculo se determina de la porción inelástica de "
            "la deriva de diseño, o de análisis no lineal.\n"
            "F.3.6.3.4 Requisitos del sistema: F.3.6.3.4.1 Ángulo de rotación del "
            "vínculo — ángulo inelástico entre vínculo y viga fuera de él, cuando la "
            "deriva total = deriva de diseño; no debe exceder: (a) 0.08 rad para "
            "vínculos de longitud <=1.6*Mp/Vp; (b) 0.02 rad para longitud "
            ">=2.6*Mp/Vp; (c) interpolación lineal entre 1.6Mp/Vp y 2.6Mp/Vp. "
            "F.3.6.3.4.2 Arriostramiento del vínculo — ambas aletas arriostradas en "
            "extremos para secciones I, con resistencia y rigidez adecuada para "
            "desarrollar la rótula plástica según F.3.4.1.2.2 para ductilidad alta.\n"
            "F.3.6.3.5 Miembros: F.3.6.3.5.1 Requisitos básicos — arriostramiento "
            "cumple límites ancho-espesor F.3.4.1.1 para ductilidad moderada; viga "
            "fuera del vínculo (si diferente sección) también. Riostra diagonal y "
            "segmento de viga fuera del vínculo se dimensionan para permanecer "
            "esencialmente elásticos bajo fuerzas del vínculo fluyendo completamente "
            "con endurecimiento, tratándose como vigas-columnas (F.2.8). Cuando la "
            "viga fuera del vínculo esté en el mismo miembro del vínculo, resistencia "
            "según propiedades esperadas (F.3.1.3.2).\n"
            "F.3.6.3.5.2 Vínculos — vigas-vínculo sometidas a flexión y cortante por "
            "excentricidades entre ejes de riostras y viga. Longitud medida como "
            "distancia libre entre conexiones de riostras para vínculos centrales, o "
            "distancia libre entre riostra y cara de columna para vínculos adyacentes "
            "a columnas (salvo F.3.6.3.6.3). (1) Limitaciones — secciones I "
            "(laminadas/armadas) o cajón armadas; no PTE. Cumplen F.3.4.1.1 para "
            "ductilidad alta (excepción: aletas de vínculos I con e<=1.6*Mp/Vp pueden "
            "satisfacer ductilidad moderada). Alma(s) de una pieza, sin refuerzo con "
            "placas de enchape ni perforaciones. Vínculos con secciones armadas: "
            "soldaduras acanaladas de penetración completa alma-aletas. Vínculos cajón "
            "armados: Iv (momento inercia respecto eje plano PAE) > 0.67*Ix. (2) "
            "Resistencia a cortante — phi_v*Vn, phi_v=0.9, menor entre fluencia a "
            "cortante en alma y fluencia por flexión: (a) fluencia por cortante: "
            "Vn=Vp  (F.3.6.3-1), donde Vp=0.6*Fy*Alw para Pu/Py<=0.15  (F.3.6.3-2), o "
            "Vp=0.6*Fy*Alw*raiz(1-(Pu/Py)^2) para Pu/Py>0.15  (F.3.6.3-3); "
            "Alw=(d-2tf)*tw para vínculos I  (F.3.6.3-4), Alw=2*(d-2tf)*tw para "
            "vínculos cajón  (F.3.6.3-5); Pu=resistencia axial requerida, N; "
            "Py=resistencia axial nominal a fluencia=Fy*Ag  (F.3.6.3-6); (b) fluencia "
            "por flexión: Vn=2*Mp/e  (F.3.6.3-7), donde Mp=Fy*Z para Pu/Py<=0.15  "
            "(F.3.6.3-8), o Mp=Fy*Z*[(1-Pu/Py)/0.85] para Pu/Py>0.15  (F.3.6.3-9); "
            "e=longitud del vínculo, distancia libre entre extremos de riostras "
            "diagonales o entre riostra y cara de columna, mm. (3) Longitud del "
            "vínculo — si Pu/Py>1.5, limitarse: cuando ρ'<=0.5, e<=1.6*Mp/Vp  "
            "(F.3.6.3-10); cuando ρ'>0.5, e<=(1.6*Mp/Vp)*(1.15-0.3*ρ')  "
            "(F.3.6.3-11); donde ρ'=(Pu/Py)/(Vu/Vy)  (F.3.6.3-12); Vu=resistencia "
            "cortante requerida, N; Vy=resistencia cortante nominal a fluencia = "
            "0.6*Fy*Alw, N  (F.3.6.3-13). Para vínculos con fuerzas axiales bajas no "
            "hay límite superior de longitud; los límites del ángulo de rotación "
            "(F.3.6.3.4.1) son prácticamente un límite inferior. (4) Rigidizadores en "
            "vínculos I — al alma en toda su altura, ambos lados, en extremos de la "
            "riostra diagonal; ancho combinado no menor que (bf-2tw), espesor no "
            "menor que 0.75*tw ni 10mm. Rigidizadores intermedios: (a) vínculos de "
            "longitud <=1.6*Mp/Vp — espaciados en intervalos que no excedan "
            "(30*tw-d/5) para rotación 0.08 rad, o (52*tw-d/5) para 0.02 rad o menos "
            "(interpolar entre 0.02-0.08 rad); (b) longitud entre 2.6Mp/Vp y 5Mp/Vp — "
            "espaciados a 1.5*bf desde cada extremo; (c) longitud entre 1.6Mp/Vp y "
            "2.6Mp/Vp — cumplir (a) y (b); (d) longitud >5Mp/Vp — no requieren "
            "rigidizadores intermedios; (e) extenderse en toda la altura; vínculos "
            "<635mm de altura solo requieren rigidizadores a un lado (espesor "
            ">= tw o 10mm, ancho >= bf/2-tw); alturas >=635mm requieren ambos lados. "
            "Resistencia requerida de soldaduras de filete: rigidizador-alma = "
            "Ast*Fy; rigidizador-aletas = Ast*Fy/4. (5) Rigidizadores en vínculos "
            "cajón — un lado de cada alma, en toda su altura, en la conexión de "
            "riostra diagonal; ancho >= b/2 (b=ancho interior del cajón), espesor "
            ">= 0.75*tw o 13mm. Intermedios: (a) longitud<=1.6Mp/Vp con h/tw>=0.64*"
            "raiz(E/Fy) — un lado, espaciados sin exceder 20*tw-(d-2tf)/8; (b) "
            "longitud<=1.6Mp/Vp con h/tw<0.64*raiz(E/Fy) — no requieren; (c) "
            "longitud>1.6Mp/Vp — no requieren; (d) extenderse en toda la altura, "
            "soldarse a cara interior/exterior de almas. Soldaduras de filete: "
            "Ast*Fy; no es necesario soldar a las aletas del cajón.\n"
            "F.3.6.3.5.3 Zonas protegidas — vínculos de PAE son zonas protegidas, "
            "cumplen F.3.4.1.3.\n"
            "F.3.6.3.6 Conexiones: F.3.6.3.6.1 Soldaduras de demanda crítica — según "
            "F.3.1.3.4.2: (1) empalmes de columna; (2) columna-placa de base (salvo "
            "impedimento de rótula); (3) según F.3.6.3.6.2(b).\n"
            "F.3.6.3.6.2 Conexiones viga-columna — cuando un miembro diagonal o su "
            "cartela conecta viga y columna: (1) simple (F.2.2.3.6.1, rotación "
            "requerida 0.025 rad); o (2) diseñada para momento igual al menor de (a) "
            "1.1*Ry*Fy*Z de la viga o (b) suma(1.1*Ry*Fy*Z) de la columna — "
            "considerado en combinación con la resistencia requerida de conexiones de "
            "riostra y de viga incluyendo fuerzas amplificadas del diafragma colector. "
            "F.3.6.3.6.3 Resistencia requerida de conexiones de riostra a tensión, "
            "compresión y flexión (incluyendo uniones viga-columna si son parte del "
            "arriostramiento) — se determinan según lo siguiente, pudiendo "
            "considerarse independientes sin interacción: (1) tensión — la menor "
            "entre: resistencia esperada a fluencia Ry*Fy*Ag (excepto perforaciones "
            "agrandadas, no requiere F.2.10.4-1/4-2, resistencia según F.3.1.3.2 para "
            "estados como bloque de cortante); fuerza máxima transferible por análisis "
            "racional; con perforaciones agrandadas, resistencia requerida "
            "deslizamiento no mayor que efectos sin sismo amplificado, para otros "
            "estados aplican cargas de (a)/(b). (2) compresión — resistencia basada en "
            "pandeo, al menos 1.1 veces la resistencia esperada a compresión "
            "(F.3.6.2.3(2)). (3) restricciones al pandeo de la riostra: (a) flexión — "
            "resistencia diseño mínima 1.1*Ry*Mp respecto al eje crítico de pandeo; (b) "
            "capacidad de rotación — suficiente para tolerar la rotación requerida "
            "para la deriva de diseño (típicamente con una sola cartela, distancia "
            "mínima igual al doble del espesor de la cartela entre extremo de riostra "
            "y línea de fluencia). F.3.6.3.6.4 Empalmes de columnas — F.3.4.2.5, "
            "soldaduras acanaladas de penetración completa, desarrollar al menos 50% "
            "de la menor resistencia de diseño a flexión conectada; planos según "
            "F.3.1.4.3; resistencia requerida a cortante suma(Mpc)/Hc. F.3.6.3.6.5 "
            "Conexiones vínculo-columna — deben ser conexiones a momento totalmente "
            "restringidas (TR), cumplir: (a) capacidad de soportar el ángulo de "
            "rotación (F.3.6.3.4.1); (b) resistencia a cortante medida al ángulo de "
            "rotación requerido >= resistencia a cortante esperada del vínculo Vn "
            "(F.3.6.3.3); (c) resistencia a flexión medida al ángulo de rotación "
            "requerido >= el momento correspondiente a la resistencia a cortante "
            "nominal del vínculo Vn (F.3.6.3.5.2(2)); (2) validación de la conexión — "
            "(a) conexión precalificada para PAE según F.3.11.2; o (b) resultados de "
            "ensayos cíclicos de calificación (mínimo 2, según F.3.11.2, basados en "
            "literatura o ensayos específicos del proyecto). Excepción — no se "
            "requieren ensayos cíclicos si: (1) reforzamiento de la conexión "
            "viga-columna en el vínculo que excluya la fluencia de la viga sobre la "
            "longitud reforzada; (2) resistencia de diseño de la sección reforzada y "
            "la conexión >= resistencia requerida con la resistencia a cortante "
            "ajustada del vínculo (F.3.6.3.3); (3) longitud del vínculo (segmento "
            "desde extremo del reforzamiento hasta la conexión de la riostra) no "
            "excede 1.6*Mp/Vp; (4) rigidizadores en la interfaz vínculo-sección "
            "reforzada según F.3.6.3.5.2(4)."
        ),
    },
    {
        "id": "NSR10-F-F_3_6_4_PAPR_completo",
        "seccion": "F.3.6.4 (Pórticos con Arriostramientos de Pandeo Restringido PAPR — completo)",
        "titulo": (
            "PAPR completo: riostra = núcleo de acero + sistema de restricción al "
            "pandeo, resistencia axial de diseño Pysc=Fysc·Asc, factores de ajuste β "
            "(compresión/tensión) y ω (endurecimiento por deformación) obtenidos de "
            "ensayos, deriva mínima 2% de altura de piso, validación por ensayos "
            "cíclicos según F.3.11.3."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.6.4 — PÓRTICOS CON ARRIOSTRAMIENTOS DE PANDEO RESTRINGIDO (PAPR).\n"
            "F.3.6.4.1 Alcance — diseñarse según esta sección.\n"
            "F.3.6.4.2 Bases de diseño — estructuras con riostras conectadas "
            "concéntricamente a vigas y columnas de fabricación especial; "
            "excentricidades menores que el peralte de viga permitidas si se "
            "consideran en fuerzas de miembros/conexiones sin cambiar la fuente de "
            "capacidad inelástica esperada. Capacidad inelástica significativa "
            "principalmente por fluencia de la riostra en tensión y compresión, "
            "proporcionando el desempeño de F.3.6.4.2.1, demostrado según "
            "F.3.6.4.5.2(3). Deformaciones esperadas: correspondientes a deriva de "
            "piso >= 2% de la altura de piso o 2 veces la deriva de diseño (la que "
            "sea mayor), más deformaciones de la riostra por deformación de la "
            "estructura debida a carga gravitacional. Diseño de manera que las "
            "deformaciones inelásticas bajo sismo ocurran principalmente como "
            "fluencia de la riostra en tensión y compresión.\n"
            "F.3.6.4.2.1 Resistencia de la riostra — resistencia ajustada establecida "
            "con base en ensayos. Conexiones de riostra y miembros adyacentes se "
            "diseñan para resistir fuerzas calculadas con base en la resistencia "
            "ajustada: en compresión, β*ω*Ry*Pysc; en tensión, ω*Ry*Pysc. Excepción: "
            "no se necesita aplicar Ry si Pysc se determina con el esfuerzo de "
            "fluencia obtenido de ensayo. β (factor de ajuste resistencia a "
            "compresión) = relación fuerza compresión máxima / fuerza tensión máxima "
            "de la muestra de ensayos de calificación (F.3.11.3.4.3), para las "
            "deformaciones esperadas; el mayor de los 2 ensayos; nunca menor que 1. ω "
            "(factor de ajuste por endurecimiento por deformación) = relación máxima "
            "fuerza a tensión medida (F.3.11.3.4.3, intervalo de deformaciones "
            "esperadas) / resistencia a fluencia medida Ry*Pysc; el mayor de los 2 "
            "ensayos; si el material ensayado del núcleo no coincide con el "
            "prototipo, ω se calcula con base en ensayos del material del prototipo.\n"
            "F.3.6.4.3 Análisis — no deben considerarse como sistema de resistencia a "
            "fuerzas gravitacionales. Resistencia requerida de columnas, vigas y "
            "conexiones con combinaciones del Título B incluyendo carga sísmica "
            "amplificada; Emh = fuerzas desarrolladas suponiendo que todas las "
            "fuerzas corresponden a resistencia ajustada a compresión o tensión. "
            "Determinar si riostras están en compresión o tensión despreciando "
            "efectos de cargas gravitacionales; considerar 2 direcciones de carga. "
            "Deformación de la riostra según F.3.6.4.2.1. Excepciones: (1) despreciar "
            "momentos por deriva sísmica, considerar los de cargas aplicadas entre "
            "puntos de soporte lateral; (2) resistencia requerida de columnas no "
            "mayor que menor entre fuerzas de levantamiento de fundación o análisis "
            "no lineal (F.3.3). Deformación de la riostra a partir de la porción "
            "inelástica de la deriva de diseño, incluyendo efectos de flexibilidad "
            "vertical de la viga; alternativamente, de análisis no lineal.\n"
            "F.3.6.4.4 Requisitos del sistema: F.3.6.4.4.1 Riostras en V y V "
            "invertida: (1) resistencia requerida de vigas interceptadas, conexiones "
            "y miembros de apoyo con combinaciones del Título B suponiendo que "
            "riostras no toman cargas vivas ni muertas; para efectos sísmicos, E en "
            "la viga se determina a partir de resistencias ajustadas a tensión y "
            "compresión; (2) vigas continuas entre columnas, ambas aletas "
            "arriostradas lateralmente cumpliendo ductilidad moderada (F.3.4.1.1); "
            "juego de riostras laterales en el punto de intersección, salvo "
            "suficiente rigidez/resistencia fuera del plano (Pu = resistencia "
            "requerida a compresión ajustada de la riostra, arriostramiento nodal "
            "según F.2.19). Para diseño/ensayos, la deformación máxima calculada de "
            "riostras se incrementa para incluir el efecto de la deflexión vertical "
            "de la viga (F.3.6.4.4.1(1)). F.3.6.4.4.2 Riostras en K — no permitidas "
            "en PAPR. F.3.6.4.4.3 Conexiones de la riostra a conexiones "
            "viga-columna — diseñadas para resistir una fuerza sísmica fuera del "
            "plano E igual al 6% de la resistencia a compresión ajustada de la "
            "riostra; rigidez requerida según F.2.20.2-4, con Pu = resistencia a "
            "compresión ajustada de la riostra.\n"
            "F.3.6.4.5 Miembros: F.3.6.4.5.1 Requisitos básicos — miembros de vigas y "
            "columnas satisfacen F.3.4.1.1 para ductilidad alta. F.3.6.4.5.2 "
            "Riostras: (1) Conjunto — núcleo de acero estructural + sistema que "
            "restringe el pandeo del núcleo. (a) Núcleo de acero — placas de 50mm o "
            "más de espesor deben satisfacer la tenacidad mínima de F.3.1.3.3; no se "
            "permiten empalmes en el núcleo. (b) Sistemas de restricción al pandeo — "
            "recubrimiento; vigas, columnas y placas de unión que conectan el núcleo "
            "son parte de este sistema (consideradas en cálculos de estabilidad); "
            "debe limitar pandeo local y general del núcleo para las deformaciones "
            "esperadas; conformidad validada por los ensayos de F.3.6.4.2.2. (2) "
            "Resistencia de diseño — núcleo diseñado para resistir la fuerza axial "
            "completa en la riostra: Pysc = Fysc*Asc  (F.3.6.4-1), phi=0.9, donde "
            "Fysc=resistencia a fluencia mínima especificada del núcleo, o "
            "resistencia real a la fluencia determinada de un ensayo, MPa; "
            "Asc=área neta del núcleo, mm2. Los efectos de las cargas calculadas con "
            "base en resistencias ajustadas de la riostra NO deben amplificarse por "
            "el factor de sobrerresistencia Ω0. (3) Validación de la conexión — con "
            "base en resultados de ensayos cíclicos de calificación (F.3.11.3), "
            "mínimo 2 satisfactorios; uno debe incluir conexión de riostra solicitada "
            "por demandas de rotación cumpliendo F.3.11.3.2, el otro puede ser "
            "uniaxial o ensayo del sistema cumpliendo F.3.3.3. Ambos tipos válidos "
            "con ensayos de literatura de proyectos similares, o ensayos específicos "
            "del proyecto. Interpolación/extrapolación de resultados para miembros de "
            "tamaño diferente debe justificarse mediante análisis racional; extrapolación "
            "sobre combinaciones similares de tamaños de núcleos y sistemas de "
            "restricción; debe cumplirse F.3.11.3. F.3.6.4.5.3 Zonas protegidas — "
            "deben incluir el núcleo de acero de las riostras y los elementos que lo "
            "conectan a vigas y columnas, satisfacen F.3.4.1.3.\n"
            "F.3.6.4.6 Conexiones: F.3.6.4.6.1 Soldaduras de demanda crítica — según "
            "F.3.1.3.4.2: (1) acanaladas en empalmes de columna; (2) columna-placa de "
            "base, salvo impedimento de rótula. F.3.6.4.6.2 Conexiones viga-columna "
            "— cuando riostra o placa de unión conecta viga y columna: (1) simple "
            "(F.2.2.3.6.1, rotación 0.025 rad); o (2) diseñada para momento "
            "simultáneo con la resistencia requerida de la conexión de riostra, "
            "igual al menor entre (a) 1.1*Ry*Fy*Z de la viga o (b) suma(1.1*Ry*Fy*Z) "
            "de la columna. F.3.6.4.6.3 Conexiones de las riostras: (1) resistencia "
            "requerida — tensión/compresión (incluyendo uniones viga-columna si son "
            "parte del sistema) >= 1.1 veces la resistencia ajustada a compresión de "
            "la riostra (F.3.6.4.2.1); con perforaciones agrandadas, resistencia "
            "requerida para deslizamiento no mayor que combinaciones sin sismo "
            "amplificado. (2) requisitos de las cartelas de unión — diseño incluye "
            "consideraciones de pandeo local y general, arriostramiento lateral "
            "consistente con el usado en los ensayos de calificación (se puede "
            "cumplir diseñando para fuerza transversal consistente con la del "
            "ensayo, añadiendo atiesadores si se requiere; sin arriostramiento "
            "transversal en ensayos, no se requiere suministrarlo; debe incluirse en "
            "el ensayo de fabricación cualquier accesorio de arriostramiento). "
            "F.3.6.4.6.4 Empalmes de columnas — F.3.4.2.5, soldaduras acanaladas de "
            "penetración completa; desarrollar al menos 50% de la menor resistencia "
            "diseño a flexión conectada; resistencia requerida a cortante "
            "suma(Mpc)/Hc."
        ),
    },
    {
        "id": "NSR10-F-F_3_6_5_MCA_1_a_5",
        "seccion": "F.3.6.5.1 a F.3.6.5.5 (Muros de Cortante de Acero MCA-DES: alcance, bases, análisis, EBH/EBV, almas, ángulo de fluencia)",
        "titulo": (
            "Muros de Cortante de Acero (MCA-DES): placas de alma conectadas a "
            "vigas/columnas (elementos de borde EBH/EBV), fluencia de la placa del "
            "alma, resistencia de diseño Vn=0.42·Fy·tw·Lcf·sen(2α), ángulo de "
            "fluencia α (40° por defecto o fórmula tan⁴α), rigidez de elementos de "
            "borde, relación de momentos EBH-EBV."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.6.5 — MUROS DE CORTANTE DE ACERO (MCA).\n"
            "F.3.6.5.1 Alcance — diseñarse según esta sección.\n"
            "F.3.6.5.2 Bases de diseño — estructuras conformadas por láminas de acero "
            "conectadas a vigas y columnas. Capacidad inelástica significativa "
            "principalmente por fluencia de la placa del alma y formación de rótulas "
            "plásticas en extremos de elementos de borde horizontales (EBH).\n"
            "F.3.6.5.3 Análisis — no debe considerarse que las almas resisten cargas "
            "de gravedad. Resistencia requerida de EBH, elementos de borde verticales "
            "(EBV) y conexiones con combinaciones del Título B incluyendo carga "
            "sísmica amplificada; Emh determinada de un análisis donde se supone que "
            "todas las almas resisten las fuerzas correspondientes a su resistencia "
            "esperada en tensión, actuando con el ángulo α (F.3.6.5.5.2), y los EBH "
            "reciben en cada extremo momentos iguales a 1.1*Ry*Mp. La tensión en las "
            "almas se halla sin considerar efectos gravitacionales. Esfuerzo de "
            "fluencia esperado del alma = Ry*Fy (con paredes perforadas, el esfuerzo "
            "de tensión efectivo esperado se define en F.3.6.5.7.1). Deben incluirse "
            "en el análisis las fuerzas cortantes de la ecuación F.3.5.1-1 — en "
            "algunos casos las fuerzas cortantes del Título B pueden gobernar el "
            "diseño de los EBH. Las fuerzas cortantes en vigas y columnas pueden ser "
            "muy grandes, y la fluencia por cortante podría ser el estado límite "
            "dominante.\n"
            "F.3.6.5.4 Requisitos del sistema: F.3.6.5.4.1 Rigidez de los elementos "
            "de borde — los EBV deben tener momento de inercia respecto al eje "
            "perpendicular al plano del alma, Ic, no menor que 0.0031*tw*h^4/L. Los "
            "EBH deben tener momento de inercia respecto al eje perpendicular al "
            "plano del alma, Iv, no menor que 0.0031*L^4/h veces la diferencia de "
            "espesores de la placa del alma arriba y abajo; donde tw=espesor del "
            "alma, mm; h=distancia entre ejes de EBH, mm; Iv=momento de inercia de un "
            "EBH respecto al eje perpendicular al plano de la placa, mm4; "
            "Ic=momento de inercia de un EBV respecto al eje perpendicular, mm4; "
            "L=distancia entre ejes de EBV, mm. F.3.6.5.4.2 Relación de momentos de "
            "la conexión EBH-EBV — deben cumplirse las relaciones viga-columna de "
            "F.3.5.3.4.1 para todas las intersecciones de elementos de borde sin "
            "considerar los efectos de las almas. F.3.6.5.4.3 Arriostramiento — los "
            "EBH deben arriostrarse de manera que satisfagan los requisitos de "
            "ductilidad moderada de F.3.4.1.2.1. F.3.6.5.4.4 Aberturas en el alma — "
            "enmarcadas en todos sus lados por elementos de borde intermedios "
            "prolongados a todo el ancho y alto del panel, a menos que se justifique "
            "otra distribución por ensayos y análisis, o lo permitido en F.3.6.5.7.\n"
            "F.3.6.5.5 Miembros: F.3.6.5.5.1 Requisitos básicos — EBH, EBV y "
            "elementos de borde intermedios satisfacen F.3.4.1.1 para ductilidad "
            "alta. F.3.6.5.5.2 Almas — resistencia de diseño a cortante del panel, "
            "phi*Vn, phi=0.9, estado límite de fluencia por cortante: "
            "Vn = 0.42*Fy*tw*Lcf*sen(2α)  (F.3.6.5-1), donde: Ab=área sección "
            "transversal de un EBH, mm2; Ac=área sección transversal de un EBV, mm2; "
            "Ic=momento inercia EBV respecto eje perpendicular, mm4; L=distancia "
            "entre ejes de EBV, mm; Lcf=distancia libre entre aletas de columna, mm; "
            "h=distancia entre ejes de EBV, mm; tw=espesor del alma, mm; α=ángulo de "
            "fluencia del alma en grados, medido con relación a la vertical — puede "
            "tomarse como 40°, o calcularse: "
            "tan^4(α) = [1 + tw*L/(2*Ac)] / [1 + tw*h*(1/Ab + h^3/(360*Ic*L))]  "
            "(F.3.6.5-2)\n"
            "F.3.6.5.5.3 Zona protegida — de MCA cumple F.3.4.1.3, incluye: (1) "
            "almas de MCA; (2) elementos que conectan las almas a EBH y EBV; (3) "
            "zonas de rótula plástica en cada extremo del EBH, en región desde la "
            "cara de columna hasta distancia igual a un peralte de la cara de "
            "columna, o como se especifica en F.3.5.3.5.3."
        ),
    },
    {
        "id": "NSR10-F-F_3_6_5_MCA_6_a_7",
        "seccion": "F.3.6.5.6 a F.3.6.5.7 (MCA: conexiones EBH-EBV/almas, empalmes de columna, almas perforadas)",
        "titulo": (
            "Conexiones del muro de cortante de acero (soldaduras demanda crítica, "
            "conexiones EBH-EBV, zona de panel, empalmes de columna), y almas "
            "perforadas: configuración de perforaciones circulares, resistencia "
            "reducida Vn=0.42·Fy·tw·Lcf(1-0.7D/Sdiag), espesor efectivo, refuerzo de "
            "esquinas con platina curva."
        ),
        "texto": (
            "NSR-10 Título F, Capítulo F.3 — Provisiones sísmicas para acero. "
            "F.3.6.5.6 — CONEXIONES.\n"
            "F.3.6.5.6.1 Soldaduras de demanda crítica — según F.3.1.3.4.2: (1) "
            "acanaladas en empalmes de columna; (2) columna-placa de base, salvo "
            "impedimento de rótula; (3) conexiones EBH-EBV.\n"
            "F.3.6.5.6.2 Conexiones EBH-EBV — cumplen F.3.5.1.6: (1) resistencia "
            "requerida a cortante — combinaciones del Título B con carga sísmica "
            "amplificada; Emh se toma como el cortante calculado con la ecuación "
            "F.3.5.1-1 junto con el cortante de la resistencia a fluencia esperada a "
            "tensión de las almas a ángulo α. (2) zona de panel — la del EBV cercana "
            "a la parte superior y base del EBH del MCA debe cumplir F.3.5.3.6.5.\n"
            "F.3.6.5.6.3 Conexiones de almas a elementos de borde — resistencia "
            "requerida igual a la resistencia a fluencia esperada del alma a "
            "tensión, a un ángulo α.\n"
            "F.3.6.5.6.4 Empalmes de columnas — F.3.4.2.5; con soldaduras acanaladas, "
            "de penetración completa; desarrollar al menos 50% de la menor "
            "resistencia de diseño a flexión de miembros conectados; resistencia "
            "requerida a cortante suma(Mpc)/Hc.\n\n"
            "F.3.6.5.7 — ALMAS PERFORADAS.\n"
            "F.3.6.5.7.1 Configuración normal de perforaciones circulares — se "
            "permite usar placa perforada como alma de MCA cumpliendo esta sección. "
            "Patrón regular de perforaciones del mismo diámetro espaciadas "
            "uniformemente, alineadas diagonalmente con ángulo uniforme respecto a la "
            "vertical; rugosidad de bordes de aberturas <=13 micrones. (1) "
            "Resistencia — resistencia de diseño a cortante del panel phi*Vn, "
            "phi=0.9, para almas perforadas: "
            "Vn = 0.42*Fy*tw*Lcf*(1-0.7*D/Sdiag)  (F.3.6.5-3), donde D=diámetro de "
            "las perforaciones, mm; Sdiag=distancia mínima centro a centro entre "
            "perforaciones, mm. (2) Espaciamiento — Sdiag mínimo 1.67*D. Distancia "
            "entre primeras perforaciones y conexiones del alma a EBH/EBV: mínimo D, "
            "no mayor que D+0.7*Sdiag. (3) Rigidez — de placas regularmente "
            "perforadas, calculada con espesor efectivo de placa de alma tef, dado "
            "por: tef = [1 + (pi/4)*(D/Sdiag)] / [1 - (pi/4)*(D/Sdiag)*"
            "(1 - Nr*D*sen(α)/Hc)] * tw  (F.3.6.5-4), donde: Hc=altura libre de la "
            "columna (y de la placa de alma) entre aletas, mm; tw=espesor de la "
            "placa de alma, mm; Nr=número de filas horizontales de perforaciones; "
            "α=ángulo respecto a la vertical de la línea centro a centro más corta "
            "en el arreglo de aberturas, grados. (4) Esfuerzo efectivo de tensión "
            "esperado — a usar en lugar del esfuerzo de tensión efectivo para el "
            "análisis de F.3.6.5.3: Ry*Fy*(1-0.7*D/Sdiag).\n"
            "F.3.6.5.7.2 Perforaciones de esquina reforzada — se permiten "
            "perforaciones de un cuarto de círculo en las esquinas de las almas si "
            "están conectadas a una platina curva de refuerzo bordeando la "
            "perforación, diseñada para permitir el desarrollo de toda la "
            "resistencia del alma y mantener su resistencia correspondiente a la "
            "deriva de piso de diseño. Condiciones: (1) Diseño a tensión — la platina "
            "curva debe tener resistencia de diseño que desarrolle la fuerza de "
            "tensión axial resultante de la tensión de la placa de alma en ausencia "
            "de otras fuerzas: Pu = Ry*Fy*tw*R^2 / (4*e)  (F.3.6.5-5), donde R=radio "
            "de la perforación, mm; e = R*(1-raiz(2)/2), mm  (F.3.6.5-6). Los EBH y "
            "EBV deben diseñarse para resistir las fuerzas axiales de tensión en el "
            "extremo del refuerzo curvo. (2) Diseño para fuerzas de conexión "
            "viga-columna — las platinas curvas deben tener resistencia de diseño "
            "capaz de desarrollar los efectos combinados de fuerza axial y momento "
            "en el plano del alma resultantes de la deformación de la conexión en "
            "ausencia de otras fuerzas: Pu = 15*E*Iy*Δ / (4*e^2*H)  (F.3.6.5-7). El "
            "momento es: Mu = Pu*R/2  (F.3.6.5-8), donde: E=módulo de elasticidad, "
            "MPa; Iy=momento de inercia de la placa, mm4; H=altura de piso, mm; "
            "Δ=deriva de piso de diseño, mm."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])
    print(f"Chunks a insertar: {len(CHUNKS)}")
    for c in CHUNKS:
        print(f"  {c['id']} ({c['seccion']}): {len(c['texto'])} chars")

    print("\nCargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
    textos = [c["texto"] for c in CHUNKS]
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print("\nSubiendo a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()
    print(f"OK: {len(rows)} chunks F.3.5.3(resto)-F.3.6.5 cargados con embedding.")


if __name__ == "__main__":
    main()
