"""
NSR-10 Título F, Capítulo F.4 (Estructuras de Acero con Perfiles de Lámina
Formada en Frío) — F.4.1 (Provisiones Generales) completo, en verbatim
real. Primera pieza real de F.4/F.5, el hueco más grande de todo el
corpus (0% cubierto antes de esto, ~280 páginas reales entre ambos
capítulos, mientras C/D/G/E/I/J/K ya estaban cerrados en verbatim).

F.4.1 — PROVISIONES GENERALES: F.4.1.1 (Alcance y Definiciones, glosario
extenso de ~50 términos), F.4.1.2 (Materiales — aceros aplicables NTC/
ASTM, ductilidad, espesor mínimo, 4 ecuaciones numeradas F.4.1.2-1 a
F.4.1.2-4), F.4.1.3 (Cargas), F.4.1.4 (Diseño por Esfuerzos Admisibles),
F.4.1.5 (Diseño con Coeficientes de Carga y Resistencia), F.4.1.6
(Incremento en el punto de fluencia por trabajo de formado en frío, 4
ecuaciones F.4.1.6-1 a F.4.1.6-4), F.4.1.7 (Estado de Servicio), F.4.1.8
(Documentos de Referencia — lista completa AISI/ASCE/AWS/ASME/NTC/ASTM).

Fuente: NSR-10-982-1082.pdf (Drive id 1Mr7auE8pwQ3IiQaZmLgVY5-Xdu7psmze),
páginas internas F-301 a F-313 (páginas PDF 1-13), leído visualmente
página por página (método establecido: PDF nativo descargado local +
Read con pages=, nunca el texto plano de Drive que corrompe subíndices).

Uso: python _ingest_titulo_f_f41_verbatim.py
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(PROJECT_ROOT / "apps" / "api" / ".env")

CAPITULO = "NSR-10 Título F — Estructuras Metálicas"

CHUNKS = [
    {
        "id": "NSR10-F-F_4_1_1_alcance_terminologia_a_m",
        "seccion": "F.4.1.1 (Alcance y límites de aplicabilidad; Terminología A-M)",
        "titulo": "Alcance del Capítulo F.4 (perfiles formados en frío de acero al carbono/baja aleación ≤25.4mm) y la primera mitad del glosario de términos (Acero Virgen a Elementos en Compresión Rigidizados).",
        "texto": (
            "NSR-10 Título F, Capítulo F.4 — ESTRUCTURAS DE ACERO CON PERFILES DE "
            "LÁMINA FORMADA EN FRÍO. F.4.1 — PROVISIONES GENERALES. F.4.1.1 — "
            "ALCANCE Y DEFINICIONES. F.4.1.1.1 — Alcance y límites de "
            "aplicabilidad — Esta Especificación debe aplicarse al diseño de "
            "miembros estructurales de acero de bajo carbono (acero dulce) o de "
            "baja aleación, cuya sección ha sido formada en frío, a partir de "
            "láminas, rollos, tiras, platinas o barras de espesor menor o igual a "
            "25.4 mm (1 pulgada) y usados para sostener cargas en: (a) Edificios, "
            "en los que el diseño debe hacerse de acuerdo con las especificaciones "
            "del método DCCR (Diseño con Coeficientes de Carga y Resistencia) o el "
            "método DEA (Diseño por Esfuerzos Admisibles), donde se indique "
            "explícitamente [nota al pie: el método de diseño con coeficientes de "
            "carga y resistencia, DCCR, será el procedimiento válido de diseño "
            "bajo las disposiciones de este Reglamento. Solo se permitirá el "
            "método de diseño por esfuerzos admisibles, DEA, en el numeral F.4.7, "
            "referente al diseño de Tableros Metálicos para Trabajo en Sección "
            "Compuesta]. (b) Otro tipo de estructuras, distintas de edificios, "
            "teniendo en consideración las condiciones generadas por los efectos "
            "dinámicos.\n\n"
            "F.4.1.1.2 — Terminología — Los siguientes son los significados de "
            "los diferentes términos utilizados a lo largo de esta especificación:\n\n"
            "Acero Virgen — Es el material tal y como es recibido del productor "
            "de acero o bodega antes de ser formado en frío como un resultado de "
            "las operaciones de fabricación.\n\n"
            "Aleta de una Sección en Flexión — Es el ancho plano de una aleta "
            "incluyendo cualesquier rigidizadores intermedios más las esquinas "
            "adyacentes.\n\n"
            "Alma — En un miembro sujeto a flexión, es la parte de la sección que "
            "está unida a las dos aletas, o que está unido a una sola aleta y que "
            "atraviesa el eje neutro.\n\n"
            "Análisis Racional de Ingeniería — Análisis basado en una teoría que "
            "es apropiada para la situación, en resultados de ensayos disponibles "
            "que sean relevantes y en el juicio de una buena ingeniería. Los "
            "factores de resistencia mínimos que deben utilizarse cuando se hace "
            "un análisis de este tipo son los siguientes: Para miembros: φ = 0.80. "
            "Para conexiones: φ = 0.65.\n\n"
            "Ancho Efectivo de Diseño — Es el ancho plano de un elemento reducido "
            "para propósitos de diseño, también conocido simplemente como el "
            "ancho efectivo.\n\n"
            "Ancho Plano — Es el ancho de un elemento excluyendo las esquinas "
            "medido a lo largo de su plano.\n\n"
            "Área de la Sección Transversal: Área Efectiva — El área efectiva, "
            "Ae, es calculada utilizando los anchos efectivos de los elementos "
            "componentes en concordancia con la sección F.4.2. El área efectiva "
            "será igual al área bruta o al área neta, la que sea aplicable, si "
            "los anchos efectivos de todos los elementos componentes, "
            "determinados de acuerdo con F.4.2, son iguales a los anchos planos "
            "reales. Área Total — Es el área total o completa, no reducida, A, "
            "calculada sin reducir los anchos de los elementos componentes a sus "
            "anchos efectivos. Esta puede ser un área bruta no reducida o un área "
            "neta no reducida, dependiendo donde sea aplicable. Área bruta — El "
            "área bruta, Ag, es aquella donde no se consideran reducciones por "
            "huecos, aberturas y cortes. Área Neta — El área neta, An, es igual "
            "al área bruta menos el área de huecos, aberturas y cortes.\n\n"
            "Canal Guía — Un miembro de un entramado que consiste de solo un alma "
            "y dos (2) aletas. La altura del alma debe medirse al interior de las "
            "aletas.\n\n"
            "Cargas de Servicio — Carga bajo la cual se evalúan los límites del "
            "Estado de servicio.\n\n"
            "Carga Mayorada — Producto de la carga nominal y el factor de "
            "mayoración (factor de carga).\n\n"
            "Cargas Nominales — Son las magnitudes de las cargas especificadas "
            "por este Reglamento aplicable no incluyendo los factores de "
            "mayoración.\n\n"
            "Conexión — Combinación de elementos estructurales y nudos (o juntas) "
            "usada para transmitir las fuerzas entre dos o más miembros.\n\n"
            "Correa — Miembro estructural horizontal el cual soporta un tablero "
            "de cubierta y está sujeto principalmente a flexión bajo las cargas "
            "aplicadas tales como nieve, viento o cargas muertas.\n\n"
            "DCCR — Diseño con Coeficientes de Carga y Resistencia — Es un método "
            "para dimensionar componentes estructurales (miembros, conectores, "
            "elementos de conexión y montajes) tal que la resistencia de diseño "
            "iguala o excede la resistencia requerida del componente bajo la "
            "acción de las combinaciones de carga para Diseño con Coeficientes de "
            "Carga y Resistencia. Este es el método que se utilizará en estas "
            "especificaciones.\n\n"
            "DEA — Diseño por Esfuerzos Admisibles — Es un método para "
            "dimensionar componentes estructurales (miembros, conectores, "
            "elementos de conexión y montajes) tal que la resistencia admisible "
            "iguala o excede la resistencia requerida del componente bajo la "
            "acción de las combinaciones de carga para Diseño por Esfuerzos "
            "Admisibles DEA. Este método no se utilizará en estas "
            "especificaciones, a menos que se indique lo contrario.\n\n"
            "Diafragma — cubierta, entrepiso u otra membrana o sistema de "
            "arriostramiento que transfiere fuerzas en la dirección de su propio "
            "plano al sistema resistente a fuerzas laterales.\n\n"
            "Dintel — Es un miembro horizontal que hace parte de un entramado "
            "estructural usado sobre aberturas de piso, cubierta o muro para "
            "transferir las cargas alrededor de la abertura a los miembros "
            "estructurales de soporte.\n\n"
            "Efecto de Carga — Fuerzas, esfuerzos, y deformaciones producidas en "
            "un componente estructural debido a las cargas aplicadas.\n\n"
            "Elemento Multirigidizado — Es un elemento rigidizado entre almas, o "
            "entre un alma y un borde rigidizado, por medio de rigidizadores "
            "intermedios paralelos a la dirección del esfuerzo.\n\n"
            "Elementos en Compresión No Rigidizados — Elemento en compresión "
            "plano rigidizado en solo un borde paralelo a la dirección del "
            "esfuerzo.\n\n"
            "Elementos en Compresión Rigidizados o Parcialmente Rigidizados — "
            "Elemento en compresión plano (por ejemplo, la aleta plana en "
            "compresión de un miembro en flexión o un alma o aleta de un miembro "
            "en compresión) en el cual, ambos bordes paralelos a la dirección del "
            "esfuerzo están rigidizados por uno u otro de los siguientes "
            "elementos: alma, ala, pestaña rigidizadora o labio atiesador, "
            "rigidizador intermedio, o similares."
        ),
    },
    {
        "id": "NSR10-F-F_4_1_1_terminologia_n_z_unidades",
        "seccion": "F.4.1.1.2 cont. (Terminología N-Z) y F.4.1.1.3 (Unidades)",
        "titulo": "Segunda mitad del glosario (Ensayo de Comportamiento a Talón) y el sistema de unidades de la especificación (SI, fuerza en Newtons).",
        "texto": (
            "NSR-10 Título F, Capítulo F.4 — F.4.1.1.2 — Terminología (continuación).\n\n"
            "Ensayo de Comportamiento — Ensayo realizado sobre miembros "
            "estructurales, conexiones, y montajes donde su comportamiento no "
            "puede ser determinado por las provisiones dadas en esta "
            "especificación o sus referencias.\n\n"
            "Ensayo de Comprobación — Prueba realizada, cuando es requerida, "
            "sobre miembros, conexiones y montajes, diseñada de acuerdo a las "
            "provisiones del Capítulo F.4 de esta especificación, o sus "
            "referencias, con el objeto de comparar el comportamiento real con el "
            "calculado.\n\n"
            "Esfuerzo — El esfuerzo como es usado en esta especificación "
            "significa la fuerza por unidad de área.\n\n"
            "Esfuerzo de fluencia — Término genérico para denotar ya sea, el "
            "punto de fluencia o la resistencia a fluencia, según sea apropiado "
            "para el material.\n\n"
            "Especificación Publicada — Requerimientos para un acero listado por "
            "un fabricante, procesador, productor, comercializador, u otro ente, "
            "los cuales 1. Están generalmente disponibles para dominio público o "
            "bajo requerimiento, 2. Son establecidos antes que el acero sea "
            "ordenado, y 3. Especifican al menos, las propiedades mecánicas "
            "mínimas, los límites de la composición química y, si es recubierto, "
            "las propiedades del recubrimiento.\n\n"
            "Espesor — El espesor, t, de cualquier elemento o sección será el "
            "del acero base, no incluyendo algún tipo de recubrimiento.\n\n"
            "Factor de Mayoración — Factor que toma en cuenta las desviaciones "
            "entre la carga real y la carga nominal debido a incertidumbres en el "
            "análisis que transforma la carga en un efecto de carga, y la "
            "probabilidad de que más de una carga extrema ocurra de manera "
            "simultánea.\n\n"
            "Factor de Resistencia, φ — Es un factor que toma en cuenta "
            "inevitables desviaciones entre la resistencia real y la resistencia "
            "nominal además de la manera y consecuencias de la falla.\n\n"
            "Factor de Seguridad, Ω — Factor que toma en cuenta las desviaciones "
            "entre la resistencia real y la resistencia nominal, desviaciones "
            "entre la carga real y la carga nominal, incertidumbres en el "
            "análisis que transforma la carga en un efecto de carga, y la manera "
            "y consecuencias de la falla. Este factor solo se definirá en "
            "aquellas partes donde se utilice el método DEA.\n\n"
            "Fatiga — Estado límite de iniciación de la fisura y su crecimiento, "
            "resultante de la aplicación repetida de las cargas vivas.\n\n"
            "Grado — Es una designación utilizada para el esfuerzo de fluencia "
            "mínimo.\n\n"
            "Larguero — Miembro estructural horizontal el cual soporta paneles "
            "de muro y está sujeto, principalmente, a flexión bajo las cargas "
            "horizontales aplicadas, tales como cargas de viento.\n\n"
            "Miembro Alma — Es un miembro estructural en una cercha que se "
            "conecta al cordón superior e inferior, pero no es un miembro cordón.\n\n"
            "Miembro Cordón — Es un miembro estructural que constituye al "
            "componente superior o inferior de una cercha.\n\n"
            "Miembro Estructural de Acero Formado en Frío — Son secciones "
            "fabricadas a partir de presión mecánica sobre piezas planas "
            "provenientes de láminas, longitudes cortadas de rollos o platinas, o "
            "por formación rolada en frío de rollos o láminas de acero laminado "
            "en frío o laminado en caliente. Ambas operaciones de formación son "
            "realizadas a temperatura ambiente, lo cual indica que no se "
            "introduce calor, como se hace con el proceso de formación en "
            "caliente.\n\n"
            "Momento de Fluencia — En un miembro sujeto a flexión, es el momento "
            "en el cual la fibra más extrema alcanza la primera fluencia.\n\n"
            "Muro Cortina — Es un muro que transfiere cargas transversales "
            "(fuera de su plano) y es limitado a una carga vertical "
            "sobreimpuesta, no incluyendo el peso del material del tablero, no "
            "mayor a 1.46 kN/m (100 lb/pie), o una carga vertical sobreimpuesta "
            "no mayor a 0.89 kN (200 lb).\n\n"
            "Muro de Corte — Muro que provee resistencia a cargas laterales en el "
            "plano del muro y asimismo estabilidad para el sistema estructural.\n\n"
            "Pandeo — Estado límite de cambio repentino en la geometría de una "
            "estructura o cualquiera de sus elementos bajo una condición crítica "
            "de carga.\n\n"
            "Pandeo Distorsional — Es un modo de pandeo que envuelve cambios en "
            "la forma de la sección transversal, excluyendo el pandeo local.\n\n"
            "Pandeo Flector — Modo de pandeo en el cual un miembro a compresión "
            "flexiona lateralmente sin torsión o cambio en la forma de la sección "
            "transversal.\n\n"
            "Pandeo Flexo-Torsional — Modo de pandeo en el cual un miembro en "
            "compresión dobla y se gira sobre su eje (torsional) simultáneamente "
            "sin cambio en la forma de la sección transversal.\n\n"
            "Pandeo Local — Estado límite del pandeo para un elemento en "
            "compresión donde la línea de conexión entre elementos permanece "
            "derecha y los ángulos entre elementos no cambian.\n\n"
            "Pandeo Lateral Torsional — Modo de pandeo de un miembro en flexión "
            "que envuelve deflexión fuera del plano de flexión ocurriendo "
            "simultáneamente con torsión alrededor del centro de cortante de la "
            "sección transversal.\n\n"
            "Paral — Miembro vertical de un entramado en un sistema de muro ó "
            "ensamble.\n\n"
            "Paral de Muro Cortina — Miembro en un sistema de muro exterior de "
            "acero que transfiere cargas transversales (fuera de su plano) y es "
            "limitado por una carga axial sobreimpuesta, exclusiva de los "
            "materiales de cerramiento, no mayor a 1460 N/m (100 lb/pie), ó una "
            "carga axial puntual sobreimpuesta no mayor a 890 N (200 lb) por "
            "paral.\n\n"
            "Propiedades del Acero Virgen — Propiedades mecánicas del acero "
            "virgen tales como punto de fluencia, resistencia última y "
            "elongación.\n\n"
            "Punto de Fluencia — El punto de fluencia es el primer esfuerzo en el "
            "material en el cual ocurre un incremento en la deformación sin "
            "ningún incremento del esfuerzo, tal como es definido por la NTC "
            "correspondiente.\n\n"
            "Punto de Fluencia Mínimo Especificado — Límite inferior del punto de "
            "fluencia en un ensayo especificado para calificar como adecuado un "
            "lote de acero, de uso en miembros estructurales de acero formado en "
            "frío, diseñado en ese punto de fluencia.\n\n"
            "Punto de Panel — Región de conexión entre un miembro alma y un "
            "miembro cordón en una cercha.\n\n"
            "Punto de Quiebre — Región de conexión entre dos miembros cordones de "
            "cercha donde existe un cambio de pendiente, no incluyendo el "
            "talón.\n\n"
            "Relación Ancho Plano-Espesor — Es el ancho Plano de un elemento "
            "medido a lo largo de su plano, dividido por su espesor.\n\n"
            "Resistencia a la Fluencia — Esfuerzo en el cual el material exhibe "
            "una desviación límite especificada de la proporcionalidad entre el "
            "esfuerzo y la deformación como es definido por la NTC "
            "correspondiente.\n\n"
            "Resistencia Admisible — Es la resistencia nominal dividida por el "
            "factor de seguridad, Rn/Ω. Solo se utilizará en aquellas secciones "
            "de este Reglamento donde se indique.\n\n"
            "Resistencia de Diseño — Es la resistencia nominal multiplicada por "
            "un factor de resistencia, φRn.\n\n"
            "Resistencia Disponible — Resistencia de diseño o resistencia "
            "admisible, según sea el caso.\n\n"
            "Resistencia Nominal — Resistencia de una estructura o componente "
            "(sin los factores de resistencia o factores de seguridad aplicados) "
            "para soportar los efectos de las cargas, tal como es determinado "
            "conforme con lo estipulado en esta especificación.\n\n"
            "Resistencia Requerida — Son las fuerzas, esfuerzos y deformaciones "
            "actuantes sobre un componente estructural, determinadas ya sea por "
            "un análisis estructural, para combinaciones de carga por DEA o "
            "DCCR, según sea apropiado, o como se especifica en este Reglamento.\n\n"
            "Resistencia Última — Máximo esfuerzo alcanzado por un material en el "
            "ensayo de tensión.\n\n"
            "Rollo Madre — Es un rollo continuo sin juntas soldadas tal y cual "
            "como es manejado por un molino en caliente, molino en frío, una "
            "línea de recubrimiento metálico o línea de pintura e identificable "
            "por un único número de rollo. Este rollo puede ser cortado o "
            "flejado en rollos más pequeños, sin embargo, de estos últimos puede "
            "decirse que vienen del mismo Rollo Maestro si, de acuerdo con la "
            "trazabilidad, puede determinarse el número del Rollo Original.\n\n"
            "Sección Asimétrica — Sección no simétrica alrededor de ningún eje o "
            "punto.\n\n"
            "Sección de Simetría de Punto — Es una sección simétrica alrededor "
            "de un punto (centroide) tal como una sección Z con alas iguales.\n\n"
            "Sección de Simetría Doble — Es una sección simétrica alrededor de "
            "dos ejes ortogonales que pasan por su centroide.\n\n"
            "Sección de Simetría Sencilla — Es una sección simétrica alrededor "
            "de sólo un eje que pasa por su centroide.\n\n"
            "SS (Structural Steel) — Designación ASTM para ciertos aceros planos "
            "destinados a aplicaciones estructurales.\n\n"
            "Subelemento de un Elemento Multirigidizado — Porción de un elemento "
            "mutirigidizado entre rigidizadores intermedios adyacentes, entre el "
            "alma y un rigidizador intermedio o entre el borde y rigidizador "
            "intermedio.\n\n"
            "Talón — Región de conexión entre los cordones superior e inferior "
            "de una cercha con cordones no paralelos.\n\n"
            "F.4.1.1.3 — Unidades — Esta especificación ha sido desarrollada de "
            "tal manera que cualquier sistema compatible de unidades pueda ser "
            "utilizado, excepto en aquellas situaciones donde se establezca algo "
            "diferente de manera explícita. Las unidades de trabajo consideradas "
            "en esta sección son las determinadas por el Sistema Internacional "
            "SI (fuerza en Newtons, longitud en milímetros y presión o esfuerzo "
            "en Megapascales, MPa)."
        ),
    },
    {
        "id": "NSR10-F-F_4_1_2_materiales",
        "seccion": "F.4.1.2 (Materiales: aceros aplicables, otros aceros, ductilidad, espesor mínimo)",
        "titulo": "Ecuaciones F.4.1.2-1 a F.4.1.2-4: aceros aplicables (NTC/ASTM listados), requisitos de ductilidad y sus 2 excepciones, y espesor mínimo entregado (95%).",
        "texto": (
            "NSR-10 Título F, Capítulo F.4 — F.4.1.2 — MATERIALES. F.4.1.2.1 — "
            "Aceros aplicables — Esta Especificación requiere el uso de acero de "
            "calidad estructural según definido en las siguientes "
            "especificaciones NTC de ICONTEC o ASTM de la Sociedad Americana "
            "para Ensayos y Materiales: NTC 6 (ASTM A1011/A1011M SS Grados 30 "
            "(205MPa), 33 (230MPa), 36 (250MPa) Tipos 1 y 2, 40 (275MPa), 45 "
            "(310MPa), 50 (340MPa), y 55 (380MPa); HSLAS Clases 1 y 2, Grados 45 "
            "(310MPa), 50 (340MPa), 55 (380MPa), 60 (410MPa), 65 (450MPa), y 70 "
            "(480MPa); HSLAS-F Grados 50 (340MPa), 60 (410MPa), 70 (480MPa), y "
            "80 (550MPa)) Productos planos laminados en caliente de aceros, al "
            "carbono, estructurales, alta resistencia baja aleación y alta "
            "resistencia baja aleación con capacidad de deformado — estampado. "
            "NTC 1920 (ASTM A36/A36M) Acero estructural al Carbono. NTC 1950 "
            "(ASTM A242/A242M) Acero estructural de alta resistencia y baja "
            "aleación. NTC 1985 (ASTM A572) Aceros de alta resistencia y baja "
            "aleación con colombio y vanadio, de calidad estructural. NTC 2012 "
            "(ASTM A588/A588M) Acero estructural de alta resistencia y baja "
            "aleación con esfuerzo mínimo de fluencia de 345MPa y hasta 100mm "
            "(4pulg.) de espesor. NTC 3325 (ASTM A283/A283M) Láminas gruesas de "
            "acero al carbono de resistencia a la tensión baja e intermedia. "
            "NTC 4007 (ASTM A529/A529M) Especificaciones para el acero al "
            "carbono-manganeso de alta resistencia y calidad estructural. NTC "
            "4009 (ASTM A606) Láminas y flejes de acero laminados en frío y en "
            "caliente de alta resistencia y baja aleación, con resistencia "
            "mejorada a la corrosión. NTC 4011 (ASTM A653/A653M SS Grados 33 "
            "(230MPa), 37 (255MPa), 40 (275MPa), y 50 (340MPa) Clase 1 y Clase "
            "3; HSLA tipos A y B, grados 40 (275MPa), 50 (340MPa), 60 (410MPa), "
            "70 (480MPa) y 80 (550MPa)) Productos planos de acero recubiertos "
            "con zinc — galvanizados — o recubiertos con aleación hierro zinc — "
            "galvano-recocido — mediante procesos de inmersión en caliente. NTC "
            "4015 (ASTM A792/A792M (Grados 33 (230MPa), 37 (255MPa), 40 "
            "(275MPa), y 50 clase 1 (340MPa clase 1)) Productos planos de acero "
            "recubiertos con aleación 55% Aluminio-Zinc, mediante el proceso de "
            "inmersión en caliente. NTC 4526 (ASTM A500) Tubería estructural de "
            "acero al carbono formada en frío, con y sin costura, redonda y de "
            "otras formas. NTC 5091 (ASTM A1008/A1008M SS Grados 25 (170MPa), "
            "30 (205MPa), 33 (230MPa) Tipos 1 y 2, y 40 (275MPa) Tipos 1 y 2; "
            "HSLAS Clases 1 y 2, Grados 45 (310MPa), 50 (340MPa), 55 (380MPa), "
            "60 (410MPa), 65 (450MPa), y 70 (480MPa); HSLAS-F Grados 50 "
            "(340MPa), 60 (410MPa), 70 (480MPa), y 80 (550MPa)) Productos "
            "planos, laminados en frío, de aceros: al carbono, estructurales, "
            "alta resistencia baja aleación y alta resistencia baja aleación "
            "con capacidad de deformado -estampado-. ASTM A847 Tubos "
            "estructurales de alta resistencia y baja aleación formados en "
            "frío, soldados y sin costura con mejorada resistencia a la "
            "corrosión ambiental. ASTM A875/A875M (SS Grados 33 (230MPa), 37 "
            "(255MPa), 40 (275MPa), y 50 (340MPa) clase 1 y clase 3; HSLAS "
            "Tipos A y B, Grados 50 (340MPa), 60 (410MPa), 70 (480MPa) y 80 "
            "(550MPa)) Productos planos de acero recubiertos con aleación "
            "zinc 5% Aluminio, mediante el proceso de inmersión en caliente. "
            "ASTM A1003/A1003M (ST Grados 50 (340MPa) H, 40 (275MPa) H, 37 "
            "(255MPa) H, 33 (230MPa) H) Productos planos de acero, acero al "
            "carbono, con recubrimientos metálicos y no metálicos para "
            "miembros formados en frío de uso en entramados. ASTM A1039/A1039M "
            "(SS Grados 40 (275MPa), 50 (340MPa), 55 (380), 60 (410MPa), 70 "
            "(480MPa) y 80 (550MPa)) Especificaciones estándar para acero en "
            "láminas, laminado en caliente, al carbono, comercial y "
            "estructural, fabricado mediante el proceso de fundida en rollos "
            "mellizos. Espesores del Grado 55 (380) y mayores que no cumplen "
            "el requerimiento del 10% de elongación mínima están limitados por "
            "la sección F.4.1.2.3.2.\n\n"
            "F.4.1.2.2 — Otros aceros — La lista dada en F.4.1.2.1 no excluye "
            "el uso de aceros de hasta 25.4 mm (1 pulgada) de espesor, "
            "ordenados o producidos de acuerdo con otras especificaciones, "
            "siempre y cuando se cumpla que: (1) Los aceros deben cumplir con "
            "los requisitos mecánicos y químicos de cualquiera de las "
            "especificaciones mencionadas anteriormente, u otra especificación "
            "publicada. (2) Las propiedades mecánicas y químicas serán "
            "determinadas por el productor, el proveedor, o el vendedor, de "
            "acuerdo con las siguientes especificaciones: Para láminas "
            "recubiertas, NTC 3940; para acero laminado en caliente, en frío, "
            "en rollos y láminas, NTC 7; para placas y barras, ASTM A6/A6M; "
            "para secciones estructurales huecas, los ensayos deben realizarse "
            "en concordancia con los requerimientos de la NTC 4526 (para acero "
            "al carbón) o ASTM A847 (para acero de alta resistencia baja "
            "aleación, HSLA). (3) Las propiedades del recubrimiento en los "
            "aceros se determinarán por el productor, el proveedor o el "
            "vendedor de acuerdo con lo establecido en NTC 3940. (4) El acero "
            "debe cumplir los requisitos de la sección F.4.1.2.3. (5) Si el "
            "acero va a ser soldado, su idoneidad para el proceso destinado de "
            "soldadura será establecida por el productor, proveedor o vendedor "
            "de acuerdo con las especificaciones de AWS D1.1 ó D1.3 (American "
            "Welding Society), según sea el caso. Si la identificación y "
            "documentación de la producción del acero no han sido "
            "establecidas, entonces adicionalmente a los anteriores cinco "
            "puntos, el fabricante del producto de acero formado en frío "
            "establecerá (a su proveedor o a quien corresponda) que el "
            "esfuerzo de fluencia (punto de fluencia) y la resistencia última "
            "de tensión del rollo madre sean, al menos, 10% mayores que la "
            "suministrada en la especificación publicada de referencia.\n\n"
            "F.4.1.2.3 — Ductilidad — Los aceros que no están en la lista de "
            "F.4.1.2.1 y que se usen para miembros y conexiones estructurales, "
            "de acuerdo con la sección F.4.1.2.2, deben cumplir con uno de los "
            "siguientes requisitos de ductilidad: F.4.1.2.3.1 — La relación "
            "entre la resistencia a la tensión y el esfuerzo de fluencia no "
            "debe ser menor que 1.08, y la elongación total no debe ser menor "
            "que el 10% en una longitud testigo de 50 mm ó 7% en una longitud "
            "testigo de 200 mm de la probeta estándar ensayada de acuerdo con "
            "la norma ASTM A370. Si estos requisitos no se pueden cumplir, se "
            "deben satisfacer los siguientes criterios: 1. La elongación local "
            "en una longitud de 12.7 mm a través de la fractura no debe ser "
            "menor del 20%, 2. La elongación uniforme en la región externa a "
            "la fractura no debe ser menor del 3%. Cuando la ductilidad del "
            "material se determina con base en los criterios de elongación "
            "local y uniforme, se restringe su uso al diseño de correas y "
            "largueros de acuerdo con F.4.3.3.1.1(a), F.4.3.3.1.2, F.4.4.6.1.1, "
            "F.4.4.6.1.2 y F.4.4.6.2.1. Para correas, largueros y parales de "
            "muros-cortina, sujetos a carga axial y a momento flector "
            "combinados (sección F.4.3.5), Pu/(φcPn) no debe ser mayor que "
            "0.15. F.4.1.2.3.2 — Los aceros conforme a la norma ASTM "
            "A653/A653M SS Grado 80 (550MPa), ASTM A1008/A1008M SS Grado 80 "
            "(550MPa), A792/A792M Grado 80 (550MPa), A875/A875M SS Grado 80 "
            "(550MPa) y espesores de la norma ASTM A1039 Grado 55 (380MPa), 60 "
            "(410MPa), 70 (480MPa) y 80 (550MPa) que no cumplen el "
            "requerimiento del 10% de elongación mínima, y otros aceros que no "
            "cumplen lo estipulado en el numeral F.4.1.2.3.1 se permitirán "
            "para uso en miembros en compresión de secciones cerradas cajón "
            "concéntricamente cargadas, y en configuraciones de almas "
            "múltiples tales como cubiertas, cerramientos y tableros de piso "
            "tal como se describe en la Excepción 1, seguidamente, y en la "
            "Excepción 2 descrita en este numeral, siempre y cuando se "
            "cumpla que: (1) El esfuerzo de fluencia, Fy, usado para la "
            "determinación de la resistencia nominal dada en F.4.2, F.4.3, "
            "F.4.4 y F.4.5 se toma como el menor valor entre el 75% del Punto "
            "de Fluencia Mínimo Especificado y 410 MPa. (2) La resistencia "
            "última de tensión, Fu, utilizada para determinar la resistencia "
            "nominal en el numeral F.4.5, es tomada como el menor valor entre "
            "el 75% de la resistencia última mínima especificada y 427 MPa. "
            "Alternativamente, se debe demostrar la aplicabilidad de tales "
            "aceros para la configuración con almas múltiples por medio de "
            "ensayos de carga, de acuerdo con las disposiciones de la sección "
            "F.4.6.1. Las resistencias de diseño que se basen en estos ensayos "
            "no deben exceder las resistencias disponibles calculadas de "
            "acuerdo con los numerales F.4.2 a F.4.8, usando el esfuerzo de "
            "fluencia mínimo especificado, Fsy, y la resistencia última "
            "mínima especificada Fu.\n\n"
            "Excepción 1 — Para configuraciones con almas múltiples, será "
            "permitido el uso de un esfuerzo de fluencia mínimo especificado "
            "reducido, RbFsy, para la determinación de la resistencia nominal "
            "a flexión (resistencia a momento) en numeral F.4.3.3.1.1(a), "
            "para lo cual el factor de reducción, Rb debe determinarse como "
            "sigue: (a) Aletas en compresión rigidizadas y parcialmente "
            "rigidizadas — Para w/t ≤ 0.067E/Fsy: Rb = 1.00. Para "
            "0.067E/Fsy < w/t < 0.974E/Fsy: Rb = 1 − 0.26[wFsy/(tE) − "
            "0.067]^0.4 (ecuación F.4.1.2-1). Para 0.974E/Fsy ≤ w/t ≤ 500: "
            "Rb = 0.75. (b) Aletas en compresión no rigidizadas — Para w/t ≤ "
            "0.0173E/Fsy: Rb = 1.00. Para 0.0173E/Fsy < w/t ≤ 60: Rb = 1.079 "
            "− 0.6·√(wFsy/(tE)) (ecuación F.4.1.2-2). Donde: E = módulo de "
            "elasticidad. Fsy = punto de fluencia mínimo especificado como se "
            "describe en la sección F.4.1.6.1 ≤ 550 MPa. t = espesor de la "
            "sección. w = ancho plano de la aleta en compresión. La excepción "
            "antes expuesta no aplica en tableros de acero para uso en "
            "sección compuesta con una losa de concreto debido a que el "
            "tablero actúa como un refuerzo en tensión para este caso.\n\n"
            "Excepción 2 — Para miembros en compresión, de secciones cerradas "
            "tipo cajón, concéntricamente cargadas, se permitirá el uso de un "
            "esfuerzo de fluencia reducido de 0.9Fsy, en lugar de Fy, en las "
            "ecuaciones F.4.3.4-2, F.4.3.4-3 y F.4.3.4-4 para la determinación "
            "de la resistencia axial en la sección F.4.3.4. Se usará un radio "
            "de giro reducido (Rr)(r) en la ecuación F.4.3.4-5 cuando el valor "
            "de la longitud efectiva KL sea menor a 1.1Lo, donde Lo es dado "
            "por la ecuación F.4.1.2-3 y Rr es dado por la ecuación "
            "F.4.1.2-4. Lo = π·r·√(E/Fcr) (ecuación F.4.1.2-3). Rr = 0.65 + "
            "0.35(KL)/(1.1Lo) (ecuación F.4.1.2-4). Esta ecuación es "
            "aplicable solamente cuando Fuv/Fyv ≥ 1.2, R/t ≤ 7, y el ángulo "
            "incluido es ≤ 120°. Bc = 3.69(Fuv/Fyv) − 0.819(Fuv/Fyv)² − 1.79 "
            "(ecuación F.4.1.6-3, referenciada aquí como parte de las "
            "variables de esta excepción). Donde: Lo = longitud en la cual el "
            "esfuerzo de pandeo local iguala al esfuerzo de pandeo flector. "
            "r = radio de giro de la sección transversal completa no "
            "reducida. Fcr = esfuerzo crítico mínimo de pandeo para la "
            "sección, calculado de acuerdo a la ecuación F.4.2.2-5. Rr = "
            "factor de reducción. KL = longitud efectiva.\n\n"
            "F.4.1.2.4 — Espesor mínimo entregado — El espesor mínimo de "
            "acero sin revestimiento, del producto formado en frío tal como "
            "se entrega a la obra no debe ser en ningún punto menor que el "
            "95% del espesor, t, usado en su diseño; sin embargo, los "
            "espesores pueden ser menores en los dobleces, tales como "
            "esquinas, debido a los efectos del formado en frío."
        ),
    },
    {
        "id": "NSR10-F-F_4_1_3_a_5_cargas_dea_dccr",
        "seccion": "F.4.1.3 a F.4.1.5 (Cargas; Diseño por Esfuerzos Admisibles; Diseño con Coeficientes de Carga y Resistencia)",
        "titulo": "Ecuaciones F.4.1.4-1 y F.4.1.5-1: las cargas nominales remiten al Título B, y las dos ecuaciones base de verificación (DEA: R≤Rn/Ω; DCCR: Ru≤φRn).",
        "texto": (
            "NSR-10 Título F, Capítulo F.4 — F.4.1.3 — CARGAS. F.4.1.3.1 — "
            "Cargas Nominales — Las cargas nominales serán determinadas de "
            "acuerdo con las especificaciones establecidas el Título B de "
            "este Reglamento.\n\n"
            "F.4.1.4 — DISEÑO POR ESFUERZOS ADMISIBLES. F.4.1.4.1 — Bases del "
            "Diseño — Las especificaciones de diseño dadas bajo esta sección "
            "del Reglamento están basadas en los principios del Diseño por "
            "Esfuerzos Admisibles. No aplicarán los requerimientos de este "
            "método en sección alguna de este Reglamento, excepto para "
            "tableros metálicos para trabajo en sección compuesta (Sección "
            "F.4.7). Las bases del diseño para este Reglamento estarán de "
            "acuerdo con lo registrado en la sección F.4.1.5, desarrollada "
            "para el método DCCR. F.4.1.4.1.1 — Requerimientos para Diseño "
            "por Esfuerzos Admisibles — Este método, en el caso que se "
            "especifique como el procedimiento de diseño, satisfará los "
            "requerimientos de este Reglamento cuando la resistencia "
            "admisible de cada componente estructural iguala o excede a la "
            "resistencia admisible requerida, determinada con base en las "
            "cargas nominales, para todas las combinaciones de carga "
            "aplicables. El diseño bajo este método debe ser hecho de acuerdo "
            "con la siguiente ecuación: R ≤ Rn/Ω (ecuación F.4.1.4-1). Donde: "
            "R = resistencia Admisible Requerida, usada donde se indique. Rn "
            "= resistencia Nominal Especificada dada en F.4.2 a F.4.8. Ω = "
            "factor de Seguridad especificado, usado donde se indique. Rn/Ω "
            "= esfuerzo de Diseño Admisible, usado donde se indique. "
            "F.4.1.4.1.2 — Combinaciones de carga para Diseño por Esfuerzos "
            "Admisibles — Las combinaciones de carga para el método de "
            "Diseño por Esfuerzos Admisibles están estipuladas en el Título "
            "B de este Reglamento.\n\n"
            "F.4.1.5 — DISEÑO CON COEFICIENTES DE CARGA Y RESISTENCIA "
            "(DCCR). F.4.1.5.1 — Bases del Diseño — Las especificaciones de "
            "diseño dadas bajo esta sección del Reglamento están basadas en "
            "los principios del Diseño con Coeficientes de Carga y "
            "Resistencia (DCCR) Deben aplicar todos los requerimientos de "
            "esta sección para el diseño con miembros estructurales formados "
            "en frío, excepto donde se especifique lo contrario. "
            "F.4.1.5.1.1 — Requerimientos para el Diseño con Coeficientes de "
            "Carga y Resistencia (DCCR) — El diseño satisfará los "
            "requerimientos de este Reglamento cuando la resistencia de "
            "diseño de cada componente estructural iguala o excede la "
            "resistencia requerida determinada con base en las cargas "
            "nominales multiplicadas por los apropiados coeficientes de "
            "mayoración de carga, para todas las combinaciones de carga "
            "aplicables. El diseño debe ser realizado de acuerdo con la "
            "siguiente ecuación: Ru ≤ φRn (ecuación F.4.1.5-1). Donde: Ru = "
            "resistencia requerida. Rn = resistencia nominal especificada en "
            "F.4.2 a F.4.8. φ = coeficiente de resistencia especificado en "
            "F.4.2 a F.4.8. φRn = resistencia de diseño. F.4.1.5.1.2 — "
            "Coeficientes y combinaciones de carga para DCCR — Los "
            "coeficientes de carga y sus combinaciones para el método DCCR "
            "están estipulados en el Título B de este Reglamento."
        ),
    },
    {
        "id": "NSR10-F-F_4_1_6_incremento_fluencia",
        "seccion": "F.4.1.6 (Incremento en el Punto de Fluencia y la Resistencia debido al Trabajo de Formado en Frío)",
        "titulo": "Ecuaciones F.4.1.6-1 a F.4.1.6-4: los 3 métodos permitidos (ensayo de sección completa, ensayo de columnas cortas, cálculo) para el esfuerzo de fluencia promedio Fya de esquinas formadas en frío.",
        "texto": (
            "NSR-10 Título F, Capítulo F.4 — F.4.1.6 — INCREMENTO EN EL PUNTO "
            "DE FLUENCIA Y LA RESISTENCIA DEBIDO AL TRABAJO DE FORMADO EN "
            "FRÍO. F.4.1.6.1 — Esfuerzo de Fluencia — El esfuerzo de fluencia "
            "usado en el diseño, Fy, será un valor no mayor al esfuerzo de "
            "fluencia mínimo especificado de los aceros listados en las "
            "secciones F.4.1.2.1 ó F.4.1.2.3.2, o el que se establece en "
            "F.4.6, o incrementado por efecto del trabajo de formación en "
            "frío descrito en la sección F.4.1.6.2.\n\n"
            "F.4.1.6.2 — Incremento en la resistencia debido al trabajo de "
            "formado en frío — El incremento en la resistencia debido al "
            "trabajo de formación en frío permitirá la sustitución de Fya "
            "por Fy, donde Fya es el promedio del esfuerzo de fluencia de la "
            "sección completa. Tal incremento debe ser limitado de acuerdo "
            "con las secciones F.4.3.2, F.4.3.3.1 (excluyendo la sección "
            "F.4.3.3.1.1 (b)), F.4.3.4, F.4.3.5, F.4.4.4 y F.4.4.6.1. Las "
            "limitaciones y métodos utilizados en la determinación de Fya "
            "son los siguientes: (a) Para miembros en compresión cargados "
            "axialmente y miembros en flexión para los cuales sus "
            "proporciones son tales que la cantidad ρ para la determinación "
            "de la resistencia es igual a la unidad (1.00), calculado acorde "
            "con la sección F.4.2.2 de este Reglamento para cada uno de los "
            "elementos componentes de la sección, el punto de fluencia de "
            "diseño, Fya, del acero será determinado con base en uno de los "
            "siguientes métodos: (1) Ensayos a tensión de la sección "
            "completa (Ver párrafo (a) de la sección F.4.6.3.1). (2) Ensayos "
            "sobre columnas cortas (Ver párrafo (b) de la sección F.4.6.3.1). "
            "(3) Calculado como sigue: Fya = C·Fyc + (1 − C)·Fyf ≤ Fuv "
            "(ecuación F.4.1.6-1). Donde: Fya = esfuerzo de fluencia "
            "promedio de la sección completa no reducida para miembros en "
            "compresión o de secciones con aletas completas para miembros en "
            "flexión. c = relación entre el total del área de las esquinas y "
            "el total del área de la sección transversal completa, para "
            "miembros en compresión; o relación entre el total del área de "
            "las esquinas de la aleta que controla y el total del área de la "
            "aleta que controla, para miembros en flexión. Fyf = es la media "
            "ponderada del punto de fluencia a tensión de las porciones "
            "planas establecidas de acuerdo con la sección F.4.6.3.2 de este "
            "Reglamento o el punto de fluencia del acero virgen si no se "
            "realizan ensayos. Fyc = BcFyv/(R/t)^m (ecuación F.4.1.6-2). La "
            "anterior expresión define el esfuerzo de fluencia a tensión de "
            "las esquinas. Esta ecuación es aplicable solamente cuando "
            "Fuv/Fyv ≥ 1.2, R/t ≤ 7, y el ángulo incluido es ≤ 120°. Bc = "
            "3.69(Fuv/Fyv) − 0.819(Fuv/Fyv)² − 1.79 (ecuación F.4.1.6-3). m "
            "= 0.192(Fuv/Fyv) − 0.068 (ecuación F.4.1.6-4). Donde: R = radio "
            "interno de doblez. t = espesor de la sección. Fyv = esfuerzo de "
            "fluencia a tensión del acero virgen especificado en la sección "
            "F.4.1.2 de este Reglamento o según como se establece en "
            "F.4.6.3.3. Fuv = resistencia a tensión del acero virgen "
            "especificado por la sección F.4.1.2 o establecido de acuerdo "
            "con F.4.6.3.3. (b) Para miembros en tensión axialmente cargados "
            "el punto de fluencia del acero será determinado ya sea por el "
            "método 1. o el método 3. prescrito en el párrafo a) de esta "
            "misma sección. (c) El efecto de la soldadura sobre las "
            "propiedades mecánicas de un miembro será determinado con base "
            "en ensayos sobre probetas de sección completa que contengan, "
            "dentro de la longitud testigo, el tipo de soldadura que el "
            "fabricante se propone utilizar. Se deben tomar las medidas "
            "necesarias para considerar tal efecto en el uso estructural del "
            "miembro."
        ),
    },
    {
        "id": "NSR10-F-F_4_1_7_8_servicio_referencias",
        "seccion": "F.4.1.7 y F.4.1.8 (Estado de Servicio de la Estructura; Documentos de Referencia)",
        "titulo": "Estados límite de servicio y la lista completa de normas de referencia (AISI S1xx/S2xx, ASCE 7-05, AWS D1.3/C1.1, ASME B46.1, y las 23 NTC/ASTM de materiales y conexiones).",
        "texto": (
            "NSR-10 Título F, Capítulo F.4 — F.4.1.7 — ESTADO DE SERVICIO DE "
            "LA ESTRUCTURA — Una estructura será diseñada para llevar a cabo "
            "las funciones requeridas durante su vida esperada. Los estados "
            "límite de servicio deben ser escogidos con base en la función "
            "destinada para la estructura, y deben ser evaluados usando "
            "cargas y combinaciones de carga realistas.\n\n"
            "F.4.1.8 — DOCUMENTOS DE REFERENCIA — Los siguientes documentos "
            "son las referencias y la base de este Reglamento: American "
            "Iron and Steel Institute (AISI), 1140 Connecticut Avenue, NW, "
            "Washington, DC20036: AISI S100-07, North American Specification "
            "for the Design of Cold-Formed Steel Structural Members. AISI "
            "S200-07, North American Standard for Cold-Formed Steel Framing "
            "— General Provisions. AISI S210-07, North American Standard for "
            "Cold-Formed Steel Framing — Floor and Roof System Design. AISI "
            "S211-07, North American Standard for Cold-Formed Steel Framing "
            "— Wall Stud Design. AISI S212-07, North American Standard for "
            "Cold-Formed Steel Framing — Header Design. AISI S213-07, North "
            "American Standard for Cold-Formed Steel Framing — Lateral "
            "Design. AISI S214-07, North American Standard for Cold-Formed "
            "Steel Framing — Truss Design. AISI S901-02, Rotational-Lateral "
            "Stiffness Test Method for Beam-to-Panel Assemblies. AISI "
            "S902-02, Stub-Column Test Method for Effective Area of "
            "Cold-Formed Steel Columns. AISI S906-04, Standard Procedures "
            "for Panel and Anchor Structural Tests. AISI S908-04, Base Test "
            "Method for Purlins Supporting a Standing Seam Roof System. "
            "American Society of Civil Engineers (Sociedad Americana de "
            "Ingenieros Civiles) (ASCE), 1801 Alexander Bell Drive, Reston "
            "VA, 20191: ASCE/SEI 7-05, Minimun Design Loads in Buildings and "
            "Other Structures. American Welding Society (AWS), 550 N.W. "
            "LeJeune Road, Miami, Florida 33135: AWS D1.3-98, Structural "
            "Welding Code — Sheet Steel. AWS C1.1/C1.1M–2000, Recommended "
            "Practices for Resistances Welding. American Society of "
            "Mechanical Engineers (Sociedad Americana de Ingenieros "
            "Mecánicos), ASME B46.1-2000 'Surface Texture, Surface "
            "Roughness, Waviness, and Lay'.\n\n"
            "Normas NTC (Normas Técnicas Colombianas) del ICONTEC ó ASTM "
            "(American Society for Testing and Materials) según aplique: "
            "NTC 6 (ASTM A1011/A1011M-05a) Productos planos, laminados en "
            "caliente de aceros: al carbono, estructurales, alta resistencia "
            "baja aleación con capacidad de deformado — estampado —. NTC "
            "1920 (ASTM A36/A36M-00a) Acero estructural al Carbono. NTC 1950 "
            "(ASTM A242/A242M-00a) Acero estructural de baja aleación y alta "
            "resistencia. NTC 1985 (ASTM A572/A572M-06) Aceros de calidad "
            "estructural de alta resistencia baja aleación Niobio "
            "(Columbio) — vanadio. NTC 2012 (ASTM A588/A588M-05) Acero "
            "estructural de alta resistencia y baja aleación con límite de "
            "fluencia mínimo de 345MPa en espesores hasta 100mm. NTC 2633 "
            "(ASTM A283/A283M-00) Barras y chapas de acero al carbono de "
            "media y baja resistencia a la tensión. NTC 3353 (ASTM A370-05) "
            "Definiciones y métodos para los ensayos mecánicos de productos "
            "de acero. NTC 4007 (ASTM A529/A529M-05) Especificaciones para "
            "el acero al carbono-manganeso de alta resistencia y calidad "
            "estructural. NTC 4009 (ASTM A606-04) Láminas y flejes de acero, "
            "laminados en frío y en caliente de alta resistencia y baja "
            "aleación, con resistencia mejorada a la corrosión. NTC 4011 "
            "(ASTM A653/A653M-06) Productos planos de acero recubiertos con "
            "Zinc — galvanizados — o recubiertos con aleación zinc — "
            "galvano-recocido — mediante procesos de inmersión en caliente. "
            "NTC 4015 (ASTM A792/A792M-05) Productos planos de acero "
            "recubiertos con aleación 55% aluminio-zinc, mediante el "
            "proceso de inmersión en caliente. NTC 4028 (ASTM A490M-04a) "
            "Elementos de fijación. Pernos de acero de alta resistencia, "
            "clase 10.9 y 10.9.3 para juntas de acero estructurales — "
            "sistema métrico —. NTC 4029 (ASTM A325M-06) Elementos de "
            "fijación. Pernos de alta resistencia destinados a juntas de "
            "acero estructurales — sistema métrico —. NTC 4031 (ASTM "
            "F436M-04) Elementos de fijación. Arandelas de acero templado — "
            "sistema métrico. NTC 4034 (ASTM A307-00) Elementos de "
            "fijación. Especificación para tornillos y pernos de acero al "
            "carbono con 490MPa de resistencia a la tensión. NTC 4035 (ASTM "
            "A194/A194M-00b) Especificación para tuercas de acero al "
            "carbono y aleado para alta presión y servicios de alta "
            "temperatura. NTC 4479 (ASTM A449-04b) Tornillos y pernos de "
            "acero al carbono templados y revenidos. NTC 4511 (ASTM "
            "A563M-04) Especificaciones para tuercas de acero aleado y al "
            "carbono — sistema métrico —. NTC 4512 (ASTM A354-04) "
            "Tornillos, pernos y otros elementos de fijación roscados "
            "externamente, templados y revenidos, de aleación de acero. "
            "NTC 4526 (ASTM A500-03a) Tubería estructural de acero al "
            "carbono formada en frío, con y sin costura, redonda y de "
            "otras formas. NTC 4701 (ASTM F959-04) Elementos de fijación. "
            "Indicadores directos de tensión tipo arandela compresible "
            "para uso con elementos de fijación estructurales. NTC 4965 "
            "(ASTM A563-00) Tuercas de acero al carbono y acero aleado. "
            "NTC 5091 (ASTM A1008/A1008M-05b) Productos planos, laminados "
            "en frío, de aceros: al carbono, estructurales, alta "
            "resistencia baja aleación y alta resistencia baja aleación "
            "con capacidad de deformado (estampado). ASTM A325-06 Pernos "
            "estructurales de acero, tratados térmicamente, con "
            "resistencia última mínima de 835/735ksi. ASTM A490-06 Pernos "
            "estructurales de acero tratados térmicamente (calor) con "
            "mínima resistencia última de 1050MPa. ASTM A847/A847M-05 "
            "Tubos estructurales de alta resistencia y baja aleación "
            "formados en frío, soldados y sin costura con mejorada "
            "resistencia a la corrosión ambiental. ASTM A875/A875M-05 "
            "Productos planos de acero recubiertos con aleación zinc 5% "
            "Aluminio, mediante el proceso de inmersión en caliente. ASTM "
            "A1003/A1003M-05 Productos planos de acero, acero al carbono, "
            "con recubrimientos metálicos y no metálicos para miembros "
            "formados en frío de uso en entramados. ASTM A1039/A1039M-04 "
            "Especificaciones estándar para acero en láminas, laminado en "
            "caliente, al carbono, comercial y estructural, fabricado "
            "mediante el proceso de fundición en rollos mellizos. ASTM "
            "E1592-01 Método de ensayo estándar para el comportamiento "
            "estructural de cubiertas metálicas y sistemas de cerramiento "
            "mediante la diferencia estática y uniforme de presión de "
            "aire. ASTM F436-04 Elementos de fijación. Arandelas de acero "
            "templado. ASTM F844-04 Arandela, aceros y productos planos, "
            "no templados de uso general. ASTM F959M-05a Elementos de "
            "fijación. Indicadores directos de tensión tipo arandela "
            "compresible para uso con elementos de fijación estructurales "
            "— sistema métrico. American Institute of Steel Construction "
            "(AISC), 1140 Connecticut Avenue, NW, Washington, DC20036: "
            "ANSI/AISC 360-05, Specification for Structural Steel "
            "Buildings. Steel Deck Institute. Design Manual for Composite "
            "Decks, Form Decks and Roof Decks, publication No 30, 2000. "
            "Steel Deck Institute. Composite Deck Design Handbook, March "
            "1997. Steel Deck Institute. Manual of Construction with Steel "
            "Deck, 1991."
        ),
    },
]


def main():
    from sentence_transformers import SentenceTransformer
    from supabase import create_client

    sb = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])
    print(f"Chunks a insertar: {len(CHUNKS)}")
    for c in CHUNKS:
        print(f"  {c['id']} ({c['seccion']}): {len(c['texto'])} chars")

    print("\nCargando modelo de embeddings local...")
    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
    textos = [c["texto"] for c in CHUNKS]
    vectores = model.encode(textos, normalize_embeddings=True, show_progress_bar=True)

    rows = []
    for chunk, vec in zip(CHUNKS, vectores):
        rows.append({
            "id": chunk["id"],
            "capitulo": CAPITULO,
            "seccion": chunk["seccion"],
            "titulo": chunk["titulo"][:500],
            "texto": chunk["texto"],
            "embedding": vec.tolist(),
        })

    print("\nSubiendo a nsr10_chunks (upsert por id)...")
    sb.table("nsr10_chunks").upsert(rows, on_conflict="id").execute()

    print(f"\nOK: {len(rows)} chunks verbatim de F.4.1 cargados. Numeral F.4.1 completo.")


if __name__ == "__main__":
    main()
