"""
Carga la Tabla 16 de la sección 10.2 de la NEC-SE-DS (Ecuador) --
"Poblaciones ecuatorianas y valor del factor Z" -- en
ecuador_nec_se_ds_zonificacion_poblacion.

Equivalente real al Anexo II de la E.030 de Perú (ver
scripts/ingesta/peru_e030/cargar_zonificacion_anexo2_completo.py):
consulta EXACTA de zona sísmica por localidad, no texto narrativo -- por
eso va a una tabla relacional propia, sin columna de embedding, mismo
patrón que peru_e030_zonificacion_distrital.

DIFERENCIA REAL DE FONDO con Perú (no una limitación de esta carga): el
método PRINCIPAL de zonificación de Ecuador es un MAPA (Figura 1, 6 zonas
sísmicas I-VI, ver Tabla 1 en el chunk NECSEDS-S4_1...). La Tabla 16 de
la sección 10.2 es un listado de apoyo -- "para facilitar la
determinación del valor de Z" -- con "algunas poblaciones del país", NO
una partición administrativa exhaustiva de los ~1.500 parroquias/
cantones del Ecuador como sí lo es el Anexo II peruano (mandato del
Artículo 10.1 de la E.030: "el Anexo II contiene el listado de las
provincias y distritos que corresponden a cada zona" -- sin excepción).
Se carga tal cual la trae la norma -- no se completa por inferencia lo
que el mapa cubriría para las localidades no listadas.

Fuente: PDF oficial MTOP/MIDUVI (mit.gob.ec/wp-content/uploads/downloads/
2016/04/MTOP_NEC-SE-DS.pdf), páginas internas 93-111 (Sección 10.2),
mismo documento ya usado para Sección 1 y Tablas 6/15/16 de coeficiente
R -- confirmado PDF digital real con texto extraíble (pypdf, 139
páginas).

Metodología de transcripción -- por qué NO es lectura visual página por
página como el Anexo II de Perú: el texto de ESTA tabla específica SÍ es
limpio y extraíble (a diferencia del PDF de Perú, que tiene corrupción
sistemática de fuente). Se parseó programáticamente usando la lista fija
de las 24 provincias del Ecuador + "Zona No Delimitada" (categoría
administrativa real, ver más abajo) como ancla del regex, verificado con
0 huecos de cobertura sobre el texto completo (25,083 caracteres). Se
detectaron y corrigieron 2 clases de error real durante la verificación,
NO se dieron por buenos a ciegas:
  1. Un bug de fusión de filas: la variante abreviada "STO. DOMINGO DE
     LOS TSACHILAS" no estaba en la lista de anclas, así que 15 filas de
     esa provincia se fusionaron en una sola fila gigante hasta la
     siguiente ancla válida -- detectado con una heurística de longitud
     de campo sospechosa (>70 caracteres), corregido agregando la
     variante, re-verificado (0 huecos, filas de longitud normal).
  2. 9 filas con caracteres corruptos de fuente (glitch real del PDF
     fuente, confirmado visualmente contra el documento renderizado, no
     solo del texto extraído -- ej. "AMAGUAÐA" en vez de "AMAGUAÑA",
     "BAÐOS" en vez de "BAÑOS", "SIMËN" en vez de "SIMÓN", "SUC┌A" en vez
     de "SUCUA", "CAÐI" -> "CADI" verificado visualmente contra la
     página 94 del PDF renderizado) -- las 9 se corrigieron una por una
     contra el PDF real, no por suposición.

Columna "poblacion": combina las 3 columnas de la tabla fuente
(POBLACIÓN, PARROQUIA, CANTÓN) tal como aparecen, sin separarlas -- el
texto extraído no trae un delimitador confiable entre esas 3 celdas para
separarlas por software sin arriesgar errores en un dato de consulta
exacta (verificado: intentarlo producía splits ambiguos en nombres
compuestos). Sigue siendo consultable por cualquiera de los 3 términos
vía ILIKE.

"Zona No Delimitada" (3 filas: Las Golondrinas, Manga del Cura) es una
categoría administrativa REAL de Ecuador -- territorio en disputa entre
Esmeraldas/Santo Domingo/Manabí/Los Ríos, sin provincia asignada. No es
un error de transcripción, se carga tal cual la trae la norma.

515 filas parseadas, 512 tras deduplicar 3 filas idénticas (mismo
poblacion+provincia+Z, confirmado antes de deduplicar).

Uso: python scripts/ingesta/ecuador_nec_se_ds/cargar_tabla16_poblaciones_factor_z.py [--dry-run]
"""
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
from dotenv import load_dotenv
load_dotenv(ROOT / "apps" / "api" / ".env")


FILAS: list[dict] = [
    {"poblacion": "CUENCA CUENCA CUENCA", "provincia": "AZUAY", "factor_z": 0.25},
    {"poblacion": "CHORDELEG CHORDELEG CHORDELEG", "provincia": "AZUAY", "factor_z": 0.25},
    {"poblacion": "GUALACEO GUALACEO GUALACEO", "provincia": "AZUAY", "factor_z": 0.25},
    {"poblacion": "SEVILLA DE ORO SEVILLA DE ORO SEVILLA DE ORO", "provincia": "AZUAY", "factor_z": 0.25},
    {"poblacion": "EL PAN EL PAN EL PAN", "provincia": "AZUAY", "factor_z": 0.25},
    {"poblacion": "PAUTE CHICAN (GUILLERMO ORTEGA) PAUTE", "provincia": "AZUAY", "factor_z": 0.25},
    {"poblacion": "GUARANDA GUARANDA GUARANDA", "provincia": "BOLÍVAR", "factor_z": 0.35},
    {"poblacion": "SAN LORENZO SAN LORENZO GUARANDA", "provincia": "BOLÍVAR", "factor_z": 0.35},
    {"poblacion": "SANTIAGO SANTIAGO SAN MIGUEL", "provincia": "BOLÍVAR", "factor_z": 0.35},
    {"poblacion": "SAN JOSE DEL TAMBO SAN JOSE DEL TAMBO CHILLANES", "provincia": "BOLÍVAR", "factor_z": 0.35},
    {"poblacion": "SAN SIMON SAN SIMON (YACOTO) GUARANDA", "provincia": "BOLÍVAR", "factor_z": 0.35},
    {"poblacion": "SAN MIGUEL DE BOLIVAR SAN MIGUEL SAN MIGUEL", "provincia": "BOLÍVAR", "factor_z": 0.35},
    {"poblacion": "SAN JOSE DE CHIMBO SAN JOSE DE CHIMBO CHIMBO", "provincia": "BOLÍVAR", "factor_z": 0.35},
    {"poblacion": "SIMIATUG SIMIATUG GUARANDA", "provincia": "BOLÍVAR", "factor_z": 0.30},
    {"poblacion": "SAN LUIS DE PAMBIL SAN LUIS DE PAMBIL GUARANDA", "provincia": "BOLÍVAR", "factor_z": 0.30},
    {"poblacion": "FACUNDO VELA FACUNDO VELA GUARANDA", "provincia": "BOLÍVAR", "factor_z": 0.30},
    {"poblacion": "LAS MERCEDES LAS NAVES LAS NAVES", "provincia": "BOLÍVAR", "factor_z": 0.30},
    {"poblacion": "LAS NAVES LAS NAVES LAS NAVES", "provincia": "BOLÍVAR", "factor_z": 0.30},
    {"poblacion": "SAN LUIS DE LAS MERCEDES SAN LUIS DE PAMBIL GUARANDA", "provincia": "BOLÍVAR", "factor_z": 0.30},
    {"poblacion": "ECHEANDIA ECHEANDIA ECHEANDIA", "provincia": "BOLÍVAR", "factor_z": 0.30},
    {"poblacion": "CHILLANES CHILLANES CHILLANES", "provincia": "BOLÍVAR", "factor_z": 0.40},
    {"poblacion": "CAÑAR CAÑAR CAÑAR", "provincia": "CAÑAR", "factor_z": 0.30},
    {"poblacion": "EL TAMBO EL TAMBO EL TAMBO", "provincia": "CAÑAR", "factor_z": 0.30},
    {"poblacion": "LA PUNTILLA PANCHO NEGRO LA TRONCAL", "provincia": "CAÑAR", "factor_z": 0.40},
    {"poblacion": "LA TRONCAL LA TRONCAL LA TRONCAL", "provincia": "CAÑAR", "factor_z": 0.40},
    {"poblacion": "DELEG DELEG DELEG", "provincia": "CAÑAR", "factor_z": 0.25},
    {"poblacion": "AZOGUES AZOGUES AZOGUES", "provincia": "CAÑAR", "factor_z": 0.25},
    {"poblacion": "BIBLIAN BIBLIAN BIBLIAN", "provincia": "CAÑAR", "factor_z": 0.25},
    {"poblacion": "HUACA HUACA SAN PEDRO DE HUACA", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "EL PLAYON DE SAN FRANCISCO EL CARMELO (EL PUN) TULCAN", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "MARISCAL SUCRE MARISCAL SUCRE SAN PEDRO DE HUACA", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "TULCAN TULCAN TULCAN", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "EL ANGEL EL ANGEL ESPEJO", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "SAN GABRIEL SAN GABRIEL MONTUFAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "EL CARMELO EL CARMELO (EL PUN) TULCAN", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "LA LIBERTAD LA LIBERTAD (ALIZO) ESPEJO", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "JULIO ANDRADE JULIO ANDRADE (OREJUELA) TULCAN", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "LA PAZ LA PAZ MONTUFAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "SAN ISIDRO SAN ISIDRO ESPEJO", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "SAN JOSE DE TINAJILLAS GARCIA MORENO BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "SANTA MARTHA DE CUBA SANTA MARTHA DE CUBA TULCAN", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "GARCIA MORENO GARCIA MORENO BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "MONTE OLIVO MONTE OLIVO BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "PIQUIUCHO LOS ANDES BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "PUEBLO NUEVO SAN RAFAEL BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "PUSIR SAN VICENTE DE PUSIR BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "LOS ANDES LOS ANDES BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "FERNANDEZ SALVADOR FERNANDEZ SALVADOR MONTUFAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "SAN VICENTE DE PUSIR SAN VICENTE DE PUSIR BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "MIRA MIRA (CHONTAHUASI) MIRA", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "BOLIVAR BOLIVAR BOLIVAR", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "TUFIÑO TUFIÑO TULCAN", "provincia": "CARCHI", "factor_z": 0.40},
    {"poblacion": "CALPÍ CADI COLTA", "provincia": "CHIMBORAZO", "factor_z": 0.35},
    {"poblacion": "PALLATANGA PALLATANGA PALLATANGA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "PUNGAL GRANDE GUANO GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "GUANO GUANO GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "PENIPE PENIPE PENIPE", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SAN ANDRES SAN ANDRES GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SAN ISIDRO DE PATULU SAN ISIDRO DE PATULU GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "VALPARAISO VALPARAISO GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SAN JOSE DE CHAZO SAN JOSE DEL CHAZO GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "GUANANDO GUANANDO GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "CALPI CALPI RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "LICÍN RIOBAMBA RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "QUIMIAG QUIMIAG RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "ASUNCION CALPI RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "MACAJÁ RIOBAMBA RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "PUELA PUELA PENIPE", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "RIOBAMBA GUANO GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "ILAPO ILAPO GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SAN GERARDO SAN GERARDO DE PACAICAGUAN GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SAN ANTONIO DE BAYUSHIG SAN ANTONIO DE BAYUSHIG PENIPE", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SANTA FE DE GALAN SANTA FE DE GALAN GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SAN VICENTE RIOBAMBA RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "CHAMBO CHAMBO CHAMBO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "PUNIN PUNIN RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "LICTO LICTO RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "PUNGALA PUNGALA RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "YARUQUIES RIOBAMBA RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SAN LUIS SAN LUIS RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "JUAN DE VELASCO JUAN DE VELASCO (PANGOR) COLTA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "CEBADAS CEBADAS GUAMOTE", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "CAJABAMBA VILLA LA UNION (CAJABAMBA) COLTA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "CUBIJIES GUANO GUANO", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "SAN JUAN SAN JUAN RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "COLUMBE COLUMBE COLTA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "MATUS EL ALTAR PENIPE", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "VILLA LA UNION VILLA LA UNION (CAJABAMBA) COLTA", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "GUAMOTE GUAMOTE GUAMOTE", "provincia": "CHIMBORAZO", "factor_z": 0.40},
    {"poblacion": "LLACTAPAMBA DE ALAO PUNGALA RIOBAMBA", "provincia": "CHIMBORAZO", "factor_z": 0.35},
    {"poblacion": "CHUNCHI CHUNCHI CHUNCHI", "provincia": "CHIMBORAZO", "factor_z": 0.35},
    {"poblacion": "ALAUSI SIBAMBE ALAUSI", "provincia": "CHIMBORAZO", "factor_z": 0.35},
    {"poblacion": "ANGAMARCA ANGAMARCA PUJILI", "provincia": "COTOPAXI", "factor_z": 0.30},
    {"poblacion": "LA MANA LA MANA LA MANA", "provincia": "COTOPAXI", "factor_z": 0.30},
    {"poblacion": "ZUMBAHUA ZUMBAHUA PUJILI", "provincia": "COTOPAXI", "factor_z": 0.30},
    {"poblacion": "EL CORAZON EL CORAZON PANGUA", "provincia": "COTOPAXI", "factor_z": 0.30},
    {"poblacion": "MORASPUNGO MORASPUNGO PANGUA", "provincia": "COTOPAXI", "factor_z": 0.30},
    {"poblacion": "SIGCHOS SIGCHOS SIGCHOS", "provincia": "COTOPAXI", "factor_z": 0.30},
    {"poblacion": "CUSUBAMBA CUSUBAMBA SALCEDO", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "ALAQUES ALAQUES (ALAQUEZ) LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "MULALILLO MULALILLO SALCEDO", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "PANSALEO PANSALEO SALCEDO", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "ANTONIO JOSE HOLGUIN ANTONIO JOSE HOLGUIN SALCEDO", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "GUAITACAMA GUAITACAMA (GUAYTACAMA) LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "MULLIQUINDIL MULLIQUINDIL (SANTA ANA) SALCEDO", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "SAQUISILI CHANTILIN SAQUISILI", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "MARISCAL SUCRE POALO LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "LATACUNGA LATACUNGA LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "LA VICTORIA LA VICTORIA PUJILI", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "SAN JUAN DE PASTOCALLE SAN JUAN DE PASTOCALLE LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "TANICUCHA TANICUCHI LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "TOACASO TOACASO LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "MULALO MULALO LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "SAN AGUSTIN DE CALLO MULALO LATACUNGA", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "SAN MIGUEL DE SALCEDO SAN MIGUEL SALCEDO", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "PUJILI PUJILI PUJILI", "provincia": "COTOPAXI", "factor_z": 0.40},
    {"poblacion": "PORTOVELO PORTOVELO PORTOVELO", "provincia": "EL ORO", "factor_z": 0.30},
    {"poblacion": "CHILLA CHILLA CHILLA", "provincia": "EL ORO", "factor_z": 0.30},
    {"poblacion": "PACCHA PACCHA ATAHUALPA", "provincia": "EL ORO", "factor_z": 0.30},
    {"poblacion": "PIÑAS PIÑAS PIÑAS", "provincia": "EL ORO", "factor_z": 0.30},
    {"poblacion": "ZARUMA MALVAS ZARUMA", "provincia": "EL ORO", "factor_z": 0.30},
    {"poblacion": "HUAQUILLAS HUAQUILLAS HUAQUILLAS", "provincia": "EL ORO", "factor_z": 0.40},
    {"poblacion": "SANTA ROSA SANTA ROSA SANTA ROSA", "provincia": "EL ORO", "factor_z": 0.40},
    {"poblacion": "ARENILLAS ARENILLAS ARENILLAS", "provincia": "EL ORO", "factor_z": 0.40},
    {"poblacion": "BELLAVISTA BELLAVISTA SANTA ROSA", "provincia": "EL ORO", "factor_z": 0.40},
    {"poblacion": "MACHALA MACHALA MACHALA", "provincia": "EL ORO", "factor_z": 0.40},
    {"poblacion": "BALSAS BALSAS BALSAS", "provincia": "EL ORO", "factor_z": 0.35},
    {"poblacion": "MARCABELI MARCABELI MARCABELI", "provincia": "EL ORO", "factor_z": 0.35},
    {"poblacion": "PASAJE PASAJE PASAJE", "provincia": "EL ORO", "factor_z": 0.35},
    {"poblacion": "BELLA MARIA BELLAMARIA SANTA ROSA", "provincia": "EL ORO", "factor_z": 0.40},
    {"poblacion": "EL GUABO EL GUABO EL GUABO", "provincia": "EL ORO", "factor_z": 0.40},
    {"poblacion": "LA UNION LA UNION QUININDE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "VICHE VICHE QUININDE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "MONTERREY ROSA ZARATE (QUININDE) QUININDE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "LA VILLEGAS ROSA ZARATE (QUININDE) QUININDE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "ATACAMES ATACAMES ATACAMES", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "ROSA ZARATE ROSA ZARATE (QUININDE) QUININDE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "BOLIVAR BOLIVAR MUISNE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "LA INDEPENDENCIA ROSA ZARATE (QUININDE) QUININDE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "LA TE MALIMPIA QUININDE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "ZAPALLO MALIMPIA QUININDE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "ESMERALDAS ESMERALDAS ESMERALDAS", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "SAN LORENZO SAN LORENZO SAN LORENZO", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "PUERTO GAVIOTA TONSUPA ATACAMES", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "LA CONCORDIA LA CONCORDIA LA CONCORDIA", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "PLAN PILOTO LA CONCORDIA LA CONCORDIA", "provincia": "ESMERALDAS", "factor_z": 0.40},
    {"poblacion": "VALDEZ VALDEZ (LIMONES) ELOY ALFARO", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "MUISNE MUISNE MUISNE", "provincia": "ESMERALDAS", "factor_z": 0.50},
    {"poblacion": "JUAN GOMEZ RENDON JUAN GOMEZ RENDON (PROGRESO) GUAYAQUIL", "provincia": "GUAYAS", "factor_z": 0.50},
    {"poblacion": "GENERAL VILLAMIL GENERAL VILLAMIL (PLAYAS) PLAYAS", "provincia": "GUAYAS", "factor_z": 0.50},
    {"poblacion": "LA ESTACADA PEDRO CARBO PEDRO CARBO", "provincia": "GUAYAS", "factor_z": 0.50},
    {"poblacion": "SAN LORENZO JUAN GOMEZ RENDON (PROGRESO) GUAYAQUIL", "provincia": "GUAYAS", "factor_z": 0.50},
    {"poblacion": "SAN CAMILO GUAYAS (PUEBLO NUEVO) EMPALME", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "SAN JACINTO DE YAGUACHI SAN JACINTO DE YAGUACHI SAN JACINTO DE YAGUACHI", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "MARISCAL SUCRE MARISCAL SUCRE (HUAQUES) MILAGRO", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "LORENZO DE GARAICOA CRNEL. LORENZO DE GARAICOA SIMON BOLIVAR", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "SANTO DOMINGO SIMON BOLIVAR SIMON BOLIVAR", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "SAMBORONDON SAMBORONDON SAMBORONDON", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "GENERAL VERNAZA GRAL. VERNAZA (DOS ESTEROS) SALITRE", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "MATA DE CACAO CRNEL. LORENZO DE GARAICOA SIMON BOLIVAR", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "VELASCO IBARRA VELASCO IBARRA (CAB. EL EMPALME) EMPALME", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "MILAGRO MILAGRO MILAGRO", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "PEDRO J. MONTERO GRAL. PEDRO J. MONTERO (BOLICHE) SAN JACINTO DE YAGUACHI", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "NARANJITO NARANJITO NARANJITO", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "CORONEL MARCELINO MARIDUEÑA CRNEL. MARCELINO MARIDUEÑA CRNEL. MARCELINO MARIDUEÑA", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "ALFREDO BAQUERIZO MORENO ALFREDO BAQUERIZO MORENO ALFREDO BAQUERIZO MORENO", "provincia": "GUAYAS", "factor_z": 0.30},
    {"poblacion": "CARLOS J. AROSEMENA GUAYAS (PUEBLO NUEVO) EMPALME", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "LA GUAYAQUIL BALZAR BALZAR", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "PALESTINA PALESTINA PALESTINA", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "PEDRO VELEZ EL ROSARIO EMPALME", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "SANTA LUCIA EL ROSARIO EMPALME", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "BALZAR BALZAR BALZAR", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "SANTA LUCIA SANTA LUCIA SANTA LUCIA", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "JUNQUILLAL JUNQUILLAL SALITRE", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "CERRITOS BALZAR BALZAR", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "EL SALITRE EL SALITRE (LAS RAMAS) SALITRE", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "DAULE DAULE DAULE", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "COLIMES COLIMES COLIMES", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "CASCAJAL VALLE DE LA VIRGEN PEDRO CARBO", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "ZAMORA NUEVO PEDRO CARBO PEDRO CARBO", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "EL PIÑAL DE ABAJO LIMONAL DAULE", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "PEDRO CARBO PEDRO CARBO PEDRO CARBO", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "LAS CAÑAS LOMAS DE SARGENTILLO LOMAS DE SARGENTILLO", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "PUEBLO NUEVO ISIDRO AYORA ISIDRO AYORA", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "LAS MERCEDES ISIDRO AYORA ISIDRO AYORA", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "SABANILLA SABANILLA PEDRO CARBO", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "ISIDRO AYORA ISIDRO AYORA ISIDRO AYORA", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "LOMAS DE SARGENTILLO LOMAS DE SARGENTILLO LOMAS DE SARGENTILLO", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "BALAO BALAO BALAO", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "NARANJAL NARANJAL NARANJAL", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "EL TRIUNFO EL TRIUNFO EL TRIUNFO", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "TAURA VIRGEN DE FATIMA SAN JACINTO DE YAGUACHI", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "NARCIZA DE JESUS NARCISA DE JESUS NOBOL", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "LA PUNTILLA SAMBORONDON SAMBORONDON", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "LAUREL JUNQUILLAL SALITRE", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "LAUREL LAUREL DAULE", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "PUEBLO NUEVO SIMON BOLIVAR SIMON BOLIVAR", "provincia": "GUAYAS", "factor_z": 0.50},
    {"poblacion": "SIMON BOLIVAR SIMON BOLIVAR SIMON BOLIVAR", "provincia": "GUAYAS", "factor_z": 0.50},
    {"poblacion": "KILOMETRO VEINTE Y SEIS VIRGEN DE FATIMA SAN JACINTO DE YAGUACHI", "provincia": "GUAYAS", "factor_z": 0.35},
    {"poblacion": "ELOY ALFARO ELOY ALFARO (DURAN) DURAN", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "GUAYAQUIL GUAYAQUIL GUAYAQUIL", "provincia": "GUAYAS", "factor_z": 0.40},
    {"poblacion": "CARPUELA AMBUQUI IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "CHALGUAYACU PIMAMPIRO PIMAMPIRO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "PIMAMPIRO PIMAMPIRO PIMAMPIRO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "MARIANO ACOSTA MARIANO ACOSTA PIMAMPIRO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "EL JUNCAL AMBUQUI IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN RAFAEL SAN RAFAEL OTAVALO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "AMBUQUI AMBUQUI IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN ANTONIO DE IBARRA SAN ANTONIO IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN FRANCISCO DE NATABUELA SAN ANTONIO IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN JOSE DE CHALTURA SAN JOSE DE CHALTURA ANTONIO ANTE", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "IMANTAG IMANTAG COTACACHI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "COTACACHI COTACACHI COTACACHI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "QUIROGA QUIROGA COTACACHI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN MIGUEL DE IBARRA IMBAYA (SAN LUIS DE COBUENDO) ANTONIO ANTE", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "LA CALERA COTACACHI COTACACHI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN ROQUE SAN ROQUE ANTONIO ANTE", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN JUAN DE ILUMAN SAN JUAN DE ILUMAN OTAVALO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SALINAS SALINAS IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "CAHUASQUI CAHUASQUI SAN MIGUEL DE URCUQUI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "PABLO ARENAS PABLO ARENAS SAN MIGUEL DE URCUQUI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "TUMBABIRO TUMBABIRO SAN MIGUEL DE URCUQUI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN BLAS URCUQUI SAN MIGUEL DE URCUQUI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "PRIORATO SAN MIGUEL DE IBARRA IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN MIGUEL DE YAHUARCOCHA SAN MIGUEL DE IBARRA IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "CARANQUI SAN MIGUEL DE IBARRA IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SANTA ROSA SAN MIGUEL DE IBARRA IBARRA", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "OTAVALO DOCTOR MIGUEL EGAS CABEZAS OTAVALO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "CRUZ LOMA EUGENIO ESPEJO (CALPAQUI) OTAVALO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN JOSE DE QUICHINCHE SAN JOSE DE QUICHINCHE OTAVALO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "SAN PABLO DEL LAGO SAN PABLO OTAVALO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "GONZALEZ SUAREZ GONZALEZ SUAREZ OTAVALO", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "ATUNTAQUI SAN JOSE DE CHALTURA ANTONIO ANTE", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "URCUQUI URCUQUI SAN MIGUEL DE URCUQUI", "provincia": "IMBABURA", "factor_z": 0.40},
    {"poblacion": "CHAGUARPAMBA CHAGUARPAMBA CHAGUARPAMBA", "provincia": "LOJA", "factor_z": 0.30},
    {"poblacion": "CATACOCHA CATACOCHA PALTAS", "provincia": "LOJA", "factor_z": 0.30},
    {"poblacion": "ALAMOR ALAMOR PUYANGO", "provincia": "LOJA", "factor_z": 0.40},
    {"poblacion": "MACARA MACARA MACARA", "provincia": "LOJA", "factor_z": 0.35},
    {"poblacion": "CELICA CELICA CELICA", "provincia": "LOJA", "factor_z": 0.35},
    {"poblacion": "SOZORANGA SOZORANGA SOZORANGA", "provincia": "LOJA", "factor_z": 0.35},
    {"poblacion": "CATAMAYO CATAMAYO (LA TOMA) CATAMAYO", "provincia": "LOJA", "factor_z": 0.25},
    {"poblacion": "AMALUZA AMALUZA ESPINDOLA", "provincia": "LOJA", "factor_z": 0.25},
    {"poblacion": "QUILANGA QUILANGA QUILANGA", "provincia": "LOJA", "factor_z": 0.25},
    {"poblacion": "CARIAMANGA CARIAMANGA CALVAS", "provincia": "LOJA", "factor_z": 0.25},
    {"poblacion": "LOJA LOJA LOJA", "provincia": "LOJA", "factor_z": 0.25},
    {"poblacion": "SAN JACINTO DE BUENA FE SAN JACINTO DE BUENA FE BUENA FE", "provincia": "LOS RÍOS", "factor_z": 0.35},
    {"poblacion": "JAUNECHE PALENQUE PALENQUE", "provincia": "LOS RÍOS", "factor_z": 0.35},
    {"poblacion": "ANTONIO SOTOMAYOR ANTONIO SOTOMAYOR VINCES", "provincia": "LOS RÍOS", "factor_z": 0.35},
    {"poblacion": "BABA BABA BABA", "provincia": "LOS RÍOS", "factor_z": 0.35},
    {"poblacion": "QUEVEDO QUEVEDO QUEVEDO", "provincia": "LOS RÍOS", "factor_z": 0.35},
    {"poblacion": "VINCES VINCES VINCES", "provincia": "LOS RÍOS", "factor_z": 0.35},
    {"poblacion": "PALENQUE PALENQUE PALENQUE", "provincia": "LOS RÍOS", "factor_z": 0.35},
    {"poblacion": "LA UNION LA UNION BABAHOYO", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "COSTA AZUL VALENCIA VALENCIA", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "VALENCIA VALENCIA VALENCIA", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "MONTALVO MONTALVO MONTALVO", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "QUINSALOMA QUINSALOMA QUINSALOMA", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "SAN JUAN SAN JUAN PUEBLOVIEJO", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "SAN CARLOS SAN CARLOS QUEVEDO", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "MOCACHE MOCACHE MOCACHE", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "PUEBLOVIEJO PUEBLOVIEJO PUEBLOVIEJO", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "CATARAMA CATARAMA URDANETA", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "BABAHOYO BABAHOYO BABAHOYO", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "VENTANAS VENTANAS VENTANAS", "provincia": "LOS RÍOS", "factor_z": 0.30},
    {"poblacion": "PATRICIA PILAR PATRICIA PILAR BUENA FE", "provincia": "LOS RÍOS", "factor_z": 0.40},
    {"poblacion": "COLON PORTOVIEJO PORTOVIEJO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "JULCUY JULCUY JIPIJAPA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "CHARAPOTO CHARAPOTO SUCRE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "FLAVIO ALFARO FLAVIO ALFARO FLAVIO ALFARO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SAN PEDRO DE SUMA SAN PEDRO DE SUMA EL CARMEN", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "ROCAFUERTE ROCAFUERTE ROCAFUERTE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "RIOCHICO RIOCHICO (RIO CHICO) PORTOVIEJO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SAN ISIDRO SAN ISIDRO BAHIA DE CARAQUEZ", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "ELOY ALFARO ELOY ALFARO CHONE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SAN JACINTO CHARAPOTO SUCRE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SAN VICENTE SAN VICENTE SAN VICENTE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "LEONIDAS PLAZA BAHIA DE CARAQUEZ SUCRE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "CALCETA CALCETA BOLIVAR", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "JARAMIJO JARAMIJO JARAMIJO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SANTA ANA DE VUELTA LARGA SANTA ANA DE VUELTA LARGA SANTA ANA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "CHONE CHONE CHONE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "EL AROMO MANTA MANTA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PILES MONTECRISTI MONTECRISTI", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SAN LORENZO SAN LORENZO MANTA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PACOCHE ABAJO SANTA MARIANITA MANTA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "EL LIMON PORTOVIEJO PORTOVIEJO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "CALDERON ABDON CALDERON (SAN FRANCISCO) PORTOVIEJO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PORTOVIEJO PORTOVIEJO PORTOVIEJO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SAN PLACIDO SAN PLACIDO PORTOVIEJO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SUCRE SUCRE 24 DE MAYO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SANCAN JIPIJAPA JIPIJAPA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "MEMBRILLAL MEMBRILLAL JIPIJAPA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "RIO DE CAÑA MONTECRISTI MONTECRISTI", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "JIPIJAPA JIPIJAPA JIPIJAPA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "EL ANEGADO EL ANEGADO (CAB EN ELOY ALFARO) JIPIJAPA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "EL ESFUERZO BELLAVISTA 24 DE MAYO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "NOBOA NOBOA 24 DE MAYO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "BELLAVISTA OLMEDO OLMEDO", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PAJAN PAJAN PAJAN", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "CASCOL CASCOL PAJAN", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PEDRO PABLO GOMEZ PEDRO PABLO GOMEZ JIPIJAPA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SALANGO SALANGO PUERTO LOPEZ", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "RIO CHICO SALANGO PUERTO LOPEZ", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PUERTO LOPEZ PUERTO LOPEZ PUERTO LOPEZ", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "AYAMPE SALANGO PUERTO LOPEZ", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "MONTECRISTI MONTECRISTI MONTECRISTI", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "AGUA PATO EL ANEGADO (CAB EN ELOY ALFARO) JIPIJAPA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "COJIMIES COJIMIES PEDERNALES", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PEDERNALES PEDERNALES PEDERNALES", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "QUIROGA QUIROGA BOLIVAR", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "JUNIN JUNIN JUNIN", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "CANUTO CANUTO CHONE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "TOSAGUA TOSAGUA TOSAGUA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "EL PUEBLITO CHARAPOTO SUCRE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "JAMA JAMA JAMA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "MANTA MONTECRISTI MONTECRISTI", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SAN CLEMENTE CHARAPOTO SUCRE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "SAN PABLO SAN PABLO (PUEBLO NUEVO) SANTA ANA", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "EL CARMEN EL CARMEN EL CARMEN", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "LA BRAMADORA EL CARMEN EL CARMEN", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "BARRAGANETE BARRAGANETE PICHINCHA", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "MEMBRILLO MEMBRILLO BOLIVAR", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "OLMEDO OLMEDO OLMEDO", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "PICHINCHA PICHINCHA PICHINCHA", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "LA UNION LA UNION SANTA ANA", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "LASCANO LASCANO PAJAN", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "GUALE GUALE PAJAN", "provincia": "MANABÍ", "factor_z": 0.40},
    {"poblacion": "BAHIA DE CARAQUEZ BAHIA DE CARAQUEZ SUCRE", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "MACHALILLA MACHALILLA PUERTO LOPEZ", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PUERTO DE CAYO PUERTO DE CAYO JIPIJAPA", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PUERTO RICO SALANGO PUERTO LOPEZ", "provincia": "MANABÍ", "factor_z": 0.50},
    {"poblacion": "PALORA PALORA (METZERA) PALORA", "provincia": "MORONA SANTIAGO", "factor_z": 0.30},
    {"poblacion": "PABLO SEXTO PABLO SEXTO PABLO SEXTO", "provincia": "MORONA SANTIAGO", "factor_z": 0.30},
    {"poblacion": "GENERAL LEONIDAS PLAZA GUTIERREZ GRAL. LEONIDAS PLAZA GUTIERREZ LIMON INDANZA", "provincia": "MORONA SANTIAGO", "factor_z": 0.30},
    {"poblacion": "SANTIAGO DE MENDEZ SANTIAGO DE MENDEZ SANTIAGO", "provincia": "MORONA SANTIAGO", "factor_z": 0.30},
    {"poblacion": "SUCUA SUCUA SUCUA", "provincia": "MORONA SANTIAGO", "factor_z": 0.30},
    {"poblacion": "MACAS MACAS MORONA", "provincia": "MORONA SANTIAGO", "factor_z": 0.30},
    {"poblacion": "CUYUJA CUYUJA QUIJOS", "provincia": "NAPO", "factor_z": 0.40},
    {"poblacion": "SAN FRANCISCO DE BORJA SAN FRANCISCO DE BORJA QUIJOS", "provincia": "NAPO", "factor_z": 0.40},
    {"poblacion": "EL CHACO EL CHACO EL CHACO", "provincia": "NAPO", "factor_z": 0.40},
    {"poblacion": "BAEZA BAEZA QUIJOS", "provincia": "NAPO", "factor_z": 0.40},
    {"poblacion": "PAPALLACTA PAPALLACTA QUIJOS", "provincia": "NAPO", "factor_z": 0.40},
    {"poblacion": "ARCHIDONA ARCHIDONA ARCHIDONA", "provincia": "NAPO", "factor_z": 0.35},
    {"poblacion": "COTUNDO COTUNDO ARCHIDONA", "provincia": "NAPO", "factor_z": 0.35},
    {"poblacion": "TENA TENA TENA", "provincia": "NAPO", "factor_z": 0.35},
    {"poblacion": "LA JOYA DE LOS SACHAS LA JOYA DE LOS SACHAS LA JOYA DE LOS SACHAS", "provincia": "ORELLANA", "factor_z": 0.15},
    {"poblacion": "TARACOA TARACOA ORELLANA", "provincia": "ORELLANA", "factor_z": 0.15},
    {"poblacion": "NUEVO ROCAFUERTE NUEVO ROCAFUERTE AGUARICO", "provincia": "ORELLANA", "factor_z": 0.15},
    {"poblacion": "TIPUTINI TIPUTINI AGUARICO", "provincia": "ORELLANA", "factor_z": 0.15},
    {"poblacion": "PAYAMINO PUERTO FRANCISCO DE ORELLANA ORELLANA", "provincia": "ORELLANA", "factor_z": 0.25},
    {"poblacion": "SAN SEBASTIAN DEL COCA SAN SEBASTIAN DEL COCA LA JOYA DE LOS SACHAS", "provincia": "ORELLANA", "factor_z": 0.25},
    {"poblacion": "PUERTO FRANCISCO DE ORELLANA PUERTO FRANCISCO DE ORELLANA ORELLANA", "provincia": "ORELLANA", "factor_z": 0.25},
    {"poblacion": "SHELL SHELL MERA", "provincia": "PASTAZA", "factor_z": 0.30},
    {"poblacion": "PUYO PUYO PASTAZA", "provincia": "PASTAZA", "factor_z": 0.30},
    {"poblacion": "MERA MERA MERA", "provincia": "PASTAZA", "factor_z": 0.35},
    {"poblacion": "SIMÓN BOLIVAR PUERTO QUITO PUERTO QUITO", "provincia": "PICHINCHA", "factor_z": 0.50},
    {"poblacion": "BUENOS AIRES PUERTO QUITO PUERTO QUITO", "provincia": "PICHINCHA", "factor_z": 0.50},
    {"poblacion": "EL QUINCHE EL QUINCHE QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "SAN ANTONIO DE PICHINCHA SAN ANTONIO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "CUMBAYA CUMBAYA QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ARMENIA GUANGOPOLO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "UYUMBICHO AMAGUAÑA QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ALOAG ALOAG MEJIA", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "CANGAGHUA CANGAHUA CAYAMBE", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "GUAYLLABAMBA GUAYLLABAMBA QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ASCAZUBI ASCAZUBI CAYAMBE", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "POMASQUI POMASQUI QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "CALDERON CALDERON (CARAPUNGO) QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "NAYON NAYON QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ZAMBIZA ZAMBIZA QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "YARUQUI YARUQUI QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "CHECA CHECA (CHILPA) QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ALOAG MACHACHI MEJIA", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "AMAGUAÑA AMAGUAÑA QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "PINTAG PINTAG QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "LA MERCED LA MERCED QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "PUEMBO PUEMBO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "TABABELA TABABELA QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "LLANO GRANDE CALDERON (CARAPUNGO) QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "MACHACHI MACHACHI MEJIA", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ANGUMBA TABACUNDO PEDRO MONCAYO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "HUAYCUPATA CAYAMBE CAYAMBE", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "NANEGAL NANEGAL QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "GUALEA GUALEA QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "TUPIGACHI TUPIGACHI PEDRO MONCAYO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "CAYAMBE CAYAMBE CAYAMBE", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "JUAN MONTALVO CAYAMBE CAYAMBE", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "TABACUNDO TABACUNDO PEDRO MONCAYO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "LA ESPERANZA LA ESPERANZA PEDRO MONCAYO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "GUARAQUI LA ESPERANZA PEDRO MONCAYO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "TOCACHI TOCACHI PEDRO MONCAYO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "MALCHINGUI MALCHINGUI PEDRO MONCAYO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "PERUCHO PERUCHO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "PUELLARO PUELLARO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ALCHIPICHI PUELLARO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "PULULAHUA CALACALI QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "CASPIGASI DEL CARMEN SAN ANTONIO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "CALACALI CALACALI QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "OLMEDO OLMEDO (PECILLO) CAYAMBE", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ATAHUALPA ATAHUALPA (HABASPAMBA) QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "SAN JOSE DE MINAS SAN JOSE DE MINAS QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "SAN MIGUEL DE LOS BANCOS SAN MIGUEL DE LOS BANCOS SAN MIGUEL DE LOS BANCOS", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "NANEGALITO NANEGALITO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "AYORA CAYAMBE CAYAMBE", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "SANGOLQUI SANGOLQUI RUMIÑAHUI", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "PUERTO QUITO PUERTO QUITO PUERTO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "PEDRO VICENTE MALDONADO PEDRO VICENTE MALDONADO PEDRO VICENTE MALDONADO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "TUMBACO TUMBACO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "PIFO PIFO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "TAMBILLO TAMBILLO MEJIA", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "SANTA ROSA CONOCOTO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "SAN RAFAEL AMAGUAÑA QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "CONOCOTO CONOCOTO QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "QUITO POMASQUI QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "ALANGASI ALANGASI QUITO", "provincia": "PICHINCHA", "factor_z": 0.40},
    {"poblacion": "SAN PABLO SANTA ELENA SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "ATAHUALPA ATAHUALPA SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "SANTA ELENA SANTA ELENA SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "SAN JOSE MANGLARALTO SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "LA CURIA MANGLARALTO SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "OLON MANGLARALTO SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "MONTAÑITA MANGLARALTO SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "EL MAMEY MANGLARALTO SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "FEBRES CORDERO COLONCHE SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "BAMBIL CALLAO COLONCHE SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "BARCELONA COLONCHE SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "SAN PEDRO DE VALDIVIA MANGLARALTO SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "AYANGUE COLONCHE SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "SINCAL MANGLARALTO SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "MANGLARALTO MANGLARALTO SANTA ELENA", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "LA LIBERTAD SALINAS SALINAS", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "SALINAS SALINAS SALINAS", "provincia": "SANTA ELENA", "factor_z": 0.50},
    {"poblacion": "SANTA MARÍA DEL TOACHI SANTA MARIA DEL TOACHI SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.35},
    {"poblacion": "LUZ DE AMÉRICA LUZ DE AMERICA SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "PUERTO LIMÓN PUERTO LIMON SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "EL ESFUERZO EL ESFUERZO SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "SAN JACINTO DE BUA SAN JACINTO DEL BUA SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "VALLE HERMOSO VALLE HERMOSO SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "CRISTÓBAL COLÓN VALLE HERMOSO SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "NUEVO ISRAEL STO. DOMINGO DE LOS COLORADOS SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "LAS DELICIAS STO. DOMINGO DE LOS COLORADOS SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "LA AURORA STO. DOMINGO DE LOS COLORADOS SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "JULIO MORENO STO. DOMINGO DE LOS COLORADOS SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "UNIÓN CÍVICA POPULAR STO. DOMINGO DE LOS COLORADOS SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "SUSANITA STO. DOMINGO DE LOS COLORADOS SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "EULOGIO STO. DOMINGO DE LOS COLORADOS SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "SANTO DOMINGO DE LOS COLORADOS STO. DOMINGO DE LOS COLORADOS SANTO DOMINGO", "provincia": "SANTO DOMINGO DE LOS TSÁCHILAS", "factor_z": 0.40},
    {"poblacion": "SHUSHUFINDI SHUSHUFINDI SHUSHUFINDI", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "SIETE DE JULIO SIETE DE JULIO SHUSHUFINDI", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "EL ENO EL ENO LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "AGUARICO PACAYACU LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "CHIRITZA TARAPOA CUYABENO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "SAN PEDRO DE LOS COFANES SAN PEDRO DE LOS COFANES SHUSHUFINDI", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "JIVINO SAN PEDRO DE LOS COFANES SHUSHUFINDI", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "PUERTO EL CARMEN DEL PUTUMAYO PUERTO EL CARMEN DEL PUTUMAYO PUTUMAYO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "PUERTO AGUARICO NUEVA LOJA LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "SANTA CECILIA SANTA CECILIA LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "GENERAL FARFAN GENERAL FARFAN LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "SAN MIGUEL GENERAL FARFAN LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "NUEVA LOJA NUEVA LOJA LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "SANTA ROSA NUEVA LOJA LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.15},
    {"poblacion": "JAMBELI JAMBELI LAGO AGRIO", "provincia": "SUCUMBÍOS", "factor_z": 0.25},
    {"poblacion": "SEVILLA SEVILLA CASCALES", "provincia": "SUCUMBÍOS", "factor_z": 0.25},
    {"poblacion": "EL DORADO DE CASCALES EL DORADO DE CASCALES CASCALES", "provincia": "SUCUMBÍOS", "factor_z": 0.30},
    {"poblacion": "EL DORADO DE CASCALES LUMBAQUI GONZALO PIZARRO", "provincia": "SUCUMBÍOS", "factor_z": 0.30},
    {"poblacion": "COMUNA TAMBO LOMA PILAGUIN (PILAHUIN) AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.35},
    {"poblacion": "CORAZON DE JESUS IZAMBA AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "URBANIZACION AEROPUERTO IZAMBA AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "PILAHUIN PILAGUIN (PILAHUIN) AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "QUINSAPINCHA QUISAPINCHA (QUIZAPINCHA) AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "JUAN BENIGNO VELA JUAN BENIGNO VELA AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "MARTINEZ AUGUSTO N. MARTINEZ AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "SAN ISIDRO PICAIGUA AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "TOTORAS TOTORAS AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "AMBATILLO AMBATILLO AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "ATAHUALPA ATAHUALPA (CHISALATA) AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "IZAMBA IZAMBA AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "SAN MIGUELITO SAN MIGUELITO SANTIAGO DE PILLARO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "HUACHI GRANDE HUACHI GRANDE AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "SANTA ROSA SANTA ROSA AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "AMBATO AMBATO AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "PELILEO GRANDE PELILEO SAN PEDRO DE", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "PELILEO SAN ANTONIO DE PASA PASA AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "SAN BARTOLOME DE PINLLOG SAN BARTOLOME DE PINLLOG AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "PATATE PATATE PATATE", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "SAN FERNANDO SAN FERNANDO AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "EMILIO M. TERAN EMILIO MARIA TERAN (RUMIPAMBA) SANTIAGO DE PILLARO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "MARCOS ESPINEL MARCOS ESPINEL (CHACATA) SANTIAGO DE PILLARO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "BAÑOS DE AGUA SANTA BAÑOS DE AGUA SANTA BAÑOS DE AGUA SANTA", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "ULBA ULBA BAÑOS DE AGUA SANTA", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "RIO VERDE RIO VERDE BAÑOS DE AGUA SANTA", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "GUAMBALÓ GUAMBALO (HUAMBALO) SAN PEDRO DE PELILEO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "TISALEO TISALEO TISALEO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "CEVALLOS CEVALLOS CEVALLOS", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "QUERO QUERO QUERO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "RUMIPAMBA RUMIPAMBA QUERO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "COTALÓ COTALO SAN PEDRO DE PELILEO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "SAN ANDRÉS SAN ANDRES SANTIAGO DE PILLARO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "CUNCHIBAMBA CUNCHIBAMBA AMBATO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "SAN JOSÉ DE POALÓ SAN JOSE DE POALO SANTIAGO DE PILLARO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "EL TRIUNFO EL TRIUNFO PATATE", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "SUCRE LOS ANDES (CAB EN POATUG) PATATE", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "MOCHA MOCHA MOCHA", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "PELILEO PELILEO SAN PEDRO DE PELILEO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "PILLARO PILLARO SANTIAGO DE PILLARO", "provincia": "TUNGURAHUA", "factor_z": 0.40},
    {"poblacion": "GUAYZIMI GUAYZIMI NANGARITZA", "provincia": "ZAMORA CHINCHIPE", "factor_z": 0.30},
    {"poblacion": "YANTZAZA YANTZAZA (YANZATZA) YANTZAZA", "provincia": "ZAMORA CHINCHIPE", "factor_z": 0.30},
    {"poblacion": "ZUMBA ZUMBA CHINCHIPE", "provincia": "ZAMORA CHINCHIPE", "factor_z": 0.25},
    {"poblacion": "ZAMORA ZAMORA ZAMORA", "provincia": "ZAMORA CHINCHIPE", "factor_z": 0.25},
    {"poblacion": "LAS GOLONDRINAS LAS GOLONDRINAS LAS GOLONDRINAS", "provincia": "ZONA NO DELIMITADA", "factor_z": 0.50},
    {"poblacion": "SANTA MARÍA MANGA DEL CURA MANGA DEL CURA", "provincia": "ZONA NO DELIMITADA", "factor_z": 0.40},
    {"poblacion": "SANTA TERESA MANGA DEL CURA MANGA DEL CURA", "provincia": "ZONA NO DELIMITADA", "factor_z": 0.40},]


def cargar(dry_run: bool = False):
    print(f"{len(FILAS)} filas a cargar (Tabla 16, seccion 10.2 NEC-SE-DS).")
    por_provincia: dict[str, int] = {}
    for f in FILAS:
        por_provincia[f["provincia"]] = por_provincia.get(f["provincia"], 0) + 1
    for provincia, n in sorted(por_provincia.items()):
        print(f"  {provincia}: {n} poblaciones")
    print(f"\nTotal provincias/zonas distintas: {len(por_provincia)}")

    if dry_run:
        print("[dry-run] No se inserta en Supabase.")
        return

    supabase_url = os.environ.get("SUPABASE_URL", "")
    supabase_key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    if not supabase_url or not supabase_key:
        print("ERROR: Configura SUPABASE_URL y SUPABASE_SERVICE_KEY en .env")
        return

    from supabase import create_client
    sb = create_client(supabase_url, supabase_key)
    LOTE = 200
    for i in range(0, len(FILAS), LOTE):
        lote = FILAS[i:i + LOTE]
        sb.table("ecuador_nec_se_ds_zonificacion_poblacion").upsert(
            lote, on_conflict="poblacion,provincia"
        ).execute()
        print(f"  OK lote {i // LOTE + 1}: {len(lote)} filas")
    print(f"OK: {len(FILAS)} filas insertadas/actualizadas en ecuador_nec_se_ds_zonificacion_poblacion.")


if __name__ == "__main__":
    dry = "--dry-run" in sys.argv
    cargar(dry_run=dry)
